### ISSUE TITLE
Consider using __array_ufunc__ from numpy 1.10 for YTArray

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1013]
Originally reported by: **Nathan Goldbaum (Bitbucket: [ngoldbaum](https://bitbucket.org/ngoldbaum), GitHub: [ngoldbaum](https://github.com/ngoldbaum))**

----------------------------------------

This new hook in ndarray's subclassing machinery may help us avoid a significant amount of boilerplate in the definition of YTArray.  In addition, it may also allow us to fix currently un-resolveable issues with subclassing ndarray, e.g. this example:

```
#!

>>> import numpy as np
>>> from yt.units import g
>>> a = np.array([1,2,3])
>>> print a*g
[ 1.  2.  3.] g

a*g returns a YTArray, an ndarray subclass that knows about units.
"plain" ndarrays are treated as unitless arrays.

>>> print g
1.0 g
>>> a *= g
>>> print a
array([1, 2, 3])

I don't seem to have a way to override this behavior, since
this invokes __imul__ in the ndarray class rather than __rmul__
in my subclass

>>> a = [1,2,3]
>>> print a*g
[ 1.  2.  3.] g
>>> a *= g
>>> a
YTArray([ 1.,  2.,  3.]) g


Things behave correctly when I use lists rather than ndarray.

```

Unfortunately this is blocked until numpy 1.10 is released. We will also need to be careful to not break compatibility with older versions of numpy, and be sure to not make the code paths followed in different numpy versions different.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1013

**Comment by ngoldbaum** [comment]
`__array_ufunc__` will be in the next numpy release. We should come back to this.

**Comment by neutrinoceros** [comment]
Closing since it's been long done in unyt, which is now a dependency to yt.
