### ISSUE TITLE
Projection Plot Image Size Inconsistency

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1032]
Originally reported by: **ggoodwin52 (Bitbucket: [ggoodwin52](https://bitbucket.org/ggoodwin52), GitHub: Unknown)**

----------------------------------------

I use projection plots to generate images of my simulation marching through time, then combine the images into a video using mencoder. Attached is a sample script I use to generate the images and a sample video. You will notice in the video that the frame "oscillates" as it progresses, which is very distracting from the actual simulation. This oscillation is due to some of the images being rendered with 360 pixels in the vertical direction and others rendered with 359 pixels.

Nothing changes in the window height or vertical position of the plot center, as you will see in the attached script. I have tried using different figure sizes, but the result it the same. For the vertical position of the plot center, I tried using both "height/2." and hardcoding in the coordinate (0.16 in this case), but it didn't correct the issue.

I have uploaded ten consecutive timesteps which can be used to run the attached script. You will notice that steps 308350, 308400 and 308650 are rendered with 360 pixels in the vertical direction, and all others are rendered with 359 pixels. 

Here is the tar file for the dataset: http://use.yt/upload/679cc306

I ran this script using the most updated version of development yt as well as 3.1 stable with the same result.

Perhaps there is a way to control the number of pixels used, but I could not find this in the yt documentation.

Any help is appreciated!

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1032

**Comment by ngoldbaum** [comment]
No example so I'm closing the issue.
