### ISSUE TITLE
Radial Column Density

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1047]
Originally reported by: **Bili Dong (Bitbucket: [qobilidop](https://bitbucket.org/qobilidop), GitHub: [qobilidop](https://github.com/qobilidop))**

----------------------------------------

Is anyone working on porting the [radial column density analysis module](http://yt-project.org/docs/dev/analyzing/analysis_modules/radial_column_density.html) from yt-2.x to yt-3.x? This functionality is exactly what I need for my current research. I'd like to do the work if no one else is already working on it.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1047

**Comment by brittonsmith** [comment]
Moved to Issue [#8](https://github.com/yt-project/yt_astro_analysis/issues/8) on yt_astro_analysis.
