### ISSUE TITLE
Add example for loading an SPH dataset with load_particles

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1062]
Originally reported by: **adam ginsburg (Bitbucket: [keflavich](https://bitbucket.org/keflavich), GitHub: [keflavich](https://github.com/keflavich))**

----------------------------------------

I'm trying to test out https://bitbucket.org/yt_analysis/yt/pull-requests/1688/wip-adding-support-for-octree-style-output/diff using some SPH data I have, but I don't have the fields loaded properly.

I have a loader that mostly works, but I can't add the temperature field following this example:
https://bitbucket.org/yt_analysis/yt/src/1f2ea0bf41846f243b50558c5eb9828bf06a3da2/yt/frontends/gadget/fields.py?at=yt

the loader looks like this:
https://github.com/keflavich/jimpy/blob/master/yt/to_yt.py

Optimally, the resulting dataset should have SPH fields registered. Right now this doesn't happen automatically.

This example should probably go in the docs.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1062

**Comment by qobilidop** [comment]
I believe this is taken care of in #2167.
