### ISSUE TITLE
Default origins for different geometries based on axis

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1066]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

For some geometries, like cylindrical, there are natural origins for the plots one would want to use.  For instance, if we are looking at a plot along R and z of a cylindrical dataset (i.e., slice along theta), we probably want "native" to be the default origin.  Right now, this is not implemented, and in principle it should be implemented in a way that is a bit more rigorous than the way centers, widths, etc are currently set up.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1066

**Comment by neutrinoceros** [comment]
> For some geometries, like cylindrical, there are natural origins for the plots one would want to use. For instance, if we are looking at a plot along R and z of a cylindrical dataset (i.e., slice along theta), we probably want "native" to be the default origin. Right now, this is not implemented, and in principle it should be implemented in a way that is a bit more rigorous than the way centers, widths, etc are currently set up.

I believe this _is_ now implemented but somehow this ticket survived, see
https://github.com/yt-project/yt/blob/2770642c886f1183d68094a004b0d0a32fb1d8d8/yt/visualization/plot_window.py#L210-L222
