### ISSUE TITLE
Switch HaloCatalog main loop to loop over io chunks

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1075]
Originally reported by: **Britton Smith (Bitbucket: [brittonsmith](https://bitbucket.org/brittonsmith), GitHub: [brittonsmith](https://github.com/brittonsmith))**

----------------------------------------

The loop over all halos in the HaloCatalog currently requires all processors to have the entire list of halos.  This should be changed such that process groups work only on a single io chunk.  Currently, only one io chunk exists even when the halo catalog is saved to multiple files.  This needs to be reverted to one chunk per file first.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1075

**Comment by brittonsmith** [comment]
Moved to Issue [#7](https://github.com/yt-project/yt_astro_analysis/issues/7) on yt_astro_analysis.
