### ISSUE TITLE
Add HaloCatalogTimeSeries

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1076]
Originally reported by: **Britton Smith (Bitbucket: [brittonsmith](https://bitbucket.org/brittonsmith), GitHub: [brittonsmith](https://github.com/brittonsmith))**

----------------------------------------

This is the final component outlined in YTEP-0012.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1076

**Comment by brittonsmith** [comment]
Moved to Issue [#6](https://github.com/yt-project/yt_astro_analysis/issues/6) on yt_astro_analysis.
