### ISSUE TITLE
python seg faults when trying to load face-centered Enzo MHDCT fields

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1087]
Originally reported by: **Nathan Goldbaum (Bitbucket: [ngoldbaum](https://bitbucket.org/ngoldbaum), GitHub: [ngoldbaum](https://github.com/ngoldbaum))**

----------------------------------------

Dataset is here: http://use.yt/upload/58d7f69e

Test script:

```
#!python

import yt
ds = yt.load('DD0004/DD0004')
ad = ds.all_data()
ad['BxF']
```

The traceback the Apple crash reporter generates doesn't have anything particularly illuminating in it.  The error message that gets printed to my console is:

```
#!

Python(56127,0x7fff742f5300) malloc: *** error for object 0x7ffb01f54608: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1087

**Comment by ngoldbaum** [comment]
We should come back to this now that `nodal_flag` is a thing.
