### ISSUE TITLE
[experimental] add annotate_ray and annotate_line for VR

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1126]
Originally reported by: **chummels (Bitbucket: [chummels](https://bitbucket.org/chummels), GitHub: [chummels](https://github.com/chummels))**

----------------------------------------

Create a single LineSource

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1126

**Comment by ngoldbaum** [comment]
Duplicate of #1040
