### ISSUE TITLE
Octree construction on some SPH datasets revealing large swath of simulation space with zero density

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1146]
Originally reported by: **chummels (Bitbucket: [chummels](https://bitbucket.org/chummels), GitHub: [chummels](https://github.com/chummels))**

----------------------------------------

Following the discussion in PR #1880, we identified that the octree construction was not behaving correctly for some SPH datasets.  Rather than having full coverage in mesh fields across the simulation volume, regions of no gas particles have their mesh fields deposited as zero (i.e. zero density, zero temperature, etc.).  Formally, this should never happen, and it can lead to a lot of unpredictable behavior later in processing the data.

For more information on this problem and how to reproduce it, see Pull Request #1880.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1146

**Comment by chummels** [comment]
Presumably the bulk of this will be addressed in the de-meshening, but perhaps leaving this open since I thought we were keeping octree construction as a backwards-compatible option?  And I think it's still relevant.

**Comment by ngoldbaum** [comment]
So this issue is really long. I think the conclusion is that you want the option to use the gather method to smooth onto the octree.

Can we close this issue and reopen a new one describing the specific feature request? I closed this issue because there didn't seem to be a strong call to action.

**Comment by ngoldbaum** [comment]
OK, Opened a new issue. If you agree that the new issue captures the thrust of what you wanted to get accomplished here, would you be ok with closing this one?

**Comment by chummels** [comment]
Thanks for creating the new issue, @ngoldbaum .  Closing.
