### ISSUE TITLE
Covering grids do not fill data outside domain boundaries for a periodic simulation

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1209]
Originally reported by: **Nathan Goldbaum (Bitbucket: [ngoldbaum](https://bitbucket.org/ngoldbaum), GitHub: [ngoldbaum](https://github.com/ngoldbaum))**

----------------------------------------

The following test script (adapted from a script provided to me by Marco Surace):

http://paste.yt-project.org/show/6396/

Produces the following image:

![test.png](https://bitbucket.org/repo/BXbAb/images/1362080846-test.png)

Since this simulation uses periodic boundary conditions, I would expect the data to be periodically mirrored even though we are selecting data outside the domain boundaries.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1209

**Comment by neutrinoceros** [comment]
It seems that the script needed to reproduce the problem was lost, and I don't think there's enough to work off from what's left of the issue.
