### ISSUE TITLE
Bug in HaloMassFcn output units?

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1228]
Originally reported by: **Io Odderskov (Bitbucket: [ioodderskov](https://bitbucket.org/ioodderskov), GitHub: [ioodderskov](https://github.com/ioodderskov))**

----------------------------------------

I have tried comparing the Tinker 2008 fitting function produced by HaloMassFcn to the halo mass function from the Halo Finder Comparison Project (https://arxiv.org/pdf/1104.0949v1.pdf) and to a halo catalogue from the DEUS consortium (http://www.deus-consortium.org/deuvo/#download). In these cases, the halo masses are given in Msun/h, and the cumulative halo number density in h^3/Mpc^3. According to the Yt-documentation, the masses output by the HaloMassFcn-function should be in Msun, and the number densities in 1/Mpc^3. To convert to Msun/h and h^3/Mpc^3, I multiply the masses by h, and divide the number densities with h^3. In the attached figure, this corresponds to the line labelled "Tinker2008 - masses multiplied by h", which does not match the other data sets very well. If I instead divide the masses by h, I get the line labelled Tinker2008 - masses divided by h", which looks much better. So far, the only possible explanation I have been able to find for this is that there is a problem with the units of the fitting function output by HaloMassFcn.

Here is the script: [http://paste.yt-project.org/show/6530/](http://paste.yt-project.org/show/6530/), and the plot: [http://imgur.com/otWW3QJ](http://imgur.com/otWW3QJ)

I'm using this version of yt:

  Version = 3.2.3
  Changeset = bdea84d95099 (stable) @

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1228

**Comment by ngoldbaum** [comment]
We've deprecated this code so i'm closing the issue.
