### ISSUE TITLE
Reading Gadget2 outputs with SnapFormat=2.

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1244]
Originally reported by: **Erwin Tin-Hay Lau (Bitbucket: [ethlau](https://bitbucket.org/ethlau), GitHub: [ethlau](https://github.com/ethlau))**

----------------------------------------

Are there any plans to read Gadget2 outputs with SnapFormat=2? Right now it only accepts SnapFormat=1 or HDF5 format. 

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1244

**Comment by ngoldbaum** [comment]
This is now fixed.
