### ISSUE TITLE
ellipsoidal halo analysis is broken

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1245]
Originally reported by: **Britton Smith (Bitbucket: [brittonsmith](https://bitbucket.org/brittonsmith), GitHub: [brittonsmith](https://github.com/brittonsmith))**

----------------------------------------

The ellipsoidal halo analysis example in the docs does not work.  It appears to be a simple a units error that can probably be fixed easily.  That said, this code is untested and only exists within the yt-2.x era halo finding framework.  This function needs to be ported into a recipe or callback function that works with the `HaloCatalog` if it's going to be usable.  For now, I am going to leave a note in the docs that it is currently broken.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1245

**Comment by brittonsmith** [comment]
Moved to Issue [#5](https://github.com/yt-project/yt_astro_analysis/issues/5) on yt_astro_analysis.
