### ISSUE TITLE
"Developing yt on windows" instructions in the developer guide are out of date

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1257]
Originally reported by: **Nathan Goldbaum (Bitbucket: [ngoldbaum](https://bitbucket.org/ngoldbaum), GitHub: [ngoldbaum](https://github.com/ngoldbaum))**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1257

**Comment by ngoldbaum** [comment]
Fixed
