### ISSUE TITLE
yt embedded in enzo crashes when trying to calculate fields that need ghost zones

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1268]
Originally reported by: **Bodo Schwabe (Bitbucket: [bschwabe](https://bitbucket.org/bschwabe), GitHub: Unknown)**

----------------------------------------

I currently try to run enzo with embedded parallelized python/yt (Version = 3.4-dev
Changeset = c941aa457bc3 (yt) tip) with the following user_script.py  < http://paste.yt-project.org/show/6794/ > . It works fine on a single processor (mpirun -n 1 ...) but gives me the following error message for multiple processors <http://paste.yt-project.org/show/6795/  > . Regular derived_fields are working well, but gradient_fields aren't. Thank you very much for any suggestions.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1268

**Comment by ngoldbaum** [comment]
Punting on this for 3.4.

**Comment by matthewturk** [comment]
I'm going to close this issue, as I believe it is stale and may be masking broader problems.
