### ISSUE TITLE
Add an interface for setting the background color of yt plots

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1269]
Originally reported by: **Nathan Goldbaum (Bitbucket: [ngoldbaum](https://bitbucket.org/ngoldbaum), GitHub: [ngoldbaum](https://github.com/ngoldbaum))**

----------------------------------------

This has come up several times on the mailing list recently. We should have a nicer, more obvious, documented interface for this.

Some example solutions that work right now:

https://gist.github.com/dcea5b6ede57b701f00df6089fc68b23

https://gist.github.com/98bd8fcca8da5331f056e0a8ee53fb97

http://stackoverflow.com/questions/38753964/sliceplot-for-bound-material-in-yt-without-showing-unbound

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1269

**Comment by ngoldbaum** [comment]
This is fixed
