### ISSUE TITLE
Mesh line annotations are wrong when the slice exactly intersects element boundaries.

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1273]
Originally reported by: **Anonymous**

----------------------------------------

Thanks to @xarthisius for tracking this down.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1273

**Comment by lindsayad** [comment]
@atmyers I'm guessing you've worked on `annotate_mesh_lines`? Off the top of your head, do you have an idea of where this issue might be coming from? I figured I would ask before I start delving into the cython methods `triangulate_indices` and `triangle_plane_intersect`

**Comment by atmyers** [comment]
The mesh line annotation works by triangulating the mesh and intersecting all the resulting triangles with the plane of the slice. The problem is, when slice exactly intersects the element boundaries, the triangles either lie in the plane or touch it exactly without going through, which throws off the intersection calculation. I think a way to fix it would be to detect when this happens and wiggle the plane up or down by epsilon.

**Comment by lindsayad** [comment]
Do you remember how you generated the `connectivity_coords` and `connectivity_indices` for the fake hexahedral dataset? I was interested in trying to reproduce with a much smaller mesh, 4x4x4 elements on a cube with corners [-1,-1,-1], [1, 1, 1], and slicing at z = 0 (which should be right where we have element boundaries), but the mesh annotation was flawless.

**Comment by atmyers** [comment]
IIRC, it's exported from the MOOSE example hex dataset - the one that looks like a beer mug. Is the mesh annotation also buggy on that dataset when loaded directly?

**Comment by lindsayad** [comment]
Hmm, here's what the volume rendered fake_hexahedral dataset looks like:

![selection_180](https://cloud.githubusercontent.com/assets/10248304/26558661/2741370e-4470-11e7-84ea-91bd882d7295.png)
![selection_179](https://cloud.githubusercontent.com/assets/10248304/26558662/2742035a-4470-11e7-867d-8ada74f5bd02.png)
![selection_178](https://cloud.githubusercontent.com/assets/10248304/26558663/2749ec5a-4470-11e7-9d07-b69d44927854.png)

The only hex8 data-set I found in our exodus ii frontend is the two part cylinder in `MOOSE_sample_data/out.e-s010`.
