### ISSUE TITLE
Doc notebooks are not properly evaluated

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1275]
Originally reported by: **Kacper Kowalik (Bitbucket: [xarthisius](https://bitbucket.org/xarthisius), GitHub: [xarthisius](https://github.com/xarthisius))**

----------------------------------------

There's no difference between ["raw"](http://yt-project.org/docs/dev/analyzing/analysis_modules/Particle_Trajectories.ipynb) and ["evaluated"](http://yt-project.org/docs/dev/analyzing/analysis_modules/Particle_Trajectories_evaluated.ipynb)

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1275

**Comment by ngoldbaum** [comment]
@Xarthisius sorry for taking so long to get to this. I just cut a new release of RunNotebook on pypi. Can you try installing the updated version in the docker environment that builds the docs?

**Comment by Xarthisius** [comment]
```
fido@a13f4ca2ecd9 ~ $ pip list --format=columns | grep Run
RunNotebook                  0.2
```

**Comment by ngoldbaum** [comment]
This is fixed now.
