### ISSUE TITLE
Run subset of unittests on Travis or Drone.io

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1276]
Originally reported by: **Kacper Kowalik (Bitbucket: [xarthisius](https://bitbucket.org/xarthisius), GitHub: [xarthisius](https://github.com/xarthisius))**

----------------------------------------

* Identify the minimum set of tests that would fit the free tier
* Setup webhooks

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1276

**Comment by ngoldbaum** [comment]
See #1356
