### ISSUE TITLE
Unable to filter a dataset using a derived field

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1278]
Originally reported by: **Danielle Sponseller (Bitbucket: [DSponseller](https://bitbucket.org/DSponseller), GitHub: Unknown)**

----------------------------------------

When defining a particle filter, a derived field cannot be used to determine which particles to filter out. The example below shows a field defined to be equivalent to the "particle_position_x" field. When using "particle_position_x' in the filter definition, the filter works as expected, however when the derived field is used an error is returned saying that the field cannot be found.

```
#!python

import yt

@yt.particle_filter(requires=["myField"], filtered_type='all')
def small_x(pfilter, data):
    filter = data[(pfilter.filtered_type, "myField")] < 0
    return filter

def myField(field, data):
    return data["particle_position_x"]

snap = 'GadgetDiskGalaxy/snapshot_200.hdf5'

ds = yt.load(snap)
ds.add_particle_filter('small_x')
ds.add_field("myField", function=myField, units="kpc", particle_type=True)

plot = yt.ParticlePlot(
    ds,
    ('small_x', 'particle_position_x'),
    ('small_x', 'particle_position_y'),
    ('small_x', 'myField'),
    width=(2000, 'kpc'))

plot.save("Plot")

```

Running this script produces the following error:

```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    width=(2000, 'kpc'))
  File "/Users/goldbaum/Documents/yt-hg/yt/visualization/particle_plots.py", line 399, in ParticlePlot
    x_field = ad._determine_fields(x_field)[0]
  File "/Users/goldbaum/Documents/yt-hg/yt/data_objects/data_containers.py", line 1088, in _determine_fields
    finfo = self.ds._get_field_info(ftype, fname)
  File "/Users/goldbaum/Documents/yt-hg/yt/data_objects/static_output.py", line 666, in _get_field_info
    raise YTFieldNotFound((ftype, fname), self)
yt.utilities.exceptions.YTFieldNotFound: Could not find field '('small_x', 'particle_position_x')' in snapshot_200
```

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1278

**Comment by ngoldbaum** [comment]
We should add some validation or error checking so that the error message is better.
