### ISSUE TITLE
1D Exodus II support

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1283]
Originally reported by: **Andrew Myers (Bitbucket: [atmyers](https://bitbucket.org/atmyers), GitHub: [atmyers](https://github.com/atmyers))**

----------------------------------------

Right now, the Exodus II frontend can read 2D and 3D datasets, but not 1D. Adding support for 1D should not be too hard. 

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1283

**Comment by ngoldbaum** [comment]
This appears to work now.
