### ISSUE TITLE
Halo catalog weirdness under python3

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1290]
Originally reported by: **Nathan Goldbaum (Bitbucket: [ngoldbaum](https://bitbucket.org/ngoldbaum), GitHub: [ngoldbaum](https://github.com/ngoldbaum))**

----------------------------------------

Right now the halo catalog infrastructure does something fishy with field names in python 3. Specifically, take a look at input cell 16 in this notebook:

http://yt-project.org/docs/dev/cookbook/halo_analysis_example.html#Plotting-Radial-Profiles

Note how it uses stringified versions of field tuples. The field names are somehow getting converted to strings and this is making it into output files. This isn't what happens in python2.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1290

**Comment by brittonsmith** [comment]
This has been moved to [yt_astro_analysis](https://github.com/yt-project/yt_astro_analysis) Issue [#4](https://github.com/yt-project/yt_astro_analysis/issues/4)
