### ISSUE TITLE
Dimensions for energy fields are confusing

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1301]
Originally reported by: **John ZuHone (Bitbucket: [jzuhone](https://bitbucket.org/jzuhone), GitHub: [jzuhone](https://github.com/jzuhone))**

----------------------------------------

The dimensions for `("gas", "thermal_energy")` are of specific energy, energy per unit mass.

The dimensions for `("gas", "kinetic_energy")` are of energy per unit volume. 

Different hydro codes adopt different dimension conventions for total energy and thermal energy. It seems that we need a consistent naming scheme for these that is unambiguous, e.g. perhaps `("gas", "kinetic_energy_density")`?

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1301

**Comment by ngoldbaum** [comment]
Related to #912
