### ISSUE TITLE
Add capability to visualize a single variable on multiple meshes

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1307]
Originally reported by: **Alexander Lindsay (Bitbucket: [al007](https://bitbucket.org/al007), GitHub: [al007](https://github.com/al007))**

----------------------------------------

- Starting with SlicePlot initially, it would be great to be able to visualize a variable that exists on multiple (most often geometrically and physically connected) mesh blocks. 
- This is probably unique to UnstructuredMesh (at least for now)

Currently have a hacky solution...will refine over the next couple days.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1307

**Comment by ngoldbaum** [comment]
This works now.
