### ISSUE TITLE
[Ramses] add possibility to force cosmological

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1311]
Originally reported by: **Corentin Cadiou (Bitbucket: [cphyc](https://bitbucket.org/cphyc), GitHub: [cphyc](https://github.com/cphyc))**

----------------------------------------

Regarding discussions on pull request #2491, it would be great to be able to tell yt whether a simulation is a cosmological one by implementing an extra `force_cosmological` flag into the RAMSES data loader.

The code would override any detection of the nature of the simulation using the value given in the flag. This can be useful for some cosmological simulations running down to `z<0` with `H0=1` that are detected as non-cosmological ones.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1311

**Comment by ngoldbaum** [comment]
@cphyc let me know if you need a hand moving your pull request from bitbucket to github. It would be awesome if we could get this merged.

**Comment by cphyc** [comment]
Hi @ngoldbaum I haven't had much time to spend on this issue as it's not on top of my TODO-list for now.
I'll redo the PR on github as soon as I get time.
