### ISSUE TITLE
Better support for arepo data

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1318]
Originally reported by: **Anonymous**

----------------------------------------

It seems like something recently changed in the frontend that underestimates gas temperatures in Arepo file structures.  I recently went back to a simulation to re-evaluate a temperature-based calculation, and found that all the ('gas','temperature') values seem too low by several orders of magnitude.

I'm not sure what's going on, but for example when I compare ('PartType0','Temperature') to ('gas','temperature') in a small volume of the simulation (cosmo. simulation centered on the galaxy), you can see that the distribution of temperatures look very different/offset from each other.  (Histograms attached).

Any help is appreciated.  

Thanks!
-Kyle Stewart

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1318

**Comment by jzuhone** [comment]
This issue has been closed in `main` for a while, so closing.
