### ISSUE TITLE
Shouldn't need to demote 2nd order tets in CartesianCoordinateHandler.pixelize

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1324]
Originally reported by: **Alexander Lindsay (Bitbucket: [al007](https://bitbucket.org/al007), GitHub: [al007](https://github.com/al007))**

----------------------------------------

Hypothetically, #2401 should make it so we don't have to demote second order tets when slicing through a 3D mesh, e.g. this check:

`elif field_data.shape[1] == 10`

should be removable. I would like to test this first though.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1324

**Comment by ngoldbaum** [comment]
@lindsayad still an issue?

**Comment by lindsayad** [comment]
No, this was closed by https://bitbucket.org/yt_analysis/yt/pull-requests/2550/turn-off-undesirable-reduction-to-first/diff
