### ISSUE TITLE
Add second order support for QUADS

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#1335]
Originally reported by: **Alexander Lindsay (Bitbucket: [al007](https://bitbucket.org/al007), GitHub: [al007](https://github.com/al007))**

----------------------------------------

MOOSE users fairly commonly use second order LAGRANGE polynomials on quad elements; want to natively support visualization on such elements without reverting to first order.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/1335

**Comment by ngoldbaum** [comment]
@lindsayad you did this, right?

**Comment by lindsayad** [comment]
Correct. Closed by https://bitbucket.org/yt_analysis/yt/pull-requests/2549/add-visualization-support-for-quad9/diff
