### ISSUE TITLE
annotate_timestamp fails for ParticlePlot

### ISSUE THREAD

**Issue by hyschive** [yt-project/yt#1384]
**Bug summary**
The annotate_timestamp() function does not work for ParticlePlot. The generated figure does not have the timestamp.

```python
import yt
ds = yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")
p = yt.ParticlePlot(ds, 'particle_position_x', 'particle_position_y', 'particle_mass', width=(0.5, 0.5))
p.annotate_timestamp()
p.save()
```

**Version Information**

  * Operating System: Linux
  * Python Version:  2.7.11
  * yt version: 3.4-dev (changeset a4ee70dfbcb9)

**Comment by ngoldbaum** [comment]
Hey Justin,

The callback is working, it's just drawing white text on a white background. Try with

```
p.annotate_timestamp(text_args={'color': 'k'})
```

Are you ok with closing this issue? I guess in principle we could talk about changing the default font color to black to avoid this issue.

**Comment by hyschive** [comment]
Hi Nathan,

You are correct. Sorry, I should have checked it more carefully. Thanks for
helping look into it! I've closed this issue.

Sincerely,
Justin
