### ISSUE TITLE
YT_DIR and GIT_EXE in the all-in-one script need fixes

### ISSUE THREAD

**Issue by astroboylrx** [yt-project/yt#1401]
### Bug report

**Bug summary**

When I try to install a standalone yt using the [all-in-one script](https://github.com/yt-project/yt/blob/master/doc/install_script.sh), @ngoldbaum 

(1), it seems that [YT_DIR](https://github.com/yt-project/yt/blob/master/doc/install_script.sh#L43) does not do anything, I still need to set YT_DEST and DEST_DIR to install yt to a specific path (different with the path containing the install_script.sh)

(2), even though git is already installed and INST_GIT is set to 0, [this line of code](https://github.com/yt-project/yt/blob/master/doc/install_script.sh#L1424) still assigns GIT_EXE in a wrong way. Maybe [this previous assignment](https://github.com/yt-project/yt/blob/master/doc/install_script.sh#L1077) was intended to control it?

**Code for reproduction**

```bash
$ bash ./install_script.sh
```

**Actual outcome**

```bash
# (1), the script outputs
...
Installation will be to
  /the/path/containing/install_script/yt
...
# This is not what I intended. 
# After setting both YT_DEST and DEST_DIR to another path I wanted, it worked.

# (2), the script failed at a certain point
...
Installing netcdf4
********************************************
        FAILURE REPORT:
********************************************

hdf4-4.2.12-0. 100% |###############################| Time: 0:00:01 801.02 kB/s
libnetcdf-4.4. 100% |###############################| Time: 0:00:01   1.37 MB/s
netcdf4-1.2.7- 100% |###############################| Time: 0:00:04 606.65 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
EXECUTING:
  /the/path/chosen/by/me/yt/bin/git clone https://github.com/yt-project/yt_conda /the/path/chosen/by/me/yt/src/yt_conda
./install_script.sh: line 498: /the/path/chosen/by/me/yt/bin/git: No such file or directory

********************************************
********************************************
Failure.  Check /the/path/chosen/by/me/yt/yt_install.log.  The last 10 lines are above.
```

**Expected outcome**

Not applicable.

**Version Information**

  * Operating System: GNU/Linux 2.6.32-431.el6.x86_64
  * Python Version: 2.7.10; 3.5.2
  * yt version: 3.4-dev
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
Sorry for the trouble, I didn't try testing with `INST_GIT=0` when I updated the install script for the git transition. Let me see if I can make a pull request to fix this.

**Comment by ngoldbaum** [comment]
See #1402

**Comment by astroboylrx** [comment]
Thank you so much for the prompt reply! :-)
