### ISSUE TITLE
VR Multiple Fields

### ISSUE THREAD

**Issue by eganhila** [yt-project/yt#1410]
**Bug summary**

 I'm trying to plot two fields at once by adding them independently as VolumeSources, but when I render the image they seem flipped relative to one another on the x-axis. Everything seems fine when I plot the fields as slices, so it's something going on in the volume rendering.

**Code for reproduction**

Script: https://pastebin.com/ci3u68C9
Data: http://use.yt/upload/1ca4b2cd

**Actual outcome**

http://imgur.com/a/JeFkN

**Expected outcome**
Same plots, but the volume rendering isn't flipping the H+ relative to the O2+

**Version Information**
yt 3.3.5 installed via pip

**Comment by ngoldbaum** [comment]
See #1411 

![uniformgriddata_render_h_p1_number_density](https://cloud.githubusercontent.com/assets/3126246/26264383/3c877bc6-3ca2-11e7-9b7b-93588b18756d.png)
