### ISSUE TITLE
Update to yt2 fails

### ISSUE THREAD

**Issue by pgrete** [yt-project/yt#1413]
### Bug report

**Bug summary**

Updating to an old yt2 version fails.

**Code for reproduction**

```bash
git checkout origin/yt-2.x
python setup.py develop
```

**Actual outcome**

```
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    if StrictVersion(setuptools.__version__) < StrictVersion('0.7.0'):
  File "/gfs2/work/nipgrete/yt-conda-py2/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/gfs2/work/nipgrete/yt-conda-py2/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '33.1.1.post20170320'
```

**Expected outcome**
Working yt2 version.

**Version Information**

  * Operating System: SUSE Linux Enterprise Server 11 (x86_64)
  * Python Version: Python 2.7.13
  * yt version: yt-2.x

Dependencies via conda, yt from source.

**Comment by ngoldbaum** [comment]
This isn't a problem with yt per se. Somehow you have a version of setuptools installed with a version number that distutils doesn't understand. Try pip uninstalling and reinstalling setuptools.
