### ISSUE TITLE
cyglfw3 on use.yt conda channel doesn't have an osx-64 build

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1416]
As documented here, I'm supposed to be able to conda install the dependencies for the IDV volume rendering:

http://yt-project.org/docs/dev/visualizing/interactive_data_visualization.html#installation

But right now that's breaking on my laptop:

```
PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels:
  - cyglfw3
```

Presumably we just need to upload a new build. Long term we should think about contributing these packages to conda-forge and just using their build infrastructure.

**Comment by Xarthisius** [comment]
I started working the long term solution. However, glfw3 requires a lot of dependencies that are currently missing in conda-forge. Waiting 26d for the approval for the first of them doesn't bode well... [1]

[1] https://github.com/conda-forge/staged-recipes/pull/2869

**Comment by ngoldbaum** [comment]
Ah yeah you need to ping the conda-forge maintainers sometimes. I've just done so.

**Comment by munkm** [comment]
The conda references in these docs were removed by 415efb989c2136e2b00ad199461595815ba77ec3 . Do you all think this is worth closing (@Xarthisius) as is, or should we add back in the conda references because the channel has been fixed?

**Comment by matthewturk** [comment]
So I think we should close this.  In my experimental branch, I have gotten rid of cyglfw3.
