### ISSUE TITLE
ParticlePlots have problems with log-based fields

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#1448]
### Bug report

**Bug summary**

When one attempts to make a ParticlePhasePlot of a particle-based dataset and take log-based fields like density and temperature, you get pixels that are in linear space stretched into log space.  I guess the ParticlePlot infrastructure has mostly been used with linear fields up until now (as is done in the documentation).  I think the expected behavior is for the pixels to be in log space, as they are for PhasePlots with grid-based fields.  Perhaps this is already possible, but I didn't see any mention of it in the docs, and couldn't find any relevant methods associated with the ParticlePlot class.

**Code for reproduction**

```python
import yt
ds = yt.load("FIRE_M12i_ref11/snapshot_600.hdf5")
p = yt.ParticlePlot(ds, ('PartType0', 'density'), ('PartType0', 'temperature'), [('PartType0', 'particle_mass')])
p.set_log('density', True)
p.set_log('temperature', True)
p.save()
```

**Actual outcome**

![snapshot_600_2d-profile_density_temperature_particle_mass](https://user-images.githubusercontent.com/8250999/27020572-506335a6-4ef7-11e7-8898-be90b804c5ca.png)

**Version Information**

  * Operating System: OS X
  * Python Version: 2.7.12
  * yt version: 3.3.5
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
Just to clarify, the issue is that we're using linear-spaced bins, when you want log-spaced bins?
