### ISSUE TITLE
Potential Python 3 bug in insert_image_yt and proposed fix

### ISSUE THREAD

**Issue by jsmidt** [yt-project/yt#1497]
When I try and use the "Publication-ready Figures" examples I get the following error:

>   File "/turquoise/users/jsmidt/my_conda/lib/python3.6/site-> 
> packages/yt/visualization/eps_writer.py", line 521, in insert_image_yt
>    self.field = plot.plots.keys()[0]
> TypeError: 'dict_keys' object does not support indexing

Which seems related to this issue where in Python 3 dictionary keys are not lists: https://stackoverflow.com/questions/17322668/typeerror-dict-keys-object-does-not-support-indexing

However, if you change change 

`self.field = plot.plots.keys()[0]`

to 

`self.field = list(plot.plots.keys())[0]`

in line 520 of yt/visualization/eps_writer.py, the problem seems to go away in my Python 3.6.

**Comment by ngoldbaum** [comment]
The EPS writer is unfortunately not very well tested. Your suggested change sounds good. Would you like to make a pull request?

**Comment by jsmidt** [comment]
Done.
