### ISSUE TITLE
Multiple sampling lines for LinePlot

### ISSUE THREAD

**Issue by lindsayad** [yt-project/yt#1505]
### Enhancement request

In multi-dimension simulations, it would be nice to have multiple sampling lines, e.g. multiple start and end points for `LinePlot`. E.g. I might want to plot and compare a quantity at r = 3 and r = 5 in an RZ geometry. At first thought it seems like the easiest way to accomplish this is by making the `LinePlot` attributes `start_point` and `end_point` optionally an iterable of iterables, without disrupting the current default behavior of taking a single iterable (e.g. a point with x, y, (z) coordinates). But then it seems like there would be some trickery/inconvenience with handling both the option of a single point vs. multiple points. Looking for others thoughts...

**Comment by ngoldbaum** [comment]
Maybe it would be useful to use an alternate initializer? E.g. `LinePlot.from_lines`? The most straightforward way to do that is with a classmethod, see `ProfilePlot.from_profiles`.

**Comment by lindsayad** [comment]
Closed by #1509
