### ISSUE TITLE
ProjectionPlot gives odd behavior with data_sources kwargs

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#1522]
### Bug report

**Bug summary**

In the demeshening branch, projections appear to give odd results when used with the `data_objects` keyword.  When used with spheres, the script will crash.  When used with cubes,
it will sometimes give a projection of all zeros if the box size is too small (but not so small that it doesn't contain particles).

**Code for reproduction**

```
import yt
ds = yt.load('FIRE_m12i_ref11/snapshot_600.hdf5')
c = ds.find_max(('gas', 'density'))[1]
sp = ds.sphere(c, (1, 'Mpc'))
p = yt.ProjectionPlot(ds, 'x', ('gas', 'density'), center=c, width=(2, 'Mpc'), data_source=sp)
p.save()
```

This crashes with the error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    p = yt.ProjectionPlot(ds, 'x', ('gas', 'density'), center=c, width=(1, 'Mpc'), data_source=sp)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/plot_window.py", line 1533, in __init__
    aspect=aspect)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/plot_window.py", line 678, in __init__
    PlotWindow.__init__(self, *args, **kwargs)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/plot_window.py", line 231, in __init__
    self._setup_plots()
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/plot_window.py", line 797, in _setup_plots
    image = self.frb[f]
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/visualization/fixed_resolution.py", line 136, in __getitem__
    int(self.antialias))
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/geometry/coordinates/cartesian_coordinates.py", line 136, in pixelize
    antialias, dimension, periodic)
  File "/Users/chummels/src/yt-conda/src/yt-git/yt/geometry/coordinates/cartesian_coordinates.py", line 176, in _ortho_pixelize
    le = data_source.data_source.left_edge.in_units('code_length')
AttributeError: 'YTSphere' object has no attribute 'left_edge'
```

Additionally, if you use a cube data_source, such as:

```
import yt
ds = yt.load('FIRE_m12i_ref11/snapshot_600.hdf5')
c = ds.find_max(('gas', 'density'))[1]
arr = ds.arr([200., 200., 200.], 'kpc')
box = ds.box(c-arr, c+arr)
p = yt.ProjectionPlot(ds, 'x', ('gas', 'density'), center=c, width=(2, 'Mpc'), data_source=box)
p.save()
```
the code will run, but it produces a flat image full of zeros:

![snapshot_600_projection_x_density](https://user-images.githubusercontent.com/8250999/28899641-1676441e-77a1-11e7-8d65-37eabf6e3410.png)

If I increase the `box` size to 1 Mpc, it gives correct results:

![snapshot_600_projection_x_density](https://user-images.githubusercontent.com/8250999/28899660-4432d0b6-77a1-11e7-9d4e-94abcd23b962.png)

**Version Information**
  * Operating System: OS X 10.11.6
  * Python Version: 3.6.2
  * yt version: demeshening

**Comment by MatthewTurk** [comment]
This demonstrates some of the tricky bits with respect to the demeshening, in that now the projections are not "generate once use many" and so they don't necessarily cover the whole domain.  (In the past, even if the data source was not the whole domain, we had an upper bound for the extent so we did not need to calculate it; here we do not have such an upper bound, so the region extent is computed.)  There's probably a way around this by either adding a `bounding_box` attribute to data objects or by just over-estimating them.

**Comment by ngoldbaum** [comment]
I want to spend some time rewriting how particle projections work in the demeshening. Right now it's really hacky and I'd like to make it work more like AMR projections (e.g. by smoothing onto a quadtree) to avoid needing to reimplement all the projection options and hopefully reuse a lot of the existing code in `YTQuadTreeProj`.

**Comment by MatthewTurk** [comment]
If you are up for it, I would actually like to consider making it work on the quadtree a blocker.

The biggest thing that would need to be done is to get an estimate, even if extremely coarse, of the locations that the quadtree would need to fill out.  Otherwise you will end up in a situation where you need to track particles along with the projection process.

**Comment by ngoldbaum** [comment]
Yup, I definitely want to work on this when I come back to the demeshening stuff after 3.4 gets released.

**Comment by chummels** [comment]
I re-tested the script described in this issue with the PR that @MatthewTurk just created (https://github.com/ngoldbaum/yt/pull/5), and this problem goes away.  Well, not the issue that spheres don't work as data objects in demesh, but the flat image issue above.  Hooray.  

Instead of a flat image, the script now yields:

![snapshot_600_projection_x_density](https://user-images.githubusercontent.com/8250999/39773889-2c1d9b76-52ae-11e8-84cb-7dcab82edb78.png)
