### ISSUE TITLE
AHF answer tests are flaky

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1528]
We're seeing random failures from the AHF answer tests on some PRs.

See e.g. https://tests.yt-project.org/job/yt_py3_git/414/.

**Comment by ngoldbaum** [comment]
Ping @qobilidop.

**Comment by qobilidop** [comment]
Looks like [the `h=0.7` difference](https://github.com/yt-project/yt/commit/7e7832b45ba9bfc0b1bf9f8d085a1453144003b9). I tried to update the answer tests in this [commit](https://github.com/yt-project/yt/commit/cb18d7aed74838cebe5588e46685d61ad2ca776f). Maybe this is not done correctly?

**Comment by ngoldbaum** [comment]
Hmm, odd, maybe there was a cache issue. Let me see if I can reproduce this on the test box.
