### ISSUE TITLE
Latest ver of yt (3.5dev) breaks clump finding on FITS files

### ISSUE THREAD

**Issue by afitts** [yt-project/yt#1601]
### Bug report

**Bug summary**

When attempting to use the find_clumps function on a master_clump created from a FITS file, the code fails. This functionality works fine with yt ver 3.2.3.

**Code for reproduction**

```python

# dataset for this code can be found at: http://use.yt/upload/acccd520

import yt
from yt.mods import *
from yt.analysis_modules.level_sets.api import *

pf2 = load("function05_fits_018_2_proj.fits")
master_clump = Clump(pf2.all_data(), "density")
c_max = 10**np.floor(np.log10(pf2.all_data()['density']).max()+1)
c_min = 2e-4
find_clumps(master_clump, c_min, c_max, 1.5)
```

**Actual outcome**

```
/nobackupp8/afitts/yt/yt/analysis_modules/level_sets/contour_finder.pyc in identify_contours(data_source, field, min_val, max_val, cached_fields)
     43         nid = node.node_id
     44         node_ids.append(nid)
---> 45         values = g[field][sl].astype("float64")

IndexError: too many indices for array
```

**Expected outcome**

The contour finder should have no trouble passing the sl variable to g[field] (and the find_clumps function should go off without a hitch! works in yt 3.2.3)

**Version Information**

  * Operating System: Linux
  * Python Version: 2.7.12
  * yt version: 3.5dev
  * Other Libraries (if applicable):

**Comment by jzuhone** [comment]
@afitts sorry I haven't figured this out yet--I'll try to get to it soon.

**Comment by afitts** [comment]
No worries @jzuhone, I'm using yt 3.2.3 for the time being.

**Comment by ngoldbaum** [comment]
Bisected to 9c913f66c, although the problem initially crops up with a slightly different error in ffd9edfbbfd. So this has something to do with adding support for nodal fields.

**Comment by ngoldbaum** [comment]
I've put in #1603 to fix this.
