### ISSUE TITLE
Gadget (and related frontends) internal energy unit is wrong for cosmological simulations

### ISSUE THREAD

**Issue by qobilidop** [yt-project/yt#1610]
### Bug report

**Bug summary**

[User guide for GADGET-2](https://wwwmpa.mpa-garching.mpg.de/gadget/users-guide.pdf) says to use `(km/s) ** 2` as the unit for internal energy. But in yt, the internal energy is given the unit `code_velocity ** 2`, which is equivalent to `(km/sec) ** 2 * a` in cosmological simulations. The extra scale factor `a` is unwanted. This makes temperature calculation off by a factor of `a`, such that `T_yt == a * T_true`.

**Code for reproduction**

```python
import yt

ds = yt.load(f'gizmo_64/output/snap_N64L16_085.hdf5')
ds.index
print(ds.field_info['PartType0', 'InternalEnergy'])
print(ds.quan(1, 'code_velocity ** 2').to('(km/s) ** 2'))
print(ds.scale_factor)
```

**Actual outcome**

```
On-Disk Field (PartType0, InternalEnergy): (units: code_velocity ** 2, particle field)
0.33333329781543247 km**2/s**2
0.333333297815
```

**Expected outcome**

The `units` is expected to be `(km/s) ** 2` or `code_specific_energy` that could be defined elsewhere.

```
On-Disk Field (PartType0, InternalEnergy): (units: code_specific_energy, particle field)
1.0 km**2/s**2
0.333333297815
```

**Version Information**

  * Operating System: macOS Sierra 10.12.6
  * Python Version: 3.6.3
  * yt version: 3.5.dev0 (commit [7d58e69](https://github.com/yt-project/yt/commit/7d58e699a2b5e1271a5d5a979647bff62ac6426b))

**Comment by ngoldbaum** [comment]
Ping @dnarayanan

**Comment by dnarayanan** [comment]
hmm i actually don't know if that factor scale factor should be in there or not.    this might be a question for the gadget users list serv.  apologies :(

**Comment by jzuhone** [comment]
I’m not a gadget expert, but my recollection from seeing their documentation (of various gadget derivatives) is that the scale factor is not there.

**Comment by qobilidop** [comment]
@astrosmith @atmyers @brittonsmith @bwkeller @jzuhone @lindsayad @MatthewTurk @ngoldbaum. You are pinged because you have touched the `fields.py` file for the EAGLE, OWLS or TIPSY frontend, which might be potentially influenced by this issue. In #1611 I have proposed to change the default units for `SPHDataset`'s `InternalEnergy` field from `code_velocity ** 2` to `code_specific_energy`, which defaults to `(km/s) ** 2`. I'm not sure if that's the correct assumption for all the frontends inherited from `SPHDataset`. If that's not correct, let's discuss it here how to best resolve the issue.

**Comment by dnarayanan** [comment]
bringing in @chummels as well for good measure

**Comment by bwkeller** [comment]
Tipsy doesn't write internal energy in the main tipsy files, but it is sometimes written out in a '.u' auxiliary file.  In that case, it uses code_velocity ** 2 units.

**Comment by chummels** [comment]
I have confirmed with Phil that gizmo represents internal energy as a physical unit not a comoving unit, so your fix is correct for dealing with gizmo datasets.  Thanks for tracking down this bug, @qobilidop !

**Comment by chummels** [comment]
It's also worth noting that gadget's internal energy should be in physical units too, as you correctly find in the user guide.

**Comment by qobilidop** [comment]
@bwkeller Thanks for looking! As I rethink about it, my previous description about `code_specific_energy` is not so accurate. The `code_specific_energy` is defined at the `Dataset` level, such that if `Dataset.specific_energy_unit` is not defined, `code_velocity ** 2` would be used,  which is the case for Tipsy. So in summary, there's no internal energy unit change for Tipsy. Sorry for the interruption, it took me a while to think this through.

**Comment by qobilidop** [comment]
@chummels and Phil, thanks for the confirmation!
