### ISSUE TITLE
annotate_grids() doesn't work with axisymmetric data (but should; easy fix potentially)

### ISSUE THREAD

**Issue by zingale** [yt-project/yt#1617]
### Bug report

If you do a slice plot of 2-d axisymmetric data (known as `cylindrical` to yt) the `.annotate_grids()` method does not work because of a check on geometry

**Code for reproduction**
```
import yt
from yt.units import cm

ds = yt.load("plt00010")
slc = yt.plot_2d(ds, "temperature", origin="native")
slc.annotate_grids()
slc.save("test.png")
```

**Actual outcome**

It fails with the `annotate_grids()` callback

**Expected outcome**
an axisymmetric grid is really just Cartesian with volume factors that are used for integration, etc.  So the grid plotting should not care if it is axisymmetric.  By simply editing `yt/visualizations/plot_modifications.py` and adding`cylindrical` to the `_supported_geometries` tuple in `GridBoundaryCallback`, the grids plot as expected.

My only uncertainty is what to do for 2-d cylindrical data that is r-theta?  I'd like to fix this for axisymmetric (and maybe yt should recognize axisymmetric as a geometry?), but not mislead people to think that r-theta works.

**Version Information**

Latest github on linux (Fedora 26)

  * Operating System:
  * Python Version:
  * yt version:
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
Yes this is a longstanding issue. I’d prefer just to figure out an implementation that works for all curvilinear coordinate system. However, if you don’t want to do that then I guess adding cylindrical to the list of supported geometries, but only failing for r-theta or z-theta slices is acceptable.

**Comment by ngoldbaum** [comment]
Also see #1598 which adds support for cylindrical geometries to a number of the callbacks.

**Comment by maxpkatz** [comment]
Running with the latest version of yt (which includes #1598) seems to fix this issue for me, using a 2d cylindrical AMReX dataset. So I think we can consider this closed.
