### ISSUE TITLE
SlicePlot of 2D cylindrical simulations does not correctly apply center coordinate

### ISSUE THREAD

**Issue by maxpkatz** [yt-project/yt#1663]
### Bug report

A SlicePlot applied to 2D cylindrical simulation (using theta as the slice direction) always centers on the center of the dataset, even if a different center is passed as an argument to the constructor.

**Code for reproduction**

This can be reproduced using the yt sample FLASH dataset, WDMerger_hdf5_chk_1000. I would expect the following to work:

```python
 ds = yt.load('WDMerger_hdf5_chk_1000/WDMerger_hdf5_chk_1000.hdf5')
 yt.SlicePlot(ds, 'theta', 'density', center=[2.e9, 0.0, 0.0], width=1.e9, origin='native').save()
```

**Actual outcome**

This generates an image which has a width of 1.e9 cm, which is centered at r = R / 2, z = 0, where R == 1.31e10 cm is the radial width of the dataset.

**Expected outcome**

I would expect the image to be centered at r = 2.e9, z = 0. I can achieve the expected outcome if I first create the SlicePlot and then set the center:

```python
 ds = yt.load('WDMerger_hdf5_chk_1000/WDMerger_hdf5_chk_1000.hdf5')
 sp = yt.SlicePlot(ds, 'theta', 'density', width=1.e9)
 sp.set_center([2.e9, 0.0]).save()
```

**Version Information**

  * Operating System: SLES 11 (Titan)
  * Python Version: 3.5.1
  * yt version: 3.4.0, installed via pip
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
Thanks for the clear description. Seems like a straight up bug to me.

**Comment by zingale** [comment]
I just ran this with yt 3.5dev0 from a fresh `git pull`, using python 3.6.5.  Here's the output:

![wdmerger_hdf5_chk_1000 hdf5_slice_theta_density](https://user-images.githubusercontent.com/7817509/41486512-cd165ece-70b2-11e8-989b-0e217b774fb7.png)

I _believe_ this matches the "expected output", suggesting that this is fixed.  I am not sure though what is happening for the one zone perimeter around the border.

**Comment by zingale** [comment]
oh I see -- those artifacts are referenced in a different issue (#1669).

So I think this issue is fixed and can be closed.
