### ISSUE TITLE
SlicePlot artifacts on corners/edges

### ISSUE THREAD

**Issue by maxpkatz** [yt-project/yt#1669]
### Bug report

A SlicePlot of a 2D cylindrical dataset has artifacts on the edges and corners that do not represent the underlying data.

**Code for reproduction**

This can be reproduced using the same dataset and plot as #1663. Download the WDMerger_hdf5_chk_1000 sample dataset, and then do a sliceplot:

```python
# import yt
# ds = yt.load('WDMerger_hdf5_chk_1000/WDMerger_hdf5_chk_1000.hdf5')
# yt.SlicePlot(ds, 'theta', 'density', width=1.e9).set_center([2.e9, 0.0]).save()
```

**Actual outcome**

![wdmerger_hdf5_chk_1000 hdf5_slice_theta_density](https://user-images.githubusercontent.com/8052594/34921634-319783a0-f93a-11e7-9708-87240f332695.png)

Note the spurious "hotspots" in the corners, and the solid lines along the edges.

**Version Information**
  * Operating System: SLES 11
  * Python Version: 3.5.1
  * yt version: Development (eb3358c622bc047200b9bc6a954ddee8f59a0e07)
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
I can reproduce this.

**Comment by MatthewTurk** [comment]
I was able to demonstrate that this is a problem with the width setting by comparing the results of these two:

```
yt.SlicePlot(ds, 'theta', 'ones', width=1.e9)
yt.SlicePlot(ds, 'theta', 'ones')
```
