### ISSUE TITLE
numpy 1.14.0 leads to recursion error when printing yt quantities

### ISSUE THREAD

**Issue by RicardaBeckmann** [yt-project/yt#1682]
### Bug report

With numpy version 1.14.0 (automatically installed with the install_script.sh), printing yt quantities to screen produces a "RecursionError: maximum recursion depth exceeded". Downgrading to  numpy 1.13.1 fixes the issue. 

### Code for reproduction
```python
from yt.units import m
print(m)
```

**Actual outcome**

```
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-4-c384c0c7b6c7> in <module>()
----> 1 print(m)

~/soft/yt-conda/lib/python3.6/site-packages/yt/units/yt_array.py in __str__(self)
    453 
    454         """
--> 455         return super(YTArray, self).__str__()+' '+self.units.__str__()
    456 
    457     #

~/soft/yt-conda/lib/python3.6/site-packages/numpy/core/arrayprint.py in array_str(a, max_line_width, precision, suppress_small)
   1398     # in quotes. So we return the str of the scalar value.
   1399     if a.shape == ():
-> 1400         return str(a[()])
   1401 
   1402     return array2string(a, max_line_width, precision, suppress_small, ' ', "")

... last 2 frames repeated, from the frame below ...

~/soft/yt-conda/lib/python3.6/site-packages/yt/units/yt_array.py in __str__(self)
    453 
    454         """
--> 455         return super(YTArray, self).__str__()+' '+self.units.__str__()
    456 
    457     #

RecursionError: maximum recursion depth exceeded
```

**Expected outcome**

The problem goes away when downgrading to numpy 1.13.1

**Version Information**

  * Operating System:
  * Python Version: 3.6.4
  * yt version: 3.3.5
  * Other Libraries (if applicable): numpy 1.14.0

I installed yt using the install script, and also tried updating both yt and all dependencies using conda to no avail. "conda install numpy=1.13.1" fixed the problem.

**Comment by ngoldbaum** [comment]
Hey Ricarda,

Thanks for the report. This is a known issue that's fixed on yt's master branch. Hopefully we'll have a new bugfix release out ASAP that will fix this for good. I'm closing since it's a known issue that's already fixed.
