### ISSUE TITLE
ParticleIDs loaded from Gadget binary snapshots are wrong

### ISSUE THREAD

**Issue by qobilidop** [yt-project/yt#1691]
### Bug report

**Bug summary**

ParticlesIDs are expected to be unique. But when loaded from a Gadget binary snapshot, the uniqueness is lost. This is likely to be caused by wrong assumptions of dtype during data loading.

**Code for reproduction**

```python
import yt

ds = yt.load('Gadget3-snap-format2/Gadget3-snap-format2')
ad = ds.all_data()
pid = ad['ParticleIDs']
print(len(pid), len(set(pid.v)))
```

**Actual outcome**

```
1370393 1201707
```

**Expected outcome**

```
1370393 1370393
```

I've done a test to first convert the snapshot to HDF5 and then do the same thing. It does yield the expected outcome.

**Comment by qobilidop** [comment]
So this line is causing the trouble:
https://github.com/yt-project/yt/blob/68b0e8f342bfadf188d02f8ae8696d3e81dee6ae/yt/frontends/gadget/io.py#L326

If changed to `return arr`, the expected outcome would be recovered. For `ParticleIDs`, this line converts the `dtype` from `uint32` to `float32`, during which the uniqueness is lost.

**Comment by ngoldbaum** [comment]
Clearly it's not correct to interpret an integer field as float32. We probably need a mapping from field names to field dtypes, e.g. adapting the listings in `yt/frontends/gadget/definitions.py`,

**Comment by qobilidop** [comment]
@ngoldbaum I agree that would be the long-term solution. For a short-term fix, would you be okay with simply changing that one line? I do think the `astype` part is redundant, because in previous lines `dtype` is already set to `dt` which would be `self._float_type` except for `ParticleIDs`.

**Comment by ngoldbaum** [comment]
Fair enough. I didn't notice the existing special-casing for Particle IDs above. +1 to just removing the astype call.
