### ISSUE TITLE
coordinates and fields value label:"help wanted"

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [yt-project/yt#1706]
I want to export data for other post-processing program. It it possible to get some numpy array in the following format:
`[mean_x_coordinate_of_cell, mean_y_coordinate_cell, mean_value_of_field]`
#

**Comment by ngoldbaum** [comment]
Sorry, I don't understanding what you're asking for. Can you elaborate a bit more what you are trying to do? I sense there's a language barrier so if you can include as much detail as possible it will help avoid us misunderstanding each other.

This issue tracker is primarily for tracking bugs and feature requests in yt, not as a forum for general help. For that I suggest contacting the yt-users mailing list or posting on StackOverflow in the future. This one time I'm happy to answer questions here but I'll be closing the issue so we don't track this as a yt bug.

**Comment by mahdikooshkbaghi** [comment]
Thanks for your prompt help:
here is the question on the stackoverflow:
https://stackoverflow.com/q/48969096/6905680
Best,
Mahdi
