### ISSUE TITLE
Weighted projections give incorrect results

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#1715]
### Bug report

**Bug summary**

When one tries to create a weighted projection in the demeshening branch, it looks like it's just giving a line integral of the `field * weight_field`, rather than a weighted average of `field`.

**Code for reproduction**

```
import yt
ds = yt.load('~/src/yt-data/snapshot_033/snap_033.0.hdf5')
yt.ProjectionPlot(ds, 'x', ('gas', 'temperature'), weight_field=('gas', 'density')).save('test.png')

```

**Actual outcome**

This yields this image--note the colorbar values.

![test](https://user-images.githubusercontent.com/8250999/37115219-628abb42-21ff-11e8-8439-35b1955edcea.png)

**Comment by ngoldbaum** [comment]
Currently the plan is to rewrite how projections get generated so I'm not planning on fixing this until there's some new projection infrastructure. The hope is that I won't need to rewrite all the projection options because it will just use the existing infrastucture we have for AMR codes.

If you want to fix this issue on your own using the current projection code feel free though.

**Comment by chummels** [comment]
Sure, I'm happy to fix this, because presumably it isn't a big change.  But I'm not entirely sure where to look in the code.  Can you point me in the right direction?

**Comment by ngoldbaum** [comment]
The core of the projection operation is here:

https://github.com/ngoldbaum/yt/blob/43f0bca675e4c0078c2c96626b5a8b29eade03f3/yt/geometry/coordinates/cartesian_coordinates.py#L270-L294

I think what you're going to need to do is check if `weight_field` is set and then do a second call to `pixelize_sph_kernel_projection` just for the weight field, then divide the first image by the image you get for that operation .

**Comment by chummels** [comment]
PR for this issue created here:

https://github.com/ngoldbaum/yt/pull/2

**Comment by chummels** [comment]
Resolved by the PR in @ngoldbaum 's repository.
