### ISSUE TITLE
Migrate from use.yt/with_conda to conda-forge

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1718]
Currently use.yt/with_conda is down and @Xarthisius tells me he doesn't have the bandwidth to maintain the service and make sure it stays up.

For the dependencies we are currently using it to provide pacakges for, we should either add those packages to conda-forge or rewrite the instructions for those dependencies to involve building yt and those dependencies from source.

For nightly binaries I'm not sure what to do. Probably just give up on them? Unless someone wants to take over maintenance or figure out a way to deploy nightly binaries with less maintenance burden for Kacper.

**Comment by qobilidop** [comment]
For nightly binaries, how about using TravisCI and AppVeyor for building and Anaconda Cloud for hosting? There's an [example in glueviz](https://github.com/glue-viz/conda-dev). If this is a viable option and no one else is already working on it, I'd like to have a try.

**Comment by ngoldbaum** [comment]
Please go ahead.

**Comment by qobilidop** [comment]
It's working! Here are some links:

- [GitHub](https://github.com/qobilidop/yt-conda-dev)
- [Travis CI](https://travis-ci.org/qobilidop/yt-conda-dev)
- [AppVeyor](https://ci.appveyor.com/project/qobilidop/yt-conda-dev)
- [Anaconda Cloud](https://anaconda.org/qobilidop/yt)

Now we can do this:
```
conda install -c qobilidop/label/dev yt
```

If it looks good, the next step would be moving the repo to yt-project and setting up various accounts. I might need some help on those things.

**Comment by chummels** [comment]
Whoa--nice @qobilidop !

**Comment by ngoldbaum** [comment]
That great!

Keep in mind that this issue isn't primarily about nightly builds of yt (although it's great to have those), but about binaries for the interactive data visualization dependencies.

Please feel free to open up pull requests mentioning the new nightly builds you've set up in the install instructions and on the website. Please also let me know if you need admin privileges to get these set up on yt's accounts on the various services you're using.

**Comment by jzuhone** [comment]
Nicely done!
