### ISSUE TITLE
Import error when installing yt from source

### ISSUE THREAD

**Issue by maxbeegee** [yt-project/yt#1727]
### Bug report

**Bug summary**

When doing a fresh install of yt from source, the import fails with the error message "Symbol not found: _GOMP_parallel".

**Code for reproduction**

I installed yt as documented in http://yt-project.org/docs/dev/installing.html#installing-yt-from-source, i.e., via

```
pip install -e .
```
The installation is also running fine, however, if I then import yt ("python -c 'import yt'") I obtain the error message stated below.

**Actual outcome**

```
/Users/maxbg/anaconda/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/maxbg/libs/python/my_yt/yt/yt/__init__.py", line 61, in <module>
    from yt.fields.api import \
  File "/Users/maxbg/libs/python/my_yt/yt/yt/fields/api.py", line 19, in <module>
    from . import angular_momentum
  File "/Users/maxbg/libs/python/my_yt/yt/yt/fields/angular_momentum.py", line 26, in <module>
    from .vector_operations import \
  File "/Users/maxbg/libs/python/my_yt/yt/yt/fields/vector_operations.py", line 30, in <module>
    from yt.utilities.lib.misc_utilities import obtain_rv_vec
ImportError: dlopen(/Users/maxbg/libs/python/my_yt/yt/yt/utilities/lib/misc_utilities.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /Users/maxbg/libs/python/my_yt/yt/yt/utilities/lib/misc_utilities.so
  Expected in: dynamic lookup
```

**Expected outcome**
I expect yt to import fine.
Before, I also installed yt via the anaconda installation (on the same machine) and everything worked. fine.

**Version Information**

  * Operating System: Mac OS 10.12.6
  * Python Version: 2.7.11 |Anaconda custom (64-bit)
  * yt version: dev from git
  * Other Libraries (if applicable):

**Comment by maxbeegee** [comment]
The issue seems to be because of different versions of `libgomp.1.dylib`.

Itially if I run `otool -L`, I obtain:

```
~/yt/utilities/lib$ otool -L misc_utilities.so
misc_utilities.so:
	@rpath/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/opt/local/lib/libgcc/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

And I can fix the issue if relink the libs via `install_name_tool -change @rpath/libgomp.1.dylib /opt/local/lib/libgcc/libgomp.1.dylib misc_utilities.so`

Not sure why the initial path was off...? This is a workaround, but feel free to close the issue.

**Comment by ngoldbaum** [comment]
Interesting. OpenMP isn’t normally available on MacOS. However it seems that you have gcc installed separately and are getting libgomp from that installation.


I’m not sure why the proper path didn’t get baked into the library at build time.

In any case since this will be a relatively rare issue and there’s a workaround I’m going to close this.

**Comment by chummels** [comment]
@ngoldbaum Would you mind merging this bugfix into your `sph-viz` branch, as it is causing problems on that branch too.
