### ISSUE TITLE
PhasePlot is missing [show,hide]_axes() and [show,hide]_colorbar()

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1736]
Currently the `PlotWindow` plots all have `show_axes`, `hide_axes`, `show_colorbar`, and `hide_colorbar` implemented. Since the actual functionality for hiding and displaying the colorbar is handled by the lower-level matplotlib wrapper objects (e.g. `PlotMPL`, `WindowPlotMPL`, and `PhasePlotMPL`) the implementations of these functions on the `PlotWindow` class are pretty simple:

https://github.com/yt-project/yt/blob/51cf1ce0825dd1e9ef6bbbf8e9a83a82a768cd7e/yt/visualization/plot_window.py#L1046-L1051

For example, I've pasted the implementation of `hide_colorbar` above.

As pointed out by Stephannie Tonneson on the mailing list, currently the `PhasePlot` object does not have these methods. This is a bit of an API inconsistency. I think it should be possible to move these methods to the base `PlotContainer` class or barring that, add separate implementations for these function on the `PhasePlot` class itself. This should be simple since the underlying `PhasePlotMPL` class already can handle hiding the axes and colorbar:

```python
plot = yt.PhasePlot(ds.all_data(), 'density', 'temperature', 'cell_mass')
p = plot.plots['cell_mass']
p.hide_colorbar()
plot.save()
```

**Comment by cldssty** [comment]
Ok thanks!

**Comment by Ankk98** [comment]
@cldssty seems to be inactive on this issue.
Can I take it?

**Comment by ngoldbaum** [comment]
Please feel free. Let me know if my initial description isn't enough for you to get started. I'd also encourage you to look at our developer guide: http://yt-project.org/doc/developing/index.html
