### ISSUE TITLE
Unexpected Change in Defined Quantity after Being Used to Create Data Object

### ISSUE THREAD

**Issue by stephaniehho** [yt-project/yt#1748]
### Bug report

**Bug summary**

YT changes my defined quantity (which is unexpected), after the quantity is used to create and extract information from a data object.

**Code for reproduction**

(The data used is the sample EAGLE data from yt data hub.)

```python
import yt
import numpy as np

eagle_fname = 'snapshot_028_z000p000/snap_028_z000p000.0.hdf5'

unit_base = {'UnitLength_in_cm'         : 3.085678e+24,
             'UnitMass_in_g'            :   1.989e+43,
             'UnitVelocity_in_cm_per_s' :    100000.0}

ds = yt.load(eagle_fname, unit_base=unit_base)

center = ds.arr(np.array([12.08809, 4.474372, 1.4133347]), 'Mpccm')
radius = ds.quan(0.05, 'Mpc')
cc = ds.sphere(center, (radius, 'Mpc'))

print('radius: ', radius)
print('Number of particle in cc: ', len(cc['PartType0', 'ParticleIDs']))
print('radius: ', radius)
```

**Actual outcome**

```
radius:  0.05 Mpc
Number of particle in cc:  3699
radius:  0.0338849953984 Mpc
```

**Expected outcome**

The variable "radius" is not expected to be changed.  It is not assigned to a new value by the user.  The variable is just to use for creating and extracting information from the data object (the sphere).

**Version Information**

  * Operating System: MacOS Sierra
  * Python Version: 2.7.12
  * yt version: 3.5.dev0
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
@stephaniehho just a note, in your example when you do this:

```
adius = ds.quan(0.05, 'Mpc')
cc = ds.sphere(center, (radius, 'Mpc'))
```

I'm not sure how yt should handle that. I think what you want to do is this:

```
radius = ds.quan(0.05, 'Mpc')
cc = ds.sphere(center, radius)
```

I think I'm going to make it an error for the length in a (length, unit) tuple to be a quantity, since then the units are ambiguous.

**Comment by stephaniehho** [comment]
Thanks for the tips Nathan.  This will definitely remove the ambiguity,
which also solve the issue.
