### ISSUE TITLE
annotate_domain in disagreement with rendered image.

### ISSUE THREAD

**Issue by DL6ER** [yt-project/yt#1753]
### Bug report

I want to volume-render a non-cubic simulation from FLASH. So far, I tried to follow the official [volume rendering tutorial](http://yt-project.org/doc/visualizing/volume_rendering_tutorial.html#volume-rendering-tutorial) but I'm struggling with orienting myself in the generated graphs.
I think this is mainly due to the fact that the result of `annotate_domain` does not seem to correspond to anything in the generated image:
![render6_1](https://user-images.githubusercontent.com/16748619/38739737-0c47a4d0-3f36-11e8-815c-0460e48c598d.png)

**Code for reproduction**
curldrop: http://use.yt/upload/df1b59f5

```python
import yt

ds = yt.load("CF97W4_N1B025_hdf5_plt_cnt_0055")
sc = yt.create_scene(ds)#, lens_type='perspective')

# Set up the camera parameters: focus, width, resolution
sc.camera.focus = ds.domain_center
sc.camera.resolution = (1000,500)
sc.camera.width = (100, 'pc')
sc.camera.switch_orientation()

sc.annotate_axes(alpha=0.02)
sc.annotate_domain(ds, color=[1, 1, 1, .3])
sc.save("render6_1.png", sigma_clip=3.0)
```

With `lens_type='perspective'` and otherwise unchanged code from above, things seem to be even worse:
![render6_1](https://user-images.githubusercontent.com/16748619/38739953-a057d8ac-3f36-11e8-8362-23bed86e1e43.png)

**(Roughly) expected output**
(generated using VisIt 2.13.1`)
![screenshot at 2018-04-13 16-29-51](https://user-images.githubusercontent.com/16748619/38740483-ffa07d04-3f37-11e8-8ce8-26339be32715.png)

**Version Information**

  * Operating System: Linux Mint 18
  * Python Version: Python 2.7.12 (default, Dec  4 2017, 14:50:18)
  * yt version: yt-3.4.0-595-gb30e5cb (compiled from source after cloning repository from github)
  * Other Libraries (if applicable): ---

**Comment by ngoldbaum** [comment]
Thanks for the detailed report!
