### ISSUE TITLE
Opening lots of small datasets requires a lot of RAM for the unit system

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1776]
As pointed out in #1775, loading a dataset causes quite a lot of RAM (~10 megabytes per dataset) to be allocated by the unit system, mostly to create sympy symbol objects. The memory cost seems to mostly be coming from caching unit objects. That is, if I turn off sympy's cache and comment out the usages of the LRU cache in the yt unit system the memory needed to load a dataset goes down by about 10 MB.

We should consider tuning these caches to be smaller by default. We should also investigate if there's a way to avoid keeping these expensive sympy objects in memory. I think 10 MB just for unit metadata is really excessive, it should just be a few kilobytes given the number of symbols and amount of metadata.

**Comment by astroboylrx** [comment]
Hi @ngoldbaum 

I've uploaded my dataset and scripts [here](http://use.yt/upload/33b7e323).

This time I found the simplified script actually does not consume too much memory.
```python
Filename: simplified_code.py

Line #    Mem usage    Increment   Line Contents
================================================
    12   91.320 MiB   91.320 MiB   @profile
    13                             def fft_analyses(prefix, num_files, nwave=1):
    14                                 """ load data along simulation time to calculate Fourier amplitudes """
    15
    16   91.320 MiB    0.000 MiB       t = np.zeros(num_files)
    17   91.320 MiB    0.000 MiB       amp = np.zeros(num_files)
    18
    19  239.457 MiB -7973.148 MiB       for i in range(num_files):
    20  239.457 MiB -7832.480 MiB           ds = yt.load(prefix+'{:04d}'.format(i)+".dpar.vtk")
    21  239.457 MiB -7979.820 MiB           dpar = (ds.index.grids[0])["dpar"].value[:, :, 0]
    22  239.457 MiB -7973.125 MiB           tmp = np.fft.fft2(dpar)
    23  239.457 MiB -7973.133 MiB           amp[i] = np.sum(abs(tmp[nwave::ds.domain_dimensions[0]-nwave*2, 0])) / abs(tmp[0][0])
    24  239.457 MiB -7973.148 MiB           t[i] = ds.current_time
    25
    26  216.359 MiB  -23.098 MiB       return t, amp
    27
    28                             if __name__ == "__main__":
    29                                 fft_analyses("./Parsg_Strat2d.", 301)
```
Those negative values mean a lot of memory release. The figure below better shows the memory usage as a function of time (can be replotted by `mprof plot mprofile_simplified_code.dat`).
![memprof_simplified_code](https://user-images.githubusercontent.com/3999966/39660407-3784bf3e-4ff3-11e8-9ccd-78ea1bca9925.png)


This is embarrassing... so I went back to look into my very original code. I found I had another layer of encapsulation as in the `class AthenaVtkData` 

```python
Filename: encapsulated_yt.py

Line #    Mem usage    Increment   Line Contents
================================================
    13                             class AthenaVtkData:
    14                                 """ Use yt to read data from vtk file in SI simulations """
    15 2790.465 MiB   91.289 MiB       @profile
    16                                 def __init__(self, filename):
    17                                     """ load data from VTK file using yt """
    18
➜➜  19 2797.770 MiB 2705.801 MiB           self.pf = yt.load(filename)
    20 2797.770 MiB    0.004 MiB           data = self.pf.index.grids[0]
    21 2797.770 MiB    0.000 MiB           self.t = self.pf.current_time
    22 2797.770 MiB    0.000 MiB           self.Nx = self.pf.domain_dimensions
    23 2797.770 MiB    0.676 MiB           self.dpar = np.squeeze(data['dpar'])

Filename: encapsulated_yt.py

Line #    Mem usage    Increment   Line Contents
================================================
    25   91.039 MiB   91.039 MiB   @profile
    26                             def fft_analyses(prefix, num_files, nwave=1):
    27                                 """ load data along simulation time to calculate Fourier amplitudes """
    28
    29   91.039 MiB    0.000 MiB       t = np.zeros(num_files)
    30   91.039 MiB    0.000 MiB       amp = np.zeros(num_files)
    31
    32 2808.000 MiB    0.000 MiB       for i in range(num_files):
➜➜  33 2808.000 MiB 2716.926 MiB           ds = AthenaVtkData(prefix+'{:04d}'.format(i)+".dpar.vtk")
    34 2808.000 MiB    0.020 MiB           tmp = np.fft.fft2(ds.dpar)
    35 2808.000 MiB    0.016 MiB           amp[i] = np.sum(abs(tmp[nwave::ds.Nx[0]-nwave*2, 0])) / abs(tmp[0][0])
    36 2808.000 MiB    0.000 MiB           t[i] = ds.t
    37
    38 2808.000 MiB    0.000 MiB       return t, amp
    39
    40                             if __name__ == "__main__":
    41                                 fft_analyses("./Parsg_Strat2d.", 301)
```

The usage is plotted in the two pictures below (the first one can be reproduced by `mprof plot mprofile_encapsulated_yt.dat`).
![memprof_encapsulated_yt](https://user-images.githubusercontent.com/3999966/39660413-62011c12-4ff3-11e8-8485-5111676cf1c5.png)
![image](https://user-images.githubusercontent.com/3999966/39660319-10c9a5e6-4ff1-11e8-807b-234856bfd535.png)

---
I am not entirely sure what's behind this. Any recommendations and suggestions will be appreciated!

**Comment by ngoldbaum** [comment]
What python and yt versions are you using? When I run `encapsulated_yt.py` the peak memory usage never exceeds 180 MB or so. I'm using Python3.6 and yt 3.4.1.

**Comment by astroboylrx** [comment]
Here is my version Information:

Operating System: macOS 10.13.4
Python Version: 3.6.5
yt version: 3.4.1 (installed by pip)

**Comment by ngoldbaum** [comment]
Hmm, we have basically the same setup then. I wonder what's different.

How are you running the script? I'm just doing `python encapsulated_yt.py` using the script exactly as you have it in the tarball.

Let's try to figure out what kind of objects aren't being deallocated on your machine. Can you try running this version of `encapsulated_yt.py`, which I've modified to use `objgraph`:

```python
import objgraph
import numpy as np
import yt

from yt.funcs import mylog
mylog.setLevel(40)  # This sets the log level to "ERROR"

# if with memory_profiler, you may uncomment line 25 to run
#     python -m memory_profiler encapsulated_yt.py
# to get a view of memory usage along execution.
# I didn't use a loop in order to have a better format of output.


class AthenaVtkData:
    """ Use yt to read data from vtk file in SI simulations """

    def __init__(self, filename):
        """ load data from VTK file using yt """

        self.pf = yt.load(filename)
        data = self.pf.index.grids[0]
        self.t = self.pf.current_time
        self.Nx = self.pf.domain_dimensions
        self.dpar = np.squeeze(data['dpar'])

#@profile
def fft_analyses(prefix, num_files, nwave=1):
    """ load data along simulation time to calculate Fourier amplitudes """

    t = np.zeros(num_files)
    amp = np.zeros(num_files)

    for i in range(num_files):
        ds = AthenaVtkData(prefix+'{:04d}'.format(i)+".dpar.vtk")
        tmp = np.fft.fft2(ds.dpar)
        amp[i] = np.sum(abs(tmp[nwave::ds.Nx[0]-nwave*2, 0])) / abs(tmp[0][0])
        t[i] = ds.t

    return t, amp

if __name__ == "__main__":
    objgraph.show_growth()
    fft_analyses("./vtkdata/Parsg_Strat2d.", 301)
    objgraph.show_growth()
```

You might need to install objgraph from pip.

Once it finishes running, paste the output in a comment here. The second call to `objgraph.show_growth()` will tell us the most common types that were allocated but not freed during the call to `ffy_analyses`.

Another thing to check would be to use `tracemalloc` to find where the memory allocations are happening. If there's one dominant source of memory allocations, you can also get `tracemalloc` to print the stack trace for those allocations. See: https://docs.python.org/3/library/tracemalloc.html

**Comment by ngoldbaum** [comment]
Closing in favor of https://github.com/yt-project/unyt/issues/12
