### ISSUE TITLE
load fenics data into yt instead of relaying on vtk 

### ISSUE THREAD

**Issue by GProtoZeroW** [yt-project/yt#1780]
### Bug report

**Bug summary**

Not really a bug but a feature clarification or needed extension in order to load data from fenics 
**Code for reproduction**

all the information and code is found in the following notebook https://github.com/GProtoZeroW/IssueNotebooks/blob/master/FENICS%20YT.ipynb

**Version Information**

  * Operating System: mint 18.2 64bit
  * Python Version: 3.6
  * yt version: installed on 5-11-16 from conda-forge
  * Other Libraries (if applicable): fenics 2017.2

 
installed via conda

**Comment by GProtoZeroW** [comment]
so that did feed into yt once I did a type recast on `Mconn` from `uint32`
to `np.int64` but when I go to try

```

sl = yt.SlicePlot(ds, 'z', 'test')sl.annotate_mesh_lines()

```
from (
http://yt-project.org/doc/examining/loading_data.html#unstructured-grid-data)(Unstructured
Grid Data) with `test` changed to `test1`  I get
```

ValueError: could not broadcast input array from shape (180,4,1) into
shape (180,4)

```
where I cant find where it's generating the extra 1
The notebook has been updated to reflect the current predicament
https://github.com/GProtoZeroW/IssueNotebooks/blob/master/FENICS%20YT.ipynb

**Comment by GProtoZeroW** [comment]
no prop; and that did solve everything. And I moved it to
https://github.com/PyLCARS/YT_BeyondAstro/blob/master/FEniCS_and_yt.ipynb

There is still lots of room for improvements:
camera controls (that whole doc needs a revamp)
adding better annotations to the volumetric renderings

But one big one i want to get from you right now before I move one to
temporal simulations. How would a load up a series of outputs with time and
generate a animation in yt. I have not seen any docs on how to do that.

Also, how do I overlay quiverers from a gradient calculation in the
volumetric

thanks

**Comment by ngoldbaum** [comment]
> How would a load up a series of outputs with time and generate a animation in yt.

you'd load the datasets as a time series and iterate over them, assuming they're separate files. Here's an example that uses matplotlib's animation framework:

http://yt-project.org/doc/cookbook/complex_plots.html?highlight=funcanimation#time-series-movie

> Also, how do I overlay quiverers from a gradient calculation in the volumetric

I don't think the volume renderer has this feature yet.

**Comment by ngoldbaum** [comment]
Since the original issue was resolved I’m going to close this.

Thanks for bringing this to our attention. It would be cool to build something a little more formal on this example. I know @minrk was interested in this when I spoke with him about it a year ago.

**Comment by GProtoZeroW** [comment]
Actually I need to repeat this for MEEP
https://meep.readthedocs.io/en/latest/ but I will open that in another
thread, and thanks guys
