### ISSUE TITLE
Make yt.units a shim that wraps unyt

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1785]
This issue tracks the task of replacing `yt.units` with `unyt`: https://github.com/yt-project/unyt

There are some differences in `unyt` with respect to `yt.units` so we will need to be careful to make sure that everything works the same after integrating. We also need to check the codebase to see if there are places where we can clean things up. These differences are summarized below:

* `unyt` allows you to do `e.g.` `data_with_units + data_without_units*data_with_units.units`, which obviates the need to use `unit_quantity` or `uq`.
* SI <-> MKS Electromagnetic conversions do not need to use an equivalence
* Results of operations that have complex units that have dimensions equal to a known unit name in the unit system being used are reduced to an equivalent unit in that unit system. For example, if something comes out of an operation with units like `erg * cm/km`, by default the result will be presented in `erg` (e.g. the `cm/km` will be converted to a constant that gets multiplied by the value of the object).
* MKS is the default unit system
* If you do `unyt_array([1, 2, 3], 'code_length')` you don't get a yt-specific error message suggesting to use `ds.arr` like if you do `YTArray([1, 2, 3], 'code_length')`.

**Comment by chummels** [comment]
Consistent with our discussion two weeks ago on a PR in `unyt`: https://github.com/yt-project/unyt/pull/2 , Will you make it so the astrophysics context stuff defaults to cgs?  I think you're going to find a lot of the current users upset if all of a sudden their projections are in kg/m^2 and so forth.

**Comment by ngoldbaum** [comment]
Yes, that's why I included "MKS is the default unit system" in the bullet points.

**Comment by chummels** [comment]
I saw that, but I guess we're talking past each other.  So your bullet points list the changes in `unyt` that we need to effectively cover up so that the `yt` experience is the same for users?

**Comment by jzuhone** [comment]
@chummels my view is that the experience from the point of view of `yt` is identical--the current default unit system in `yt` is cgs, so it should be that way when we use `unyt` as a backend.

**Comment by ngoldbaum** [comment]
Yup, exactly, although with the qualification that data from fields that we don't support yet might load data with MKS or other unit systems that are commonly used in that field. The astrophysics domain context will definitely have CGS units by default.

**Comment by chummels** [comment]
OK cool, then we're all on the same page.  Sorry for my mis-reading of your description.

**Comment by munkm** [comment]
I think this is is satisfied now, so I'm going to close it. Feel free to reopen if you all think that yt.units still hasn't outsourced enough to unyt.
