### ISSUE TITLE
Unable to create interactive data visualization 

### ISSUE THREAD

**Issue by yuanzeluo** [yt-project/yt#1786]
### Bug report

**Bug summary**

Getting RunTime Errors and cannot produce a interactive data visualization (the window pops up but shows nothing) . I did this before with the same FITS file but now have trouble reproducing it. I have cyglfw3 and pyopengl installed.
The file used: http://use.yt/upload/ca449c95
A 3D volume rendering of the data using yt.create_scene(): http://use.yt/upload/1fc36c70

**Code for reproduction**

```python
# Paste your code here
import sys
sys.path.insert(0, "/Users/CEiffel/yt") 
import yt
import time
import yt.visualization.volume_rendering.interactive_vr as ivr
from yt.visualization.volume_rendering.interactive_loop import \
    RenderingContext
import h5py
import numpy as np
from yt.visualization.volume_rendering import glfw_inputhook

ds = yt.load("NGC5908.co.xycut.K.fits", nan_mask = 0.0)
ds.periodicity = (True, True, True)
shape = ds.domain_dimensions



rc = RenderingContext(960, 960)


dd = ds.all_data()
collection = ivr.BlockCollection()
collection.add_data(dd, "intensity")



scene = ivr.SceneGraph()

scene.add_collection(collection)

# Create default camera
position = (0.0, 0.0, 0.0)
c = ivr.TrackballCamera(position=position,
                        focus=ds.domain_center, near_plane=0.1)
# Start rendering loop
rc.start_loop(scene, c)
#
```

**Actual outcome**

```
# If applicable, paste the console output here

/anaconda/lib/python3.6/site-packages/yt/units/yt_array.py:1293: RuntimeWarning: invalid value encountered in log10
  out_arr = func(np.asarray(inp), out=out, **kwargs)
/anaconda/lib/python3.6/site-packages/yt/visualization/volume_rendering/interactive_vr.py:422: RuntimeWarning: All-NaN axis encountered
  self.min_val = min(self.min_val, np.nanmin(block.my_data[0].min()))
/anaconda/lib/python3.6/site-packages/yt/visualization/volume_rendering/interactive_vr.py:423: RuntimeWarning: All-NaN axis encountered
  self.max_val = max(self.max_val, np.nanmax(block.my_data[0].max()))
```

**Expected outcome**

**Version Information**

  * Operating System: macOS
  * Python Version: 3.6
  * yt version: 3.4.1
  * Other Libraries (if applicable): cyglfw3 3.1.0.2,  pyopengl 3.1.1a1

**Comment by yuanzeluo** [comment]
Tried again after changing line 422 and 423 in interactive_vr.py to be
```
self.min_val = min(self.min_val, np.nanmin(block.my_data[0]))
self.max_val = max(self.max_val, np.nanmax(block.my_data[0]))
```

Now the rendering window shows something but it's something really weird...
<img width="960" alt="screen shot 2018-05-16 at 15 18 01" src="https://user-images.githubusercontent.com/28064192/40142509-6feac9c0-591e-11e8-99ef-2f639ad8ebba.png">

**Comment by ngoldbaum** [comment]
This will get fixed in the refactor of IDV, closing for now.
