### ISSUE TITLE
Spherical coordinates viz

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#1796]
After discussion with @ngoldbaum , we determined that the convention that is self-consistently applied throughout yt's coordinate handling is OK for spherical coordinates.  The variable that runs from 0..pi is called theta and the variable that runs from 0..2pi is called phi.  This is not what we expect in physics, but is coordinated with the mathematical convention.

Using thing as-is, volume is computed correctly, and the FLASH frontend is correctly set up.  `geom_transforms` in `yt/testing.py` is OK, too.  We can verify this by computing `.r[:].sum("cell_volume")` on a dataset.

With #1791 , we correctly do things in geographic coordinate handler, but this exposed that the spherical coordinate handler was (I believe) backwards *in the visualization*, but not the rest.

Unless we take on a process of changing all variable names from theta to phi, what needs to happen next:

- [x] Comments throughout the code and docs explaining the pi and 2pi variables
- [ ] Possibly a second class of Spherical handler that switches these, or maybe changes them to "azimuthal" and "axial" or something.
- [x] Carefully adjust the `sanitize_center` and `sanitize_width` functions in the spherical coordinate handler to ensure they are correctly set for the appropriate axes.
- [ ] Add a section to the documentation about "coordinate system reference" -- a table that describes each of the extant coordinate systems/geometries, their expected bounds, and their visualization methods.

Initial inspection suggests that the third item is complete, but I will be constructing a notebook that demonstrates this.

**Comment by ngoldbaum** [comment]
This should also fix the errors like this that recently cropped up in the unit tests:

```
Exception ZeroDivisionError: 'float division' in 'yt.utilities.lib.pixelization_routines.aitoff_thetaphi_to_xy' ignored
ZeroDivisionError: float division
Exception ZeroDivisionError: 'float division' in 'yt.utilities.lib.pixelization_routines.aitoff_thetaphi_to_xy' ignored
```

These errors were introduced by merging #1791. If this take a lot of time to fix, a quick fix specifically for the error messages generated by the unit tests would be to revert the changes to the spherical coordinate handler in that PR.

**Comment by neutrinoceros** [comment]
I think we can check the third box with #3533

**Comment by neutrinoceros** [comment]
@matthewturk so I think items 1 and 3 are done, AFAICT, item 2 isn't necessary, and item 4 is covered with https://yt-project.org/doc/visualizing/plots.html#slice-plots-and-projection-plots-in-spherical-geometry
Can we close this ?

**Comment by matthewturk** [comment]
Yup!  Thank you.
