### ISSUE TITLE
Unable to load object after saving using `YTDataContainer.save_object()`

### ISSUE THREAD

**Issue by git-abhishek** [yt-project/yt#1836]
### Bug report

**Bug summary**

Unable to load the object after saving using `YTDataContainer.save_object()` for the case when  `filename` is not supplied while calling `save_object()`.
 
**Steps for reproduction**
1. Make config parameter [`serialize`](https://github.com/yt-project/yt/blob/master/yt/config.py#L23) to `True`. 
2. Modify [line](https://github.com/yt-project/yt/blob/master/yt/geometry/geometry_handler.py#L164) by following:
```python
    if hasattr(obj, 'value'):
        obj = cPickle.loads(obj.value)
    else:
       obj = cPickle.loads(obj)
```
3. **Code for reproduction** 
```python
    ds = fake_particle_ds()
    sp = ds.sphere(ds.domain_center, 0.25)
    sp.save_object("my_sphere")
    loaded_sphere = ds.index.load_object("my_sphere")
    for k in loaded_sphere._key_fields:
        assert_array_equal(loaded_sphere[k], sp[k])
```

**Actual outcome**

Error is thrown: `_pickle.UnpicklingError: could not find MARK`

**Expected outcome**

Test in step 3 should pass.

**Comment by brittonsmith** [comment]
We've come to a decision that object-saving functionality that makes use of pickle has become to difficult to maintain, especially given that the `ytdata` frontend makes it mostly (if not entirely) redundant. I'm going to close this issue in favor of Issue #2021.
