### ISSUE TITLE
Input validation for selection data containers

### ISSUE THREAD

**Issue by git-abhishek** [yt-project/yt#1843]
### Bug report

**Bug summary**

Add input validation for different geometric selectors of data containers as done in #1833.
These geometries are:
```
YTPoint, YTOrthoRay, YTRay, YTSlice, YTCuttingPlane, YTRegion, YTSphere, YTEllipsoid, YTCutRegion
```
**Initial bug was filed for `YTDisk` in #1768 .**
Similar issue to add input validation could be found at #1839 .

**Comment by ngoldbaum** [comment]
This was fixed by #1870.
