### ISSUE TITLE
RAMSES key error

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#1847]
### Bug report

**Bug summary**

When creating a derived field for a RAMSES dataset that depends on hydro and rt (any combination as long as the fields aren't stored in the same file), a `KeyError` is raised. This is due to the fact that the code is trying to read all the fields from the same file.

**Code for reproduction**

This requires [ramses_rt_00088](http://yt-project.org/data/ramses_rt_00088.tar.gz). See https://gist.github.com/cphyc/dc445db37e09bf2a89adf50409866f26.

**Version Information**

  * Operating System: Arch linux
  * Python Version: 3.6.5
  * yt version: master
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
Hey Corentin, just checking do you want help with fixing this?

**Comment by cphyc** [comment]
Hey,
I won't have time to look at this anytime soon, so if any help is welcome!
