### ISSUE TITLE
Units get lost in profiles

### ISSUE THREAD

**Issue by MatthewTurk** [yt-project/yt#1849]
Making a 2D profile gives strange results on some sample datasets:

```#python
>>> import yt
>>> ds = yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")
>>> prof = ds.r[:].profile(["density", "temperature"], "cell_volume", weight_field=None)
>>> prof["cell_volume"].units
code_length**3
>>> prof["cell_volume"].max()
2.7982080370624824e+73 code_length**3
```

I'm on the current `master` (following result of merging #1845).  Plotting gives the same thing.

**Comment by MatthewTurk** [comment]
I should note, it's reporting that it's `code_length` but it's in `cm`.

**Comment by ngoldbaum** [comment]
I get the correct answer with `yt 3.4.1`, gonna attempt to bisect now.

**Comment by ngoldbaum** [comment]
This is due to #1799, I will work on a fix for this
