### ISSUE TITLE
Add `smooth` callback

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#1875]
**Suggested implementation**

Add a new callback to the projection/plot object to be able to smooth the plot window using some function. One suggestion would be to use something like
```
p = yt.SlicePlot(ds, 'x', 'density')
p.smooth_plot(kernel_name, kernel_parameters)
```
where `kernel_name` could be e.g. a Gaussian Kernel.

**Comment by ngoldbaum** [comment]
I can give suggestions about how to implement this if you'd be interested.

**Comment by cphyc** [comment]
What I've done so far:
```

class SmoothCallback(PlotCallback):
    """
    Smooth the plotting window.

    [WIP]
    """
    _type_name = "smooth"
    _supported_geometries = ("cartesian", "spectral_cube")

    _kernels = ['gaussian']

    def __init__(self, kernel_name, kernel_params={}):
        if callable(kernel_name):
            self.kernel = kernel_name
            self.kernel_params = kernel_params
        else:
            self.kernel = getattr(self, kernel_name)
            self.kernel_params = kernel_params

    def __call__(self, plot):
        data = plot.image._A.copy()

        plot.image._A = self.kernel(data, **self.kernel_params)

    def gaussian(self, data, sigma=5):
        from scipy.ndimage import gaussian_filter
        return np.ma.masked_array(gaussian_filter(data, sigma))
```

**Comment by ngoldbaum** [comment]
The `plot` object passed to the `__call__` method has an `frb` attribute you can use so you don't need to reimplement gaussian smoothing.

The names for callbacks are generated here: 

https://github.com/yt-project/yt/blob/master/yt/visualization/plot_window.py#L976

I like the naming uniformity that the names of all the callbacks begin with `annotate_` but if you feel strongly about the name then I guess we could add an override.

For the unit issue, the `project_coords`, `sanitize_coordinate_system`, and `convert_to_plot` methods might be useful.

**Comment by cphyc** [comment]
I'm not sure I understand your first comment. I see there's an `frb` attribute which, if I understand correctly, has itself an `apply_gauss_beam` method. However, it is not enough to just call this method as this would not update the image right?

**Comment by ngoldbaum** [comment]
I think it would, but after experimenting a bit I think we'd need to do a bit more to wire things up. Ideally this would "just work" but it looks like the call to `plot.save()` isn't causing the filter to be applied for some reason:

```
plot = yt.ProjectionPlot(ds, 'z', ('gas', 'density'), width=(15, 'kpc'))
plot.frb.apply_gauss_beam(nbeam=100, sigma=20)
plot.save()
```

**Comment by chummels** [comment]
Didn't we used to have Smoothed Projection Plots as default?  How was that smoothing done?

**Comment by MatthewTurk** [comment]
We had sampled off axis projections, yes. But it was done very differently - using the volume rendering infrastructure. This is a post-viz operation, not a different viz op.

**Comment by ngoldbaum** [comment]
Do we still want this open given the existence of #1877? I don't think this is necessary if you can just manipulate the underlying FRB.

**Comment by cphyc** [comment]
I'm OK with closing it.
