### ISSUE TITLE
Feature request: per-field configuration

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#1888]
### Feature request

As of today, there is no way for users to configure the defaults of the plots (colormap, unit, background color, ...) _per field_. It would be nice to extend the yt configuration file so that you can pass it some defaults for fields.

### Suggested format

```
[gas]
density_colormap = dusk
density_unit = mp/cm**3
temperature_colormap = seismic
[star]
particle_mass_colormap = viridis
```

### What should and should not be in ?

If we implement this one, we should discuss what can and cannot be part of the default configuration. For example, using the above configuration, what should be the default unit for the following line
```python
p = yt.ProjectionPlot(ds, 'x', 'density')
```
The configuration seem to tell that it should be using `mp/cm**3` but the result is homogeneous to `mp/cm**2`.

The question essentially boils down to whether we want
- a per field configuration
- a per field per plot type configuration

The second one, while more cumbersome for the user seem to be the easiest to implement. However, it doesn't help distinguish
```python
p1 = yt.ProjectionPlot(ds, 'x', 'density')
p2 = yt.ProjectionPlot(ds, 'x', 'density', weight_field='cell_mass')
```

### Suggested list of tweakable defaults

* colormap
* unit ?
* boundaries (`zlim`)
* background color

We should also make clear what strategy is applied if there are different configuration in, say the main yt config file and a local `ytrc` file (I guess the latter overrides the former?).

**Comment by ngoldbaum** [comment]
Unfortunately it seems python's `configparser` ignores subsections: https://stackoverflow.com/questions/16350462/configparser-getting-value-from-ini-file-with-section-and-subsection-as-shown-be

I wonder if the [toml format](https://github.com/toml-lang/toml) is ini-like enough that we could just silently switch to using that without breaking anything...
