### ISSUE TITLE
annotate_clumps() plot_args not working

### ISSUE THREAD

**Issue by astro313** [yt-project/yt#1896]
Hi,

I am using the yt clump finder and I am trying to plot all the clumps identified (including all the parents of all the leafs). I want to annotate the clumps identified in each level of the tree with a different color, but it seems to me that `annotate_clumps()` is ignoring the keywords in `plot_args`. What is the proper syntax for setting different colors in `annotate_clumps()`?

```
    master_clump = Clump(dd, field)
    master_clump.add_validator("min_cells", N_cell_min)
    find_clumps(master_clump, c_min, c_max, step)

   prj = yt.ProjectionPlot(ds, 0,
                                    field,
                                    center='c')

   tc1 = [c for c in master_clump]
   prj.annotate_clumps(tc1, plots_args={'color': 'black'})
   prj.show()
```
It does not throw an error, but the output plot just annotates the contours in the default colors, and completely ignores the plot_args. 

  * Operating System:
  * Python Version: 2.7
  * yt version: 3.4.1

**Comment by ngoldbaum** [comment]
I believe you want to say `plots_args={'colors': 'black'}` (not `'color'` as you have it).

The callback should take keyword arguments accepted by [axes.contour](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.contour.html).

**Comment by astro313** [comment]
Thanks Nathan. `colors` solved the problem. I thought the keyword is `color` since that's what I used with annotate_marker() according to the cookbook, and it does work.

**Comment by ngoldbaum** [comment]
That's right, and this is an inconsistency in matplotlib's API that we're exposing. I think this has come up before, what we can do is add a catch for this exact issue and just replace `'color'` with `'colors'` inside yt. It's easy enough to do that and should make yt easier to use.
