### ISSUE TITLE
Unstructured mesh slices return data with inconsistent shapes

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#1916]
### Bug report

**Bug summary**

This was initially reported on the mailing list as a failure in the annotate_contours plot callback.

The issue is illustrated with the following script:

```
import yt
ds = yt.load('source.e', step=-1)

slc = ds.slice(2, 1.0)

# fcoords expects four elements in the slice
print(slc.fcoords)

# but we seem to have 8 elements returned
print(slc['all', 'group_0'])
```

Right now this prints:

```
[[0.5 0.5 1.5]
 [1.5 0.5 1.5]
 [0.5 1.5 1.5]
 [1.5 1.5 1.5]] code_length
[0.02927492 0.00967331 0.00967331 0.00469298 0.         0.
 0.         0.        ] dimensionless
```

**Expected outcome**

```
[[0.5 0.5 1.5]
 [1.5 0.5 1.5]
 [0.5 1.5 1.5]
 [1.5 1.5 1.5]] code_length
[0.02927492 0.00967331 0.00967331 0.00469298] dimensionless
```

**Version Information**

  * Operating System: mac
  * Python Version: 3.7.0
  * yt version: current master branch
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
here's a patch that i'm pretty sure is wrong (don't think the mask is correct) but it allows the script to run without crashing:

```
diff --git a/yt/frontends/exodus_ii/io.py b/yt/frontends/exodus_ii/io.py
index fa9de1d0a..a639026b7 100644
--- a/yt/frontends/exodus_ii/io.py
+++ b/yt/frontends/exodus_ii/io.py
@@ -72,20 +72,32 @@ class IOHandlerExodusII(BaseIOHandler):
                     mesh_ids = [int(ftype[-1])]
                     chunk = chunks[mesh_ids[0] - 1]
                     objs = chunk.objs
+                masks = []
                 if fname in self.node_fields:
                     field_ind = self.node_fields.index(fname)
                     fdata = ds.variables['vals_nod_var%d' % (field_ind + 1)]
                     for g in objs:
+                        mask = g._get_selector_mask(selector)
+                        if mask is None:
+                            mask = np.array([False])
+                        masks.append(mask)
                         ci = g.connectivity_indices - self._INDEX_OFFSET
                         data = fdata[self.ds.step][ci]
                         ind += g.select(selector, data, rv[field], ind)  # caches
                 if fname in self.elem_fields:
                     field_ind = self.elem_fields.index(fname)
                     for g, mesh_id in zip(objs, mesh_ids):
+                        mask = g._get_selector_mask(selector)
+                        if mask is None:
+                            mask = np.array([False])
+                        masks.append(mask)
                         fdata = ds.variables['vals_elem_var%deb%s' %
                                                        (field_ind + 1, mesh_id)][:]
                         data = fdata[self.ds.step, :]
                         ind += g.select(selector, data, rv[field], ind)  # caches
+                mask = np.concatenate(masks)
+                rv[field] = rv[field][mask]
             return rv

     def _read_chunk_data(self, chunk, fields):
```

**Comment by ngoldbaum** [comment]
ping @MatthewTurk @atmyers

**Comment by ngoldbaum** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/3126246/43156798-bad619c8-8f40-11e8-99b3-674824dd6d9a.png">

**Comment by loganharbour** [comment]
Is this a heavy or a light task?

**Comment by ngoldbaum** [comment]
Relatively heavy, if you've never touched yt internals before I probably wouldn't try it.

**Comment by loganharbour** [comment]
Yep, I'm definitely realizing that. oh well, was worth a try

**Comment by ngoldbaum** [comment]
I think I have a fix though. Does this look right to you?

https://i.imgur.com/ikVIZ5W.png

**Comment by loganharbour** [comment]
That dataset is _extremely_ scaled down... so I can't guarantee for sure but for what is given it looks correct

**Comment by ngoldbaum** [comment]
I've opened #1918. I'm not sure how much stuff this breaks, let's see what the tests say.

**Comment by ngoldbaum** [comment]
Feel free to share the full-size dataset too.

**Comment by loganharbour** [comment]
http://use.yt/upload/a1faf6c2

Checking the following (as you first did):
```
ds = yt.load('saaf_cfem_sn_ls20_r2.e', step=-1)
slc = ds.slice('z', 0)
print(slc.fcoords.size)
print(slc['all', 'fcs_total_scalar_flux_g0'].size)
```

The printed sizes are 11520 and 30720

**Comment by loganharbour** [comment]
Err... I realize now that the coordinate `size` should be 3x the value `size`. However, issue still stands

**Comment by ngoldbaum** [comment]
So the issue with that one is that `fcs_total_scalar_flux_g0` is a nodal field but the contour callback doesn't support nodal data, we only support element-centered data. If you look at slc['all', 'fcs_total_scalar_flux_g0'].shape, you'll see that it has the correct size:

```
In [3]: ds = yt.load('saaf_cfem_sn_ls20_r2.e', step=-1)
   ...: slc = ds.slice('z', 0)
   ...: print(slc.fcoords.shape)
   ...: print(slc['all', 'fcs_total_scalar_flux_g0'].shape)
(3840, 3)
(3840, 8)
```

(the fact that the leading entry in the `shape` is the same means that we're selecting the correct number of elements, which is what #1918 fixes)

I guess we could to some sort of interpolation to the element centers to handle nodal fields for `annotate_contour`, I'm not sure offhand what the correct fix is. Maybe @atmyers has thoughts.

**Comment by loganharbour** [comment]
Ahh, I didn't even consider that the simplified case I sent was elemental instead. Glad to have found a separate issue. This makes sense. For the time being I can just project my solution to element averages and use said solution separate for the contours. I appreciate the quick responses and fixes today.

**Comment by atmyers** [comment]
I think the best thing to do is introduce the interpolation at the plot_modification level - I think having the data_source return all 8 values is what we want most of the time.

**Comment by ngoldbaum** [comment]
Agreed! Is there an existing routine to go from generic nodal data to cell-centered data? Maybe just restrict that to unstructured mesh data, so the interpolation would use the proper Jacobean for that element.

**Comment by atmyers** [comment]
There isn't a function to do that at the moment, but such a thing would look pretty similar to `pixelize_element_mesh` I think. That function discovers the right kind of interpolation to due for the element type based on the shape and dimensionality of the data. Once you get down to a single element, all the different element types know how to sample at real points inside them. This code lives in `utilities/lib/element_samplers.pyx.`

**Comment by ngoldbaum** [comment]
#1918 addresses this.
