### ISSUE TITLE
Explore using pooch for sample data

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#1974]
The [pooch](https://github.com/fatiando/pooch/) project seems like a really nice way to manage sample data.  Making our sample data accessible in such a way could be quite nice.

**Comment by Ankk98** [comment]
Can I work on this issue?

**Comment by MatthewTurk** [comment]
@ankk98 absolutely! That'd be very cool.

**Comment by munkm** [comment]
Resolved via yt-project/yt#2417
