### ISSUE TITLE
parallel_analysis_interface.py issue

### ISSUE THREAD

**Issue by sflarkin** [yt-project/yt#1988]
Hello All,

I am having an error in the parallel_analysis_interface.py file. I have encountered this error in two places. Firstly on the main yt branch, and secondly on a branch of yt called yt-agora based in python 2.7 (you can find this repository here https://bitbucket.org/migroch/yt-agora) It loos like this function has not been changed since then. 

What I am doing is running rockstar, and it is deciding how many writers to assign to the job. Here is the error message I get in yt-agora, I would also post the error message in base yt, but I have misplaced it, and will keep looking for it.

Traceback (most recent call last):
  File "./scripts/runagora.py", line 325, in <module>
    num_readers=args['num_readers'])
  File "./scripts/runagora.py", line 223, in run_rockstar
    total_particles=total_particles)
  File "/home1/sflarkin/build/yt-agora/yt/analysis_modules/halo_finding/rockstar/rockstar.py", line 259, in __init__
    self.pool, self.workgroup = self.runner.setup_pool()
  File "/home1/sflarkin/build/yt-agora/yt/analysis_modules/halo_finding/rockstar/rockstar.py", line 109, in setup_pool
    (self.num_writers, "writers") ]
  File "/home1/sflarkin/build/yt-agora/yt/utilities/parallel_tools/parallel_analysis_interface.py", line 403, in from_sizes
    pool.add_workgroup(size, name = name)
  File "/home1/sflarkin/build/yt-agora/yt/utilities/parallel_tools/parallel_analysis_interface.py", line 371, in add_workgroup
    group = self.comm.comm.Get_group().Incl(ranks)
AttributeError: 'NoneType' object has no attribute 'Get_group'

As the error is caused by not having the attribute Get_group, I looked in the directories of each of the parts of self.comm.comm to see if there was anything like it. The results are below.

dir(self) ['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add_workgroup', 'available_ranks', 'comm', 'free_all', 'free_workgroup', 'from_sizes', 'ranks', 'size', 'tasks', 'workgroups']

dir(self.comm) ['_Communicator__tocast', '__class__', '__del__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_distributed', '_grids', 'alltoallv_array', 'barrier', 'claim_object', 'comm', 'do_not_claim_object', 'get_filename', 'is_mine', 'merge_quadtree_buffers', 'mpi_Request_Testall', 'mpi_Request_Waitall', 'mpi_Request_Waititer', 'mpi_allreduce', 'mpi_bcast', 'mpi_exit_test', 'mpi_info_dict', 'mpi_nonblocking_recv', 'mpi_nonblocking_send', 'par_combine_object', 'preload', 'probe_loop', 'rank', 'recv_array', 'recv_quadtree', 'send_array', 'send_quadtree', 'size', 'write_on_root']

dir(self.comm.comm) ['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

As you can see, there is no Get_group() property in any of them. I am wondering if anyone knows the correct way to fix this, as I am not very familiar with parallel allocation.

**Comment by ngoldbaum** [comment]
Ho Sean,

To debug this we need an example script to trigger the error. It’s going to be hard to help much without such a example.

**Comment by sflarkin** [comment]
Oh sorry, thought I had included that. The script that triggered it in base yt was the one I sent earlier in my pull request when trying to debug the seg-fault, found here https://github.com/sflarkin/Rockstar_script/blob/master/runrockstar.py.

For the other repository it was this script, https://bitbucket.org/mornkr/agora-analysis-script/src/c5b1838bf5b11365917809649dac76045f70fa6d/yt-sunrise_pipeline/runRockstar.py?at=default&fileviewer=file-view-default.

Oh an Nathan, a quick update on the convo we were having in the pull request thread. This yt-agora repository was the yt version I had mentioned that has integrated rockstar-galaxies. I had forgotten about it at the time I mentioned that.

**Comment by sflarkin** [comment]
Im not sure how difficult that would be, as I am not aware of the changes that were made to make rockstar-galaxies compatible. I just was able to build it properly, and am currently doing some tests on its version of rockstar to see if it works properly. If anyone on the yt dev team wants to build it, tell them to contact me as it does not build from just the base yt build, you have to do some modifications to work properly.

**Comment by sflarkin** [comment]
I have been looking around the function add_workgroup as it is what fails. 

def add_workgroup(self, size=None, ranks=None, name=None):
        if size is None:
            size = len(self.available_ranks)
        if len(self.available_ranks) < size:
            mylog.error('Not enough resources available, asked for %d have %d',
                size, self.available_ranks)
            raise RuntimeError
        if ranks is None:
            ranks = [self.available_ranks.pop(0) for i in range(size)]
        # Default name to the workgroup number.
        if name is None:
            name = str(len(self.workgroups))
        group = self.comm.comm.Get_group().Incl(ranks)
        new_comm = self.comm.comm.Create(group)
        if self.comm.rank in ranks:
            communication_system.communicators.append(Communicator(new_comm))
        self.workgroups.append(Workgroup(len(ranks), ranks, new_comm, name))

I have looked through all the variables passed to it by the num_writers function, and everything appears to work exactly as intened, until the 

group = self.comm.comm.Get_group().Incl(ranks)

line. I am wondering what this defination does, as I am unfamiliar with parallel communicators, to see if there is a way to add the correct when the pool is defined in the from_sizes function where it is created.

**Comment by ngoldbaum** [comment]
I don't have a straightforward way to reproduce this and it seems to only be an issue in practice in the yt-agora fork? I'm closing this issue until we have a way to reproduce this on the master branch of the main yt repo.
