### ISSUE TITLE
Point function not working for negative coordinates

### ISSUE THREAD

**Issue by guido-granda** [yt-project/yt#2026]
### Bug report

**Bug summary**
Hello, 
I found an error of the routine used to get any field value at a fixed point. I doesn't work for negative coordinates regardless the fact that they belong to the computational domain of the simulation.
Use this link the get the snapshot I used: http://use.yt/upload/6a7caf42
**Code for reproduction**

```python
import yt
from yt.units import pc

ds=yt.load('lr_hdf5_plt_cnt_0005')
x_c=-2.5
y_c=-2.5
z_c=-2.5

point=ds.point([x_c,y_c,z_c]*pc)
dens=point['gas','density']
print(point)
print(dens)

```

**Actual outcome**

```
yt : [INFO     ] 2018-09-13 16:33:10,385 Parameters: current_time              = 6.9637940045e+12
yt : [INFO     ] 2018-09-13 16:33:10,386 Parameters: domain_dimensions         = [256 256 256]
yt : [INFO     ] 2018-09-13 16:33:10,386 Parameters: domain_left_edge          = [ -1.54283920e+19  -1.54283920e+19  -1.54283920e+19]
yt : [INFO     ] 2018-09-13 16:33:10,386 Parameters: domain_right_edge         = [  1.54283920e+19   1.54283920e+19   1.54283920e+19]
yt : [INFO     ] 2018-09-13 16:33:10,386 Parameters: cosmological_simulation   = 0.0
YTPoint (lr_hdf5_plt_cnt_0005): , p=[ -7.71419395e+18  -7.71419395e+18  -7.71419395e+18] cm
[] g/cm**3

```

**Expected outcome**
I would expect to get a density value.

**Version Information**

  * Operating System: GNU/Linux
  * Python Version: Python 3.5.4
  * yt version: Version 3.4.1

**Comment by ngoldbaum** [comment]
It looks like this is fixed already on the master branch:

```
YTPoint (lr_hdf5_plt_cnt_0005): , p=[-7.71419395e+18 -7.71419395e+18 -7.71419395e+18] cm
[6.40043755e-24] g/cm**3
```

You can build yt from source following these instructions:

http://yt-project.org/doc/installing.html#installing-yt-from-source

We will hopefully have yt 3.5.0 released very soon, we're in the middle of a sprint specifically to get it out the door.

Thanks very much for the detailed report! Please *do* open issues like this one with this much awesome context and reproducibility in the future :)
