### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by Xarthisius** [yt-project/yt#2031]
We should define environments for testing (py2, py3) and docs building at least. How about:
* requirements.txt (for common deps)
* requirements-test-py2.txt
* requirements-test-py3.txt
* requirements-docs.txt

**Comment by ngoldbaum** [comment]
-1 on a top-level requirements.txt file. We used to have one, it went out of date, and people got confused and used it anyway. I’m +1 with having test-specific requirements files in the `tests` directory though.

**Comment by MatthewTurk** [comment]
I like the idea of a `requirements.txt` file simply because it gets seen by lots of other tools, and would increase our ability to be deployed with those tools.  Perhaps this is not really a big deal and I'm overthinking it, but it seems like this could be a reasonably straightforward thing to do and keep up to date.

**Comment by ngoldbaum** [comment]
yt is a library though, `requirements.txt` files are for apps. What would it help to have one that's not encoded in yt's `install_requires` in the setup.py?

I definitely agree with kacper that having a requirements file for the tests would be useful, as that's a specific deployment of yt for testing purposes and is more like setting up an app where having a requirements file with a explicitly listed exact set of dependencies makes sense.

**Comment by Xarthisius** [comment]
https://github.com/yt-project/yt/pull/1844 is definitely an example that this should be fixed sooner, rather than later.

**Comment by ngoldbaum** [comment]
A PR adding a test requirements file that the jenkins host uses to install dependencies from would be accepted pretty quickly I think :)
