### ISSUE TITLE
Profiled "cell_mass" has only zero values.

### ISSUE THREAD

**Issue by Xarthisius** [yt-project/yt#2048]
### Bug report

As reported by @stonnes on [yt-users ml](https://mail.python.org/mm3/archives/list/yt-users@python.org/thread/HLA2V45O376LDMDVY2Y2WJBW4WJJG2FG/) profiled fields in PhasePlot have invalid values.

**Code for reproduction**

```
import yt

ds = yt.load('IsolatedGalaxy/galaxy0030/galaxy0030')
pp = yt.PhasePlot(ds, "z", "density", ["cell_mass"], weight_field=None)
assert pp.profile.items()[0][1].d.max() > 0.0
```

Regression was introduced by PR #1799

**Comment by ngoldbaum** [comment]
I bet this is the same as #1850

**Comment by ngoldbaum** [comment]
This is fixed now
