### ISSUE TITLE
Potential curvilinear geometry support for plot modifications?

### ISSUE THREAD

**Issue by jisuoqing** [yt-project/yt#2096]
Some plot modifications such as `annotate_line_integral_convolution` and `annotate_streamlines` potentially works fine with curvilinear geometries, by converting vector fields from curvilinear to cartesian geometry. An example as follows:

```python
import yt
import numpy as np

@yt.derived_field(name="magnetic_cyl_to_x", units="gauss")
def _magnetic_cyl_to_x(field,data):
    return data["magnetic_field_r"] * np.cos(data["theta"]) - data["magnetic_field_theta"] * np.sin(data["theta"])

@yt.derived_field(name="magnetic_cyl_to_y", units="gauss")
def _magnetic_cyl_to_y(field,data):
    return data["magnetic_field_r"] * np.sin(data["theta"]) + data["magnetic_field_theta"] * np.cos(data["theta"])

filename = 'taylor_hdf5_plt_cnt_0150'
ds = yt.load(filename) # load 3D cylindrical data
ds.coordinates.name = "cartesian" # cheat here to avoid unsupported geometry error
slc = yt.SlicePlot(ds, "z", "magnetic_field_strength")
slc.annotate_line_integral_convolution("magnetic_cyl_to_x", "magnetic_cyl_to_y")
slc.save("lic.png")
slc.annotate_clear()
slc.annotate_streamlines("magnetic_cyl_to_x", "magnetic_cyl_to_y")
slc.save("stream.png")
```

And it will produce the following figures:

![lic](https://user-images.githubusercontent.com/15147123/48585313-202e7000-e8e1-11e8-9d0b-076162a42b1d.png)
![stream](https://user-images.githubusercontent.com/15147123/48585322-24f32400-e8e1-11e8-887e-03441d51142a.png)

The streamline annotation does not work properly because `yt.utilities.lib.pixelization_routines.pixelize_cartesian` is used; but if we use `plot.data.ds.coordinates.pixelize`, the streamline will work. So the question is why the former routine instead of the latter is chosen for pixelization?

**Comment by MatthewTurk** [comment]
Oh, huh.  Neat.  I think it's an oversight why we don't use that routine.  So, probably good to switch it -- but let's check the orientation of everything, etc.

Really great work.
