### ISSUE TITLE
Issue with multiple N-body species for artio

### ISSUE THREAD

**Issue by gillenbrown** [yt-project/yt#2137]
### Bug report

**Bug summary**

When multiple N-body species are present in artio, yt cannot distinguish them, leading to errors and incorrect behavior when accessing the particle fields.

**Code for reproduction**

Dataset uploaded through curldrop at: http://use.yt/upload/abd30619 This is a DM-only artio zoom-in cosmological simulation. There are 7 different DM masses, which artio treats as different species. There are no differences in the species other than the mass.

```python
import yt
ds = yt.load("multiresolution_art/continuous_a1.0005.art")

# compare the true number of DM particles to the number yt can find
total_nbody = sum([ds.artio_parameters["num_particles_per_species"][i]
                   for i in range(ds.artio_parameters["num_particle_species"][0])
                   if ds.artio_parameters["particle_species_labels"][i] == "N-BODY"])
print("true number N-BODY:", total_nbody)
print("found number N-BODY:", len(ds.r[("N-BODY", "MASS")]))

# Try to get all particles 
ds.r[("all", "MASS")]
```

**Actual outcome**

```
true number N-BODY: 38965305
found number N-BODY: 34787336
```
Then the last line gives a`KeyError: (0, 'MASS')`

The number of found N-body particles is the number of the lowest mass particles in the dataset (species=0).

**Expected outcome**

It should be possible to access all N-body particles, and calling `ds.r[("all", "MASS")]` should not raise an error. 

The code works as expected using the artio dataset that's publicly available through yt, since it only has one set of N-body particles.

**My investigation**

The KeyError is happening in `yt/frontends/artio/data_structures.py`, in the `ARTIOOctreeSubset.fill_particles()` method. I think I've figured out that this happens because all the DM species have the label "N-BODY" and so get assigned the same index in line 97. Then as the species are iterated over, line 111 pops the DM index. Since all DM species have identical values, the first one works correctly, but any subsequent ones fail at line 107 with a KeyError. 

I haven't investigated this reason behind `ds.r[("N-BODY", "MASS")]` only getting species=0, but I presume its for similar reasons (all N-body particles have the same label). 

yt is reading the outputs correctly, since `ds.artio_parameters` shows all species of dark matter and the correct number of particles associated with each. It's only accessing these particles that causes problems.

I'd be happy to work on a pull request to fix this. Is there a preferred solution for multiresultion N-body particles in yt for other frontends?

**Version Information**

  * Operating System: macOS Sierra 10.12.6
  * Python Version: 3.6.6
  * yt version: 3.5.0
  * Other Libraries (if applicable):

**Comment by ngoldbaum** [comment]
Thanks for the detailed report!

Each particle type should be able to be read independently as a different field type if they’re stored independently in the output file.

You could take a look at how the SPH particle frontends set this up.

**Comment by gillenbrown** [comment]
They are stored separately, so I'll make sure to keep them separate. I'll take a look at how those other frontends work, thanks.

**Comment by MatthewTurk** [comment]
Looks like #2140 closed this!
