### ISSUE TITLE
doc builder needs a cython version bump

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#2180]
We recently bumped the minimum required version of cython on the yt-4.0 branch. This is causing the doc builder to fail on #2172. @Xarthisius can you bump cython to the newest release on the doc builder's docker image?

**Comment by ngoldbaum** [comment]
See https://tests.yt-project.org/job/yt_docs_new/247/console for an affected doc build log.

**Comment by Xarthisius** [comment]
```
$ TZ=America/Chicago date
Tue Mar  5 16:23:16 CST 2019
$ cython --version
Cython version 0.28.4
```
