### ISSUE TITLE
Consider a more search-engine friendly name?

### ISSUE THREAD

**Issue by nilsdeppe** [yt-project/yt#2198]
### Bug report

**Bug summary**

First of all, thanks for creating and maintaining yt! I wanted to point out to the developers that trying to find help for yt-related issues online is extremely difficult. Searching, for example, `yt-project set image resolution` returns many unrelated results with some search engines (e.g. DuckDuckGo) and no actually helpful results for resolving the problem. Unfortunately, it's not clear to me how to properly fix this without renaming the project, which is not something easily done.  If a successor to `yt` is ever developed I think the ability to find help via online searches would be a useful thing to consider during the naming process :)

I've had the same experience with `VisIt`, and I'm hoping naming visualization frameworks names that are nearly impossible to find help with online is not going to be a trend :)

**Comment by ngoldbaum** [comment]
You may have more success searching our sphinx documentation: http://yt-project.org/doc/search.html

**Comment by munkm** [comment]
I'd like to echo @ngoldbaum 's suggestion for searching the docs. I also tried the search you mentioned  in duckduckgo and noticed that if I searched yt-project with quotes the first search result is our plots tutorial that includes setting the image size with `set_figure_size()` and the resolution with `set_buff_size()`. I find that searching with quotes can help force my search engine to return results relevant to something that may have competing results from things with similar names/phrases. 

I'm going to close this issue as we don't have any successors to yt planned, and renaming the project right now would likely be very disruptive to our existing users. I'd be happy to reopen if a renaming discussion happens at a later point.

**Comment by nilsdeppe** [comment]
Okay, sounds good. Thank you!

**Comment by MatthewTurk** [comment]
I'm rather sympathetic to this concern.

**Comment by jzuhone** [comment]
I am also sympathetic to the concern, but I agree with @munkm that renaming the project would be _significantly_ disruptive.
