### ISSUE TITLE
Reduce size of pep8speaks config file

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#2201]
After https://github.com/OrkoHunter/pep8speaks/pull/106 has been merged, it looks like we can reduce the config file presence -- and reduce duplication -- for pep8speaks.

I believe it would be sufficient to remove our .pep8speaks.yml file, but we should investigate if we can remove the "ignore" and "exclude" sections and leave the bits where we define how the bot should talk.

**Comment by brittonsmith** [comment]
Looks like the PR has now been merged. Someone can give this a try if they like.

**Comment by MatthewTurk** [comment]
@brittonsmith Excellent!  I think this would be a great first-time contribution...

**Comment by neutrinoceros** [comment]
Closing as we stopped using pep8speak for a little while now
