### ISSUE TITLE
Updated NumFOCUS donation link

### ISSUE THREAD

**Issue by lisamartin72** [yt-project/yt#2216]
Hi, I am a new staff member at NumFOCUS. We have updated our donation provider from Flipcause to Salsa. The new link is: 

https://numfocus.salsalabs.org/donate-to-yt/index.html

Please update your website accordingly. : )

Thanks, 

Lisa Martin
NumFOCUS

**Comment by ngoldbaum** [comment]
I don't think we have a donate button on the website at all. Maybe we should add one?

**Comment by lisamartin72** [comment]
Most of the NumFOCUS projects have a donation link on their website.
