### ISSUE TITLE
Update docs for deposited particle fields

### ISSUE THREAD

**Issue by qobilidop** [yt-project/yt#2218]
The "Deposited Particle Fields" and following sections in `doc/source/analyzing/fields.rst` need to be updated to incorporate changes in yt-4.0. I've left a `FIXME` there. This issue is to make sure it gets done before yt-4.0.

Related issues:
- #2205
- #2192

**Comment by matthewturk** [comment]
@AshKelly Would you be open to helping me write some of this?

**Comment by jzuhone** [comment]
@matthewturk @AshKelly do we have any further thoughts on this one?

**Comment by matthewturk** [comment]
@jzuhone I'm trying to take it on
