### ISSUE TITLE
Doc notebooks are down

### ISSUE THREAD

**Issue by qobilidop** [yt-project/yt#2220]
[This page](https://yt-project.org/docs/dev/examining/generic_particle_data.html) is blank, and so do several other ones, all of which are notebooks with sphinx source code like this:

```
.. notebook:: Loading_Generic_Particle_Data.ipynb
```

**Comment by ngoldbaum** [comment]
@Xarthisius is it possible either RunNotebook or nbconvert are not installed on the doc build image? Looking at the build log it seems like the code in the try block is raising an exception so the notebook evaluating extensions never get added:

https://github.com/yt-project/yt/blob/623e88ee50bd7649bde4c78cf7fcd71a9589405c/doc/source/conf.py#L41-L48

**Comment by Xarthisius** [comment]
hmmm

```
fido@a13f4ca2ecd9 ~ $ pip install --user runnotebook
Requirement already satisfied: runnotebook in ./.local/lib64/python3.6/site-packages
fido@a13f4ca2ecd9 ~ $ pip install --user nbconvert
Requirement already satisfied: nbconvert in ./.local/lib64/python3.6/site-packages
```

I'll take a look...

**Comment by Xarthisius** [comment]
ok, trying to actually import them yields:

```
>>> import RunNotebook
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fido/.local/lib64/python3.6/site-packages/RunNotebook/__init__.py", line 1, in <module>
    from . import notebook_sphinxext
  File "/home/fido/.local/lib64/python3.6/site-packages/RunNotebook/notebook_sphinxext.py", line 7, in <module>
    from sphinx.util.compat import Directive
ImportError: cannot import name 'Directive'
```

**Comment by Xarthisius** [comment]
Run update and now they import fine.  Let me know if that fixes the issue.

**Comment by ngoldbaum** [comment]
@Xarthisius any chance you can manually re-trigger a build for yt 3.5.1?

**Comment by Xarthisius** [comment]
I'll do that as soon as I can. However I hit a snag that's not related, but introduces weird errors in build process. Unfortunately, there's a big event I need to prepare for tomorrow so it may take some time for me to fix this.

**Comment by ngoldbaum** [comment]
No worries, take your time.

**Comment by Xarthisius** [comment]
I've updated https://yt-project.org/doc/ and evaluated notebooks/cells are now present.
