### ISSUE TITLE
Version numbers of dependencies specified in many places

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#2224]
In looking at #2219, I noticed that the numpy version had to be updated a few places.  It would be nice (someday) to specify this one place and throw the appropriate errors based on a single definition of the required version of dependencies.

**Comment by neutrinoceros** [comment]
I just saw this. Technically #3074 is a duplicate issue to this one, but has a lot more detail, so I think we should close this one.
Also  #3078 is a first step towards solving this :)
