### ISSUE TITLE
a bug in yt/frontend/io.py

### ISSUE THREAD

**Issue by vikramkhaire** [yt-project/yt#2237]
I am new to yt. I was testing a few things with
trident. I tried an example from
https://trident.readthedocs.io/en/latest/generated/trident.make_onezone_d...

The code breaks at some line in yt/yt/frontend/ytdata/io.py
I think this block needs small change from dx to x in two places. 
```
if ptype == "grid":
dx = f["grid"]["dx"][()].min()
dx = self.ds.quan(
dx, parse_h5_attr(f["grid"]["dx"],
"units")).to("code_length")
```
as:
```
if ptype == "grid":
dx = f["grid"]["x"][()].min()
dx = self.ds.quan(
dx, parse_h5_attr(f["grid"]["x"],
"units")).to("code_length")
```

**Comment by munkm** [comment]
Hi @vikramkhaire. I just followed the example [here](https://trident.readthedocs.io/en/stable/generated/trident.make_onezone_dataset.html) from the trident docs and was able to create the following figure without an error: 
![image](https://user-images.githubusercontent.com/6745434/56751580-0aed2580-674c-11e9-9a4a-e40c6f135db8.png)

Can you tell me a little bit about what yt version and trident versions you're using, please? Could you also show the full printout of the error message and traceback that you get, and at which step in the example from the trident docs that it happens? I'd like to be able to replicate this to see the error you're getting.

**Comment by chummels** [comment]
Thanks, @munkm .  I think you'll get the error that @vikramkhaire is having if you mix the wrong versions of trident and yt.  @vikramkhaire : try to either use the stable version of yt + stable version of trident OR the `sph-viz` branch of trident and the`yt-4.0` branch of yt as per: https://nbviewer.jupyter.org/url/trident-project.org/notebooks/trident_demesh_install.ipynb

Please let us know if this addresses your problem.

**Comment by chummels** [comment]
This may still be an issue until we release a new version of Trident to match the yt-4.0 release.  But we cannot put out that Trident release until there is a yt_astro_analysis release to match the yt-4.0 release (see https://github.com/yt-project/yt_astro_analysis/issues/86).  But yes, I think we can close this current issue when those releases occur.

**Comment by neutrinoceros** [comment]
Yt_astro_analysis 1.1 is out, and is compatible with yt 4
Now waiting on Trident

**Comment by chummels** [comment]
I'm working on it.

**Comment by neutrinoceros** [comment]
@chummels, maybe you'd want to transfer this issue to the trident-project ? Anyway I'll close it for now as it seems like a no-op for yt itself.
