### ISSUE TITLE
field_parameters disappear for grid objects

### ISSUE THREAD

**Issue by RicardaBeckmann** [yt-project/yt#2263]
### Bug report
**Bug summary**

When trying to generate a derived_field of sampling_type='particle', field parameters are not found within the field generating function for grid-based data objects. They do work fine for other objects, such as all_data and sphere

**Code for reproduction**

```python
import yt

def _test_field_particle(field,data):
    print("has_parameter inside the function:",data.has_field_parameter('test_parameter'))
    if data.has_field_parameter('test_parameter'):
        param=data.get_field_parameter('test_parameter')
    else:
        param=0.0
    return data['particle_ones']*param

test_param=3.0
ds=yt.load('ramses_new_format/output_00002/info_00002.txt')

print("sampling_type='particle'")
ds.add_field(('test_field_part'),function=_test_field_particle,sampling_type='particle')

print("All data")
print('--------')
ad=ds.all_data()
ad.set_field_parameter('test_parameter',test_param)
print(ad['test_field_part'].max())
print("has_parameter outside the function:",ad.has_field_parameter('test_parameter'))
print('::::::::::')

print("Arbitrary grid")
print('--------')
resolution=128
grid= ds.arbitrary_grid([0.0, 0.0, 0.0], [1.0, 1.0, 1.0],dims=[128, 128, 128])
grid.set_field_parameter('test_parameter',test_param)
print(grid['test_field_part'].max())
print("has_parameter outside the function:",grid.has_field_parameter('test_parameter'))
print('::::::::::')
```

**Actual outcome**

```
sampling_type='particle'
has_parameter inside the function: False
All data
--------
has_parameter inside the function: True
has_parameter inside the function: True
has_parameter inside the function: True
3.0 dimensionless
has_parameter outside the function: True
::::::::::
Arbitrary grid
--------
has_parameter inside the function: False
has_parameter inside the function: False
has_parameter inside the function: False
0.0 dimensionless
has_parameter outside the function: True
::::::::::
```
As you can see, the field_parameter is not found for the grid object, but is found for all_data. This changes the values generated by the derived_field.

**Expected outcome**

As can be seen, the ad object finds the field_parameter within _test_field_particle and returns the correct result. The arbitrary_grid, on the other hand, does not find the field_parameter within _test_field_particle and so returns zeros, even though the parameter is found outside the function. 

I would have expected the outcome for both objects to be identical.

It does work well for both objects when using sampling_type='cell', and data['ones'] instead of data['particle_ones']. For sampling_type='cell', the field_parameters do not seem to be an issue.

**Version Information**
  * Operating System: unix
  * Python Version: 3.7.1
  * yt version:3.6.dev0 (updated this morning)
  * Other Libraries (if applicable): 

installed using pip install -e from the source code downloaded this morning

**Comment by brittonsmith** [comment]
Fixed in PR #2269.
