### ISSUE TITLE
Trouble loading in cosmological tipsy data

### ISSUE THREAD

**Issue by ibutsky** [yt-project/yt#2299]
### Bug report

**Bug summary**

I recently ran a git pull on the yt-4.0 branch, and I can no longer load in the cosmological tipsy simulations I'd been analyzing. The simulation output is too big to include here, but I attached a screenshot of the error

![Screen Shot 2019-07-18 at 4 49 55 PM](https://user-images.githubusercontent.com/850402/61499542-7c6bf700-a97c-11e9-9804-4e530671f839.png)

**Version Information**

  * Operating System: NASA Pleiades, comp-intel/2018.3.222 module
  * Python Version: python3/Intel_Python_3.6_2018.3.222 module
  * yt version: yt-4.0 branch, commit e4fc8cff0eb7cd4847dfb28055e2382b3a0962fa
  * Other Libraries (if applicable):

**Comment by jzuhone** [comment]
Hi Iryna,

I have a guess as to why this  could  be happening--I’ll have a look at this tomorrow.

John Z

**Comment by ibutsky** [comment]
Thanks, John! I just saw the new pull request, and it works!

**Comment by munkm** [comment]
Resolved via yt-project/yt#2300
