### ISSUE TITLE
`mpl_kwargs={'format' : ext}` is ignored when saving a slice plot

### ISSUE THREAD

**Issue by shoheiogawa** [yt-project/yt#2310]
### Bug report

**Bug summary**

`SlicePlot` object ignores file specication by `mpl_kwargs={'format' : ext}` in `save` even though some other options  are effective.

**Code for reproduction**

```python
import yt
import matplotlib.pyplot as plt

supported_file_formats = plt.gcf().canvas.get_supported_filetypes()
print('Matplotlib supports:')
for k, v in supported_file_formats.items():
    print(k, v)

print('Remove pgf')
del supported_file_formats['pgf']
ds = yt.load('MOOSE_sample_data/out.e')
slc = yt.SlicePlot(ds, 'z', 'diffused', origin='native')
for ext in supported_file_formats.keys():
    print('Saving as ' + ext)
    slc.save('images/mplkwargs_for_{:s}'.format(ext), mpl_kwargs={'format' : ext})
```

**Actual outcome**

The output files are all in png.
```
mplkwargs_for_eps_Slice_z_diffused.png
mplkwargs_for_jpeg_Slice_z_diffused.png
mplkwargs_for_jpg_Slice_z_diffused.png
mplkwargs_for_pdf_Slice_z_diffused.png
mplkwargs_for_png_Slice_z_diffused.png
mplkwargs_for_ps_Slice_z_diffused.png
mplkwargs_for_raw_Slice_z_diffused.png
mplkwargs_for_rgba_Slice_z_diffused.png
mplkwargs_for_svg_Slice_z_diffused.png
mplkwargs_for_svgz_Slice_z_diffused.png
mplkwargs_for_tif_Slice_z_diffused.png
mplkwargs_for_tiff_Slice_z_diffused.png
```

**Expected outcome**

Each image should be saved using the given format to `mpl_kwargs={'format' : ext}`

**Version Information**

  * Operating System:
  * Python Version:
  * yt version:
  * Other Libraries (if applicable):

**Comment by shoheiogawa** [comment]
Potentially related to issue #2309

**Comment by munkm** [comment]
Hi @shoheiogawa! @matthewturk submitted yt-project/yt#2318 to address yt-project/yt#2309. Once that's merged, would you mind checking to see if this issue still persists?

**Comment by shoheiogawa** [comment]
@munkm once the code is merged, I will check if the issue has been solved.
