### ISSUE TITLE
runtime error during volume rendering 

### ISSUE THREAD

**Issue by juliusknapp** [yt-project/yt#2313]
### Bug report

getting a  runtime error when trying to render image:
RuntimeError: Support for the <ufunc 'clip'> ufunc with 3 inputs has not beenadded to YTArray.
see https://mail.python.org/archives/list/yt-users@python.org/thread/YU3CPQDX5OIBBLJXLFXV2KGQWN7LXODJ/

"""
The code has to run in a jupyter enviroment
this is taken from
(https://yt-project.org/doc/quickstart/volume_rendering.html
"""

import yt

ds = yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")
sc = yt.create_scene(ds)

sc.camera.set_width(ds.quan(20, 'kpc'))

source = sc.sources['source_00']

tf = yt.ColorTransferFunction((-28, -24))
tf.add_layers(4, w=0.01)

source.set_transfer_function(tf)

sc.show()

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/src/python_virtual_env/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/src/python_virtual_env/lib/python3.7/site-packages/yt/visualization/volume_rendering/scene.py in _repr_png_(self)
    926         png = self._last_render.write_png(filename=None,
    927                                           sigma_clip=self._sigma_clip,
--> 928                                           background='black')
    929         self._sigma_clip = None
    930         return png

~/src/python_virtual_env/lib/python3.7/site-packages/yt/data_objects/image_array.py in write_png(self, filename, sigma_clip, background, rescale, clip_ratio)
    287         """
    288         if rescale:
--> 289             scaled = self.rescale(inline=False)
    290         else:
    291             scaled = self

~/src/python_virtual_env/lib/python3.7/site-packages/yt/data_objects/image_array.py in rescale(self, cmax, amax, inline)
    240                 np.multiply(self[:, :, 3], 1.0/amax, out[:, :, 3])
    241 
--> 242         np.clip(out, 0.0, 1.0, out)
    243         return out
    244 

<__array_function__ internals> in clip(*args, **kwargs)

~/src/python_virtual_env/lib/python3.7/site-packages/numpy/core/fromnumeric.py in clip(a, a_min, a_max, out, **kwargs)
   2035 
   2036     """
-> 2037     return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
   2038 
   2039 

~/src/python_virtual_env/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     59 
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:
     63         # A TypeError occurs if the object does have such a method in its

~/src/python_virtual_env/lib/python3.7/site-packages/numpy/core/_methods.py in _clip(a, min, max, out, casting, **kwargs)
    130     else:
    131         return _clip_dep_invoke_with_casting(
--> 132             um.clip, a, min, max, out=out, casting=casting, **kwargs)
    133 
    134 def _mean(a, axis=None, dtype=None, out=None, keepdims=False):

~/src/python_virtual_env/lib/python3.7/site-packages/numpy/core/_methods.py in _clip_dep_invoke_with_casting(ufunc, out, casting, *args, **kwargs)
     83     # try to deal with broken casting rules
     84     try:
---> 85         return ufunc(*args, out=out, **kwargs)
     86     except _exceptions._UFuncOutputCastingError as e:
     87         # Numpy 1.17.0, 2019-02-24

~/src/python_virtual_env/lib/python3.7/site-packages/yt/units/yt_array.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
   1399                 raise RuntimeError(
   1400                     "Support for the %s ufunc with %i inputs has not been"
-> 1401                     "added to YTArray." % (str(ufunc), len(inputs)))
   1402             if unit is None:
   1403                 out_arr = np.array(out_arr, copy=False)

RuntimeError: Support for the <ufunc 'clip'> ufunc with 3 inputs has not beenadded to YTArray.

<Scene Object>:
Sources: 
    source_00: <Volume Source>:YTRegion (galaxy0030): , center=[1.543e+24 1.543e+24 1.543e+24] cm, left_edge=[0. 0. 0.] cm, right_edge=[3.086e+24 3.086e+24 3.086e+24] cm transfer_function:<Color Transfer Function Object>:
x_bounds:[-28, -24] nbins:256 features:
	('gaussian', 'location(x):-28', 'width(x):0.01', 'height(y):(0.43, 0.024, 0.047, 0.001)')
	('gaussian', 'location(x):-27', 'width(x):0.01', 'height(y):(0.34, 0.34, 0.68, 0.01)')
	('gaussian', 'location(x):-25', 'width(x):0.01', 'height(y):(0.66, 0.66, 0.32, 0.1)')
	('gaussian', 'location(x):-24', 'width(x):0.01', 'height(y):(0.98, 0.98, 0.91,   1)')

Camera: 
    <Camera Object>:
	position:[1. 1. 1.] code_length
	focus:[0.5 0.5 0.5] code_length
	north_vector:[ 0.81649658 -0.40824829 -0.40824829] dimensionless
	width:[0.01999791 0.01999791 0.01999791] unitary
	light:None
	resolution:(512, 512)
Lens: <Lens Object>:
	lens_type:plane-parallel
	viewpoint:[-11545.30474893 -11545.30474893 -11545.30474893] code_length

**Version Information**

  * Operating System: macOS mojave
  * Python Version: 3.7.4
  * yt version: 3.5.1
  * Other Libraries (if applicable): numpy 1.17.0

installed via pip

**Comment by jzuhone** [comment]
This is due to a change in NumPy 1.17:
https://github.com/numpy/numpy/blob/master/doc/release/1.17.0-notes.rst#clip-now-uses-a-ufunc-under-the-hood

We'll have to fix this here in the master branch but also in [http://github.com/yt-project/unyt](unyt) for yt 4.0.

**Comment by jzuhone** [comment]
In theory you could temporarily get around this by downgrading to NumPy 1.16 until we provide a fix.

**Comment by jzuhone** [comment]
This code is sufficient to reproduce the error:

```python
import yt
import numpy as np
a = yt.YTArray(np.random.uniform(size=10), "cm")
a.clip(0.4,  0.6)
```

**Comment by jzuhone** [comment]
@ngoldbaum will we have to include a check for the NumPy version in the code? You know more about this than me.

**Comment by ngoldbaum** [comment]
Yes, probably. We have version checks for other ufuncs that were added in recent versions of numpy iirc. Also if numpy is going to be adding more ufuncs like this we could make the code strip units when `__array_ufunc__` sees a ufunc it doesn’t know about instead of raising an error. That’s probably more forward compatible. Can you open an issue in unyt for this as well? I’m finishing up here in NYC but should have time to poke at this next week.

**Comment by juliusknapp** [comment]
Dear John,

yes, I confirm, version 1.16 works perfect!

Cheers

Christoph

**Comment by j-rahman** [comment]
Does not work in `Numpy 1.17.2`. Try the volume rendering part here: https://yt-project.org/doc/examining/generic_array_data.html.

**Comment by ngoldbaum** [comment]
Yes, to get this to work you'll need to downgrade to numpy 1.16 or build yt from source.

**Comment by j-rahman** [comment]
Why is it that these requirements are not mentioned in the "getting started" guides? I have been trying to get started with the examples provided but somehow I end up needing to reinstall very specific versions of dependencies which should have been taken care of by package managers or the "All-in-One Installation Script", no? 😓

**Comment by ngoldbaum** [comment]
Basically it's been a while since we've done a release and numpy has broken a number of things since then in their releases that have happened since our last release. Once we do a new release things should be simpler. I'm sorry you had some trouble.
