### ISSUE TITLE
'accumulation' keyword not working on ProfilePlot

### ISSUE THREAD

**Issue by claytonstrawn** [yt-project/yt#2325]
**Bug summary**

When creating a ProfilePlot with both log = False and accumulation =True, it appears to give something which is not accumulating (for example, not uniformly increasing)

**Code for reproduction**
This code uses the sample data from ART-NMSU called `D9p_500`

```
import yt
pathname = "/Users/claytonstrawn/D9p_500/10MpcBox_HartGal_csf_a0.500.d" #change this to whatever you're using
ds = yt.load(pathname)
m,c = ds.find_max('density')
halo = ds.sphere(c,(100,'kpc'))
profiles = yt.create_profile(halo,'radius',['mass'],accumulation=True,logs={'radius':False})
plot = yt.ProfilePlot.from_profiles(profiles)
plot.show()
```
Just for convenience, here's what you get when you turn off accumulation: something that is definitely different, but not very much?
```
profiles_nonaccumulating = yt.create_profile(halo,'radius',['mass'],accumulation=False,logs={'radius':False})
plot_nonaccumulating = yt.ProfilePlot.from_profiles(profiles_nonaccumulating)
plot_nonaccumulating.show()
```

Results below: 
![image](https://user-images.githubusercontent.com/33767568/64640770-8a0f8d00-d3bf-11e9-9be1-4d993350a27a.png)
![image](https://user-images.githubusercontent.com/33767568/64640805-9f84b700-d3bf-11e9-9ce1-12fb03d83de1.png)

**Version Information**
I'm using yt-4.0 from source (with `pip install .`), on a Mac running MacOS 10.14.6

**edit**
the problem is not with the log, here's some other examples:
```
profiles_withlog = yt.create_profile(halo,'radius',['mass'],accumulation=True,logs={'radius':True})
plot_withlog = yt.ProfilePlot.from_profiles(profiles_withlog)
plot_withlog.show()
plot_defaults = yt.ProfilePlot(halo,'radius',['mass'],accumulation=True)
plot_defaults.show()
```
The above snippets both make this image: 
![image](https://user-images.githubusercontent.com/33767568/64641351-d8715b80-d3c0-11e9-8fce-c866ab63be53.png)

**Comment by matthewturk** [comment]
@claytonstrawn I had to dig into it to see what the issue is, and I think it's related to, for instance, #1774  and #2211 in that it's due to the `weight_field` argument.

What's happening is that by *default*, we're setting the `weight_field` -- which makes it take an average.  Thing is, we almost *never* want this when we're doing an accumulation.  (I think?)

*If* I read the code correctly, it's doing an accumulation of both the numerator and the denominator, *then* dividing.  So if we define `v_i` to be the (final) value in bin `i`, `f_i` to be the sum of all field values that fall into that bin, and the same for `w_i` in place of `f_i` for the weight field, we are defining it as:

`v_i == sum(f_j ; j < i) / sum( f_j * w_j ; j < i )`

So we're accumulating before doing the average, basically.

I set `weight_field = None` and got these results for the two plots, which look right to me.

![accumulation_true](https://user-images.githubusercontent.com/89019/64733245-fc5c9c00-d4a9-11e9-995b-ea9988279690.png)
![accumulation_false](https://user-images.githubusercontent.com/89019/64733244-fc5c9c00-d4a9-11e9-8807-c1c2c74897d6.png)

**Comment by claytonstrawn** [comment]
Ok great. I think I see now, the 'accumulation' graph just looks like a smoothed mass graph because it's still giving an average value, but averaged over the whole sphere instead of the binned shell. As far as I can tell, at least from my understanding of what the "accumulation" keyword is for, you're right that there's no point to doing this weighting behavior when accumulating. 

Would it be a good idea restrict ProfilePlot to only let you accumulate "extensive" values (energy, mass, momentum) instead of "intensive" (pressure, temperature, velocity, density)? Or at least make no-averageing the default when you have something extensive.

**Comment by matthewturk** [comment]
I do think it would be a good idea to set defaults!  I'm not sure we have the functionality to determine what is extensive/intensive in the code right now, but I do think we could at least by default change the weight field *default* based on whether or not we're accumulating.

**Comment by jzuhone** [comment]
extensive vs. intensive is not a thing, though it would be nice to have it. I had some ideas a long time ago about making yt equation-of-state aware, and this could go nicely into something like that. One can dream...

**Comment by claytonstrawn** [comment]
@matthewturk another somewhat different comment about ProfilePlot - Is there an issue open already regarding the ylabel being cut off when the tick numbers are several digits long? You can see that in your second image, for example. 

This should be a straightforward fix though, all it would take is some kind of fixing the position of the label to the figure instead of the axis (if I'm understanding it right)

**Comment by matthewturk** [comment]
@jzuhone let's turn those dreams lucid!

@claytonstrawn Is that something fixable with yt-specific code, or is it something that would be more naturally done via matplotlib?  My hesitancy is that going down the road of wrapping matplotlib code often leads to diminishing returns, as opposed to exposing it.

**Comment by brittonsmith** [comment]
I just want to add one thing before this issue gets closed. There is a use case for doing weighted averages with `accumulation=True`. The main one I'm thinking of is computing the virial radius, which is defined as the radius at which the mean density **in the enclosed sphere** is some threshold value. This is case where you don't want to do the average just in the bin, but everything up to and including that bin.

My interpretation here is that the code is working correctly and there is no remaining issue. The matplotlib issue mentioned is something outside of our control. I think this issue can be closed, but maybe I'll defer to @matthewturk to do it.

**Comment by matthewturk** [comment]
I have not thought about it as deeply as you have, so I *reject* your deferral!

**Comment by brittonsmith** [comment]
Then I've closed this. @claytonstrawn, if you think there's more to work out here, please feel free to reopen.
