### ISSUE TITLE
text not applied to images

### ISSUE THREAD

**Issue by christopherlovell** [yt-project/yt#2340]
### Bug report

**Bug summary**
When adding text to a plot using the standard matplotlib commands, the text is not visible on the first call to `.show()` or `.save(...)`. If `.text(...)` is called again on the same axis, the text is then visible.

**Code for reproduction**

This example is run on a cosmological hydro sim, but is reproducible with any input data.

```python
ds = yt.load('some/test/data/snapshot_000.hdf5')

center = np.array([18423.5,25232.6,26172.1])
width = 400
slc = SlicePlot(ds, 'x', 'density',  width=(width,'kpc'), center=center)

ax = slc.plots['density'].axes

ax.text(-170,-150,'some text text', size=15, color='white')
slc.show()

ax.text(-170,-150,'some text text', size=15, color='white')
sl.show()
```

*output*:
![test_A_Slice_x_density](https://user-images.githubusercontent.com/4648092/66040454-57b10580-e50f-11e9-9be1-3003bd4ed23d.png)
![test_B_Slice_x_density](https://user-images.githubusercontent.com/4648092/66040458-5a135f80-e50f-11e9-9646-1a777d787594.png)

**Expected outcome**

Text should show on the first call to `slc.show()` or `slc.save(...)`.

**Version Information**

  * Operating System: unix
  * Python Version: 
  * yt version: 3.5.1
  * Other Libraries (if applicable): matplotlib 3.1.1

python through conda, yt from `conda-forge` source

**Comment by matthewturk** [comment]
Hi Christopher!  Thanks for reporting this issue.  It is indeed the case
that the axes get cleared -- unfortunately this is a product of how we
(currently) set up our PlotWindow objects.  Right now, whenever the "data"
or "axes" are invalidated, it wipes the contents.  This may be able to
change in some future version, but for now, the way around this is to use
the `annotate_text` call on the plot objects themselves.

**Comment by christopherlovell** [comment]
Ah OK, will use `annotate_text1`
