### ISSUE TITLE
Plot axes labels should be in code units, not CGS, when the dataset uses a code unit system

### ISSUE THREAD

**Issue by ngoldbaum** [yt-project/yt#2353]
## Bug report

I'm submitting this on behalf of @neutrinoceros who for some reason is unable to submit an issue via the GitHub web UI.

**Bug summary**
`yt.load(<datafile>, unit_system="code")` produces inconsistent unit labelling between the field and the plot axes, e.g. a density field is labelled in "code mass/code length^3" but the axes are labelled in "cm" instead of "code length"

**Code for reproduction**
I'm using the public dataset `KelvinHelmholtz` from Pluto. I selected it because it's lightweight, but the behaviour I'm reporting is general to all frontends I've tested (including Enzo with dataset EnzoKelvinHelmholtz).

```python
dp = yt.load("data.0004.hdf5", unit_system="code")
# flipping the axes for readability since this dataset's domain is rectangular
ds.coordinates.x_axis[2] = 1
ds.coordinates.x_axis['z'] = 1
ds.coordinates.y_axis[2] = 0
ds.coordinates.y_axis['z'] = 0

p1 = yt.plot_2d(ds, "density")
p1.show()
```

**Actual outcome**
![data 0004 hdf5_Slice_z_density raw](https://user-images.githubusercontent.com/14075922/67873928-8503ca00-fb34-11e9-8947-479bda8b4b81.png)

**related**
setting the plot -square- width  without specifying a unit will make the axes labels in "code units" (regardless the unit system used), so there must be everything we need already.
```python
p1.set_width(1, )
p1.show()
```
![data 0004 hdf5_Slice_z_density width_1](https://user-images.githubusercontent.com/14075922/67873931-8634f700-fb34-11e9-8fee-83fc569235ee.png)

**Comment by munkm** [comment]
I double checked with `EnzoKelvinHelmholtz` and this is now resolved in master from the fix in yt-project/yt#2354

**Comment by neutrinoceros** [comment]
thanks @munkm !

**Comment by munkm** [comment]
Thank you @neutrinoceros! Your contributions have been really great!
