### ISSUE TITLE
Geographic coordinate handler unit issues

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#2373]
In plots that use the geographic coordinate handler, we should be specifying the units for `extent` as `code_length` (i.e., lat / lon) but it's converting them to `cm`.  This is done for completely understandable reasons (and is the confluence of pushing lat/lon into a mono-unit array) but results in cartopy returning a `MULTISTRING EMPTY` projection for the bounds.

This can likely be handled at the level of the coordinate handler.

This bug isn't actionable yet, but I will update it as I continue digging.

**Comment by munkm** [comment]
Thanks for digging into this. I'm all for investing time strengthening the geographic coordinate handlers.

**Comment by matthewturk** [comment]
One possible solution is to set `ds.no_cgs_equiv_length`.  But, in the subclasses of `PWViewerMPL`, we have this construction:

```python
if axes_unit is None:
    axes_unit = get_axes_unit(width, ds)
self.set_axes_unit(axes_unit)
```

This is where the axes units would be set to `code_length`, which enables us to `set_extent` corectly.  But, this happens *after* the superclass is called.  It's in the superclass that (for instance) `self.ds` is set.  So we can't just transplant it upward without making changes to all the subclasses.

I've come up with a fix that adds another special case to the unit system check, in a forthcoming PR.
