### ISSUE TITLE
[AMRVAC] bug: "e" field is assigned wrong name and unit

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#2375]
# Bug report
In AMRVAC, the on-disk field `"e"` is currently assigned the name `"energy"` and corresponding unit `mass_unit * length_unit**2 / time_unit_**2`, which is incorrect.

This field is in fact defined as the "energy density" in AMRVAC's documentation, though it remains ambiguous because the expression could be loosely used to mean "specific energy", which is not the same thing.

The fix is easy, but it needs to be discussed with AMRVAC's experts first.

**Comment by neutrinoceros** [comment]
related although independent https://github.com/yt-project/yt/issues/1301. I'm surprised this issue is still open almost 3yrs later, has this seen any evolution ? (ping @jzuhone)

**Comment by n-claes** [comment]
The on-disk field `e` in amrvac datasets denotes the _total energy density_ defined as
`rho * v**2`, and hence has units `g / (cm * s**2)` in cgs (since `rho` has units `g / cm**3`)
