### ISSUE TITLE
Add tab-completion for fields

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#2397]
Data objects all define a `__getitem__` method, which accepts fields from the dataset `field_list` and `derived_field_list`.  This list can be enormously long, however.  IPython (5.0+) defines a very straightforward way of constructing tab completions which we could utilize:

https://ipython.readthedocs.io/en/stable/config/integrating.html#tab-completion

Defining this on the base object would make it much simpler to navigate large lists of fields.

**Comment by samwalkow** [comment]
I can take this one!
