### ISSUE TITLE
numpy-induced bugs caught on apveyor

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#2445]
### Bug report

**Bug summary**

As I reported a few days back on slack, 2 new bugs have emerged with the latest numpy release (1.18.1) and are currently affecting all PRs (e.g. #2440 #2443 #2444 ). I'm reporting them properly here to help us keep track of them. I attempted to fix both and did not succeed thusfar.

**Code for reproduction**

failing tests are the following

- yt.units.tests.test_ytarray.test_ufuncs
Traceback :
```python
Traceback (most recent call last):
3233  File "C:\Miniconda36-x64\envs\test\lib\site-packages\nose\case.py", line 197, in runTest
3234    self.test(*self.arg)
3235  File "C:\projects\yt\yt\units\tests\test_ytarray.py", line 878, in test_ufuncs
3236    unary_ufunc_comparison(ufunc, YTArray([.3, .4, .5], 'cm'))
3237  File "C:\projects\yt\yt\units\tests\test_ytarray.py", line 809, in unary_ufunc_comparison
3238    ret1, ret2 = ufunc(a)
3239  File "C:\projects\yt\yt\units\yt_array.py", line 1378, in __array_ufunc__
3240    out_arr = func(np.asarray(inp), out=out, **kwargs)
3241TypeError: 'out' must be a tuple of arrays
```
I tried to monkey-patch this one but couldn't find an elegant (or any) fix, so I'm letting to someone with more experience with numpy's ufuncs. Note that this error can be reproduced locally with pytest already.

- yt.visualization.tests.test_color_maps.TestColorMaps.test_make_colormap
Traceback :
```python
Traceback (most recent call last):
3247  File "C:\Miniconda36-x64\envs\test\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
3248    num = operator.index(num)
3249TypeError: 'numpy.float64' object cannot be interpreted as an integer
3250
3251During handling of the above exception, another exception occurred:
3252
3253Traceback (most recent call last):
3254  File "C:\projects\yt\yt\visualization\tests\test_color_maps.py", line 50, in test_make_colormap
3255    name='french_flag', interpolate=False)
3256  File "C:\projects\yt\yt\visualization\color_maps.py", line 554, in make_colormap
3257    np.linspace(color[j], next_color[j], interval)
3258  File "<__array_function__ internals>", line 6, in linspace
3259  File "C:\Miniconda36-x64\envs\test\lib\site-packages\numpy\core\function_base.py", line 121, in linspace
3260    .format(type(num)))
3261TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```
so this one seems like a typecasting issue, where we are using a float-like numpy type instead of an integer type. It's likely only a matter of localising the "misstyped" variable, as I did here https://github.com/yt-project/yt/pull/2419

**Comment by munkm** [comment]
Resolved via yt-project/yt#2448
