### ISSUE TITLE
Bug in Dataset.find_max() for non-cartesian (polar) datasets

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#2446]
### Bug report

**Bug summary**
using `ds.find_max(field)` returns surprising values for the position array (second return), that do not seem to translate to the actual coordinates of the maximum.

**Code for reproduction**

Here are three different ways to compute an angular position for the maximum density in a polar dataset (amrvac):

```python
from numpy import arctan2
import yt
yt.mylog.setLevel(30)

ds = yt.load("amrvac/bw_polar_2D0000.dat")
assert ds.geometry == "polar"

# first method
ad = ds.all_data()
t1 = ad["theta"][ad["density"].argmax()]
print(t1)

# second method
t2 = ad.argmax("density", axis="theta")
print(t2)

# third method (broken)
x,y,_ = ds.find_max("density")[1]
t3 = arctan2(y, x)
print(t3)
```

**Actual outcome**

```
2.773437264497239 dimensionless
2.773437264497239 dimensionless
1.3679895475969959 dimensionless # <- inconsistent
```

**Comment by neutrinoceros** [comment]
I just discovered that this corrupts the underlying data such that `ds.covering_grid` will produce artifacts.

for instance
```python
import numpy as np
import matplotlib.pyplot as plt
import yt
ds = yt.load("amrvac/bw_polar_2D0000.dat")

fig, axes = plt.subplots(ncols=3, figsize=(10,10), sharex=True, sharey=True)
increment = np.pi/2/len(axes)
total_rot = 0

for i, ax in enumerate(axes):
    cg = ds.covering_grid(
            level=ds.max_level,
            left_edge=ds.domain_left_edge,
            dims=[128, 128, 1],
            use_pbar=False,
    )
    density_map = cg["density"].squeeze().value
    ax.imshow(density_map, cmap="thermal")
    ax.set_title(f"rot = {total_rot/np.pi:.2f} $\pi$")
    ds.rotate_frame_by(increment)
    total_rot += increment
```
results in
![ytrot](https://user-images.githubusercontent.com/14075922/74938352-21a4ed00-53ee-11ea-949e-4b128365b37e.png)

where black regions have uniform value "0".

As the definition for covering_grid seems to be obfuscated, I don't know how to inspect this further.

**Comment by matthewturk** [comment]
Intuitively this feels like a situation where we have an array that is getting converted in-place, or getting modified in-place, and that this is touching somewhere in the polar coordinate handler.  I am going to take a look at this during some slack time today but it might take longer than I can devote today.

**Comment by neutrinoceros** [comment]
note while this bug hasn't magically disappeared with the switch to unyt (I was kinda hoping it would), `find_min` is now broken
```python
ds.find_min("density")
>>> IterableUnitCoercionError: Received a list or tuple of quantities with nonuniform units: [unyt_quantity(0.9921875, 'cm'), unyt_quantity(3.16613635, '(dimensionless)'), unyt_quantity(0.5, 'cm')]
```
maybe a completely unrelated issue though.

**Comment by neutrinoceros** [comment]
alright so actually I just realised that 
```python
# third method (broken)
x,y,_ = ds.find_max("density")[1]
t3 = arctan2(y, x)
print(t3)
```
is "wrong" because this `y` is in fact an angle (theta) and is being attached a unit by `ds.find_max`'s internals. Maybe there's a better approach than what I did so far on #2744 to make this more intuitive or discoverable, but in the mean time I think it's okay to close this since it's arguably "not a bug".
