### ISSUE TITLE
Trouble Implementing Derived Fields Using Cantera

### ISSUE THREAD

**Issue by whitmanscu** [yt-project/yt#2465]
**Bug summary**

I'm working with an AMReX dataset that has temperature, pressure, etc. but no viscosity. I'd like to use Cantera through python to calculate viscosity as a derived field in yt. However, I'm running into the issue that `gas.TPX` in Cantera expects scalar values for T and P, while I have these as fields in yt (`data["temperature"]`, etc.), which wants derived fields to work as ufuncs according to the documentation. I've tried using `np.vectorize` and `np.frompyfunc` to pass in the T and P fields to cantera, but am getting errors that look like `KeyError: <ufunc '? (vectorized)'>` and `unit_operator = self._ufunc_registry[ufunc]` . Any advice on how to best accomplish this? I'm not sure if I'm going about it wrong, or if there's actually a limitation in the way that yt and Cantera are able to work together.

**Code for reproduction**

I'm able to reproduce this using the `castro_sedov_2d_cyl_in_cart_plt00150` dataset in the yt examples database. I have conda-forge installations of yt, numpy and cantera on my laptop.

```python
import yt
import numpy as np
import cantera as ct


def set_TPX(T, P):
    gas = ct.Solution("Air.cti")
    gas.TPX = T, P, 'O2:1.0, N2:3.76'
    return gas.viscosity


def _nu(field, data):
        vfunc = np.frompyfunc(set_TPX, 2, 1)
        dyn_visc = vfunc(data["Temp"], data["pressure"])
        return dyn_visc / data["density"]


ds = yt.load("castro_sedov_2d_cyl_in_cart_plt00150")

ds.add_field(("gas", "nu"), function=_nu,
             units=ds.unit_system["length"]**2/ds.unit_system["time"],
             sampling_type="cell")

```

**Actual outcome**

This results in the following error message(s)

```
Traceback (most recent call last):
  File "calc_nu.py", line 23, in <module>
    sampling_type="cell")
  File "/Users/sam/miniconda3/envs/cantera2/lib/python3.7/site-packages/yt/data_objects/static_output.py", line 1249, in add_field
    deps, _ = self.field_info.check_derived_fields([name])
  File "/Users/sam/miniconda3/envs/cantera2/lib/python3.7/site-packages/yt/fields/field_info_container.py", line 362, in check_derived_fields
    fd = fi.get_dependencies(ds = self.ds)
  File "/Users/sam/miniconda3/envs/cantera2/lib/python3.7/site-packages/yt/fields/derived_field.py", line 216, in get_dependencies
    e[self.name]
  File "/Users/sam/miniconda3/envs/cantera2/lib/python3.7/site-packages/yt/fields/field_detector.py", line 108, in __missing__
    vv = finfo(self)
  File "/Users/sam/miniconda3/envs/cantera2/lib/python3.7/site-packages/yt/fields/derived_field.py", line 256, in __call__
    dd = self._function(self, data)
  File "calc_nu.py", line 14, in _nu
    kin_visc = vfunc(data["Temp"], data["pressure"])
  File "/Users/sam/miniconda3/envs/cantera2/lib/python3.7/site-packages/yt/units/yt_array.py", line 1384, in __array_ufunc__
    unit_operator = self._ufunc_registry[ufunc]
KeyError: <ufunc '? (vectorized)'>
```

**Expected outcome**

I would like to be able to use Cantera 0D capabilities to implement derived fields with yt in a general sense

**Version Information**

  * Operating System: OSX (also replicated on a Cray machine with PrgEnv-gnu)
  * Python Version: 3.7
  * yt version: 3.5.1 (and master)
  * Other Libraries (if applicable): Cantera 2.4.0

all packages and libraries were installed with conda.

**Comment by ngoldbaum** [comment]
It looks like casting to ndarray works as a temporary workaround:

```
def _nu(field, data):
    vfunc = np.frompyfunc(set_TPX, 2, 1)
    dyn_visc = vfunc(data["Temp"].d, data["pressure"].d)
    dyn_visc = yt.YTArray(dyn_visc, "Pa*s")
    return dyn_visc / data["density"]
```

Since this is really about supporting `np.vectorize` and `np.frompyfunc` in yt's unit system I'm going to close this issue in favor of a more focused issue in unyt. Since this is fixed in unyt it can be backported to yt.units.
