### ISSUE TITLE
missing tag objects in master branch

### ISSUE THREAD

**Issue by migueldvb** [yt-project/yt#2512]
### Bug report

**Bug summary**

The two most recent release tags are missing in the master branch
of the yt repository.

**Code for reproduction**

Using the `git describe` command to get the most recent reachable tag from the
master branch with number of commits after tagging gives:

```
> git describe --tags
yt-3.4.1-2531-g3eb79bbe5
```

**Actual outcome**

These are the tags reachable from HEAD in master:

```
git tag --merged master

ast_gplv3
yt-2.0
yt-2.0.1
yt-2.1
yt-2.2
yt-2.3
yt-2.4
yt-2.5
yt-2.5.1
yt-2.5.2
yt-2.5.3
yt-2.5.4
yt-2.5.5
yt-2.6
yt-2.6.1
yt-2.6.2
yt-2.6.3
yt-3.0.0
yt-3.0.1
yt-3.0.2
yt-3.0a1
yt-3.0a2
yt-3.0a3
yt-3.0a4
yt-3.1.0
yt-3.2
yt-3.2.1
yt-3.2.2
yt-3.2.3
yt-3.3.0
yt-3.3.1
yt-3.3.2
yt-3.3.3
yt-3.3.4
yt-3.3.5
yt-3.4.0
yt-3.4.1
```

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

```
> git describe --tags
yt-3.5.0-2531-g3eb79bbe5
```

Both yt-3.5.0 and yt-3.5.1 tags can be found in the
stable branch (commits 62febd1f2f1d205193c721dd0dd87154af82c739 and
1dbe1593a61a29ce09ed4fa1727f3012cfefb066 that change version numbers in
source files) among with some backported changesets.

It looks like the `yt-3.5.0` tag should have ended in the master branch since
version 3.6.dev0 is based on 3.5.0 although the tag is not there.

**Version Information**

  * Operating System:
  * Python Version:
  * yt version:
  * Other Libraries (if applicable):

**Comment by munkm** [comment]
Hi @migueldvb, the 3.5x tags should be on master now. However, the -x series the most recent release won't be on master because we do the tagging on the `stable` branch (so for now the most recent tags will be 3.5x on master and you'll be able to access the 3.6x tags on stable. The behavior you're describing is expected based on our development process, so I'm going to close this.
