### ISSUE TITLE
Potential bug in testing fake amr dataset or Stream frontend ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#2522]
### Bug report

I *think* something is amiss here. (grid levels appear less symmetrical than designed to)

**Code for reproduction**
```python
import yt 
ds = yt.testing.fake_amr_ds()
for ax in "xyz":
    p = yt.SlicePlot(ds, ax, "grid_level") 
    p.set_cmap('grid_level', 'arbre') 
    p.set_log('grid_level', False)
    p.annotate_grids() 
    p.save('/tmp/fake_grid') 
```

**Actual outcome**
![fake_grid_level_Slice_x_grid_level](https://user-images.githubusercontent.com/14075922/78790896-75c05c80-79af-11ea-9d08-ebb06388e1e5.png)
![fake_grid_level_Slice_y_grid_level](https://user-images.githubusercontent.com/14075922/78790902-76f18980-79af-11ea-91e1-bfaeecff1f39.png)
![fake_grid_level_Slice_z_grid_level](https://user-images.githubusercontent.com/14075922/78790630-182c1000-79af-11ea-8c23-3cfac3587722.png)

To me this looks more like a frontend defect than an issue with the actual underlying data.
If this is indeed a bug (as opposed to deliberate design in the fake dataset), it is potentially harming development of present and future features based on this dataset for dev and testing.

**Comment by matthewturk** [comment]
It is actually *real*, in that this is drawn from `IsolatedGalaxy/galaxy0030/galaxy0030`.  So I think this is not a bug.

**Comment by neutrinoceros** [comment]
oh, indeed, it's even indicated in the source code 🤦‍♂ 
my bad, issue closed !
