### ISSUE TITLE
cosmology_answers.yml not found on PyPI

### ISSUE THREAD

**Issue by olebole** [yt-project/yt#2532]
### Bug report

**Bug summary**

When I try to run the tests, I get a message that `cosmology_answers.yml` could not be found. While it is in the repository, it is not distributed with the PyPI tarball.

**Code for reproduction**

Just running `python3.8 -m nose -v`

**Actual outcome**

```
======================================================================
ERROR: Test cosmology calculator functions against previously calculated values.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/yt-3.6.0/.pybuild/cpython3_3.8_yt/build/yt/testing.py", line 651, in true_wrapper
    return func(*args, **kwargs)
  File "/build/yt-3.6.0/.pybuild/cpython3_3.8_yt/build/yt/utilities/tests/test_cosmology.py", line 227, in test_cosmology_calculator_answers
    data = yaml.load(open(fn, 'r'), Loader=yaml.FullLoader)
FileNotFoundError: [Errno 2] No such file or directory: '/build/yt-3.6.0/.pybuild/cpython3_3.8_yt/build/yt/utilities/tests/cosmology_answers.yml'

----------------------------------------------------------------------
Ran 1587 tests in 428.796s

FAILED (errors=1)
```

**Expected outcome**

The test passes

**Version Information**

  * Operating System: Debian unstable
  * Python Version: 3.8
  * yt version: 3.6.0

Yt was installed from PyPI.

**Comment by Xarthisius** [comment]
Thanks for the report! We'll include it in the next bugfix release. In the meantime I'd suggest skipping that test for building the deb package.

**Comment by munkm** [comment]
Our next bugfix release (3.6.1) will still have this issue but the following releases should hopefully include the fixing PR.
