### ISSUE TITLE
importing yt requires pytest

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt#2565]
Importing yt now requires `pytest` to be installed. I'm creating an issue here because I'm not sure the best solution. I see a few options:

1. add pytest to `install_requires`
2. remove `run_nose` from `yt/__init__.py` (the one import from `yt/testing.py` where `pytest` is imported.
3. import `pytest` only inside the function that uses it.

I'm happy to do this, but just don't know which would be preferred.

**Comment by matthewturk** [comment]
@brittonsmith if we jammed `import pytest` into `run_nose` would that do it?

**Comment by brittonsmith** [comment]
Yeah, I think it's actually a different function in `yt/testing.py` that needs it, but jamming it in there would work fine. I was hesitant to do that straight away because I assumed more pytest functionality would be coming soon, but I'll just go ahead and do that.

**Comment by matthewturk** [comment]
It is coming soon, but even so, I don't know that we want it as a hard dep.

**Comment by brittonsmith** [comment]
I presume at that time we can get rid of the `run_nose` import in `yt/__init__.py`. Then this won't matter.

**Comment by munkm** [comment]
+1 to this. I think we should not have pytest as a hard dep.

**Comment by brittonsmith** [comment]
Fixed in PR #2566.
