### ISSUE TITLE
CI: is appveyor still necessary ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#2599]
A question about CI: Is the original reason for having appveyor + travis that Travis didn’t run on windows ? Apparently now it does, though with limited support. Since we don’t seem to use a very complicated configuration for appveyor, maybe it’s be worth reevalutating Travis as a windows option ?

Motivation for this inquiry: I recently cluttered the appveyor queue by pushing often (exceeding one push every hour). Travis however runs jobs concurrently and I have yet to see its queue saturate.

**Comment by munkm** [comment]
I support simplifying our CI. I'm glad we have an issue to discuss it. 

Some other options that we have (disclaimer: I haven't looked too deeply into the feasibility of any of these yet) other than moving everything to Travis could be 
* moving everything to circleCI, which we've talked about in the past. 
* using github actions
* azure seems to have unlimited minutes for open source and 10 free parallel jobs, which could be nice?

**Comment by neutrinoceros** [comment]
quick note: circleCI's free plan doesn't include macOS -> I assume that's a deal-breaker ?

**Comment by jzuhone** [comment]
@neutrinoceros i would say it is a deal-breaker, yes.

**Comment by munkm** [comment]
This page seems to say that Xcode is in the build environments? https://circleci.com/build-environments/

**Comment by neutrinoceros** [comment]
It seems that the windows build (appveyor) started failing on every single PR, even though I'm pretty confident that most of them don't affect the build itself.
I believe this is a side-effect of one specific failure caused in #2598 , that probably corrupted the build cache. Working on a fix now, but unless I'm mistaken, this is one more reason the CI should be reevaluated.

**Comment by munkm** [comment]
Based on when PRs started failing on appveyor, that error started on commits before the first commit in 2598.

**Comment by neutrinoceros** [comment]
Oh you're right, I went ahead of myself :/

**Comment by brittonsmith** [comment]
Perhaps we could save MacOS build minutes on circleci by only doing periodic nightly or weekly builds rather than building all PRs.

**Comment by neutrinoceros** [comment]
github actions look very neat. Without digging too much, I have not yet found any good argument against it.

**Comment by brittonsmith** [comment]
Github actions seems good. If it works on a number of OSs and we could cut down on the services, I'd be in favor.

**Comment by matthewturk** [comment]
My personal preference would be to use Github actions as much as possible, and use Azure pipelines in conjunction with that.  Consolidation would be awesome.

**Comment by matthewturk** [comment]
And honestly, putting stuff like the release workflow into github actions, etc, would be great too...

**Comment by munkm** [comment]
I'm going to assign this to myself and I'll start setting up some stuff with GH actions that we can all preview to see if it's what we want.

**Comment by cphyc** [comment]
Solved by #2908.
