### ISSUE TITLE
[ANN] block merging on 4.0 branch

### ISSUE THREAD

**Issue by munkm** [yt-project/yt#2601]
Right now @matthewturk is working on finishing up the 4.0/master merge in yt-project/yt#2437 . Merging PRs into both master and yt-4.0 are making this PR take longer and ultimately delaying our release of 4.0. It was discussed in a triage meeting a few weeks back that we pause merges with the 4.0 branch until 2437 is completed. I've personally not been merging PRs on that branch and I suspect other maintainers are also, but this should be documented publicly somewhere so it is clear why approved PRs are not getting merged. Of course, all of this is up for discussion here in this issue and on the mailing list.

**Comment by jzuhone** [comment]
I am totally in favor of this.

**Comment by neutrinoceros** [comment]
I support this too !

**Comment by cphyc** [comment]
Should this issue be closed now?

**Comment by munkm** [comment]
Yep it should!
