### ISSUE TITLE
YTEP-0003 conventions for ARTIO 

### ISSUE THREAD

**Issue by cavestruz** [yt-project/yt#2608]
### Bug report

**Bug summary**

ARTIO still has variable names that need to be modified to [YTEP-0003 conventions](https://ytep.readthedocs.io/en/master/YTEPs/YTEP-0003.html).  

- [ ]  modify fields such as `HeIII density` -> `He_p2_density` in line 53 of yt/frontends/artio/fields.py
- [ ]  add old field names to yt/fields/field_aliases.py to allow for backwards compatibility using `ds._setup_deprecated_fields()`

Note: Self-assigning with @provider10

**Expected outcome**

To be able to access ARTIO fields with either field name.

**Comment by cavestruz** [comment]
Hi @neutrinoceros,

@provider10 has almost finished all of the changes needed according to the checklist above [in a branch off of our fork](https://github.com/cavestruz/yt/tree/issue/2608/artio-with-ytep-0003-conv).  But, we do want to make sure that folks using the other field names can easily use (and know to use) the back-compatibility functionality.  Might there be any thoughts or suggestions for putting in a specific error message for ARTIO users to let them know that they are missing the if the `ds._setup_deprecated_fields()` if the user has _not_ added it?

Thank you!  
- Camille and Raziq

**Comment by neutrinoceros** [comment]
Hi ! Can you open a PR from this branch ? it would make the review easier since the diff would immediately available.
In any case, I do have an idea how this could be implemented but I would like the opinion of more experienced yt devs on this. I'll add my idea on your PR as a comment for it to be discussed :)

**Comment by Provider10** [comment]
This issue is addressed with [PR 2613](https://github.com/yt-project/yt/pull/2613) and I think should be closed.

**Comment by neutrinoceros** [comment]
Agreed, thanks for reminding me !
