### ISSUE TITLE
ParticleSubselectionTests for yt4-merge

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#2616]
We need to add independent checks of the particle machinery in addition to answer tests:

 - [x] eagle
 - [x] gadget_fof
 - [x] flash (particle)
 - [x] owls
 - [x] rockstar
 - [x] swift
 - [x] tipsy
 - [x] ytdata (?)
 - [x] sph
 - [x] open_pmd
 - [x] art
 - [x] ahf
 - [x] arepo

Here is an example of doing this: https://github.com/yt-project/yt/blob/b20c3edbbc5b057077d12dc456974f797ce726f6/yt/frontends/gadget/tests/test_outputs.py#L111

**Comment by jzuhone** [comment]
I can take some of these on.

**Comment by matthewturk** [comment]
I will take gadget_fof, rockstar, tipsy and open_pmd

**Comment by matthewturk** [comment]
I went ahead and implemented all of the remaining ones.

**Comment by munkm** [comment]
I think this is fixed
