### ISSUE TITLE
Add narrative documentation for how the demeshening works

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#2629]

**Comment by matthewturk** [comment]
This is a great idea.  I think we need to expand our "yt 4 differences"
list.

**Comment by munkm** [comment]
@matthewturk you are the best person to write this right now.

**Comment by matthewturk** [comment]
Ok

**Comment by jzuhone** [comment]
@matthewturk just checking in on this one

**Comment by matthewturk** [comment]
it's a shame I don't have the time in my prompt because look at what I have to show right now:

```
$ git checkout -b demeshening_docs
Switched to a new branch 'demeshening_docs'
```

thank you for checking in, though -- the accoundabilibuddy stuff works well for me.
