### ISSUE TITLE
load_sample should include default arguments

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#2636]
Some of our datasets that can be loaded with `load_sample` require some additional arguments to be passed.  These should be included in the `load_sample` function and `sample_data_registry.json`.

**Comment by chrishavlin** [comment]
ended up here searching for `load_sample` issues, pretty sure this can be closed. @neutrinoceros ?

**Comment by neutrinoceros** [comment]
Hum yeah, I don't know exactly when this was fixed, but it was already done by the time #3377 was open more than 2 years ago.
Thanks @chrishavlin for noticing !
