### ISSUE TITLE
Creation of any region fails under yt-4 on windows installation

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#2651]
### Bug report

**Bug summary**

I've installed the tip of the yt-4.0 branch on a windows virtualbox instance, and most basic functionality seems to fail due to a common error: `ParticleBitmap.load_bitmasks()`.  I've included what I thought was the simplest code for reproduction, but this occurs if you try to access any data with `ds.r[('gas', 'temperature')]` in particle-based datasets.  Note, this doesn't seem to affect grid-based datasets, as I received no errors using the `IsolatedGalaxy` dataset.  I see none of these errors in OS X, but other users in the Trident community using linux and os X have anecdotally said that they saw similar `load_bitmasks()`-based errors with different functionality pop up recently in the yt-4.0 branch.

**Code for reproduction**

```python
import yt
fn = 'FIRE_M12i_ref11/snapshot_600.hdf5'
ds = yt.load(fn)
ad = ds.all_data()
```

**Actual outcome**

```
yt : [INFO     ] 2020-06-19 11:12:50,452 Calculating time from 1.000e+00 to be 4.355e+17 seconds
yt : [INFO     ] 2020-06-19 11:12:50,452 Assuming length units are in kpc/h (comoving)
yt : [INFO     ] 2020-06-19 11:12:50,549 Parameters: current_time              = 4.3545571088051405e+17 s
yt : [INFO     ] 2020-06-19 11:12:50,549 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2020-06-19 11:12:50,561 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2020-06-19 11:12:50,561 Parameters: domain_right_edge         = [60000. 60000. 60000.]
yt : [INFO     ] 2020-06-19 11:12:50,561 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2020-06-19 11:12:50,561 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2020-06-19 11:12:50,561 Parameters: omega_lambda              = 0.728
yt : [INFO     ] 2020-06-19 11:12:50,561 Parameters: omega_matter              = 0.272
yt : [INFO     ] 2020-06-19 11:12:50,561 Parameters: omega_radiation           = 0.0
yt : [INFO     ] 2020-06-19 11:12:50,561 Parameters: hubble_constant           = 0.702
yt : [INFO     ] 2020-06-19 11:12:50,577 Allocating for 4.787e+06 particles

Initializing coarse index :   0%|          | 0/10 [00:00<?, ?it/s]
Initializing coarse index :  20%|##        | 2/10 [00:00<00:00, 16.00it/s]
Initializing coarse index :  40%|####      | 4/10 [00:00<00:00, 14.39it/s]
Initializing coarse index :  70%|#######   | 7/10 [00:00<00:00, 17.32it/s]
Initializing coarse index : 100%|##########| 10/10 [00:00<00:00, 18.29it/s]

Initializing refined index:   0%|          | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "c:\users\ieuser\yt\yt\geometry\particle_geometry_handler.py", line 136, in _initialize_index
    rflag = self.regions.load_bitmasks(fname)
  File "yt\geometry\particle_oct_container.pyx", line 997, in yt.geometry.particle_oct_container.ParticleBitmap.load_bitmasks
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    ad = ds.all_data()
  File "c:\users\ieuser\yt\yt\data_objects\static_output.py", line 930, in all_data
    self.index
  File "c:\users\ieuser\yt\yt\data_objects\static_output.py", line 505, in index
    self, dataset_type=self.dataset_type)
  File "c:\users\ieuser\yt\yt\geometry\particle_geometry_handler.py", line 28, in __init__
    self._initialize_index()
  File "c:\users\ieuser\yt\yt\frontends\sph\data_structures.py", line 75, in _initialize_index
    super(SPHParticleIndex, self)._initialize_index()
  File "c:\users\ieuser\yt\yt\geometry\particle_geometry_handler.py", line 144, in _initialize_index
    self._initialize_refined_index()
  File "c:\users\ieuser\yt\yt\geometry\particle_geometry_handler.py", line 200, in _initialize_refined_index
    mask_threshold = mask_threshold)
  File "yt\geometry\particle_oct_container.pyx", line 621, in yt.geometry.particle_oct_container.ParticleBitmap._refined_index_data_file
  File "yt\geometry\particle_oct_container.pyx", line 691, in yt.geometry.particle_oct_container.ParticleBitmap.__refined_index_data_file
ValueError: Item size of buffer (4 bytes) does not match size of 'uint64_t' (8 bytes)
```

**Expected outcome**

I expect that it would generate the region and return without any output/error.

**Version Information**
  * Operating System: Windows 10 Enterprise Evaluation 1809
  * Python Version: 3.7.7
  * yt version: yt-4.0 branch current tip as of Friday, June 19 (37052e657253321)
  * Other Libraries (if applicable): 

I installed yt-4.0 using Miniconda on a vanilla virtual machine box:
  * Installed Miniconda3-Latest-Windows-x86.exe from https://repo.anaconda.com/miniconda
  * conda install numpy scipy cython git
  * Install Windows Compilers for compiling yt cython source.  See https://wiki.python.org/moin/WindowsCompilers and section on Microsoft Visual C++ 14.2 standalone: Build Tools for Visual Studio 2019
  * git clone https://github.com/yt-project/yt.git
  * cd yt
  * git checkout yt-4.0
  * git pull
  * pip install -e .

**Comment by matthewturk** [comment]
It should be detecting and removing existing EWAH files.  Can you try removing any EWAH files and trying again?

**Comment by chummels** [comment]
It doesn't appear that any EWAH files have been created at all for this dataset.  I don't see any in the directory where the dataset exists, nor in the directory where I'm running the script.  I tried moving the datafile to a different directory entirely and re-running the script and it fails at the same point, after it has read in the coarse indices but before it's able to generate the refined indices.

**Comment by matthewturk** [comment]
Hmm, interesting.

To work around issues on windows, we changed the size of the word to 32 bits.  What that error is suggesting is that the type size has a mismatch somewhere.  We did have some issues with Windows, which @jzuhone worked on in WSL, so it's possible there is another edge case that is breaking it.

But on the plus side, this is all happening in the type of the headers.  So that's interesting.  I assume you're starting afresh based on your comments, so I'm not totally sure.

**Comment by chummels** [comment]
Yeah, this is a fresh install with virtually no other changes on the system.  I'm actually testing it out because a trident user with a windows machine was encountering this problem, so I wanted to be able to reproduce it.  I'm happy to help diagnose this, but I'm really unfamiliar with this section of the code.  But if you give me a corner I can dig into, I might be able to help more?  Or maybe @jzuhone has ideas on where this issue is arising?

**Comment by jzuhone** [comment]
I can have a look

**Comment by jzuhone** [comment]
@chummels I can't reproduce this, but I think the reason is because the Miniconda that you linked to is the 32-bit Python installation, not the 64-bit one. This explains why the error you're seeing is complaining about unsigned int types. 

The Miniconda installer you need is this one: 

https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe

Note the one you listed was missing the "64" in the filename. 

To my knowledge, we have never supported 32-bit Windows installations.

**Comment by chummels** [comment]
@jzuhone You are absolutely correct.  The problem was in the fact that I was using a 32-bit Python installation through conda.  When I re-installed conda using the 64-bit Windows py3.7 installer, this problem goes away and yt operates properly.  I had mistakenly thought that since I was installing Windows as a VirtualBox instance on a OS X install that was itself 32-bit, that things had to remain 32-bit.  But I was wrong.  I'll close this issue.  Thanks for the help!
