### ISSUE TITLE
Decreasing code duplication

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#2708]
### Issue

**Issue summary**

Currently there is a lot of code duplication in `yt/frontends/`. Fixing this would likely require a massive revamping and update of the codebase, but would improve code readability and maintenance.

I am opening the issue to track this issue and provide some scripts to work on it.

**Code for reproduction**

```bash
pylint --disable=all --enable=similarities yt/frontends/
```
The output can be found in [yt.frontends.similarities.log](https://github.com/yt-project/yt/files/4858256/yt.frontends.similarities.log).

**Expected outcome**

No duplication! Or only a few lines where we want things to be explicit, e.g. when defining fields.

**Comment by neutrinoceros** [comment]
I'd like to see a plot with the history of that number (maybe normalised by the total number of lines), maybe sample once every 10 commits or so ?

**Comment by cphyc** [comment]
![duplicate_ratio](https://user-images.githubusercontent.com/5411875/86256412-35d4d400-bbb0-11ea-8244-d15f22d9c299.png)

---

The data to generate the plot are obtained from
```bash
#!/bin/bash

echo "commit,date,nlines,nduplicates" > duplicates.csv
for commit in $(git rev-list master | python -c 'import sys; v=sys.stdin.read(); print("\n".join(v.split("\n")[::500]))'); do
    git checkout $commit -q || exit 1
    commit_date=$(git show -s --format=%ci $commit)
    nduplicates=$(pylint --disable=all --enable=similarities $(git ls-files yt/frontends) | wc -l)
    nlines=$(git ls-files yt/frontends | xargs cat | wc -l)
    echo $commit, $commit_date, $nlines, $nduplicates
done >> duplicates.csv
```

The plot is made with
```python
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('duplicates.csv')
df['date'] = pd.to_datetime(df['date'])
df['duplicate_ratio'] = df['nduplicates'] / df['nlines'] * 100

plt.plot('date' ,'duplicate_ratio', data=df)
plt.xlabel('Date')
plt.ylabel('Duplicate ratio (%)', color='C0')

plt.twinx()
plt.plot('date', 'nduplicates', data=df, color='C1')
plt.ylabel('# duplicates', color='C1')
plt.savefig('duplicate_ratio.png')
```

**Comment by matthewturk** [comment]
I would be so incredibly interested in pursuing de-duplication.

**Comment by cphyc** [comment]
Update on Wed 05 Aug 2020
![duplicate_ratio](https://user-images.githubusercontent.com/5411875/89387408-bd0eed80-d702-11ea-856e-30a352cbcde6.png)

**Comment by neutrinoceros** [comment]
Good job ! Wait...
Can you narrow it down to one commit ?

**Comment by cphyc** [comment]
> Good job ! Wait...
> Can you narrow it down to one commit ?

The commit in question is ebadee6, which is our black pass. This made many lines that were functionally equivalent but written in slightly different ways apparent, so I believe black just made the duplicate detection more robust!

**Comment by chummels** [comment]
Here's a start: #3308 .  It seems like perhaps this could extend to some of the other files in the skeleton frontend with superclasses.

**Comment by neutrinoceros** [comment]
Note that I find it has been extremely painful to maintain frontends subclassing *each other*, even though that probably started with deduplication in mind.
On the other hand, having more abstract classes layers between the root `Dataset` and frontend-defined subclasses may still be a good idea as long as there's only a couple of them. Possibly `ParticleDataset`, `AMRDataset`, `OctreeDataset`... depending on what's relevant.

**Comment by neutrinoceros** [comment]
So I'm still not convinced this is realistically actionnable. IMHO, lots of small improvements can be performed in `yt/frontends` but hardly any that could bring closure.
I'm going to aggressively close this to make ever so slightly more room to other things. Please anyone reopen if you disagree :)
