### ISSUE TITLE
Clarity of volume rendering workflow examples (Scene.render() vs Scene.save())

### ISSUE THREAD

**Issue by chrishavlin** [yt-project/yt#2733]
### Bug report 

Not a bug, but the proper workflow for when to use `Scene.render()` and `Scene.save()` needs clarification. 

There are several docstring examples (e.g., [Scene.render](https://yt-project.org/doc/reference/api/yt.visualization.volume_rendering.scene.html#yt.visualization.volume_rendering.scene.Scene.render) and [Scene.save](https://yt-project.org/doc/reference/api/yt.visualization.volume_rendering.scene.html#yt.visualization.volume_rendering.scene.Scene.save)) for rendering that suggest the following workflow : 

```python
import yt
ds = yt.load('IsolatedGalaxy/galaxy0030/galaxy0030')
sc = yt.create_scene(ds)
im = sc.render() 
sc.save(sigma_clip=4.0) 
```
But `sc.save()` contains a call to `sc.render()`, so this workflow will render twice. 

`sc.save()` was changed (see [this commit](https://github.com/yt-project/yt/commit/cd2184576cd38468a6f59ad4611c06817bdfec0b)) so that `sc.render()` is always called, so presumably this is the desired behavior and the docstrings should just be corrected, but there should also be a comment in the code of `Scene.save()` explaining the need to always call `Scene.render()`. Are there ever cases where one would call `Scene.render()` ? 

The volume rendering examples [here](https://yt-project.org/docs/dev/visualizing/volume_rendering.html) only include the call to `Scene.scene()`, the examples [here](https://yt-project.org/docs/dev/cookbook/simple_plots.html#simple-volume-rendering) sometimes use `yt.volume_rendering()` and also `write_png`: 

```
im, sc = yt.volume_render(ds, 'density')
im.write_png("original.png", sigma_clip=8.0)
```
Note also that the docstring for [Scene.save](https://yt-project.org/doc/reference/api/yt.visualization.volume_rendering.scene.html#yt.visualization.volume_rendering.scene.Scene.save)  also has and alternate example in which `Scene.render()` is not called, but it's not clear why one would use either example. 

Perhaps a diagram of when to use what method would be useful?

**Comment by chrishavlin** [comment]
@ngoldbaum , your input here would probably be insightful here since you modified `Scene.save()` :)

**Comment by matthewturk** [comment]
@chrishavlin I think Nathan is taking a bit of time off, and hopefully we can work through this.  I'll dig in and report what I can.

**Comment by chummels** [comment]
I believe the reason that there is some repetition in calling `render()` internally is due to the fact that it isn't obvious one needs to `render()` prior to saving or volume rendering, based on other parts of the yt codebase (e.g., `ProjectionPlot`).  So `render()` gets called internally prior to `save()` to ensure that the user *has* rendered so it doesn't fail on `save()`.  `render()` also gets called in the one-stop helper function `volume_render()`.

**Comment by chrishavlin** [comment]
Closing now that #2743 was merged.
