### ISSUE TITLE
try yt link on yt-project.org not working

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt#2742]
Clicking on that take me to:
https://girder.hub.yt/undefined

with the message:
```
404 Not Found
Nothing matches the given URI
```

**Comment by neutrinoceros** [comment]
Couldn't reproduce on my machine/network
It gets me as far as the login prompt, haven't check if it works after that (I don't really want to create credentials just for this).

**Comment by brittonsmith** [comment]
It happens after the login for me. I've gotten someone else to give this a try. You get a message about loading a notebook but eventually a 404 error.

**Comment by neutrinoceros** [comment]
Thanks for the clarification ! I wasn't sure when the error was supposed to happen.

**Comment by Xarthisius** [comment]
We have recently changed the ip for the server hosting hub.yt. However, that change was not reflected in a firewall settings on the compute node that launches the notebooks. I believe it's working now. Please reopen if that's not the case.

**Comment by brittonsmith** [comment]
Works again! Thanks!
