### ISSUE TITLE
photon_simulator.py: replace pyfits-deprecated "update_ext_name"-method with ".name attribute"?

### ISSUE THREAD

**Issue by alexkolo** [yt-project/yt#2747]
`photon_simulator.py` uses the `update_ext_name` method for an BinTableHDU object, while the `pyfits.py` version used to create this object has already deprecated this method (since version 3.2) and recommends using the `.name` attribute or Header.set instead. [1] 

This results in the error: `AttributeError: 'BinTableHDU' object has no attribute 'update_ext_name'` for certain methods of `photon_simulator.py`.

For instance, a fix for `write_simput_file` could look like this:
```
        #tbhdu.update_ext_name("PHLIST") # Deprecated since version 3.2 of pyfits: Use the .name attribute
        tbhdu.name = "PHLIST"

        #wrhdu.update_ext_name("SRC_CAT") # Deprecated since version 3.2 of pyfits: Use the .name attribute
        wrhdu.name = "SRC_CAT"
```

[1] https://pyfits.readthedocs.io/en/v3.3.0/api_docs/api_tables.html#pyfits.BinTableHDU.update_ext_name

**Comment by jzuhone** [comment]
Hi @alexkolo:

The `photon_simulator` code in yt is deprecated and is no longer being updated. You should now use the separate package [pyXSIM](https://hea-www.cfa.harvard.edu/~jzuhone/pyxsim), which is the successor to `photon_simulator`.

**Comment by alexkolo** [comment]
Dear @jzuhone 
I'm sorry. I overlooked that in the description. Although I noticed that the `project_photons` method of `pyXSIM` doesn't have an option for a responses-files anymore. I know there are other packages, which can do this, but it was certainly very convenient for a quick check.
