### ISSUE TITLE
Pickling is unsafe and brittle

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#2784]
### Bug report

**Bug summary**

I noticed there's a handful of places in the code base where we use the `pickle` module to dump and load data.
After reading [this blogpost](https://nedbatchelder.com/blog/202006/pickles_nine_flaws.html) (in particular point 1 and 2), I feel like these should be reimplemented with safer data storing methods when possible, or simply removed if they turn out not used.

**Comment by brittonsmith** [comment]
This sounds familiar, as in I think getting rid of `pickle` code is a conclusion that we've arrived at before, but have not followed through on. There may be exceptions, but I think `yt.save_as_dataset` is probably the most reliable method for saving and reloading data. At least, I believe its the one we endorse the most.

**Comment by neutrinoceros** [comment]
I'm curious what is this function used for ? Building datasets from scratch with the Stream frontend and saving them, or something else ?

**Comment by brittonsmith** [comment]
It's basically a way of saving arbitrary array data to a format that can be yt.loaded. It's become the basis for the `HaloCatalog` frontend and I use it in `ytree` as well. [Here](https://yt-project.org/docs/dev/analyzing/saving_data.html) are the docs in it.

**Comment by neutrinoceros** [comment]
Nice one ! indeed this is much better, and I think we could probably just get rid of of `save_object` methods, going to try this now !
