### ISSUE TITLE
load particles from generic AMReX dataset

### ISSUE THREAD

**Issue by darylbond** [yt-project/yt#2805]
I am attempting to read in particle data generated by AMReX and note that if I comment out `AMReXDataset._is_valid()` then I can access my particle data. Essentially I just want the `AMReXDataset._parse_parameter_file()` function, which is effectively permanently disabled by `AMReXDataset._is_valid` always returning `False`. Is it possible to do away with this function and just rely on the `BoxlibDataset` version?

https://github.com/yt-project/yt/blob/4acdd33ac2b9fc646388c24aaf74857aa3bf844c/yt/frontends/boxlib/data_structures.py#L1722

**Comment by neutrinoceros** [comment]
Hi @darylbond .
If this method hard-returns False it signals that the class isn't meant to be instantiated by `yt.load()`.
However the class isn't actually used anywhere in the code base, so I think that what's really happening here is that the `_is_valid()` method was never implemented.


> note that if I comment out AMReXDataset._is_valid()

I note that his workaround won't work on the latest version of master since this method is now required in children classes of `Dataset` to be instantiated.

ping @zingale and @matthewturk for possible implementations of this missing bit ?

**Comment by neutrinoceros** [comment]
For reference, what class is your dataset loaded with (if you _don't_ modify the AMRRexDataset class) ?
Here's how to inspect it
```python
ds = yt.load(yourfile)
print(type(ds))
```

**Comment by neutrinoceros** [comment]
Actually it looks to me like the file could be validated as long as
1) it's Boxlib valid
2) particles can be found the way `AMRexDataset.parse_parameter_file()` expects them

I could try out this implementation if you are able to share the dataset :)

**Comment by darylbond** [comment]
My apologies, I should have checked I was running the latest version before posting.

The unmodified class loads the dataset as a `yt.frontends.boxlib.data_structures.BoxlibDataset`.

If you could implement this functionality would be greatly appreciated. I was able to access both particle datasets in the attached amrex plotfile using the hack I implemented on version 3.4.0.

[plt.Cavity00010.zip](https://github.com/yt-project/yt/files/5020330/plt.Cavity00010.zip)

**Comment by neutrinoceros** [comment]
> My apologies, I should have checked I was running the latest version before posting.

nothing to apologise for, I was merely pointing out a change for reference !

It worked like a charm, I opened a PR with the fix (#2806). If this doesn't break any existing test it should be quickly available on master.
Feel free to tryout the attached branch to check it works for you too !

**Comment by neutrinoceros** [comment]
> My apologies, I should have checked I was running the latest version before posting.

Reading myself back I realise that my first message may have seemed somewhat passive-aggressive. So sorry about that, it was absolutely not the intended tone :-)

**Comment by darylbond** [comment]
All is well that ends well! I have tested your fix and it works beautifully. Many thanks for the fast turnaround from my posting the issue to having a PR raised, greatly appreciated.

**Comment by neutrinoceros** [comment]
You're welcome. Thanks for reporting and narrowing it down upstream !

**Comment by neutrinoceros** [comment]
Also note that a workaround on the user side that works with any version of yt that has the `AMReXDataset` class is to load directely with
```python
from yt.frontends.boxlib.data_structures import AMReXDataset
ds = AMReXDataset(output_dir, *args, **kwargs)
```

**Comment by neutrinoceros** [comment]
Quick question @darylbond , do you know if the file `inputs` is _always_ named as such for AMRex data ?

**Comment by zingale** [comment]
an inputs file can have any name.  It is passed via the command line.  Most of the time it will have the word `inputs` in it, but I'm sure there are exceptions.

**Comment by neutrinoceros** [comment]
> an inputs file can have any name. It is passed via the command line. Most of the time it will have the word inputs in it, but I'm sure there are exceptions.

Thank you so much for this, I wasn't aware (and it shows in how I redesigned the code). Fortunately, the current version shows a weakness with OrionDataset _and_ the original validator for this class has exactly the mechanism we need to introduce the required flexibility. I'll patch this in a few minutes

**Comment by neutrinoceros** [comment]
@darylbond 
Here's a quick follow up.

FYI , the _preferred_ way to import the AMReXDataset class should actually be this one
```python
from yt.frontends.boxlib.api import AMReXDataset
ds = AMReXDataset(output_dir, *args, **kwargs)
```
unfortunately the entries are currently missing in the api module (this is fixed in #2814), so it will work in the future but not with past versions.

Also, while digging into the original fix for this issue I realised there are actually many hidden issues with Boxlib dataset classes in general so I'll need to work a bit more on it before #2806 can be merged.
For that purpose, it would be helpful if we could use your dataset in tests. Would you allow we add it to yt's publicly available sample collection so we can use it to bullet proof the code base in the future ? Thanks !

**Comment by darylbond** [comment]
Thanks for the update.

I have cleaned out some custom entries in the dataset which may have introduced some confusion and reuploaded it here. You are very welcome to use it as a sample.

[plt.amrex.zip](https://github.com/yt-project/yt/files/5032483/plt.amrex.zip)

**Comment by neutrinoceros** [comment]
Thanks a lot for doing this ! I appreciate it :-)

**Comment by neutrinoceros** [comment]
Actually I'm seeing you removed the `inputs` file entirely. It is my understanding that such a file is in fact always to be expected in a BoxLib data directory, and I think it would be better to keep it attached: yt actively uses it to read the simulations parameters. Is it okay for you if I keep it included in the sample ?

**Comment by neutrinoceros** [comment]
I went ahead and uploaded the original full-dataset, but I'm happy to revert this if needed !

**Comment by zingale** [comment]
just catching up here.  There is not requirement that an inputs file is always expected in the BoxLib data directory.  In fact, I am not aware of any codes that do this.

Some codes have adopted some form of a job_info file that has a lot of information about the build environment, machine run, CPU time usage, git hashes, runtime parameter values, etc.

**Comment by neutrinoceros** [comment]
Okay so if I'm reading the original code right, this means that all BoxLibDatase subclasses have very brittle validators indeed.
#2837 makes this more apparent and easier to fix afterwards. @zingale could you review it ? :)
