### ISSUE TITLE
Refactor and rearrange code for clarity

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#2827]
This is a proposal; I've started a draft PR as well which I will edit this to reference.

We have a couple really big files in yt.  I'd like to propose that we begin to extract them into subfiles, to make it easier to modify them, and to identify where one begins and another ends.  The three files in question I would like to apply this to first are:

Filename | Lines
-|-
`yt/data_objects/data_containers.py` | 3024
`yt/data_objects/construction_data_containers.py` | 2845
`yt/data_objects/selection_data_containers.py` | 1332

Additionally, it seems that the `yt/visualization/` directory could use a rearrangement, which I will detail a bit further down.

Ideally, this would be a *strict* refactoring -- there would be *no* changes in functionality, and all tests should continue to pass.  Furthermore, because this would be largely in areas of the code that don't see much churn, it should avoid conflicts with existing PRs.

**Comment by neutrinoceros** [comment]
update:

Filename | Lines
-|-
`yt/data_objects/data_containers.py` | 1538 (-1486)
`yt/data_objects/construction_data_containers.py` | 2869 (+24)
`yt/data_objects/selection_data_containers.py` | 0 (file deleted)

I think this can be closed now that #2828 and #2829 were merged ?

**Comment by matthewturk** [comment]
I do think this can be, but I wonder if we should expand this to include things like the visualization tools.  I suppose that could be a different PR+Issue combo, though!
