### ISSUE TITLE
Volume rendering widget

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#284]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

A volume rendering widget in reason would be great.  Perhaps a direct, literal port of this one?

http://www.flickr.com/photos/matthewturk/4189749374/

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/284

**Comment by munkm** [comment]
@matthewturk do we want this to be a priority? I know you've been working on volume rendering in general. I think we could close this issue and come back to it another time.

**Comment by munkm** [comment]
I'm going to close for now but if somebody feels like resurrecting this issue feel free! 👻

**Comment by matthewturk** [comment]
I think it's okay to leave this closed, but it sure would be nice when we get one to reference "Issue #284".  ;-)
