### ISSUE TITLE
Too many status updates printed when processing fields in AMRVAC data

### ISSUE THREAD

**Issue by Kiradorn** [yt-project/yt#2859]
### Bug report

**Bug summary**

When processing AMRVAC data that lacks ghostfield information, currently yt prints many many instances of warnings that there are gaps in the data. Please may these status updates be modified to RuntimeWarnings instead?

**Code for reproduction**

File for reproduction has already been requested to be added to the online repository but here's the tarball: http://use.yt/upload/1cbbc47e

```python
overrides = dict(length_unit=(1e8, 'cm'), temperature_unit=(1e6, 'K'), numberdensity_unit=(1e8,'cm**-3'))
ds=yt.load('file.dat', units_override=overrides)
ds.periodicity = 3*[True]
p=yt.plot_2d(ds, 'vorticity_magnitude')
p.show()
```

**Actual outcome**

```
yt : [WARNING  ] 2020-08-14 09:33:26,380 Overriding code units: Use this option only if you know that the dataset doesn't define the units correctly or at all.
yt : [INFO     ] 2020-08-14 09:33:26,381 Overriding length_unit: 1e+08 cm.
yt : [INFO     ] 2020-08-14 09:33:26,382 Overriding temperature_unit: 1e+06 K.
yt : [INFO     ] 2020-08-14 09:33:26,384 Overriding numberdensity_unit: 1e+08 cm**-3.
yt : [INFO     ] 2020-08-14 09:33:26,442 Parameters: current_time              = 925.0
yt : [INFO     ] 2020-08-14 09:33:26,443 Parameters: domain_dimensions         = [528 528   1]
yt : [INFO     ] 2020-08-14 09:33:26,444 Parameters: domain_left_edge          = [-12.   0.   0.]
yt : [INFO     ] 2020-08-14 09:33:26,445 Parameters: domain_right_edge         = [12. 25.  1.]
yt : [INFO     ] 2020-08-14 09:33:26,446 Parameters: cosmological_simulation   = 0
yt : [INFO     ] 2020-08-14 09:33:27,311 Using full MHD energy for thermal pressure.
/Users/kiradorn/codes/yt/yt/frontends/amrvac/data_structures.py:67: RuntimeWarning: ghost-zones interpolation/smoothing is not currently supported for AMRVAC data.
  category=RuntimeWarning,
yt : [INFO     ] 2020-08-14 09:33:28,824 zeros found in density, patching them to compute corresponding velocity field.
yt : [INFO     ] 2020-08-14 09:33:28,848 zeros found in density, patching them to compute corresponding velocity field.
yt : [INFO     ] 2020-08-14 09:33:28,875 zeros found in density, patching them to compute corresponding velocity field.
yt : [INFO     ] 2020-08-14 09:33:28,900 zeros found in density, patching them to compute corresponding velocity field.
etc.etc.etc.etc
```
The final plot still appears after some time but the excessive warnings cause significant slow down.

**Expected outcome**

A single warning that there are holes in the density, due to no ghostcells, and that these will be filled.

**Version Information**
  * Operating System: mac OSx Mojave 10.14.6
  * Python Version: 3.7.6
  * yt version: 4.0
  * Other Libraries (if applicable): N/A

python was installed using conda
yt was installed using 'git clone [...]', cd , 'pip install -e .'

**Comment by neutrinoceros** [comment]
Thanks for the report !
I actually didn't recognize the message at first but it's specific to AMRVAC, so I'm adding the frontend label.
Also, this may be considered a bug. I never intended the message to clump you log, so indeed a runtime warning feels like the best approach.
