### ISSUE TITLE
Type annotation

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#2864]
This is meant to be a starting point for some discussion, although there have been previous discussions, too!  #2352 for instance.

Now that we are Python 3-only, we should explore adding type hints to the codebase.  I think the most straightforward way of doing this piecemeal would be to use the [`pytest-annotate`](https://blog.kensho.com/pytest-annotate-is-now-open-source-5dd6f6d51d0f) plugin for pytest, and then run it through [pyannotate](https://github.com/dropbox/pyannotate).  I've done an example of this [here](https://gist.github.com/matthewturk/7cd0cd153e987b038aef40cc9347cb46/).

There are a numbero f things that are maybe sub-optimal about it, though -- specifically, it results in a lot of absolute imports, and sometimes the import structure resolves differently than what we use in yt so it adds double-imports, etc.  (i.e., we might import `RandomState` from `np.random` but they might import from `np.random.mtrand`.)

What we might consider doing is hitting the most relevant areas of the code, specifically the user-facing APIs in the data containers, the developer-facing APIs in the frontend code, and then see how far that gets us.  It would also be a good opportunity to connect this with using [traitlets](https://github.com/yt-project/ytep/pull/8) since we'd have a blueprint for which types are what.

**Comment by neutrinoceros** [comment]
> What we might consider doing is hitting the most relevant areas of the code, specifically the user-facing APIs in the data containers, the developer-facing APIs in the frontend code

excellent plane, I support this !

**Comment by neutrinoceros** [comment]
Quick note that those two flake8-plugins may be useful in getting there
https://pypi.org/project/flake8-annotations/
https://github.com/asottile/flake8-typing-imports

**Comment by neutrinoceros** [comment]
and another one https://github.com/best-doctor/flake8-annotations-complexity

**Comment by neutrinoceros** [comment]
note that numpy exposes a `testing` module https://numpy.org/doc/stable/reference/typing.html#module-numpy.typing
It is however documented as requiring Python 3.8 so I guess we can start using it next year.

**Comment by neutrinoceros** [comment]
I think it's safe to close this now that #3546 went in
