### ISSUE TITLE
Remove Appveyor and appveyor.yml file

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#2921]
Following #2908, the Windows tests are not run on Appveyor anymore but on Travis instead. We should remove any reference of Appveyor in the Github configuration and in the git repository.

We have left a dummy configuration file so that Appveyor is happy and marks the builds as succeeded (even though **no test** are being run on Appveyor, see https://github.com/yt-project/yt/pull/2908/files#diff-180360612c6b8c4ed830919bbb4dd459R1).

This issue is just so that we don't forget to eventually remove the `appveyor.yml` file and deactivate the Appveyor testing in one go. This can happen once currently opened pull requests get merged, etc.

**Comment by neutrinoceros** [comment]
This was solved in ce5e21dfd2f914bbbe98283bb8dab2cd6f73bacf
