### ISSUE TITLE
Out of date dependencies

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#2925]
### Bug report

Some of our dependencies have released major versions that we don't test against. We should probably ensure that they are working before the yt 4.0 release.

To name a few
| package | pinned version   | current latest version |
| :-------- | :-------------- | :--------------------- |
| astropy | 3.2.3 | 4.0.1 |
| pytest | 5.2 | 6.1.0 |
| scipy | 1.3.2 | 1.5.2 |
| xarray | 0.12.3 | 0.16.1 |
| cartopy | 0.17.0 | 0.18.0 |
| pint | 0.8.1 | 0.16.1 |
| pandas | 0.25.3 | 1.1.2 |

Note: I suspect pint is only used to benchmark against unyt, in which case it's not necessary to install it to test yt anymore.

**Comment by Xarthisius** [comment]
FTR I also set up a test job that removes all pinning from `tests/test_*.txt`. It runs daily with master. 

https://tests.yt-project.org/job/yt_py38_latest_deps/

**Comment by neutrinoceros** [comment]
Oh nice, I wasn't aware !
This is mostly about "documenting" what works but it's good to know that we're already catching dependency related breakage.
