### ISSUE TITLE
Check if compiler supports required features before buiding yt

### ISSUE THREAD

**Issue by Xarthisius** [yt-project/yt#2933]
### Bug report

**Bug summary**

Trying to build yt with old C compiler (e.g. gcc-4.8.x), results in a cryptic error:

```
error: can't copy 'build/lib/yt/geometry/particle_oct_container.cpython-36m-x86_64-linux-gnu.so': doesn't exist or not a regular file
```

It would be nice if we checked if compiler used for build handles required standard

**Comment by neutrinoceros** [comment]
As a wild guess I think this _should_ be specified in `pyproject.toml` but I can't find any documentation on how to do this.
Now I'm curious to know why it's possible to have the minimal compatible version of Cython installed (as specified by pyproject.toml) but not the appropriate compiler.

**Comment by ax3l** [comment]
Partly related to #2933

**Comment by Xarthisius** [comment]
I believe this was fixed by https://github.com/yt-project/yt/pull/3072
