### ISSUE TITLE
Geographic projections raise AssertionError from GEOS

### ISSUE THREAD

**Issue by Xarthisius** [yt-project/yt#2941]
### Bug report

Trying to draw coastlines causes assertion error. 

**Code for reproduction**

```python
import numpy as np
import yt

#sizes = [72, 721, 1152]
sizes = [72, 181, 288]
dims = ["altitude", "latitude", "longitude"]
bbox = np.array([[1.0, 72.0], [-90, 90], [-180, 179.6875]])
data = dict(AIRDENS=yt.YTArray(np.ones(sizes), "kg * m**-3"))

ds = yt.load_uniform_grid(data, sizes, 1.0, geometry=("geographic", dims), bbox=bbox)
p = yt.SlicePlot(ds, "altitude", "AIRDENS")
p._setup_plots()
p.plots["AIRDENS"].axes.set_global()
p.plots["AIRDENS"].axes.coastlines()  # commenting this line out makes it work
p.save()
```

**Actual outcome**

```
python: LineString.cpp:121: const geos::geom::CoordinateSequence* geos::geom::LineString::getCoordinatesRO() const: Assertion `0 != points.get()' failed.
Aborted (core dumped)
```

**Expected outcome**

Nice png.

**Version Information**

  * Operating System: Ubuntu 18.04
  * Python Version: 3.8.5
  * yt version: `88597474c Merge pull request #2926 from neutrinoceros/bump_deps`
  * Other Libraries (if applicable):
     ```
     virtualenv -p /usr/bin/python3.8 venv
     . ./venv/bin/activate
     pip install -q -r tests/test_prerequirements.txt 
     pip install -q -r tests/test_requirements.txt 
     pip install -e .
     ```

**Comment by matthewturk** [comment]
Is it possible that there are no coastlines in the image?

**Comment by Xarthisius** [comment]
> Is it possible that there are no coastlines in the image?

If only I knew how the coastlines are created or where they're coming from, I'm sure I'd be able to answer that :) Point is: they were there 2 days ago, now they're gone.

**Comment by munkm** [comment]
Based on the bbox lat/lon it looks like this is a full earth image so I would imagine there are coastlines.

**Comment by Xarthisius** [comment]
```
pip uninstall shapely
pip install shapely --no-binary shapely
```
"Fixes" the issue...

**Comment by munkm** [comment]
Ah ok so the GEOS build with shapely was different than the one for cartopy (I suppose we could verify that if we wanted). What Kacper just wrote is a suggested fix in other cartopy issues.
