### ISSUE TITLE
RAMSES data at high redshift

### ISSUE THREAD

**Issue by cspotz** [yt-project/yt#2959]
Hello,
I have been user of YT for a year and experienced a little trouble to read my latest RAMSES simulation. I want to use RAMSES at very high redshift (start at z~1000 with no radiation) and use a different parametrization for scale factor ( a(t) prpto t). It implies that I am having very high values for z and t_frw leading YT to raise the following error.

Here is the code I wrote :
```python
import yt
ds = yt.load('output_00131/info_00131.txt')
```

And here is the error message :
```
IndexError                                Traceback (most recent call last)
<ipython-input-7-49e2114551c4> in <module>
----> 1 ds = yt.load('output_00131/info_00131.txt')

~/.local/lib/python3.6/site-packages/yt/convenience.py in load(*args, **kwargs)
     84     candidates = find_lowest_subclasses(candidates)
     85     if len(candidates) == 1:
---> 86         return candidates[0](*args, **kwargs)
     87     if len(candidates) == 0:
     88         if ytcfg.get("yt", "enzo_db") != '' \

~/.local/lib/python3.6/site-packages/yt/frontends/ramses/data_structures.py in __init__(self, filename, dataset_type, fields, storage_filename, units_override, unit_system, extra_particle_fields, cosmological, bbox)
    410 
    411         Dataset.__init__(self, filename, dataset_type, units_override=units_override,
--> 412                          unit_system=unit_system)
    413 
    414         # Add the particle types

~/.local/lib/python3.6/site-packages/yt/data_objects/static_output.py in __init__(self, filename, dataset_type, file_style, units_override, unit_system)
    247         self._create_unit_registry()
    248 
--> 249         self._parse_parameter_file()
    250         self.set_units()
    251         self._assign_unit_system(unit_system)

~/.local/lib/python3.6/site-packages/yt/frontends/ramses/data_structures.py in _parse_parameter_file(self)
    575             iage = np.min([iage,self.n_frw//2 + (iage - self.n_frw//2)//10])
    576 
--> 577             self.time_simu = self.t_frw[iage  ]*(age-self.tau_frw[iage-1])/(self.tau_frw[iage]-self.tau_frw[iage-1])+ \
    578                              self.t_frw[iage-1]*(age-self.tau_frw[iage  ])/(self.tau_frw[iage-1]-self.tau_frw[iage])
    579 

IndexError: index 2686 is out of bounds for axis 0 with size 1001
```

As I understood, I just need the place where the bounds for those parameters in YT is stored.
My dataset can be dowloaded here : https://filesender.renater.fr/?s=download&token=663f4954-6761-4313-b01f-222e5a026034

edit by @neutrinoceros : code formatting

**Comment by cphyc** [comment]
As a temporary workaround, can you confirm that loading with
```python
import yt
ds = yt.load('output_00131/info_00131.txt', cosmological=False)
```
does work?
It will prevent yt from trying to convert from RAMSES times to physical times (and should prevent the error you have). The problem is then that you don't have `ds.current_redshit` defined, and the times you get will likely be incorrectly converted.

**Comment by cphyc** [comment]
Note that this is indeed a bug, caused by yt's internal assumption that RAMSES times are given in "super-comoving" units (see https://ui.adsabs.harvard.edu/abs/1998MNRAS.297..467M/abstract).
You can bypass that by preventing its detection as a "cosmological" simulation.

**Comment by cspotz** [comment]
Yes, I worked and indeed in that case the redshift is not printed. Thanks a lot !

**Comment by cphyc** [comment]
Could you give a shot at #2960 and tell me whether it is indeed a solution to your issue? With this fix, you should be able to simply do
```python
import yt
ds = yt.load('output_00131/info_00131.txt')
```
It should detect it could not convert the times, and fall back to non-cosmological (and you should see a new warning!).

----

In order to test it (and assuming you installed yt through `git`).
```bash
# in the folder where you cloned yt
git remote add cphyc https://github.com/cphyc/yt.git
git fetch cphyc
git checkout bugfix/2959
python setup.py develop
```

**Comment by cspotz** [comment]
I've just installed it with git (previously I used pip). After doing so, it worked smooth and gave me:
```
yt : [WARNING  ] 2020-11-10 17:55:34,683 Yt could not convert conformal time to physical time. Yt will assume the simulation is *not* cosmological.
yt : [INFO     ] 2020-11-10 17:55:34,752 Parameters: current_time              = -735.562862149458
yt : [INFO     ] 2020-11-10 17:55:34,752 Parameters: domain_dimensions         = [256 256 256]
yt : [INFO     ] 2020-11-10 17:55:34,752 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2020-11-10 17:55:34,752 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2020-11-10 17:55:34,752 Parameters: cosmological_simulation   = 0
info_00131
```
