### ISSUE TITLE
amrex dataset detection appears broken

### ISSUE THREAD

**Issue by zingale** [yt-project/yt#3005]
### Bug report

**Bug summary**

If I try to load a Castro dataset, I get:

```
  File "/raid/zingale/development/yt-mz/yt/yt/loaders.py", line 98, in load
    raise YTAmbiguousDataType(fn, candidates)
yt.utilities.exceptions.YTAmbiguousDataType: Multiple data type candidates for det_strang_cfl0.5_dtnuce1e+200_nzones256/det_x_plt00210
The following independent classes were detected as valid :
<class 'yt.frontends.boxlib.data_structures.CastroDataset'>
<class 'yt.frontends.boxlib.data_structures.AMReXDataset'>
A possible workaround is to directly instantiate one of the above.
Please report this to https://github.com/yt-project/yt/issues/new
```

**Code for reproduction**

Using this dataset:
http://bender.astro.sunysb.edu/random/det_x_plt00000.tgz

Do
```
yt.load("det_x_plt00000")
```

A workaround is to use the hash `9071f0dc3` for yt.

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

should be able to load the dataset

**Version Information**

  * Operating System: Fedora 33
  * Python Version: 3.9.0
  * yt version: 4.0.dev0
  * Other Libraries (if applicable): 

installed yt from source

**Comment by neutrinoceros** [comment]
Hi @zingale, sorry about this, this must be an undesirable side effect of https://github.com/yt-project/yt/pull/2938
I worked a fair bit on simplifying the validators for Boxlib child classes, but it's still not very robust. In fact this is a predictable situation where both strings `"amrex"` and `"castro"` are present in the paramfile (`job_info`).
Could you explain why both are showing up and how should yt guess that it's indeed a Castro-typed dataset ?

**Comment by zingale** [comment]
yes, they will both always show up in all MAESTROeX, NyX, and Castro datasets.  The reason is that they are all different git repos, so we need to keep track of the individual hashes of each.

So Castro will always report the Castro, AMReX, and Microphysics hashes (the last doesn't matter to yt really)
MAESTROeX will always report the MAESTROeX, AMReX, and Microphysics
Nyx will always report the Nyx, AMReX hashes

probably true for WarpX too

**Comment by neutrinoceros** [comment]
I see. I don't know what we should do about it then because I don't know of a reliable way yt could guess the appropriate type.
In the mean time you can replace the call to `yt.load` with
```python
from yt.frontends.boxlib.api import CastroDataset
ds = CastroDataset(<data_file>)
```

**Comment by zingale** [comment]
A Castro `job_info` file always has:
```
 Castro Job Information
```
right at the top, so that unambiguously identifies it as a Castro dataset.

Likewise,  MAESTROeX `job_info` files always have:
```
 MAESTROeX Job Information
```
right at the top.

**Comment by neutrinoceros** [comment]
Nice ! Is this rule general to all boxlib types ?

**Comment by zingale** [comment]
sadly no.  Each application is allowed to do whatever they want in the job_info file (and maybe not have one at all).  There are probably dozens of AMReX codes, so I certainly don't know them all.

**Comment by neutrinoceros** [comment]
That's already valuable info. The problem here is that it's more a matter of making `AMRExDataset` invalid. Do you have any experience with this one ?

**Comment by Xarthisius** [comment]
Back in the day, when `load()` encountered a datasets that matched `A.is_valid()` and `B.is_valid()`, where `B` was a subclass of `A`, it automatically went with `B`. If that change that sounds like a regression.

**Comment by neutrinoceros** [comment]
actually @Xarthisius , I now think you had the right idea there. Maybe those classes _shouldn't_ be siblings after all: if one code is a direct descendent of another, maybe this hierarchy should be reflected by inheritance here ?

**Comment by matthewturk** [comment]
Reading this over, I am left to wonder if possibly a solution would be to provide the base-level amrex frontend, with optional "if detected" customizations.  Do we have a handle on how distinct each are, and how those distinctions manifest themselves?

**Comment by matthewturk** [comment]
I like some form of frontend/hint/etc.

**Comment by munkm** [comment]
`code` sounds like a good choice! I think we can be more explicit in our docs that frontend does not always mean the same thing as code too. It's easy to forget when some codes do have frontends named for them.
