### ISSUE TITLE
quickstart tutorials out of date?

### ISSUE THREAD

**Issue by gawells** [yt-project/yt#3048]
So far I'm unable to load demo data to run any of the quickstart tutorials. I installed version 3.6.1 in anaconda (manjaro linux, kernel 5.4.85), python 3.7.8.

E.g. `yt.load_sample` doesn't seem to be a valid method, and `yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")` gives the following error:

```
yt : [ERROR    ] 2021-01-29 01:20:43,682 None of the arguments provided to load() is a valid file
yt : [ERROR    ] 2021-01-29 01:20:43,683 Please check that you have used a correct path
```
and `ds = yt.load("enzo_tiny_cosmology", "DD0046/DD0046")` gives

```
yt : [ERROR    ] 2021-01-29 01:14:00,939 Couldn't figure out output type for enzo_tiny_cosmology
```

**Comment by matthewturk** [comment]
Hi @gawells -- at present, you have to download the data files before that will work.  We're changing this in a future version, so that you can just use `load_sample` but with 3.6.1 that won't do it.

You can find them here: https://yt-project.org/data/

Can you download those, untar them, and see if that fixes your issue?

**Comment by gawells** [comment]
Hi
 
Part of the problem was that one the datasets hadn't finished downloading, only noticed now. But I had to replace needs to replace `yt.load("IsolatedGalaxy","galaxy0030/galaxy0030")` with `yt.load("IsolatedGalaxy/galaxy0030/galaxy0030")` etc in some of the notebooks.

**Comment by neutrinoceros** [comment]
>  But I had to replace yt.load("IsolatedGalaxy","galaxy0030/galaxy0030") with yt.load("IsolatedGalaxy/galaxy0030/galaxy0030") etc in some of the notebooks.

for reference, I just tried greping for this in the code base and couldn't find any occurence (even adjusting for the fact that we now use black on our docs). I'm going assume that those have been fixed already in the dev version of the docs.

**Comment by neutrinoceros** [comment]
It seems to me that the initial question was answered and that there's isn't anything to be done now. Feel free to reopen if need be.
