### ISSUE TITLE
Integrate parallelism with ParaView

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#305]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

ParaView integration (the "Stream" frontend) should include processor specification for grid objects.  (@gzagaris will be able to provide insight into how this can be implemented.)

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/305

**Comment by ngoldbaum** [comment]
Paraview integration is long lost, closing due to irrelevance with current codebase.
