### ISSUE TITLE
Logging should be more flexible and output to different backends

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#306]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

ParaView, for instance, has its own logging.  We should make an additional handler for outputting to ParaView's logging system.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/306

**Comment by ngoldbaum** [comment]
Closing due to lack of example. I also think we mostly fixed this when we overhauled how we set up our logger a while back.
