### ISSUE TITLE
Randomly failing answer test

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3069]
### Bug report

**Bug summary**

Since the release of numpy 1.20.0 (and still with 1.20.1), one of our answer test is randomly failing in all PRs.

The name of the test is
`VRImageComparison_UniformGridData_vr_pitch_plane-parallel_0002`

it is generated from
`yt/visualization/volume_rendering/tests/test_vr_orientation.py`

The quick and dirty remedy is to deactivate this test (this is #3068), though it should be inspected in more details in the future so I'm opening this issue to keep track of it.

**Comment by jzuhone** [comment]
I assume we still need to get this fixed before 4.0?

**Comment by munkm** [comment]
Yes we should.

**Comment by matthewturk** [comment]
This is in VR, so ... is it possible that this is related to `OMP`?  Are we hitting a condition where we're no longer copying an array that we should, or something?

**Comment by matthewturk** [comment]
@Xarthisius any chance you have the artifacts handy?

**Comment by matthewturk** [comment]
The difference in the success for `perspective` vs `plane-parallel` suggest to me that the difference may arise from something in `generate_vector_info_plane_parallel`, `calculate_extent_perspective` or `calculate_extent_plane_parallel`.  One distinct possibility is that a change in numpy 1.20.0 had impacts on these operations.

**Comment by Xarthisius** [comment]
> @Xarthisius any chance you have the artifacts handy?

They're in `answer-store/`

**Comment by matthewturk** [comment]
@Xarthisius those are the reference answers, but not the randomly failed one.  I'll try to replicate here.

**Comment by brittonsmith** [comment]
It seems doubtful that we'll ever have the time to fix this. I would recommend that the test tolerances be loosened so that they will pass.
