### ISSUE TITLE
YtConfig __getitem__ is slightly broken

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3155]
### Bug report

If one attempts to display the main (and currently only) section of the configuration from an interactive session it should be doable like this
```python
from yt.config import ytcfg
print(ytcfg["yt"])
```
Though currently this fails with

```
KeyError: 'Cannot get key y'
```
Because the underlying code was only ever tested with double keys, the string`"yt"` is treated as an iterable.
It's probably an easy fix but I'd rather just report it for now.
ping @cphyc in case you're interested in looking this up

**Comment by neutrinoceros** [comment]
note: the reason I discovered this is that I was trying to write existence checks for deprecated parameters in #3106 as

```python
if "colored_logs" in ytcfg["yt"]:
     self["logging", "use_color"] =  ytcfg["yt", "colored_logs"]
```

which would be immensely superior to their current implementation
```
try:
    self["logging", "use_color"] = self.get("yt", "colored_logs")
except KeyError:
    pass
```
especially as the list grows

**Comment by cphyc** [comment]
Argh, that's indeed quite ugly!
