### ISSUE TITLE
supporting MPL 3.4 and beyond: ax labelling is currently broken

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3174]
### Bug report

**Bug summary**

I started exploring our CI failures with matplotlib 3.4 in #3153
I report that the following code reproduced the error seen in many (all ?) answer tests

**Code for reproduction**

```python
import matplotlib
import yt

ds = yt.testing.fake_amr_ds()
p = yt.SlicePlot(ds, "z", "Density")
p.save(f"/tmp/benchmark_mpl{matplotlib.__version__}_")
```

**Actual outcome**

This is the result with matplotlib 3.3
![benchmark_mpl3 3_Slice_z_Density](https://user-images.githubusercontent.com/14075922/114056533-0fa43900-9892-11eb-9106-58e6f2c63ccc.png)

and here is the one with matplotlib 3.4
![benchmark_mpl3 4_Slice_z_Density](https://user-images.githubusercontent.com/14075922/114056572-19c63780-9892-11eb-9637-c36771d7ee35.png)

It's likely a bug upstream, I'll need to inspect this further to try and produce a minimal example without yt.

**Comment by Xarthisius** [comment]
They simply changed default math font from cm (computer modern) to dejavu

**Comment by neutrinoceros** [comment]
Oh ! I completely failed to consider that it was font change and not a labelling change, thanks a lot !
I also didn't know we used a matplotlibrc file for tests, that's nice.
This means fixing our CI is trivial (hurray), let's hope nothing _else_ breaks.

**Comment by neutrinoceros** [comment]
It worked, but some differences remain. I don't think there's anything left to do but update answers on our side. Closing this.
