### ISSUE TITLE
Memory and CPU usage with small Gadget data sets

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#3192]
After the change in #2575, we run into some real problems with some smaller datasets, where essentially the entire dataset gets expanded up to the maximum bitmap level.  This is problematic for datasets like `Gadget3-snap-format2`, which have multiple data files, very few particles, but big smoothing lengths that cover many low-order cells.

Default behavior for this script:

```python
import yt

with yt.memory_checker():
    ds = yt.load_sample("Gadget3-snap-format2")
    ds.index
```

produces a ridiculous amount of memory usage and takes a hubble time.

This can be essentially completely remedied by setting the `index_order` to have a *lower* order for the second component.  I'm tempted to consider a heuristic setting of the index order to be the appropriate fix.

**Comment by matthewturk** [comment]
@chummels you mentioned seeing something similar a while back with a different dataset; see if setting `index_order = (2, 4)` or something in the `load` call fixes it?

**Comment by matthewturk** [comment]
One possibility I'm exploring is to adjust the default `order2` to make sure it doesn't result in some cell size that's smaller than a reasonable fraction of the mean/median/min smoothing length.

**Comment by chummels** [comment]
I'll try this out on that super-low-res AREPO dataset that was taking forever to load.
