### ISSUE TITLE
Future note: we should consider updating the cut_region docs and notes to make these tuples.

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#3201]
Future note: we should consider updating the cut_region docs and notes to make these tuples.

_Originally posted by @munkm in https://github.com/yt-project/yt/pull/3101#discussion_r614254587_

**Comment by brittonsmith** [comment]
I want to add to this that the cut_region helper functions like `include_above` don't work with tuple field names. It should be an easy fix. I kept forgetting to make an issue for it.

**Comment by munkm** [comment]
Oooh yes we should fix this. Thank you for commenting it here britton.

**Comment by cphyc** [comment]
> I want to add to this that the cut_region helper functions like `include_above` don't work with tuple field names. It should be an easy fix. I kept forgetting to make an issue for it.

I have a good news for you, it has been fixed by #3101!
![image](https://user-images.githubusercontent.com/5411875/115035102-7e097c80-9ecc-11eb-963d-53d203d15366.png)
