### ISSUE TITLE
document alternate visualization methods for particle data

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt#3230]
### Bug report

In lieu of fixing Issue #2205 for the yt-4.0 release, we should add some documentation discussing other ways to visualize particle data, specifically depositing onto covering/arbitrary grids.

**Comment by matthewturk** [comment]
Since #3305 got merged, can we close this, or does it need more?

**Comment by brittonsmith** [comment]
That PR was meant to do it and I have nothing more I can think of to say!
