### ISSUE TITLE
Filling out the yt4differences docs page

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#3231]
**Summary**

Right now the [yt4 differences doc page](https://yt-project.org/docs/dev/yt4differences.html) is pretty good, but I think it needs to be fleshed out to really hold the hands of users as they make the transition from yt3 to yt4.  There's nothing so frustrating as to move to a new version of a code, find all of your scripts break, and not know how to fix them.

I've already described this in a comment on Issue #3125 , but it seemed worth having this in a standalone trackable issue.

**Details**

In particular, the [yt4 differences page](https://yt-project.org/docs/dev/yt4differences.html) needs 

- a high level description of the changes between yt3 and yt4, including major changes under the hood as well as API changes.

- Documentation on how to convert old scripts to work with yt4.  Maybe we should describe a bullet point list as a sort of algorithm that a user can follow to convert their old scripts, like what was done in the [yt3 differences page](https://yt-project.org/docs/dev/yt3differences.html). So something like: "Search your scripts and replace any field name strings as field name tuples" with an example.

In particular, it might be worthwhile to sit down with a friend or colleague who is used to working with the stable version of yt, and take them through the process of the upgrade. Then have them use their scripts, and see what fails. On the things that fail, were the error messages obvious as to what needed to change and how to change it? Did we miss it in our description of "what changed" in yt4 and do we need to include something else in our list of items that users need to account for in converting yt3 scripts to yt4?

Anyway, these are all just ideas from someone who remembers how frustrating it can be to upgrade to a new version and have all of your old scripts break. We cannot make it automated, but we can help a lot in easing this process for the user.

**Comment by chummels** [comment]
I've assigned this to myself, but I also encourage other people to help with this.  I think it would be extremely beneficial for those of us more familiar with yt4 to take a colleague who uses yt3 and take them through the process of upgrading, then trying to run some of their old scripts.  Use that experience to add items to the "how to upgrade your scripts from yt3 to yt4".

**Comment by matthewturk** [comment]
@chummels Thanks for doing so much on this.  I see the todo list on #3281 and it looks quite comprehensive!
