### ISSUE TITLE
"deprecated" functions without a body

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3239]
See
- https://github.com/yt-project/yt/blob/c196d8d838ef57425f72be97fa974da8525bc49e/yt/fields/particle_fields.py#L797#L821
- https://github.com/yt-project/yt/blob/16cf684ca50a3ad034e8721b184a7609dd192772/yt/data_objects/static_output.py#L1675#L1717

Keeping these around after removing their body of the function doesn't make much sense. I think they should either be removed completely or restored to a usable form for one more minor release.

_Originally posted by @neutrinoceros in https://github.com/yt-project/yt/pull/3021#r573735042_

**Comment by matthewturk** [comment]
I think these are now no-ops -- we can remove them in a future version, maybe in 4.1?

**Comment by neutrinoceros** [comment]
I think it's safe to close it then, thanks !
