### ISSUE TITLE
Update installation documentation

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3244]
### Bug report

**Bug summary**

`doc/source/installing.rst` is due for an update regarding the different dev branches (it says that `stable` == `yt-3.x`).
Maybe we want to create an actually `yt-3.x` branch from `stable` and state that `stable` is the release branch (so it works with any past and future major version).
It should also mention yt4differences, as it does yt3differences

**Comment by matthewturk** [comment]
Good idea!

**Comment by neutrinoceros** [comment]
@matthewturk I'm happy to do this myself for the record :)
I'll be dealing with it once the setup.cfg PR is merged

**Comment by matthewturk** [comment]
I'd love that, thank you.

**Comment by neutrinoceros** [comment]
Quick question: anybody knows whether the install_script is still relevant (https://github.com/yt-project/yt/blame/main/doc/install_script.sh) ?
I'm guessing it's probably not used and likely broken since the last relevant edits were done 5yrs ago

**Comment by brittonsmith** [comment]
@neutrinoceros, some time ago there was consensus about removing the install script. I had planned to do it, but hadn't gotten round to it. I think I may have lost steam when I realized that this would require the update to the installation docs that you are now doing. If you're game for it, I'd say go ahead and remove the install script.

**Comment by neutrinoceros** [comment]
Note that I'd probably need a hand with the conda side of things. I think I'll focus on docs and maybe remove references to the install script, but let the script itself around for a minor release or two. I'll propose to formally deprecate it when and if I get to the point I'm sure it can be removed without annoying anyone.
