### ISSUE TITLE
Failing answer tests

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3256]
### Bug report

**Bug summary**

Currently 2 answer tests are failing on the main branch (since mpl 3.4.2 was released last week).
Here are their names:
`GenericImage_UniformGridData_all_line_answers_multi_line_plot_None_None`
`GenericImage_UniformGridData_all_line_answers_line_plot_None_None`

I don't understand where they are being generated so it's pretty much impossible for me to start fixing them atm.

The bug is that axis ticks are inverted somehow (possibly a bug upstream ?)

<img width="1715" alt="Screenshot 2021-05-12 at 21 38 58" src="https://user-images.githubusercontent.com/14075922/118034616-796ca280-b36a-11eb-92bf-ea8ae547db1d.png">

**Comment by cphyc** [comment]
That's interesting. It looks like the actual behaviour is matplotlib's default one (i.e. ticks to the outside) while the expected one is a bit bizarre (ticks in the inside on the lhs and to the outside on the rhs).

**Comment by neutrinoceros** [comment]
Reported upstream as #20219

**Comment by jzuhone** [comment]
@neutrinoceros what should we do as a work-around in the meantime?

**Comment by neutrinoceros** [comment]
right now we can simply skip this version. This is what I'm doing in #3257
It seems that there's a debate going on in matplotlib so it might become the de facto canonical behaviour, but I suggest we wait on their decision to act on it.
