### ISSUE TITLE
Feature request: suggestions for typos in load_sample

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3266]
### Feature

I think it would be really useful to use the same suggestion mechanism as in https://github.com/yt-project/yt/pull/3184 for load_sample.
Related to #3263
The implementation will be pretty trivial to perform once #3184 is merged

**Comment by chummels** [comment]
Yeah, this would be super awesome!

**Comment by neutrinoceros** [comment]
So I want to wait for #3336 to go in, because the fix will otherwise create unnecessary conflicts as it will very likely affect the same lines.
