### ISSUE TITLE
Make sure deprecation warnings are displayed for removed load params

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3292]
In this commit

https://github.com/yt-project/yt/commit/00fb76aa161f1b621dfcbe00e3ee58ef7b89be28
@chummels added a note on two removed load parameters that I believe did not receive a proper deprecation cycle. I want to make sure they can still be passed (albeit a no-op) in Yt 4.0

**Comment by chummels** [comment]
Just to be clear--I didn't remove those parameters.  The new way in which yt deals with particles obviates the need for them.  I only removed the out-of-date documentation on them.  But you're right that it might be worth deprecating their use so it doesn't cause old scripts to fail.

**Comment by neutrinoceros** [comment]
Actually I started looking into this and it looks like the parameters are still exactly as exposed as in yt3.6.1
I assume they have no impact.
Do you think if we could simply mark them as deprecated in the load function itself (rather than in specialized Dataset subclasses where they are actually implemented)?

**Comment by chummels** [comment]
That seems reasonable to me.

**Comment by neutrinoceros** [comment]
discussion summary from yesterday's triage with @chummels and @cphyc (started typing this during the meeting but forgot to publish):
- nothing to deprecate in the ART frontend (n_ref and over_refine_factor are not exposed)
- RAMSES probably don't use it, it's just passed around, so it could be cleaned up but it's very likely that nobody uses it so we probably don't need to deprecate here either.

**Comment by neutrinoceros** [comment]
I'm not so sure there's anything left to be done here anymore, so I'll close. @chummels , @cphyc, feel free to reopen this if you judge otherwise.
