### ISSUE TITLE
Enzo_64 dataset not loadable by load_sample()

### ISSUE THREAD

**Issue by chummels** [yt-project/yt#3296]
### Bug report

As I was updating the quickstart notebooks, I came upon a failure for `load_sample()` being unable to load the `Enzo_64` dataset.  See [here](https://yt-project.org/docs/dev/quickstart/simple_visualization.html).  When I attempt this command locally, yt automatically downloads and untars the dataset, but it seems like it's trying to look at a filename called `None`.  No problems in loading the dataset manually with `load()`.

**Code for reproduction**

```python
ds = yt.load_sample("Enzo_64", "DD0043/data0043")
s = yt.SlicePlot(ds, "z", ["density", "velocity_magnitude"], center="max")
s.set_cmap("velocity_magnitude", "kamae")
s.zoom(10.0)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-12-7024538d34af> in <module>
----> 1 ds = yt.load_sample("Enzo_64", "DD0043/data0043")
      2 s = yt.SlicePlot(ds, "z", ["density", "velocity_magnitude"], center="max")
      3 s.set_cmap("velocity_magnitude", "kamae")
      4 s.zoom(10.0)

/var/jenkins_home/workspace/yt_docs/yt/loaders.py in load_sample(fn, progressbar, timeout, **kwargs)
   1363         if timeout is not None:
   1364             mylog.info("Ignoring the `timeout` keyword argument received.")
-> 1365         return load(loadable_path, **kwargs)
   1366 
   1367     try:

/var/jenkins_home/workspace/yt_docs/yt/loaders.py in load(fn, *args, **kwargs)
     78     # either in the current dir or yt.config.ytcfg['data_dir_directory']
     79     if not fn.startswith("http"):
---> 80         fn = str(lookup_on_disk_data(fn))
     81 
     82     candidates = []

/var/jenkins_home/workspace/yt_docs/yt/sample_data/api.py in lookup_on_disk_data(fn)
    162     if not alt_path.exists():
    163         err_msg += f"\n(Also tried '{alt_path}')."
--> 164         raise FileNotFoundError(err_msg)
    165 
    166     return alt_path

FileNotFoundError: No such file or directory: '/mnt/yt/Enzo_64/None'.
(Also tried '/mnt/yt/Enzo_64/None').
```

**Comment by neutrinoceros** [comment]
This is possibly fixed in #3262 (to be confirmés)

**Comment by neutrinoceros** [comment]
Nevermind the actual issue is that the load_name for this dataset it declared as the string `"None"`.

**Comment by neutrinoceros** [comment]
Ok I appended a commit to #3262, which now includes a fix for this !

**Comment by neutrinoceros** [comment]
this is the new commit https://github.com/yt-project/yt/pull/3262/commits/1ad872aac2ce024a68c072095ae9bcb23d507852

Note that I also clean up the call for `"enzo_tiny_cosmology"` which included an unused second argument.
In fact the original implementation of yt.load_sample had a second_positional argument `specific_file`, which isn't part of the current implementation (because the same data can be passed as part of the first arguement).

**Comment by chummels** [comment]
Awesome!  Thanks for looking into this!
