### ISSUE TITLE
docs from Jupyter notebooks not being updated

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt#3304]
It looks like docs rendered from Jupyter notebooks using the `notebook` are not being built. For an example, see
https://yt-project.org/docs/dev/examining/generic_particle_data.html

Even what is displayed there is significantly out of date compared to the current state of the docs source.

**Expected outcome**

That they be rendered.

**Version Information**

  * Operating System:
  * Python Version:
  * yt version:
  * Other Libraries (if applicable):

**Comment by chummels** [comment]
Isn't the problem just that it's loading with the `n_ref` kwarg and subsequently everything is failing?

**Comment by brittonsmith** [comment]
That was removed from that notebook a long time ago. The current version is not being built.

**Comment by chummels** [comment]
That's weird.  When I look at the source in the dev tip, it still shows exactly what is being rendered in the docs, including the `n_ref` kwarg.  But perhaps I'm misunderstanding you.

**Comment by brittonsmith** [comment]
Huh, you are right. I don't know how I managed to convince myself otherwise. I will close this. Thanks for double-checking this.

**Comment by neutrinoceros** [comment]
> Huh, you are right. I don't know how I managed to convince myself otherwise.

@brittonsmith , possibly you were just reading the stable version of the docs, instead of the dev one ?

**Comment by brittonsmith** [comment]
Honestly, I have no idea what was happening with me. I was looking at the dev docs and the main branch of the repo. I **thought** I was looking at the correct notebooks and not finding a match between the source and what was being rendered. I need to run a level 2 diagnostic on myself.
