### ISSUE TITLE
Custom RAMSES gravity files

### ISSUE THREAD

**Issue by cspotz** [yt-project/yt#3314]
I have customize some RAMSES simulations and now I have extra gravity fields inside my file grav.out.
Trying to read them with YT causes a bug because, the file size is expected to be smaller.
```
ad['acceleration_x']
ValueError: Size obtained (8) does not match with the expected size (4) of record
```
Could you point out to me where/how to customize YT so that I can handle the new fields ?

**Comment by cphyc** [comment]
Hi,

The issue you are seeing seems to be due to some quantity in your 
`grav_XXXXX.outYYYYY being written in double-precision or 64 bit integer 
where yt expect them in single precision or 32 bit integer.

Could you provide additional information regarding how you customized 
the gravity files, and in particular whether the headers differ from the 
main version? Also, in what precision (single or double) are the fields 
written in the gravity files?

In principle, if we (yt) have done a good job and your gravity files are 
regular gravity files with extra fields written in double precision, it 
is expected it should work out of the box. If your case doesn't fall in 
these categories, there are many solutions depending on how exactly the 
gravity files are written! If it falls in these categories, the bug is 
probably on yt side.

Best,
Corentin

**Comment by cspotz** [comment]
Hello,
I wrote in in single precision however all the gravity quantity were duplicated. Here is the relevant pat of the RAMSES routine output_poisson.f90 that I customized to produce my files  `grav_XXXXX.outYYYYY
```
do ind=1,twotondim
              iskip=ncoarse+(ind-1)*ngridmax
              ! Write potential
              do i=1,ncache
                 xdp(i)=phi(ind_grid(i)+iskip)
                xdp2(i)=phi2(ind_grid(i)+iskip) !second phi
              end do
              write(ilun)xdp
              write(ilun)xdp2
              ! Write force
              do ivar=1,ndim
                 do i=1,ncache
                    xdp(i)=f(ind_grid(i)+iskip,ivar)
                 end do
                 write(ilun)xdp
              end do
              ! Write second force (after all the ndim component of the first force)
              do ivar=1,ndim
                 do i=1,ncache
                    xdp2(i)=f2(ind_grid(i)+iskip,ivar)
                 end do
                 write(ilun)xdp2
              end do
           end do
```
I did not touch neither the header of my gravity files nor the precision.

**Comment by cphyc** [comment]
Hi! Most of the work to support your use case was already in the code base, but it was missing one last push!
I have created a pull request to add support for your use case in #3332.
To test it:
1. Checkout my branch
```bash
# Assuming you already installed yt from source (see https://yt-project.org/docs/dev/installing.html#installing-yt-from-source)
# to be run in the folder containing `yt`
git remote add cphyc https://github.com/cphyc/yt.git
git fetch cphyc

# Now checkout the branch
git checkout fix/issue-3314
python -m pip install -e . -v  # install yt
```
2. Customize the list of fields to be read in your gravity files by adding the following in `~/.config/yt/yt.toml`
```toml
[ramses-grav]
fields = ["Potential", "A_NAME_FOR_PHI2", "x-acceleration", "y-acceleration", "z-acceleration"]
```

**Comment by cspotz** [comment]
Hey,
I could get your branch and install it.
I defined my yt.toml in this way
```
[ramses-grav]
fields = ["Potential", "PHIm", "x-acceleration", "y-acceleration", "z-acceleration", "x-macceleration", "y-macceleration", "z-macceleration"]
```
and after running YT I could access the newly created files eg.
```
print(dir(ds.fields.gravity))
```
gives me 
```
['PHIm', 'Potential', 'cell_volume', 'dx', 'dy', 'dz', 'path_element_x', 'path_element_y', 'path_element_z', 'vertex_x', 'vertex_y', 'vertex_z', 'volume', 'x', 'x-acceleration', 'x-macceleration', 'y', 'y-acceleration', 'y-macceleration', 'z', 'z-acceleration', 'z-macceleration']
```
So I am happy.
However if I try to access a field, I still get the same error, namely running
```
ad = ds.all_data()
ad[('gravity','PHIm')]
```
gives me again
```
ValueError: Size obtained (8) does not match with the expected size (4) of record

```
May I point out that if I run vanilla RAMSES (without my patch which adds a second potential), I am able to access the gravity files (without  vanilla yt.toml obviously).
``ad[('gravity','Potential')]
unyt_array([0., 0., 0., ..., 0., 0., 0.], 'code_velocity**2')
``

**Comment by cphyc** [comment]
Could you confirm that `xdp` and `xdp2` are both `real(dp)`?

**Comment by cspotz** [comment]
Yes, here it is 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stahl/PostDocParis/Simulations/yt-git/yt/yt/data_objects/data_containers.py", line 258, in __getitem__
    self.get_data(f)
  File "/home/stahl/PostDocParis/Simulations/yt-git/yt/yt/data_objects/selection_objects/data_selection_objects.py", line 196, in get_data
    fluids, self, self._current_chunk
  File "/home/stahl/PostDocParis/Simulations/yt-git/yt/yt/geometry/geometry_handler.py", line 226, in _read_fluid_fields
    self._chunk_io(dobj), selector, fields_to_read, chunk_size
  File "/home/stahl/PostDocParis/Simulations/yt-git/yt/yt/frontends/ramses/io.py", line 115, in _read_fluid_selection
    rv = subset.fill(fd, field_subs, selector, file_handler)
  File "/home/stahl/PostDocParis/Simulations/yt-git/yt/yt/frontends/ramses/data_structures.py", line 437, in fill
    return self._fill_no_ghostzones(fd, fields, selector, file_handler)
  File "/home/stahl/PostDocParis/Simulations/yt-git/yt/yt/frontends/ramses/data_structures.py", line 343, in _fill_no_ghostzones
    oct_handler,
  File "yt/frontends/ramses/io_utils.pyx", line 188, in yt.frontends.ramses.io_utils.fill_hydro
  File "yt/utilities/cython_fortran_utils.pyx", line 133, in yt.utilities.cython_fortran_utils.FortranFile.read_vector
ValueError: Size obtained (4) does not match with the expected size (8) of multi-item record
```
 Here is the definition of `xdp` and `xdp2`  :
```fortran
real(dp),allocatable,dimension(:)::xdp,xdp2
```

**Comment by cphyc** [comment]
Hi @cspotz , could you upload one of the `grav_xxxxx.outyyyyy` files so that I can inspect it?

**Comment by cspotz** [comment]
Here it is,
[grav_00209.zip](https://github.com/yt-project/yt/files/6606867/grav_00209.zip)

**Comment by cphyc** [comment]
Cheers! I've looked into it and it has the structure I was expecting, so I believe it should work. Since it does not, I probably introduced a bug somewhere!

How large is the entire dataset? If it is small enough (< a few GiB), could you share it? It may be more efficient to load e.g. the first output instead of the 209th.
Note that you can upload datasets with `yt upload name_of_zip_file.zip`.

**Comment by cspotz** [comment]
I have uploaded it there : http://use.yt/upload/f91a2145, it is 1.9 Gb.

**Comment by cphyc** [comment]
Hi! I _think_ I fixed the issue. Could you have a go with the latest version (commit f2f8fdd7facc226defc2e988b84b0b3da87403eb)?

**Comment by cspotz** [comment]
It seems functional now. Thanks a lot.
I also tried with another type of modified gravity files by changing the yt.toml accordingly and could load again the gravity sector of RAMSES, so the changes we discussed seems applicable to a variety of grav files..
As a side remark, YT considers that the new tables loaded are "dimensionless", so for completeness, it could be nice to have the units editable as well (maybe in yt.toml ?). But to get some science done your current commit is awesome already.

**Comment by cphyc** [comment]
@cspotz yes indeed, yt can only infer the units of fields it knows for now, but your suggestion would be a really good improvement in yt. It would however require much more work than what's already in #3332, so I'd argue merging #3332 first and create a way of providing custom units later one.

In the meantime, you can create a derived field to convert the unitless fields into unitful ones using https://yt-project.org/doc/developing/creating_derived_fields.html. Note that you have access to RAMSES' `unit_l, unit_m, unit_t` in `ds.parameters`.
