### ISSUE TITLE
FITS.ds9_region requires pyregion

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#3320]
### Bug report

**Bug summary**

The function `yt.frontends.fits.misc:ds9_region` requires the package pyregion to be installed and fails with a `ModuleNotFoundError` when the function is called. This should make use of the on-demand import mechanism.

**Comment by neutrinoceros** [comment]
We migrated away from pyregion in https://github.com/yt-project/yt/pull/4235, but this issue is still relevant and and easy fix, let's clear it out.
