### ISSUE TITLE
Installing unpinned dependencies with setup.cfg

### ISSUE THREAD

**Issue by Xarthisius** [yt-project/yt#3392]
### Bug report

**Bug summary**

We have a [job](https://tests.yt-project.org/job/yt_py38_latest_deps/) on Jenkins that used to test yt with the latest version of all dependencies. It's currently failing cause it's based on a very dumb way of getting dependencies via `sed`:

```
sed -e '/^[[:alnum:]]/ s/\([0-9A-Za-z\-]*\)\(.*\)/\1/g' \
  -i tests/test_prerequirements.txt \
  -i tests/test_requirements.txt
```

Unfortunately, we removed `*requirements.txt` and rely on `setup.cfg` to install dependencies. We need to come up with a new way of unpinning packages on-the-fly. I'm filing this issue to solicit help. I'll accept even a dumb solution a.k.a. different `sed` spell...

**Comment by neutrinoceros** [comment]
Sorry about the disruption. Before I start working on this, is it okay to edit setup.cfg on the fly ?

**Comment by Xarthisius** [comment]
> Sorry about the disruption. Before I start working on this, is it okay to edit setup.cfg on the fly ?

Anything works. Yes, preferably it doesn't even have to be committed to yt-project/yt.

**Comment by neutrinoceros** [comment]
Here's a semi-maintainable solution as a Python script
```python
#!/usr/bin/env python
# unpin_requirements.py

from collections.abc import MutableMapping
import configparser
import io

def unpin(s:str) -> str:
    s0, _, _upper_lim = s.partition("<")
    return s0.strip(",")

def unpin_mapping(m:MutableMapping, key) -> None:
    reqs = m[key].split("\n")
    m[key] = "\n".join(unpin(_) for _ in reqs)

if __name__ == "__main__":
    cp = configparser.ConfigParser()
    cp.read("setup.cfg")
    unpin_mapping(cp["options"], "install_requires")
    for target in cp["options.extras_require"].keys():
        unpin_mapping(cp["options.extras_require"], target)

    output = io.StringIO()
    cp.write(output)
    s = output.getvalue().replace("\t", " "*4)
    s = "\n".join(_.rstrip() for _ in s.split("\n"))
    with open("setup.cfg", "w") as fh:
        fh.write(s)
```

the formatting part is of course not necessary, but I wrote it to minimise the resulting diff
```patch
diff --git a/setup.cfg b/setup.cfg
index ad593265d..c8124e8ff 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -38,7 +38,7 @@ project_urls =
 packages = find:
 install_requires =
     iPython>=1.0
-    matplotlib!=3.4.2,>=2.0.2,<3.5
+    matplotlib!=3.4.2,>=2.0.2
     more-itertools>=8.4
     numpy>=1.13.3
     pyyaml>=4.2b1
@@ -128,3 +128,4 @@ ignore = E203, # Whitespace before ':' (black compatibility)
     W503, # Line break occurred before a binary operator (black compatibility)
 enable-extensions = G  # flake8-logging-format (extension is disabled by default)
 jobs = 8
+
```

known limitation: this won't work in case the upper limit for a package isn't the last spec in the line.

**Comment by Xarthisius** [comment]
Thank you! I made some modifications (file is available here: http://use.yt/upload/4ac32ad5) and tests are back up online.
