### ISSUE TITLE
BUG: firefly-dependent code is currently broken

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3415]
### Bug report

**Bug summary**

In #3362 I dropped firefly from our optional deps following its removal from GitHub + PyPI
However the parts of yt that depend on it are still here and weren't updated to work with the replacement.

I don't think that fixing this is urgent, but I'm noting it down as a reminder that it should be addressed for yt 4.1

ping @agurvich :)

**Comment by agurvich** [comment]
Thanks for the reminder! The API is set in stone now and the only issue remaining is how to pip install for the CI tests. Unfortunately for our branding purposes the pypi package `firefly` exists already but seems like it was abandoned. Over the past month I've tried getting in contact w/ the owners and 2 weeks ago submitted a name transfer request, see: 

https://github.com/pypa/pypi-support/issues/1177

I'll get to work on the yt PR and hopefully the only thing that will need to be changed is the name of the package the CI should pip install for the testing (sorry I couldn't make it for 4.0, congrats by the way!!).

**Comment by neutrinoceros** [comment]
Good that you're trying to get your hands on the PyPI page ! However I'd expect your request to take at least a few month in order to resolve. Would it be acceptable, as a short term solution, to publish an installable version of the *old* project (firefly-api), even outside PyPI, and point to _that_ link in the corresponding yt error message ?

**Comment by agurvich** [comment]
I was able to reupload firefly-api to pypi when you first realized it had disappeared: https://pypi.org/project/firefly-api. 

I think that should work?

**Comment by neutrinoceros** [comment]
Yeah, thanks !

**Comment by neutrinoceros** [comment]
Fixedvia #3435
