### ISSUE TITLE
DOC: yt4 differences missing deprecation section

### ISSUE THREAD

**Issue by munkm** [yt-project/yt#3451]
### Bug report

**Bug summary**

https://github.com/yt-project/yt/pull/2767 deprecated the axis argument in SlicePlot, but this isn't documented in the yt4 differences page. https://yt-project.org/docs/4.0.0/yt4differences.html . This will definitely break user scripts in yt 4.1 if they are using `axis` as a kwarg so we should document it very clearly and say how to update their scripts.

**Comment by neutrinoceros** [comment]
So actually the yt4differences pages is missing a full "Deprecation" section. I'm going to put this in the 4.0.2 milestone and try to get it rolling before the bugfix release so users still get a chance at seeing what's deprecated in the docs before we do a 4.1 release.
