### ISSUE TITLE
Gadget hdf5 snapshot not recognized as cosmological simulation

### ISSUE THREAD

**Issue by ajouellette** [yt-project/yt#3452]
### Bug report

**Bug summary**

I have an hdf5 snapshot file from a GADGET-4 cosmological simulation (http://use.yt/upload/cc9c9536). When I try to load it with yt it is not recognized as cosmological even though Omega Lambda does exist in the Parameters section of the file and has a value of 0.691.

**Code for reproduction**

```python
pd = yt.load("snapshot_000.hdf5")
```

**Actual outcome**

```
yt : [INFO     ] 2021-07-23 16:55:01,180 Omega Lambda is 0.0, so we are turning off Cosmology.
yt : [INFO     ] 2021-07-23 16:55:01,180 Assuming length units are in kpc (physical)
yt : [INFO     ] 2021-07-23 16:55:01,244 Parameters: current_time              = 0.10009285727652542
yt : [INFO     ] 2021-07-23 16:55:01,244 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2021-07-23 16:55:01,244 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2021-07-23 16:55:01,244 Parameters: domain_right_edge         = [50. 50. 50.]
yt : [INFO     ] 2021-07-23 16:55:01,244 Parameters: cosmological_simulation   = 0
```

**Expected outcome**
The snapshot should be recognized as a cosmological simulation since Omega Lambda is not zero.

**Version Information**

  * Operating System: Linux
  * Python Version: 3.9.6
  * yt version: 4.0.1
  * Other Libraries (if applicable):

Installed using pip

**Comment by neutrinoceros** [comment]
Hi @ajouellette, thank you for reporting this issue.
I've dug a little into this and here's what I was able to grasp so far:

this is where cosmology is "turned off" is the source code
https://github.com/yt-project/yt/blob/ba44836cfb6171e843458a1f66b54000875222d3/yt/frontends/gadget/data_structures.py#L380

I note that yt is able to parse the following metadata from your hdf5 file:
```
{
    'BoxSize': 50.0,
    'Git_commit': b'8ee7f358cf43a37955018f64404db191798a32a3',
    'Git_date': b'Tue Jun 15 15:10:36 2021 +0200',
    'MassTable': array([0.        , 0.51104908]),
    'NumFilesPerSnapshot': 1,
    'NumPart_ThisFile': array([      0, 2097152], dtype=uint64),
    'NumPart_Total': array([      0, 2097152], dtype=uint64),
    'Redshift': 8.990722886822095,
    'Time': 0.10009285727652542,
    'NumFiles': 1,
    'Massarr': array([0.        , 0.51104908])
}
```

note that, while `'Redshift'` is present, it seems it didn't retrieve a value for `OmegaLambda`. I'm not really familiar with hdf5 so I'm a bit limited in going further. Would you be able to provide a minimal script using only h5py to show how to obtain this value ?

**Comment by jzuhone** [comment]
I can have a look at this later today

**Comment by ajouellette** [comment]
`OmegaLambda` is in the attributes of the Parameters section, so this is the way I get its value:
```python
import h5py
snapshot = h5py.File("snapshot_000.hdf5")
OmegaLambda = snapshot["Parameters"].attrs["OmegaLambda"]
```

**Comment by jzuhone** [comment]
@ajouellette is this a change in Gadget4 from previous versions? That may be the reason. It that case it's going to be a simple fix.

**Comment by ajouellette** [comment]
Possibly. I haven't used the hdf5 files from previous versions, so I'm not sure if its any different.
