### ISSUE TITLE
BLD: functions that differ only in their return type cannot be overloaded (on FreeBSD)

### ISSUE THREAD

**Issue by yurivict** [yt-project/yt#3459]
### Bug report

**Bug summary**
Build fails on FreeBSD 13:
```
In file included from yt/utilities/lib/image_samplers.cpp:677:
yt/utilities/lib/platform_dep_math.hpp:15:13: error: functions that differ only in their return type cannot be overloaded
inline bool __isnormal(double x) {
       ~~~~ ^
/usr/include/math.h:189:5: note: previous declaration is here
int     __isnormal(double) __pure2;
~~~     ^
```

**Comment by neutrinoceros** [comment]
Hi @yurivict, it seems that this could (maybe ?) be solved by patching the preprocessor directives logic in `yt/utilities/lib/platform_dep_math.hpp`, though I don't know much about FreeBSD (or c++). @cphyc, @matthewturk, maybe you guys have ideas where to start ?
