### ISSUE TITLE
Migrate to hglib for mercurial API

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#346]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

yt should use the mercurial IPC protocol rather than directly calling the API.

https://bitbucket.org/idank/python-http://mercurial.selenic.com/wiki/PythonHglib
http://mercurial.selenic.com/wiki/CommandServer

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/346

**Comment by ngoldbaum** [comment]
We fixed this a long time ago.
