### ISSUE TITLE
BUG: instability on Jenkins CI

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3491]
### Bug report
**Bug summary**
Reporting this to give it more visibility.

Since last Friday (August 27, 2021), the "yt_py38_latest_deps" CI job on Jenkins has been failing with 236 errors, all of them image comparison failures, and all about some missing font file.
These errors are also popping on every PR opened since then (see #3488 , #3489 and #3490).

**Comment by Xarthisius** [comment]
> "yt_py38_latest_deps" CI job on Jenkins has been failing with 236 errors
> These errors are also popping on every PR opened since then (see #3488 , #3489 and #3490).

`yt_py38_latests_deps` doesn't run on PRs. It's being executed nightly on main. Having said that I can see that `yt_py38_git` is failing too.

**Comment by Xarthisius** [comment]
Probably related to:

```
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeOneSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeTwoSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeThreeSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeFourSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeFiveSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmsy10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmr10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmtt10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmmi10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmb10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmss10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmex10'] not found. Falling back to DejaVu Sans.
```

**Comment by neutrinoceros** [comment]
> yt_py38_latests_deps doesn't run on PRs. It's being executed nightly on main. Having said that I can see that yt_py38_git is failing too.

Oh my bad, I thought I made the distinction clear here but seems like I didn't.

**Comment by Xarthisius** [comment]
https://github.com/matplotlib/matplotlib/issues/20850 ?

**Comment by Xarthisius** [comment]
Looks like new font registry was generated few days ago. I think that's when problems started:

```
fido@c1af1189021c ~/.cache/matplotlib $ ls -lrth
total 132K
drwxr-xr-x 2 fido fido   6 Nov  7  2019 tex.cache
-rw-r--r-- 1 fido fido 41K Nov  7  2019 fontlist-v300.json
-rw-r--r-- 1 fido fido 24K Nov 25  2019 fontList.json
-rw-r--r-- 1 fido fido 44K Mar 20  2020 fontlist-v310.json
-rw-r--r-- 1 fido fido 20K Aug 26 13:17 fontlist-v330.json
```

**Comment by neutrinoceros** [comment]
Nice catch. Seems like the bleeding-edge CI job wasn't enough to catch this one. How about we update the "latest_deps" Jenkins job to use the dev version of matplotlib instead of the the latest release ?
In the mean time, we can also hotfix this on our side by forbidding Matplotlib 3.4.3, correct ?

**Comment by Xarthisius** [comment]
What I did:

```
$ mv fontlist-v330.json fontlist-v330.old
# activate env used by CI
$ python -c 'import matplotlib.pyplot as plt'
```

Now:

```
fido@c1af1189021c ~/.cache/matplotlib $ ls -lrth
total 176K
drwxr-xr-x 2 fido fido   6 Nov  7  2019 tex.cache
-rw-r--r-- 1 fido fido 41K Nov  7  2019 fontlist-v300.json
-rw-r--r-- 1 fido fido 24K Nov 25  2019 fontList.json
-rw-r--r-- 1 fido fido 44K Mar 20  2020 fontlist-v310.json
-rw-r--r-- 1 fido fido 20K Aug 26 13:17 fontlist-v330.old
-rw-r--r-- 1 fido fido 43K Aug 30 14:35 fontlist-v330.json
```

I think it's going to fix the issue. Can you retrigger job somewhere?

**Comment by neutrinoceros** [comment]
done ! see https://github.com/yt-project/yt/pull/3489

**Comment by neutrinoceros** [comment]
Well played, looks like it worked indeed !
