### ISSUE TITLE
Multiple data type candidates

### ISSUE THREAD

**Issue by mameehan5** [yt-project/yt#3510]
### Bug report

**Bug summary**

Multiple data types were found to be eligible for loading the dataset due to shear coincidence that the string in `_subtype_keyword` matches an expression for the name of the computer.

**Code for reproduction**
```python
ts = yt.DatasetSeries("plt?????", parallel=True)
```
The dataset is an `AMReXDataset`, which is how I would prefer to load it, but in `job_info`, there is a line 
```
build machine: Linux onyx07 4.4.178-94.91-default #1 SMP Thu May 2 20:14:31 UTC 2019 (d683ca1) x86_64 x86_64 x86_64 GNU/Linux
```
which has the `_subtype_keyword` `nyx`, which means a `NyxDataset` is also valid.

**Actual outcome**

```
yt.utilities.exceptions.YTAmbiguousDataType: Multiple data type candidates for plt66875
The following independent classes were detected as valid :
<class 'yt.frontends.boxlib.data_structures.NyxDataset'>
<class 'yt.frontends.boxlib.data_structures.AMReXDataset'>
A possible workaround is to directly instantiate one of the above.
Please report this to https://github.com/yt-project/yt/issues/new
```

**Expected outcome**

Ideally, this would load as normal. The possible workaround to instantiate using `from yt.frontends.boxlib.data_structures import AMReXDataset` to load the datset does not work for data series. 

My thinking is that it would be nice to avoid this all together by passing a keyword, such as
```
yt.DatasetSeries("plt?????", parallel=True, dataset='AMReXDataset')
```
which would force yt to load the files as that dataset. This could be useful for others who ever have a similar issue.

**Version Information**

  * Operating System: macOS Catalina
  * Python Version: 3.6.13
  * yt version: 4.1.dev0

Using conda and an install from source.

**Comment by neutrinoceros** [comment]
> The possible workaround to instantiate using from yt.frontends.boxlib.data_structures import AMReXDataset to load the datset does not work for data series.

just a quick note that the normal way to do this from the user standpoint is to import from `yt.frontends.boxlib.api` instead
```
from yt.frontends.boxlib.api import AMReXDataset
```

but indeed this is the workaround for this unfortunate situation.

> My thinking is that it would be nice to avoid this all together by passing a keyword

This would go against the design patterns in place, but yeah I guess we could have such a keyword as supported workaround, but I'd argue that the argument should be a class, not a str representing a class name, for it to be sane.

Possible duplicate: https://github.com/yt-project/yt/issues/3005
Deep down the issue is two fold:
- the mechanism to guess what exact boxlib child class is more appropriate is very fragile
- we don't currently have a way to force instantiation of a specific `Dataset` class in `DatasetSeries`.

This second point seems easy to fix, I'd support a PR implementing your proposed patch.
The former is harder to fix but obviously I'd also be game to review a patch there.

**Comment by mameehan5** [comment]
> the normal way to do this from the user standpoint is to import from `yt.frontends.boxlib.api` instead

Thanks for showing me this!

The boxlib architecture is certainly difficult and there are more now that are based off AMReX, making possibly harder to keep up.

Let me know what you think of this PR for the fix. Happy to make changes, this was the first way I could think of to fix the issue.

**Comment by Xarthisius** [comment]
> we don't currently have a way to force instantiation of a specific `Dataset` class in `DatasetSeries`.

We do, cause sometimes specific frontends require some magic. A gist of it:

```
import yt
from yt.data_objects.time_series import DatasetSeries
from yt.frontends.boxlib.api import AMReXDataset


class AMReXDatasetSeries(DatasetSeries):
    _dataset_cls = AMReXDataset


ts = yt.AMReXDatasetSeries("plt?????", parallel=True)
```

**Comment by neutrinoceros** [comment]
Oh right. That should have been clear when I reviewed the PR. Though this feels very atypical for yt, I would like to know where you stand on the proposal for adding a keyword argument to DatasetSeries.

**Comment by mameehan5** [comment]
@Xarthisius This is great! I am actually happy to close this issue with this fix. 

> ```ts = yt.AMReXDatasetSeries("plt?????", parallel=True)```

should be `ts = AMReXDatasetSeries("plt?????", parallel=True)` for anyone who sees this down the line.

**Comment by Xarthisius** [comment]
> Oh right. That should have been clear when I reviewed the PR. Though this feels very atypical for yt, I would like to know where you stand on the proposal for adding a keyword argument to DatasetSeries.

It's fine. Just don't overcomplicate it. Optionally, set `_dataset_cls` in the `__init__`, as you mentioned in #3512
