### ISSUE TITLE
BUG: piling up memory bloat while plotting in a loop

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3513]
### Bug report

**Bug summary**

Generating a simple plot in a loop creates significant memory waste

**Code for reproduction**
Using [`memory_profiler`](https://pypi.org/project/memory-profiler/) as
```shell
wget https://yt-project.org/data/solar_prom2d.tar.gz
tar -xvzf solar_prom2d.tar.gz
mprof run benchmark.py
mprof plot
```
with
```python
# benchmark.py
import sys
import time

import yt

def main(n) -> int:
    yt.set_log_level("error")
    for _ in range(n):
        ds = yt.load("solar_prom2d/output0001.dat")
        pp = yt.ProjectionPlot(ds, "z", ("gas", "density"))
        del ds, pp
    return 0

if __name__ == "__main__":
    sys.exit(main(100))
```

**Actual outcome**

![mprof_res](https://user-images.githubusercontent.com/14075922/133330260-5e52ef72-2854-4474-b4ab-3a2afa08ca49.png)

The job is ending up eating 4GiB (!) or RAM just because it ran 100 times the same 2D render of a 600MiB dataset.

notes
1) I see no difference with our without the `del` statement. Seems like the garbage collector is doing a decent job, or at least I can't really top it with del
2) I tried patching the plot classes to force closure/deletion of embedded  matplotlib figures, to no avail.

I don't currently have any idea what might be causing this bloat and how to address it.

**Expected outcome**

Memory usage shouldn't drift.

**Version Information**
  * Operating System: MacOS
  * Python Version: 3.9.5
  * yt version: main branh (Version = 4.1.dev0, Changeset = 4d81bc35b08f)
  * Other Libraries (if applicable): `memory_profiler` 0.58.0

**Comment by cphyc** [comment]
On top of my head, did you try replacing the line with the projection plot with, say `ad = ds.all_data(); ad["density"]`?
I am wondering if the issue isn't about loading the dataset and keeping some reference of it somewhere, thus preventing the memory from being freed.

Another random thought is that you could try adding  `import gc; gc.collect()` right after `del`ing. This'll force the garbage collection to happen now. That should tell us if the issue is on Python's side who is too last to free the memory or if we're doing something wrong on yt's side.

14 Sep 2021 21:49:22 Clément Robert ***@***.***>:

> 
> *Bug report*
> 
> *Bug summary*
> 
> Generating a simple plot in a loop creates significant memory waste
> 
> *Code for reproduction*
> Using *memory_profiler[https://pypi.org/project/memory-profiler/]* as
> 
> $ wget https://yt-project.org/data/solar_prom2d.tar.gz
> $ tar -xvzf solar_prom2d.tar.gz
> $ mprof run benchmark.py
> $ mprof plot
> 
> with
> 
> # benchmark.py
> import sys
> import time
> 
> import yt
> 
> def main(n) -> int:
>     yt.set_log_level("error")
>     for _ in range(n):
>         ds = yt.load("solar_prom2d/output0001.dat")
>         pp = yt.ProjectionPlot(ds, "z", ("gas", "density"))
>         del ds, pp
>     return 0
> 
> if __name__ == "__main__":
>     sys.exit(main(100))
> 
> *Actual outcome*
> 
>  [https://user-images.githubusercontent.com/14075922/133330260-5e52ef72-2854-4474-b4ab-3a2afa08ca49.png][mprof_res][https://user-images.githubusercontent.com/14075922/133330260-5e52ef72-2854-4474-b4ab-3a2afa08ca49.png]
> 
> notes
> 
1. > I see no difference with our without the *del* statement. Seems like the garbage collector is doing a decent job, or at least I can't really top it with del
2. > I tried patching the plot classes to force closure/deletion of embedded matplotlib figures, to no avail.
> 
> I don't currently have any idea what might be causing this bloat and how to address it.
> 
> *Expected outcome*
> 
> Memory usage shouldn't drift.
> 
> *Version Information*
> 
* > Operating System: MacOS
* > Python Version: 3.9.5
* > yt version: main branh (Version = 4.1.dev0, Changeset = 4d81bc3[https://github.com/yt-project/yt/commit/4d81bc35b08f6f31dba6a9ff6f9d0b046c3c5687])
* > Other Libraries (if applicable): *memory_profiler* 0.58.0

**Comment by neutrinoceros** [comment]
Calling `gc.collect()` right after `del` seems to marginally improve the situation. Now let's try to replace plotting with loading as you suggest
![Figure_1](https://user-images.githubusercontent.com/14075922/133397890-752027c6-600d-4d4e-82b0-50851c19e020.png)

**Comment by neutrinoceros** [comment]
replacing `pp = yt.SlicePlot(...)` with `ad = ds.all_data(); ad["gas", "density"]` yields much more reasonable results. Now it seems pretty clear that something is done wrong either in yt or possibly matplotlib.
![Figure_2](https://user-images.githubusercontent.com/14075922/133400354-b671f0a3-ef19-494e-b04c-ca3d31e49318.png)

**Comment by matthewturk** [comment]
Can you try doing `ds.r[:,:,0.5]` or maybe `ds.r[::256j,::256j,0.5]` or something like that, to create the slice and/or the FRB without calling matplotlib?

**Comment by neutrinoceros** [comment]
I can't find a single way to slice this 2D dataset that works atm. This is out of scope but I figure we should fix this too at some point.
```
yt.utilities.exceptions.YTDimensionalityError: Dimensionality specified was 3 but we need 2
```

```
IndexError: list index out of range
```

```
RuntimeError: unyt_quantity values must be numeric
```
Let's try a similar benchmark with our best friend `"IsolatedGalaxy"`

**Comment by matthewturk** [comment]
You could manually create a slice, though.

**Comment by matthewturk** [comment]
One possibility is that we are retaining references to the figures, which
retain references to the datasets.  I don't know that it's matplotlib *yet*
that is the reason; we do a lot of wrapping matplotlib, too.  It might be
worthwhile to append all of the created SlicePlot objects to a weak value
store, and then use the gc reference finder to check on them after the loop
concludes.

**Comment by neutrinoceros** [comment]
Hopefully I can attempt this later.

**Comment by neutrinoceros** [comment]
So I've tried to find what object refused to die with this:

```python
import yt
import time
import sys
import gc
from pprint import pprint
import weakref
from typing import Any

ref_store: list[dict[str : weakref.ReferenceType]] = []

attrs: list[str] = [
    "axes",
    "canvas",
    "cax",
    "cb",
    "figure",
    "image",
]


def main(n: int = 100) -> int:
    yt.set_log_level("error")
    start = time.monotonic()
    for _ in range(n):
        ds = yt.load("tmp/solar_prom2d/output0001.dat")
        pp = yt.ProjectionPlot(ds, "z", ("gas", "density"))

        ref_store.append(
            {
                attr: weakref.ref(getattr(pp.plots["gas", "density"], attr))
                for attr in attrs
            } | {
                "plot_obj": weakref.ref(pp.plots["gas", "density"]),
                "pp": weakref.ref(pp),
                "frb": weakref.ref(pp._frb),
                "frb_data": weakref.ref(pp._frb.data["gas", "density"]),
            }
        )
    stop = time.monotonic()
    delta = stop - start
    print(f"Ran {n} loops in {delta:.1f} s")
    breakpoint()
    return 0


if __name__ == "__main__":
    sys.exit(main(5))
```
After playing around in the debugger, my conclusions seem to be that relevant attributes attached to the projection-plot object are correctly cleaned up after 2 iterations in my loop. In any case the heaviest object generated by one iteration, by my estimation, is the frb data array (800x800x64 bytes). Assuming they are never cleaned, 100 iterations should lead to ~3.8GiB of RAM consumed, which is suspiciously closed to what I measure. Though I may not be using my tools well, because it _looks_ to me that they are indeed cleaned. 🤷🏻‍♂️

**Comment by matthewturk** [comment]
`800x800x64` *bytes*?  Is that a typo for 800x800x64 bits?

So yes, this is odd.  And I am wondering if the `YTImageArray` is somehow retaining itself.  I wonder if it's something about that double-subclass.

**Comment by neutrinoceros** [comment]
> 800x800x64 bytes? Is that a typo for 800x800x64 bits?

yes of course, I meant *bits*, sorry. The fact that they are homophones in French doesn't help.

I've tried to replace the default FRB resolution from 800x800 to 4x4, i.e. diminishing the potential memory pollution by 20k x, and I saw no improvement.
Note that the `ImageArray` objects are tracked in my script above and I can see them being killed by the garbage collector, so I'm really not convinced that the issue is here, but I admit I don't know how to inspect this further atm.

**Comment by matthewturk** [comment]
I think what I'm wondering is if the `ImageArray` objects -- which are distinct from the buffers allocated by numpy if `OWNDATA` is not set -- are but one of the references to the data.

I'm curious if maybe there's something going on with the pixelization process that's causing the buffers to get lost/forgotten.

**Comment by neutrinoceros** [comment]
How do you define "lost/forgotten" here ? I fail to understand how any object can survive in memory when nothing seems to bel referring to it, even after `gc.collect()` was called.

**Comment by matthewturk** [comment]
I guess what I'm saying is that it's possible that the buffers underlying
the arrays may not be owned by the arrays, so would not be tracked by the
gc in the same way.

**Comment by neutrinoceros** [comment]
I confirm that `ImageArray` instances have `OWNDATA = False`, but seems to me that the *double* subclassing has nothing to do with it, as pure `unyt_array` objects *also* don't own their data.
That said, I wasn't able to generate any significant memory usage by creating large-(ish) ImageArray or unyt_array instances in a loop.

**Comment by neutrinoceros** [comment]
quick note that running this benchmark again with a ~3MB dataset (bw_cartesian_3d, also amrvac format) shows a much slower bloating
![Figure_1](https://user-images.githubusercontent.com/14075922/134411798-eaa5a157-9f2a-4cc8-9000-9b6f9ab59c13.png)

This seems to indicate that the mystery "zombie" objects are not images (whose size doesn't depend on the data being plotted), so maybe more plausibly, some selections/region objects ?

**Comment by neutrinoceros** [comment]
I've attempted to patch unyt itself, hacking into `unyt_array.__new__` to force unyt arrays to own their data but only got myself into some infinite loop. I'll try again later.

**Comment by neutrinoceros** [comment]
I do. Unless we can gather evidence that this is a pure matplotlib bug, I still believe there's something to fix on the yt side.

**Comment by neutrinoceros** [comment]
I found a couple very similar issues were reported to matplotlib
https://github.com/matplotlib/matplotlib/issues/19769
https://github.com/matplotlib/matplotlib/issues/21788
https://github.com/matplotlib/matplotlib/issues/22448

I'm less and less convinced that it's in our power to address the problem, so I'll close.
