### ISSUE TITLE
BUG: Uninitialized memory in Athena++ selection

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3619]
### Bug report

**Bug summary**

So there currently seems to be an issue with a single test that I've seen failing repeatedly these days.
Namely, it `yt/frontends/athenapp/tests/test_outputs.py::test_disk` and the failing assertion is:
https://github.com/yt-project/yt/blob/9a6def95a14c1883e74325113055ffa14fb9e48a/yt/frontends/athena_pp/tests/test_outputs.py#L31

So we can see from the recent history that the call to `total_quantity` returns random results, including

- a random float https://tests.yt-project.org/job/yt_py38_git/4106/
- another random float https://tests.yt-project.org/job/yt_py38_git/4107/
- a nan https://tests.yt-project.org/job/yt_py38_git/4109/

Note that all the examples above are from running #3489, which is clearly unrelated to the failing code, but I've seen it for other PRs as well, it's hard to find another example within the recent history because most jobs we still have logs for were failed for different reasons or cancelled.

I assume this is a parellelism bug given that `total_quantity` is `TotalQuantity` object, derived from `DerivedQuantity`, and  workers synchronisation issues seem like a plausible explanation to getting random results to an otherwise deterministic function

see
https://github.com/yt-project/yt/blob/69ada921cd0f15677611303934c140fcd93c1089/yt/data_objects/derived_quantities.py#L55

I think the breaking test isn't worth blocking PRs and consuming many hours of CI from resubmissions, so I'm going to open a with the problematic line deactivated, but it won't close this issue.

**Comment by jzuhone** [comment]
This has likely been resolved by https://github.com/yt-project/yt/pull/4562.
