### ISSUE TITLE
BUG: [4.0.1] Error running pytest on installed package

### ISSUE THREAD

**Issue by olebole** [yt-project/yt#3655]
### Bug report

I am currently preparing the new yt version for uploading as a Debian package. Aside from running the tests during build time, we run them on the installed package regularly to check the package works in a changing environment.

**Bug summary**

When In install the package onto its standard place in Debian (in `/usr/lib/python3/dist-packages/`), and running pytest, I get the following error:

```
$ python3 -m pytest --pyargs yt
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
Matplotlib: 3.3.4
Freetype: 2.11.0
rootdir: /home/ole
plugins: filter-subpackage-0.1.1, remotedata-0.3.2, hypothesis-5.43.3, mpl-0.11, openfiles-0.5.0, astropy-header-0.1.2, doctestplus-0.11.0, asdf-2.8.1, mock-3.6.1, cov-2.12.1, arraydiff-0.3
collected 809 items / 1 error / 808 selected                                   

==================================== ERRORS ====================================
__________ ERROR collecting frontends/gdf/tests/test_outputs_nose.py ___________
In test_sedov_tunnel: function uses no argument 'axis'
```

See [here](https://salsa.debian.org/debian-astro-team/yt/-/jobs/2157142/raw) for a full test log.

**Code for reproduction**

See above

**Actual outcome**

See above

**Expected outcome**

I expect that the test works in the same manner as during the build (i.e. it should pass, as shown [here](https://salsa.debian.org/debian-astro-team/yt/-/jobs/2157134/raw))

**Version Information**

  * Operating System: Debian unstable
  * Python Version: 3.9.7
  * yt version: 4.0.1
  * Other Libraries (if applicable):
    - pytest: 6.2.5
    - nose: 1.3.7

(all from Debian packages)

**Comment by Xarthisius** [comment]
When you want to run pytest suite outside the source tree you still need to use the flags that are passed to pytest by default from `pyproject.toml`:

https://github.com/yt-project/yt/blob/yt-4.0.1/pyproject.toml#L66-L74

**Comment by olebole** [comment]
This does not work for me:
```
$ python3 -m pytest -rsfE --ignore-glob='*_nose.py' --ignore='yt/frontends/owls_subfind/tests/test_outputs.py' --ignore='*/test_outputs.py' --pyargs yt
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
Matplotlib: 3.3.4
Freetype: 2.11.0
rootdir: /home/ole/Projects/2015/upstream/iraf/pyraf, configfile: setup.cfg
plugins: filter-subpackage-0.1.1, remotedata-0.3.2, hypothesis-5.43.3, mpl-0.11, openfiles-0.5.0, astropy-header-0.1.2, doctestplus-0.11.0, asdf-2.8.1, mock-3.6.1, cov-2.12.1, arraydiff-0.3
collected 809 items / 1 error / 808 selected                                   

==================================== ERRORS ====================================
__________ ERROR collecting frontends/gdf/tests/test_outputs_nose.py ___________
In test_sedov_tunnel: function uses no argument 'axis'
```
Maybe the `--ignore…` options can't be combined with `--pyargs`?

**Comment by neutrinoceros** [comment]
It’s worth noting that we have an upcoming bugfix release in the shop too (4.0.2).

**Comment by olebole** [comment]
What worked for me was to remove all `*_nose.py` files and `yt/frontends/gdf/tests/test_outputs.py` from the installed package.
I am wondering why they are still in the yt sources? Obviously they are neither used for testing, nor for the regular use of the package?

**Comment by neutrinoceros** [comment]
Actually we're not done migrating from nose to pytest, so these tests files are not retired yet. A portion of our CI is still running nose.

**Comment by Xarthisius** [comment]
I ran:

```
$ docker run --rm -ti --entrypoint=/bin/bash python:3.9-bullseye
(container) $ pip install yt==4.0.1 pytest==6.2.5 nose==1.3.7
(container) $ python3 -m pytest --pyargs yt
.... # fails as reported
(container) $ python3 -m pytest -rsfE --ignore-glob='*_nose.py' --ignore='yt/frontends/owls_subfind/tests/test_outputs.py' --ignore='*/test_outputs.py' --pyargs yt
===================================================================================== test session starts =====================================================================================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /
collected 809 items                                                                                                                                                                           

usr/local/lib/python3.9/site-packages/yt/data_objects/level_sets/tests/test_clump_finding.py .ss                                                                                        [  0%]
usr/local/lib/python3.9/site-packages/yt/data_objects/tests/test_bbox.py .                                                                                                              [  0%]
usr/local/lib/python3.9/site-packages/yt/data_objects/tests/test_boolean_regions.py ........^C
```

Clearly there's some difference in behavior with yt installed from .deb. Unless you're planning to provide a PR with some non-invasive changes, there's nothing for us to do here.
