### ISSUE TITLE
BLD: Test error on 32 bit with numpy 1.19.5

### ISSUE THREAD

**Issue by olebole** [yt-project/yt#3656]
### Bug report

During the Debian package preparation, Python and the numpy package used in the i386 CI tests on our Gitlab was updated, which causes a number of test failures with 32 bit x86. 

**Bug summary**

There are now 57 failures; they seem to be connected with the use of `numpy.argsort()`:
```
____________________________ test_bitmap_save_load _____________________________

    def test_bitmap_save_load():
[…]
        # Create bitmap and save to file
>       reg0 = FakeBitmap(npart, nfiles, order1, order2, left_edge, right_edge, periodicity)

/builds/debian-astro-team/yt/debian/output/source_dir/.pybuild/cpython3_3.9_yt/build/yt/geometry/tests/test_particle_octree.py:296: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/builds/debian-astro-team/yt/debian/output/source_dir/.pybuild/cpython3_3.9_yt/build/yt/geometry/tests/test_particle_octree.py:161: in FakeBitmap
    nsub_mi, coll = reg._refined_index_data_file(
yt/geometry/particle_oct_container.pyx:683: in yt.geometry.particle_oct_container.ParticleBitmap._refined_index_data_file
    out_collection = self.__refined_index_data_file(_in_coll, pos, hsml, mask,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   sorted_order = np.argsort(morton_indices)
E   ValueError: Item size of buffer (4 bytes) does not match size of 'uint64_t' (8 bytes)

yt/geometry/particle_oct_container.pyx:751: ValueError
```
This is a regression, it did not happen with 1.19.4:

* [full build log with Python 3.9.7, numpy 1.19.5 **[fail]**](https://salsa.debian.org/debian-astro-team/yt/-/jobs/2157260/raw)
* [full build log with Python 3.9.0, numpy 1.19.4 **[pass]**](https://salsa.debian.org/debian-astro-team/yt/-/jobs/1161009/raw)

**Code for reproduction**

See above

**Actual outcome**

See above

**Expected outcome**

yt tests should pass on numpy 1.19.4 as well as on 1.19.5.

**Version Information**
  * Operating System: Debian unstable, arch: i386
  * Python Version: 3.9.7
  * yt version: 4.0.1
  * numpy 1.19.5

All from Debian packages

**Comment by neutrinoceros** [comment]
Note that on Linux + Python 3.9, yt should build against numpy 1.19.3 (see https://github.com/scipy/oldest-supported-numpy/blob/master/setup.cfg), which _should_ retain ABI compatibility with 1.19.4 and 1.19.5
If you are already building with numpy 1.19.3, I don't think there's much we can do about it on the yt side. Unless I'm missing something, this looks more like a numpy regression to me.
I cannot find any note specifically on 32 bits build in numpy's recent release notes.

**Comment by olebole** [comment]
I still don't have a good idea; also forcing to re-cythonize didn't help.
The problem seems to be in lines 751 resp. 753 of `particle_oct_container.pyx`:  https://github.com/yt-project/yt/blob/6a90b9649cab14fa6fe84b9c7bb62858fbb7adf7/yt/geometry/particle_oct_container.pyx#L750-L753

In 55 failures, these two lines raise the exception
```
ValueError: Item size of buffer (4 bytes) does not match size of 'uint64_t' (8 bytes)
```
Any hint what this could be? I am not that experienced in cython to understand this here...

**Comment by neutrinoceros** [comment]
Did you ask numpy dev about this ? Solving this on the yt side really looks out of reach (at least to me), especially if the problem only appeared after numpy was upgraded in your build system.

**Comment by olebole** [comment]
The problem seems to be the assignmen of the value returned from `argsort` to `sorted_order`:
```Cython
cdef np.ndarray[np.uint64_t, ndim=1, cast=True] sorted_order
if hsml is None: 
    sorted_order = np.argsort(morton_indices) 
[…]
```
`sorted_order` is declared to be `uint64`, but `argsort` on a 32-bit machine returns an `int32` array:
```Python
>>> import numpy as np
>>> m = np.array([23,  1, 23,  7, 89, 67, 28, 96, 44, 55, 27, 13], dtype=np.uint64)
>>> np.argsort(m)
array([ 1,  3, 11,  0,  2, 10,  6,  8,  9,  5,  4,  7], dtype=int32)
```
On x86_64, it returns an `in64` array, which has the same size as `uint64`.
Could this be explicitely casted (which I don't know how this is done in Cython)?

**Comment by cphyc** [comment]
It guess it may be enough to add

**Comment by olebole** [comment]
wouldn't it then be enough to have this?
```Python
sorted_order = np.argsort(…).astype(np.uint64_t, copy=False)
```
That would automatically pass-through if it had the same size.
I'll try it out later.

**Comment by cphyc** [comment]
> wouldn't it then be enough to have this?
> 
> ```python
> sorted_order = np.argsort(…).astype(np.uint64_t, copy=False)
> ```
> 
> That would automatically pass-through if it had the same size. I'll try it out later.

I didn't know about the `copy=False` optional argument, but yes, that would be a better solution (possibly equivalent from a numerical standpoint). If that works, we'd be happy to have you submit a PR or, if you don't have time for this, we could submit one ourselves.
Thanks for debugging!

**Comment by neutrinoceros** [comment]
adding this to the next bugfix release milestone. Thank @cphyc for looking over this !
