### ISSUE TITLE
Colortransferfunction map_to_colormap makes last values for all channels zero

### ISSUE THREAD

**Issue by MironLeon** [yt-project/yt#3660]
### Bug report

**Bug summary**

When using the `map_to_colormap` of a `yt.visualization.volume_rendering.transfer_functions.ColorTransferFunction` object, the last value of the `red`, `green`, `blue`, `alpha` channels are always zero.

**Code for reproduction**

```python
import yt
tf = yt.visualization.volume_rendering.transfer_functions.ColorTransferFunction(
    x_bounds=(0.0, 1.0),
    nbins=8
)
tf.map_to_colormap(
    tf.x_bounds[0],
    tf.x_bounds[1],
    colormap='Blues',
)
print(tf.alpha.y)
print(tf.red.y)
print(tf.green.y)
print(tf.blue.y)
tf.show()
```

**Actual outcome**
I have not been able to see if this actually influences rendering, but the transfer function looks off
![image](https://user-images.githubusercontent.com/89517300/141096293-f548f171-83b4-4645-a020-d9a71e60f649.png)

```
[1., 1., 1., 1., 1., 1., 1., 0.]
[0.96862745, 0.84069204, 0.67189542, 0.41708574, 0.21568627, 0.06251442, 0.03137255, 0.]
[0.98431373, 0.90163783, 0.81437908, 0.68063053, 0.52941176, 0.35750865, 0.18823529, 0]
[1., 0.95866205, 0.90065359, 0.83823145, 0.75424837, 0.64290657, 0.41960784, 0]
```

**Expected outcome**

I would expect for a flat transfer function that all alpha values are the same value and all the color channels last value represent the max blue in the 'Blues' colormap (something like (0, 0.1, 0.3)?)

**Version Information**
  * Operating System: Ubuntu 20.04.3 LTS
  * Python Version: 3.8.7
  * yt version: 4.0.1

I installed yt with just `pip install yt`. Same issue also occurs in 3.6.1

**Comment by neutrinoceros** [comment]
Thanks for reporting this ! This looks like an off-by-one error and I believe the patch is trivial.

**Comment by neutrinoceros** [comment]
@meeseeksdev backport to yt-4.0.x

**Comment by neutrinoceros** [comment]
no idea where the logs are. Let's try this one more time and if it fails again I'll do manually
@meeseeksdev backport to yt-4.0.x

**Comment by neutrinoceros** [comment]
ah. My bad I'm commenting the issue instead of the PR... sorry guys !
