### ISSUE TITLE
BUG: slice plot can not be saved in "pdf" format

### ISSUE THREAD

**Issue by Xiaolong-Du** [yt-project/yt#3677]
### Bug report

**Bug summary**

Slice plot can not be saved in "pdf" format or any other format other than the default "png".

**Code for reproduction**

```python
import numpy as np
import yt

dataRandom = np.random.random([32,32,32])
data       = dict(density=(dataRandom,"Msun/Mpc**3"))

bbox       = [[0,1], [0,1], [0,1]]

ds         = yt.load_uniform_grid(data=data, domain_dimensions=dataRandom.shape, length_unit="Mpc", \
                                  bbox=np.array(bbox))

slc        = yt.SlicePlot(ds, 2, [('gas', 'density')])

slc.save("random.pdf")
```

**Actual outcome**

```
yt : [WARNING  ] 2021-11-18 22:23:25,995 Received two valid image formats 'pdf' (from `filename`) and 'png' (from `suffix`). The former is ignored.
yt : [INFO     ] 2021-11-18 22:23:25,996 Saving plot random_Slice_z_density.png
```

**Expected outcome**

I was able to generate "pdf" plots with yt 3.x. But when I update yt to 4.x recently, the issue appears. I did some tests, it seems to be caused by the following function in the file "yt/visualization/_commons.py"

```python
def validate_image_name(filename, suffix: Optional[str] = None) -> str:
    """
    Build a valid image filename with a specified extension (default to png).
    The suffix parameter is ignored if the input filename has a valid extension already.
    Otherwise, suffix is appended to the filename, replacing any existing extension.
    """
    name, psuffix = os.path.splitext(filename)
    psuffix = normalize_extension_string(psuffix)

    if suffix is not None:
        suffix = normalize_extension_string(suffix)

    if psuffix in SUPPORTED_FORMATS:
        if suffix in SUPPORTED_FORMATS and suffix != psuffix:
            mylog.warning(
                "Received two valid image formats '%s' (from `filename`) "
                "and '%s' (from `suffix`). The former is ignored.",
                psuffix,
                suffix,
            )
            return f"{name}.{suffix}"
        return str(filename)

    if suffix is None:
        suffix = "png"

    if suffix not in SUPPORTED_FORMATS:
        raise ValueError(f"Unsupported file format '{suffix}'.")

    return f"{filename}.{suffix}"
```
As can be seen, even if "psuffix" is a supported format, it is always replaced by "suffix". This is inconsistent with the comment at the beginning of the function that the replacement is only done when the specified format is not supported. After changing the condition sentences in the middle of the function to

```python
    if psuffix in SUPPORTED_FORMATS:
        return str(filename)
    else:
        if suffix in SUPPORTED_FORMATS and suffix != psuffix:
            mylog.warning(
                "Received two valid image formats '%s' (from `filename`) "
                "and '%s' (from `suffix`). The former is ignored.",
                psuffix,
                suffix,
            )
            return f"{name}.{suffix}"
```
everything  goes back to normal and I can save the plot in the format I specified.

**Version Information**

  * Operating System: Linux 2.6.32-504.30.3.el6.x86_64 x86_64
  * Python Version: 4.1.dev0
  * yt version: 3.8.8
  * Other Libraries (if applicable):

**Comment by neutrinoceros** [comment]
Thank you so much for reporting this ! So your patch indeed fixes the bug but it will also bypass the warning in when conflicting arguments are detected. I think the real cause of the bug isn't in this function, but lies in the fact that many `save()` methods have an explicit default value for the `suffix` argument (namely `suffix=".png"`), that we cannot differentiate internally from a user passing this argument explicitly.
So I think the correct patch would be to use a sentinel value for a default and handle it everywhere needed. Beware that it is considerably more work (although not a substantial amount). Since you've started to work on this on your own (thank you _so_ much for that), do you wish to pursue and submit a PR ? It doesn't have to be perfect on first try and I can guide you through the process, otherwise I'd be happy to fix this myself. Please let me know what you'd like more.

**Comment by Xiaolong-Du** [comment]
Hi @neutrinoceros , thanks for your reply. You are right that the changes I made will also lead to other issues. I would be happy to help submit a PR. Unfortunately, I will not be able to find the time to do this in the near future. So it would be great if you could fix this.

**Comment by neutrinoceros** [comment]
Ok will do, thanks for getting back to me !
