### ISSUE TITLE
ENH: Enable SemiStructuredGrid to be specified with dx, dy, dz arrays

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#3694]
Supporting "stretched" grids requires that we allow some of our grids to utilize arrays of dx, dy, and dz.  Right now the `SemiStructuredGrid` object instead utilizes the full unstructured mesh machinery.

I believe this will require:

 - [ ] adding an implementation of `get_global_startindex()` to the class (and thus also requiring this be specified at load time; this could also be inferred at load time)
 - [ ] Modify the various mask and selection routines to *not* use the unstructured mesh components, but instead to utilize modified versions of the grid selection routines that accept the arrays of dx's (or positions)

Note that this is not sufficient for full parity, as it will also require that we modify the projection machinery to avoid using the `ires` and `relative_refinement` functions.

Here is a handful of bits of patches that may support this:

https://gist.github.com/matthewturk/7146bc51fe34cad9f5fc85139f406569

**Comment by neutrinoceros** [comment]
`SemiStructuredGrid` doesn't exist, did you mean to write `SemiStructuredMesh` ?

> adding an implementation of get_global_startindex() to the class

which class ? still `SemiStructuredMesh` ?

I'd like to better understand how these can be connected to frontends.
Looking at existing ones, it seems that only `stream` and `moab` are subclassing SemiStructuredMesh. I note that they both seem to:
- define a subclass of `SemiStructuredMesh`
- derive their Hierarchy classes from `UnstructuredIndex`

Given that `SemiStructuredMesh` is a subclass of `UnstructuredMesh`, I am now wondering whether there would be any reason to have a `SemiStructuredIndex` class too, other than symmetry. If not, could you explain why ?

**Comment by matthewturk** [comment]
So!  Why we want to avoid subclassing `UnstructuredMesh` is that `UnstructuredMesh` is -- by design! -- much more general than we need to be here.  We can rely on a bunch of things we use in the grid frontends (like having left and right edges) that will optimize things a lot.

**Comment by neutrinoceros** [comment]
It is really hard for me to parse what specifically should be done.
Again, the `SemiStructuredGrid` class doesn't exist (anymore, I assume), so it's not obvious what you're pointing to
>Supporting "stretched" grids requires that we allow some of our grids to utilize arrays of dx, dy, and dz.

which "some" ? and what do you mean by "our grids" ? Do you mean the `GridIndex` class (and/or its children) ?

> Right now the SemiStructuredGrid object instead utilizes the full unstructured mesh machinery.

I don't get a clear idea what "full unstructured mesh machinery" is, where it lives and why it's too general now.

> Why we want to avoid subclassing UnstructuredMesh 

wait we don't ? So is the `moab` frontend still a relevant example ?



A pretty simple question that I don't get the answer to right now is wether we need new base classes (and if so, which ones), or if we need just to extend existing ones.

**Comment by matthewturk** [comment]
I believe that this *mostly* is resolved -- via a different named subclass -- by #2998 .
