### ISSUE TITLE
Support for face-centered data

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#370]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/370

**Comment by ngoldbaum** [comment]
We now have basic support for face-centered data thanks to @atmyers
