### ISSUE TITLE
TST: "latest_deps" job is broken

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3704]
### Bug report

**Bug summary**

#3543 broke the "yt_py38_latest_deps" daily job on Jenkins https://tests.yt-project.org/job/yt_py38_latest_deps/440/console

I believe the issue is that our Python script to edit requirements on the fly isn't smart enough to deal with `python_version < '3.10'` specifications, so it creates invalid specs and breaks installation.
I don't think this script is public, but @Xarthisius linked a version of it in #3392
I'll try to come up with a patch here.

**Comment by neutrinoceros** [comment]
This regex-based version seems to work on my end. Only the `unpin` function is changed
```python
#!/usr/bin/env python
# unpin_requirements.py

from collections.abc import MutableMapping
import configparser
import io
import re

PINNED_VERSION_REGEXP = re.compile(r",?(<|<=|==)([0-9a-z]+\.?)+")

def unpin(s:str) -> str:
    return re.sub(PINNED_VERSION_REGEXP, "", s)

def unpin_mapping(m:MutableMapping, key) -> None:
    reqs = m[key].split("\n")
    m[key] = "\n".join(unpin(_) for _ in reqs)

if __name__ == "__main__":
    cp = configparser.ConfigParser()
    cp.read("setup.cfg")
    unpin_mapping(cp["options"], "install_requires")
    for target in cp["options.extras_require"].keys():
        unpin_mapping(cp["options.extras_require"], target)

    output = io.StringIO()
    cp.write(output)
    s = output.getvalue().replace("\t", " "*4)
    s = "\n".join(_.rstrip() for _ in s.split("\n"))
    with open("setup_out.cfg", "w") as fh:
        fh.write(s)
```

**Comment by neutrinoceros** [comment]
@Xarthisius you might want to have a look at this

**Comment by Xarthisius** [comment]
Updated. It would probably make sense if we made that script a part of the main repo. Maybe put it in the `tests/` directory?

**Comment by neutrinoceros** [comment]
sure. I'll open a PR
