### ISSUE TITLE
Add support for multiple delivery locations for reason payloads

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#371]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

Currently, every time a payload is delivered, reason pops it from the stack.  We should make it possible to deliver payloads to multiple places; each viewer should get a UUID, and only when all the viewers have received a payload should it get popped from the handler.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/371

**Comment by ngoldbaum** [comment]
Reason is no longer in the codebase
