### ISSUE TITLE
develop a new frontend for PLUTO

### ISSUE THREAD

**Issue by xshaokun** [yt-project/yt#3711]
Hi folks,

As suggested by @matthewturk [here](https://mail.python.org/archives/list/yt-users@python.org/thread/CXWQYHC32GEY57YJHNL6N3WNJJFDDAS5/), this issue is opened for discussing the possibility and details of developing a new frontend for PLUTO, which is able to support not only Chombo HDF5 format but also general data format such as .vtk, .dbl and etc. I'm not sure if i'm capable to do this although i am interested. 

Referring to the [document](https://yt-project.org/doc/developing/creating_frontend.html#boostraping-a-new-frontend), unit handler, the main task is to write data reading function for the corresponding format and unit conversion function, right? Beyond those, what is needed to do?

Mention incidentally that I've been building [a package](https://github.com/xshaokun/PLUTOpy) for PLUTO which reads data through `pyPLUTO`, a python package implemented in PLUTO code. Inspiring by yt, this package could handle the conversion between physical units and code units, although not by `unyt` but `astropy.units` module. I would be glad if this is helpful for building the unit conversion function in the new frontend.

Regards,
Shaokun

**Comment by neutrinoceros** [comment]
Hi !
On my phone now, I’ll write a more detailed answer later but FYI I wrote and published a extension frontend for Idefix, whose a direct descendant of Pluto, that you can find here

https://pypi.org/project/yt-idefix/

I believe it should support with Pluto vtk already, and if not it should be easy to fix.

The biggest limitation (and the reason why it’s not already integrated in yt’s main code base) concerns grid stretching. See the README there.

**Comment by xshaokun** [comment]
> Hi ! On my phone now, I’ll write a more detailed answer later but FYI I wrote and published a extension frontend for Idefix, whose a direct descendant of Pluto, that you can find here
> 
> https://pypi.org/project/yt-idefix/
> 
> I believe it should support Pluto vtk already, and if not it should be easy to fix.
> 
> The biggest limitation (and the reason why it’s not already integrated in yt’s main code base) concerns grid stretching. See the README there.

Thanks for your extension! I did some simple tests for your extension following the guide of yt and it works for me, especially `OffAxisProjection` function I want to use! It looks like this could be used as a semi-frontend currently.

However, the unit system seems cgs in default while my outputs are in code units. Is that means I should output my data in cgs or create a unit system manually and specify it when I load data?

**Comment by neutrinoceros** [comment]
> I did some simple tests for your extension following the guide of yt and it works for me, especially OffAxisProjection function I want to use

Awesome ! glad you like it

> However, the unit system seems cgs in default while my outputs are in code units. 

Sound like you want to load as

```python
ds = yt_idefix.load("your_file.vtk", unit_system="code")
```

And if you want to pass explicit normalisation factors, this is how you do it

```python
ds = yt_idefix.load("your_file.vtk", units_override={"length_unit": "km", "time_unit": "yr"})
```


Here's the repo, is https://github.com/neutrinoceros/yt_idefix

**Comment by neutrinoceros** [comment]
@xshaokun I think at this point we can be confident in that `yt_idefix` is working for you, so I'll just close this as there's probably nothing to do on this side at the moment. Thanks again for starting this discussion !
