### ISSUE TITLE
Reason does not know about fields initially

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#372]
Originally reported by: **John Wise (Bitbucket: [jwise77](https://bitbucket.org/jwise77), GitHub: [jwise77](https://github.com/jwise77))**

----------------------------------------

When a dataset is loaded into reason with pf = load(...), it does not know about the available fields until the hierarchy is loaded.  This can be worked around by executing pf.h and then making a slice or projection.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/372

**Comment by ngoldbaum** [comment]
Reason is no longer in the codebase
