### ISSUE TITLE
BUG: 237 new failures on Jenkins

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3728]
### Bug report

**Bug summary**

Today's daily job on Jenkins showed up with 237 (new) failures https://tests.yt-project.org/job/yt_py38_latest_deps/459/
(For reference, the recurring ones are known to originate from sympy https://github.com/sympy/sympy/issues/22241)

Interestingly, the same failures started appearing on normal jobs too, earlier yesterday, see for instance https://tests.yt-project.org/job/yt_py38_git/4423/

I have attempted to identify what could have changed upstream in a 24h window but didn't find any such diff in the job logs.

The errors we get are, I think, all similar to this one:
<img width="1089" alt="Screenshot 2021-12-19 at 12 13 41" src="https://user-images.githubusercontent.com/14075922/146672898-9363dbdd-e28b-49a1-ae79-ab48fcd97af3.png">

that is, they are all image comparison tests, and what's changed is the font.
I vaguely remember seeing such a problem in the recent past, which was caused by a font file being corrupted of renamed for some reason on the test server, so I suspect this is what's happening here too since there doesn't seem to be any suspect upstream (as far as I can tell).

@Xarthisius, could you have a look please ?

**Comment by matthewturk** [comment]
This seems like as good a time as any to mention that I think we should move away from this resting on @Xarthisius .  I think we need to have a strategy session about how we can properly move these tests away, and how we can improve the testing infrastructure as a whole.

I mean, it's Sunday at 5:45 AM in Champaign!  @neutrinoceros I know that you want this to be accomplished, but we can't put this on Kacper all the time, and so you and I should discuss how to move this weight from him.

**Comment by neutrinoceros** [comment]
Strongly agreed.

**Comment by neutrinoceros** [comment]
Looks like the issue was fixed in daily jobs, however the situation has aggravated in PR-triggered jobs
