### ISSUE TITLE
Cannot create phase plot with Ramses output

### ISSUE THREAD

**Issue by ttepperg** [yt-project/yt#3753]
Hi,

When trying to create a simple phase plot from a Ramses output (following the example given in the docs):

my_sphere = ds.sphere("c", (50, "kpc"))
plot = yt.PhasePlot(
    my_sphere, ("gas", "density"), ("gas", "temperature"), [("gas", "mass")], weight_field=None
)
plot.save()

I get the following error:

yt.utilities.exceptions.YTFieldNotFound: Could not find field '('gas_tracer', ('gas', 'mass'))' in info_00001.

I'm using the most recent (2022) Ramses version and and YT 3.6.1

Cheers

Thor

**Comment by ttepperg** [comment]
Hi,

I updated to v 4.0.1 and the issue disappeared.

Cheers

Thor.

**Comment by neutrinoceros** [comment]
Glad the newest version fixed your problem !
