### ISSUE TITLE
pytest is now a hidden hard dependency

### ISSUE THREAD

**Issue by brittonsmith** [yt-project/yt#3771]
### Bug report

We now import `pytest` directly in `yt/testing.py`, but `pytest` is not yet listed as a hard dependency. This will cause a `ModuleNotFoundError` to be raised after installing yt until you install pytest manually.

I'm opening an issue rather than a PR because I don't know whether people would prefer to put the `pytest` import in a try block or make it a dependency.

**Comment by cphyc** [comment]
And is `yt/testing.py` imported anywhere in the codebase (outside the tests themselves)?

**Comment by neutrinoceros** [comment]
> And is yt/testing.py imported anywhere in the codebase (outside the tests themselves)?

I didn't think so... but here's  a minimal reproducer
```
cd /tmp/
python3.9 -m venv .env && source .env/bin/activate
pip install --upgrade pip
pip install git+https://github.com/yt-project/yt.git
python -c "import yt"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/yt_test/.env/lib/python3.9/site-packages/yt/__init__.py", line 92, in <module>
    from yt.testing import run_nose
  File "/private/tmp/yt_test/.env/lib/python3.9/site-packages/yt/testing.py", line 15, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

I would argue that the _ideal_ solution would be to not import from yt.testing in yt.__init__
The only cost is that the `run_nose` function wouldn't be available from the `yt` namespace, which I hope is acceptable to everyone given that we have to get rid of nose eventually anyway.

**Comment by neutrinoceros** [comment]
Also: I checked that this only affects the dev branch, it hasn't been shipped in any release so far
