### ISSUE TITLE
BUG: loading from urls is (very likely) broken

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3774]
### Bug report

**Bug summary**
This came up when I opened #3772, I'll just edit the relevant bits from there:

So, supposedly, `yt.load` supports loading from a url, as the following line suggests
https://github.com/yt-project/yt/blob/636057b11db35215432bcb1132fd9d44381ad07d/yt/loaders.py#L93

However, I don't know of a frontend where it's actually exercised.
Moreover I think the patch #3525 actually breaks this functionality (which didn't pop up in tests), but hasn't landed in a release yet.

Is there anywhere in code base that we actually implement loading anything from urls ? if so, then there's a bug to patch for yt 4.1, otherwise we could just simplify `yt.load`.

**Comment by matthewturk** [comment]
It should be; the SDF frontend utilized it. While it may not work now, I do not want to deliberately remove it any further.
