### ISSUE TITLE
Commit a8b395e prevents dark matter-only Enzo simulations from being analyzed

### ISSUE THREAD

**Issue by anchwr** [yt-project/yt#3809]
### Bug report

**Bug summary**

As of commit a8b395e1833381d1647d1b91c7ecda99a09ec75b, yt appears to fail with dark matter-only Enzo simulations as soon as frontends.enzo.fields.setup_energy_field() is called (e.g., via ds.all_data() or ds.add_particle_filter()). These simulations do not have an explicit energy field, so an error is triggered at [line 278 of frontends/enzo/fields.py](https://github.com/yt-project/yt/blob/main/yt/frontends/enzo/fields.py#L278), since ('enzo', None) is not a valid field name.

**Code for reproduction**

```python
import yt
ds = yt.load('DD0064/DD0064')
ads = ds.all_data()
```
Sample dataset that generates error at: http://use.yt/upload/35be3369

**Actual outcome**

```
Traceback (most recent call last):
  File "Research/Outputs/TestSphere.py", line 15, in <module>
    ads = ds.all_data()
  File "/Users/anna/yt/yt/data_objects/static_output.py", line 1052, in all_data
    self.index
  File "/Users/anna/yt/yt/data_objects/static_output.py", line 546, in index
    self.create_field_info()
  File "/Users/anna/yt/yt/data_objects/static_output.py", line 592, in create_field_info
    self.field_info.setup_fluid_fields()
  File "/Users/anna/yt/yt/frontends/enzo/fields.py", line 189, in setup_fluid_fields
    self.setup_energy_field()
  File "/Users/anna/yt/yt/frontends/enzo/fields.py", line 280, in setup_energy_field
    ("enzo", te_name), sampling_type="cell", units="code_velocity**2"
  File "/Users/anna/yt/yt/fields/field_info_container.py", line 425, in add_output_field
    self[name] = DerivedField(name, sampling_type, NullFunc, **kwargs)
  File "/Users/anna/yt/yt/fields/derived_field.py", line 134, in __init__
    validate_field_key(name)
  File "/Users/anna/yt/yt/funcs.py", line 1206, in validate_field_key
    "Expected a 2-tuple of strings formatted as\n"
TypeError: Expected a 2-tuple of strings formatted as
(field or particle type, field name)
Received invalid field key: ('enzo', None), with type <class 'tuple'>
```

**Expected outcome**

This shouldn't usually produce any output. As far as I can tell, it works on commits prior to a8b395e1833381d1647d1b91c7ecda99a09ec75b

**Version Information**

  * Operating System: macOS 10.15.7
  * Python Version: 3.7.7
  * yt version: 4.1.dev0
  * Other Libraries (if applicable): N/A

yt installed from source

**Comment by neutrinoceros** [comment]
Thank you for reporting this regression with such care, pinning the exact commit the problem bisects to and providing a usable dataset for reproduction. I assume for now that this reveals a bug in the Enzo frontend, so I'm going to triage it as such. I'll take a deeper look soon.

**Comment by anchwr** [comment]
Awesome! Thanks!

**Comment by matthewturk** [comment]
@anchwr thank you so much for reporting!

I think a fix for this should go into 4.0.3.  @brittonsmith I wanted to CC you on this just to make sure you saw it.

**Comment by neutrinoceros** [comment]
@matthewturk Unless I'm mistaken this bug only appeared on the main branch so far (#3433) so there's no need to backport it to 4.0.x

**Comment by matthewturk** [comment]
@neutrinoceros good catch
