### ISSUE TITLE
Convert to using tomli

### ISSUE THREAD

**Issue by henryiii** [yt-project/yt#3830]
The library currently depends on the dead "toml" library, instead of the "tomli" library (which was just accepted into the stdlib as "tomllib" for Python 3.11. It should be a really easy swap; it's almost the same API as toml, it just expects binary files instead of unicode ones if using `toml{i,lib}.load`. `loads` is the same. Writing is a separate library.

Working on pyodide at https://github.com/pyodide/pyodide/pull/2234 and don't want to have to port a dead library.

**Comment by matthewturk** [comment]
@henryiii Thanks for the issue -- and I agree, this is the right thing to do.  Do you happen to know if there is an idiomatic way to handle it for existing installations that may already have `toml` but not `tomli`?

**Comment by henryiii** [comment]
Sadly, yes: https://github.com/pypa/build/blob/5d711b4cb24b2d9ed0884a5a9ba54252440899a2/src/build/__init__.py#L44-L49

Though otherwise the PyPA completely moved over to tomli for pip, setuptools, etc (except for build, we needed to keep it as bootstrappable as possible so that abomination is still in there).

Do you happen know what non-optional requirements in install_requires are actually optional?

**Comment by henryiii** [comment]
(That's going to be extra fun once it has a `if sys.version_info < (3, 11)` toggle around a `tomli`/`tomllib` choice - waiting for a `tomllib` implementation to be available, though)

**Comment by neutrinoceros** [comment]
> Do you happen know what non-optional requirements in install_requires are actually optional?

@henryiii I was about to say "none", but after a more carful check I think `pyyaml` is actually optional. I believe it's the only one though.

I was aware of PEP 680 being accepted and the `toml` package being unsupported, but there was no clear benefit from migrating early. Now that there is, I guess this should be done in time for our next release.

> Do you happen to know if there is an idiomatic way to handle it for existing installations that may already have toml but not tomli?

I'm curious what's the gain we expect here ? Why not just move from a hard dependency to another ?

**Comment by henryiii** [comment]
I'd highly recommend the hard dependency.

There's not much here:
https://github.com/pyodide/pyodide/blob/ab08812ca564738966cd57024f0931c065a461e5/packages/yt/meta.yaml#L14-L17

Ahh, it looks like a lot got added for 4.0. And 3.x doesn't support matplotlib 3.5. Okay. :/

**Comment by henryiii** [comment]
Is IPYthon actually _required_?

**Comment by neutrinoceros** [comment]
> Is IPython actually required?

I thought it was, but I don't see it being imported at the top-level in any module actually.
