### ISSUE TITLE
OWLS electron number density field returns no value

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#3838]
I randomly stumbled upon this piece of code which seems to be missing a return statement. Is that on purpose?

https://github.com/yt-project/yt/blob/35ce91c32bc8aa43262292b001953fc0bc6f3ff2/yt/frontends/owls/fields.py#L201-L204

**Comment by matthewturk** [comment]
Wow, yeah.  Good point!

I don't remember who had taken on the OWLS frontend, but I think @chummels may have done some work with it (perhaps via EAGLE?) some bit ago.

**Comment by jzuhone** [comment]
I think I touched this last, will submit a fix.
