### ISSUE TITLE
DOC: private methods used in cookbook recipe

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3845]
### Bug report

**Bug summary**

in #2567, `doc/source/cookbook/render_two_fields_tf.py` was added to the cookbook
On the two following lines, the private method `_get_field_info` is used
https://github.com/yt-project/yt/blob/ef08989d8222e7172751d17009959102db05dd20/doc/source/cookbook/render_two_fields_tf.py#L15
https://github.com/yt-project/yt/blob/ef08989d8222e7172751d17009959102db05dd20/doc/source/cookbook/render_two_fields_tf.py#L30

This should be refactored to avoid showing private elements
@zingale, do you know how we could do this ?

**Comment by zingale** [comment]
they might not actually be needed, since log might be the default.  But it is common to want to change the log-ness for volume renders, so if there isn't a public-API, we definitely will want to show how a user can do it in any case.
