### ISSUE TITLE
BUG: plot.hide_axes(show_frame=True) is broken

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#3852]
### Bug report

**Bug summary**
The `show_frame` argument has no effect
This is visible in the second-to-last example in this docs section
https://yt-project.org/doc/visualizing/plots.html#colormaps

**Comment by neutrinoceros** [comment]
Oh, so it's not that it doesn't work, it's really just that the explanation is superfluous and confusing. I'll fix this in #3849

**Comment by chummels** [comment]
I'm looking at the docs example you've linked, and there is no reference to a `show_frame` kwarg in `plot.hide_axes`, but there is a `draw_frame` kwarg.  Is that what you mean?  Also, according to that documentation, it *does* seem to be working, as it enables the use of the `set_background_color()`.  So I'm confused how this is a bug at all.  But maybe I'm misunderstanding what you're describing in this bug report.

**Comment by neutrinoceros** [comment]
> there is a draw_frame kwarg. Is that what you mean?

indeed, my mistake.


>  it does seem to be working, as it enables the use of the set_background_color().

You're right. I guess I was confused by the name and expected some frame to show around the figure, not the background itself. Even reading it now I find this documentation confusing :/

**Comment by neutrinoceros** [comment]
I tried to retro-engineer my own thought process and couldn't make sense of this. I also linked #3849 here but I don't see any difference in behaviour between the main branch and that one, so I'm going to say "case closed" here.

Unrelated but there's also some good news for this particular example in the docs, the latest build (yt 4.0.2) produced this image 
![Screenshot 2022-08-08 at 15 11 53](https://user-images.githubusercontent.com/14075922/183425918-bd7a1b9b-e973-40be-95c2-fd1ef6aeabb3.png)

And now (main branch) we're getting this
![1_branch](https://user-images.githubusercontent.com/14075922/183426203-c352ae51-84f5-4aa7-b0e1-650c254db307.png)

I wouldn't be surprised that this was fixed with #4050 

anyway, closing this
