### ISSUE TITLE
New axis manipulations (swap, flip) can lead to unexpected result

### ISSUE THREAD

**Issue by chrishavlin** [yt-project/yt#3890]
Starting this issue to track some consequences of #3640.

#3640 Introduces the plot callbacks `swap_axes`, `flip_horizontal` and `flip_vertical` to manipulate figure axes. To swap axes, the implementation relies on manually exchanging the x and y arguments to the underlying matplotlib plot calls, which enforces an order of operations that can be confusing when using in combination with the flip axes callbacks, especially while plotting interactively. 

Prior to the next release it would be good to decide if the current behavior is sufficient with clear documentation or if there is a way to add more intuitive behavior. 

## the "problem" 

Because `swap_axes` relies on exchanging  the x and y arguments to plot calls, a `swap_axes` callback is **always** applied before any axis flip commands, meaning the following: 

```python
slc = yt.SlicePlot(...)
slc.swap_axes()
slc.flip_horizontal()
```
and
```python
slc = yt.SlicePlot(...)
slc.flip_horizontal()
slc.swap_axes()
```

both resolve to swap_axes then flip_horizontal, resulting in the same image. 

I've found this to be initially counterintuitive when testing things out interactively and looking at images after each step -- one might expect the following

```python
slc = yt.SlicePlot(...)
slc.flip_horizontal()
slc.show()
```

```
# new cell
slc.swap_axes()
slc.show()
```
to first first flip the x axis and then exchange the flipped-x and the y, but it will actually add an initial swap of the x-y and the flip the image's new x axis. After playing around with this, I got used to remember that these callbacks apply to the image axes and not the dataset coordinates, but I initially thought something was wrong...

## some possible solutions

So the above behavior makes sense from an implementation perspective, but  maybe there are ways that this could be made more intuitive for a user. Some ideas:

1. Simply make the new documentation very clear that these callbacks apply to image axes and not dataset coordinates and that they always resolve to swap then flip. 
2. Track the order in which callbacks are added and adjust appropriately -- i.e., if `slc.flip_horizontal` is followed by `slc.swap_axes`, internally resolve to `slc.swap_axes` and `slc.flip_vertical`. This has potential for much confusion .... 
3. Introduce an new axis transformation callback that is tied to the dataset's coordinate, e.g., `slc.flip_axis('x')` , which would internally call `flip_horizontal` or `flip_vertical` after figuring out where the dataset's x coordinate ends up. 
4. Similar to 3, but instead re-write `flip_horizontal` and `flip_vertical` to accept dataset coordinate arguments.

**Comment by neutrinoceros** [comment]
Thanks for opening this !

Since the original PR's discussion is enormous, I'll repeat a bit of context here for posterity; I've asked Chris to open this discussion in order to make sure it would be addressed before the feature is release without blocking the initial PR for longer.  I'll try to give an educated opinion on the matter soon.

**Comment by neutrinoceros** [comment]
I can't convince myself that there's a definite most "intuitive" alternative that I can confidently come up with by myself.
So, I'm thinking maybe we should make a small poll and circulate it to the users mailing list. WDYT ?

**Comment by chrishavlin** [comment]
The more I think about this, the more I'm inclined to vote for a variation of option 3 above: having a single `slc.flip_axis(coord= ...)`  method, where `coord` could be set to any of the dateset coordinates being used in the plot or to `"horizontal"` or `"vertical"` to refer to the image axes. There's still potential for some confusion, and we'd need more checks (e.g., catching cases where `flip_axis` is called multiple times with conflicting arguments), but I think being able to specify the axis to flip by the dataset coordinate name  would make the interface more intuitive.  

But hopefully we'll get some opinions after the PR gets merged and folks have a chance to test out the current behavior.

**Comment by neutrinoceros** [comment]
Another point I should have raised is that in non-Cartesian geometries, there isn't always a simple and intuitive label attached to an axis as x, y and z, so I don't see how `flip_axis(coord=...)` would work outside the happy path of Cartesian geometry.

**Comment by chrishavlin** [comment]
Reminder: as part of resolving this, it'd be good to make the example docs use a case that is less symmetric. If we decide to just keep the current behavior, I'll open a dedicated PR for that. But if we end up changing the behavior, we'll need to update the docs anyway so I'll do it then.

**Comment by chrishavlin** [comment]
Given the lack of opinions on this, I'm inclined to let the current version go into the upcoming release without modification and see if we get feedback as folks start to use the new feature. Sound alright?

I will work on a docs-only PR to make the example less symmetric.

**Comment by neutrinoceros** [comment]
Agreed. It's probably the best way to go now.

**Comment by matthewturk** [comment]
I think this is the best option.
