### ISSUE TITLE
The legend cancels the logarithmic form

### ISSUE THREAD

**Issue by czc-zju** [yt-project/yt#3950]
How can I make the legend not follow the logarithmic form?
![0](https://user-images.githubusercontent.com/81547457/170878752-95e1a0fd-d47f-4467-abe5-91b1eb23d0fd.png)

**Comment by neutrinoceros** [comment]
@czc-zju use the `set_log` method

**Comment by neutrinoceros** [comment]
https://yt-project.org/doc/reference/api/yt.visualization.plot_container.html?highlight=set_log#yt.visualization.plot_container.PlotContainer.set_log

**Comment by czc-zju** [comment]
Fantastic!!!
I have tried it and it works perfectly!!!
thanks a lot.
