### ISSUE TITLE
Halo Analysis Not Working

### ISSUE THREAD

**Issue by ngountanis** [yt-project/yt#3978]
I used the HOP halo finder to create a Halo Catalog. Now I want to analyze the catalog, but none of the example code is working. For example, when I do help(HaloCatalog), it gives me a bunch of example code. I copied and paste them into my Jupyter notebook, changing the file to match my file. When I do that, though,I get errors. 

def _mass(halo):
    # assume some entry "particle_mass" exists in the quantities dict
    return halo.quantities["particle_mass"]

add_quantity("mass", _mass)

# add it to the halo catalog action list
hc.add_quantity("mass")

Just gives me 

NameError                                 Traceback (most recent call last)
<ipython-input-3-33c7d397d4d8> in <module>
      3     return halo.quantities["particle_mass"]
      4 
----> 5 add_quantity("mass", _mass)
      6 
      7 # add it to the halo catalog action list

NameError: name 'add_quantity' is not defined

I don't know what to do. I updated everything, but the example code doesn't work.

**Comment by neutrinoceros** [comment]
where are you copying examples from ? This sounds a lot like you're looking out of date documentation

**Comment by brittonsmith** [comment]
Yes, this looks like an older version of the `HaloCatalog`. Can you try following this documentation: https://yt-astro-analysis.readthedocs.io/en/latest/

**Comment by neutrinoceros** [comment]
Gonna close this since OP is not responding. Please reopen if necessary
