### ISSUE TITLE
Some geographic mapping issues

### ISSUE THREAD

**Issue by chrishavlin** [yt-project/yt#4039]
Starting this issue to document some issues with yt's geographic plotting functionality.

### Test data and environment

Links to the data used below, both are seismic models (internal_geographic in yt jargon) the first is a global model (longitude from -180 to 180, latitude -90 to 90), the second covers only the western US. 
- https://ds.iris.edu/files/products/emc/emc-files/GYPSUM_percent.nc 
- https://ds.iris.edu/files/products/emc/emc-files/wUS-SH-2010_percent.nc 

And here's a function for loading that data in as a internal_geographic uniform grid datasets: https://gist.github.com/chrishavlin/aaf887a5f36eb5f6a7f7ae45f936c2fa

The following used a conda environment with python 3.9.10, cartopy 0.20.3 , geos 3.11.0 , proj 9.0.1 yt 4.1.dev0 on unbuntu 18.04.

### Problem 1: extents

I know there's been some issues here previously (#3705, #3708), but the current state does not do so well... 

The default behavior for a global dataset is good: 

```python
ds = get_internal_IRIS("internal_geographic_global")
c = ds.domain_center
c[0] = 100
p = yt.SlicePlot(ds,'depth','dvs', center=c)
p.set_mpl_projection('Robinson')
p.set_log('dvs',False)
p.set_zlim('dvs',-8, 8)
p.set_cmap('dvs','magma_r')

p._setup_plots()
carto_ax = p.plots['dvs'].axes
carto_ax.add_feature(cfeature.NaturalEarthFeature(
        'cultural', 'admin_0_countries', '10m',
        edgecolor='black', facecolor='none'))
p.show()
```
![Screenshot from 2022-07-28 15-26-40](https://user-images.githubusercontent.com/22038879/181631023-6e495299-7d94-4d10-a508-776e3f975d3e.png)

But any subsets are **VERY** wrong: 

```python
c = ds.domain_center
c[0] = 100
p = yt.SlicePlot(ds,'depth','dvs', center=c, width=[100, 60], origin="native")
p.set_log('dvs',False)
p.set_zlim('dvs',-8, 8)
p.set_cmap('dvs','magma_r')
p._setup_plots()
carto_ax = p.plots['dvs'].axes
carto_ax.add_feature(cfeature.NaturalEarthFeature(
        'cultural', 'admin_0_countries', '10m',
        edgecolor='black', facecolor='none'))
p.show()
```
![Screenshot from 2022-07-28 15-29-02](https://user-images.githubusercontent.com/22038879/181631409-a539b3a0-d149-4645-a1e0-7b230ad19a7e.png)

This happens because the extent gets set to None for cartopy GeoAxes (happens [here](https://github.com/yt-project/yt/blob/93e7c6e9974b5d7174992787a1b9b8c65048941e/yt/visualization/base_plot_types.py#L305)) and so the image slice gets stretched to fill the globe. Commenting out that `extent = None` line results in a correct image:

![Screenshot from 2022-07-28 16-00-44](https://user-images.githubusercontent.com/22038879/181636657-554ffcc1-75ba-47bd-9b74-b0d6049c64b8.png)

Note that the GeoAxes extent is still the whole globe and can be zoomed in with a call the axis' `set_extent` method:

```
carto_ax.set_extent((-50, 50, -30, 30))
p.show()
```

![Screenshot from 2022-07-28 16-03-43](https://user-images.githubusercontent.com/22038879/181637106-a86fe381-7f10-4bc6-8266-5e88a737f030.png)

 
**For a dataset that does not cover the whole globe, it immediately gets stretched**:

```python
ds = get_internal_IRIS("internal_geographic_partial")

c = ds.domain_center
c[0] = 100
p = yt.SlicePlot(ds,'depth','dvs', center=c)
p.set_mpl_projection('Robinson')
p.set_log('dvs',False)
p.set_zlim('dvs',-8, 8)
p.set_cmap('dvs','magma_r')

p._setup_plots()
carto_ax = p.plots['dvs'].axes
carto_ax.add_feature(cfeature.NaturalEarthFeature(
        'cultural', 'admin_0_countries', '10m',
        edgecolor='black', facecolor='none'))
p.show()
```
![Screenshot from 2022-07-28 15-34-53](https://user-images.githubusercontent.com/22038879/181632393-b6cbcaa7-d1e7-4384-957e-a59ddd5f67ce.png)

Again commenting out that `extent=None` line, it gets correctly placed in the globe:

![Screenshot from 2022-07-28 15-35-09](https://user-images.githubusercontent.com/22038879/181632491-49d1e63a-1e6b-4a79-858f-192517c5ab18.png)

Given the cartopy incompatibility issues (#3705), simply removing the `extents = None` is obviously not an option. It would be possible only set `extents=None` when the extent covers the globe, but I'll have to check if that will expose previous issues... 

### Problem 2: rotating a view 

This is likely related, but worth mentioning separately: rotating the view is not straightforward. For reference, here's the default plot for the global data again:

![Screenshot from 2022-07-28 15-37-49](https://user-images.githubusercontent.com/22038879/181632891-b9c4dc16-500b-4df7-b6bd-d8ddfdbf555d.png)

Trying to rotate the view with yt's `center` argument does rotate the selection correctly but since this doesn't register anything with the GeoAxes, subsequent plots do not respect the rotation: 

```python
c = ds.domain_center
c[0] = 100
c[2] = 50
p = yt.SlicePlot(ds,'depth','dvs', center=c)
p.set_log('dvs',False)
p.set_zlim('dvs',-8, 8)
p.set_cmap('dvs','magma_r')

p._setup_plots()
carto_ax = p.plots['dvs'].axes
carto_ax.add_feature(cfeature.NaturalEarthFeature(
        'cultural', 'admin_0_countries', '10m',
        edgecolor='black', facecolor='none'))
p.show()
```

![Screenshot from 2022-07-28 15-39-06](https://user-images.githubusercontent.com/22038879/181633112-942e2b37-c711-4567-a5d9-6ef688dc770c.png)

If you're aware of this behavior, you can avoid it by adjusting the projection instead of the center argument:

```python
c = ds.domain_center
c[0] = 100
p = yt.SlicePlot(ds,'depth','dvs', center=c)
p.set_mpl_projection(('Mollweide', (), {'central_longitude': 50}))
p.set_log('dvs',False)
p.set_zlim('dvs',-8, 8)
p.set_cmap('dvs','magma_r')

p._setup_plots()
carto_ax = p.plots['dvs'].axes
carto_ax.add_feature(cfeature.NaturalEarthFeature(
        'cultural', 'admin_0_countries', '10m',
        edgecolor='black', facecolor='none'))
p.show()
```

![Screenshot from 2022-07-28 15-40-16](https://user-images.githubusercontent.com/22038879/181633301-8a495238-957a-4053-be0a-23aa9f302340.png)

But it'd be nice if the default projection takes into account the SlicePlot center argument.

**Comment by neutrinoceros** [comment]
> Given the cartopy incompatibility issues (https://github.com/yt-project/yt/issues/3705), simply removing the extents = None is obviously not an option.

I wouldn't be so sure actually. We have very limited venue to test integration with cartopy (at the moment we only test it on windows + conda) because it's so hard to setup, and I don't think we do _any_ kind of automated image testing for it, which might explain how I got it so bad when I wrote this line. Maybe this line could be conditional (depending on cartopy's version), or maybe we could just clean it up and only claim support with the latest version of cartopy (which is the only one we test for at any point anyway). Anyway my point is: don't treat this line as sacred. I may only have been smashing my keyboard until CI got green again.

And thank you very much for all the work you've done to report these problem !

**Comment by matthewturk** [comment]
I'm not totally sure that I understand -- if I am reading it right, the problem with having it *not* call `set_extent` at all was for subsets of the globe, right?  But now that seems to work?

And if I am understanding, I think that if we have a minimum cartopy version set, we should just ... be OK?  So maybe just avoiding calling `set_extent` is the solution?  Here, I find that removing the line works for both full and subset with no hangs.

**Comment by chrishavlin** [comment]
Update from some discussion between me and Matt -- we decided that we probably **do** want to call `set_extent`. 

I just pushed up a draft ( #4040 ) that only calls it if the plot is not a global plot (within the tolerance of the transform). I think that might do a good job... going to still look into potentially setting a `central_longitude` for the projection when possible (and if feasible).
