### ISSUE TITLE
BLD: Future incompatibility with Cython 3.1

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4044]
### Bug report

**Bug summary**

Building yt's Cython extensions with Cython 3.0.0a10 revealed that some modules are currently relying on deprecated API, as for instance

```
warning: yt/utilities/lib/image_samplers.pxd:18:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
```

Namely, we currently use `IF` and `DEF` here and there, which are going away at some point in a future version of Cython
(see https://github.com/cython/cython/issues/4310)
I estimate that we have 16 occurrences of `DEF` and 2 `IF`, so I'm hopeful that refactoring all of them is feasible

**Comment by neutrinoceros** [comment]
I was able to shrink the number of such compilation warnings in #4043 from >100 to about 10.

**Comment by neutrinoceros** [comment]
There's only one usage of `IF/ELSE` that I don't know how to refactor, namely

https://github.com/yt-project/yt/blob/93e7c6e9974b5d7174992787a1b9b8c65048941e/yt/utilities/lib/ewah_bool_array.pxd#L94-L97


It corresponds exactly to the following commit https://github.com/yt-project/yt/commit/bd1fb35fe29555979aec6fff1701b8792df0f827

I asked the Cython help mailing list about it and so far this is the answer I got

>I'd probably just replace this with
>
>     ctypedef uint32_t ewah_word_type
>
>I can't really see a difference between these two cases here.

@jzuhone, do you remember this and can you explain what problem this solved ? Do you know if it's still relevant ?

**Comment by matthewturk** [comment]
I remember this being extremely annoying to fix, but I can't remember why.

**Comment by neutrinoceros** [comment]
This is still relevant after #4575 is merged, however this is an incompatibility with Cython 3.1 at the earliest.
