### ISSUE TITLE
REG: orion2 .sink files are not being read

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4078]
### Bug report

**Bug summary**

@drannarosen reported on Slack that the dev version of yt doesn't currently parses Orion2 datasets correctly, and a lot of derived fields are not being read at all.

**Code for reproduction**

I was able to reproduce the problem using data @drannarosen shared with me. The data sample is comprised of three files
`data.0125.hdf5`, `data.0125.sink` and `orion2.ini`

```python
import yt

def test_orion2():
    ds = yt.load("data.0125.hdf5")
    assert ('io', 'particle_angmomen_x') in ds.field_list
```

**Actual outcome**
The test breaks on the main branch but passes on yt 4.0.5
I was able to bisect the regression to #3615
I'll inspect this a bit further. Worst case scenario I may just propose we revert that PR.

**Comment by neutrinoceros** [comment]
reverting doesn't work for this patch (too old and too big, at least one line was further edited since it was merged), so we have to find an actual fix.
for information @cphyc

**Comment by neutrinoceros** [comment]
@drannarosen would you agree to share your example dataset with more than just me and post download links here too ?

**Comment by drannarosen** [comment]
@neutrinoceros, yes please feel free to share it for troubleshooting.
