### ISSUE TITLE
Resource usage for gradient computation

### ISSUE THREAD

**Issue by mameehan5** [yt-project/yt#4096]
### Bug report

**Bug summary**

The gradient computation using `SlicePlot` (as an example) seems to use more computational resources than required. This can be seen when you compare the duration of the computation and memory consumption with two drastically different window sizes. 

**Code for reproduction**

The location of the data provided in this script is provided #4083 . 

```python
import yt

def big_image():
	ds = yt.load('./data/plt144000', unit_system="mks")
	ds.add_gradient_fields(('boxlib','x_velocity'))
	sz = yt.SlicePlot(ds,'z',('boxlib','x_velocity_gradient_x'), origin="native", center=(0.0,0.05,0.0), width=0.1)
	sz.set_log(('boxlib','x_velocity_gradient_x'), False)
	sz.save(name='./memory_images/big_grad.png')

def small_image():
	ds = yt.load('./data/plt144000', unit_system="mks")
	ds.add_gradient_fields(('boxlib','x_velocity'))
	sz = yt.SlicePlot(ds,'z',('boxlib','x_velocity_gradient_x'), origin="native", center=(0.0,0.005,0.0), width=0.01)
	sz.set_log(('boxlib','x_velocity_gradient_x'), False)
	sz.save(name='./memory_images/small_grad.png')

if __name__ == '__main__':
	big_image()
	small_image()
```

**Actual outcome**

I ran the above script using `mprof run python yt_memory.py` to track memory. The following image is outputted. 

![grad_memory](https://user-images.githubusercontent.com/36512136/186505806-5a648136-e996-4232-b603-2256fd755443.png)

Note that this behavior is different than non-gradient fields. For example, replacing `x_velocity_gradient_x` with `x_velocity` yields the following trace. 

![nongrad_memory](https://user-images.githubusercontent.com/36512136/186506249-9d4aa8d7-483b-48bd-b3a8-6ad35c72344c.png)

**Expected outcome**

Since the interrogation window is much smaller with the second `SlicePlot`, I would have expected the computation time to also take significantly less time, as it does with the non-gradient field. I also might have expected the memory to be less for a smaller window. 

Additionally, my original motivation for posting this issue was actually related to memory consumption because as my datasets become large (say 100 GB per plot file), I simply cannot even compute a gradient field using `ds.r` over a small window of the domain, even with a supercomputer, hence why I used a memory plot here. This could possibly be related to #3958 .

**Version Information**
  * Operating System: macOS catalina
  * Python Version: 3.7.7
  * yt version: 4.0.4

Everything was installed via conda.

**Comment by neutrinoceros** [comment]
Hi Mike,
it looks to me that you may have ran your benchmark only on your branch #4083, because it crashes on the main branch if I don't add `ds.force_periodicity()`.
I also don't see the same behaviour on the main branch, if I just take the big image example:
![Figure_1](https://user-images.githubusercontent.com/14075922/186611201-26a5fe29-ed7b-4338-8b49-d03c0935f738.png)

there's indeed a peak near the end of the script, and it _does_ take a while, but the second long episode we see on your plot seems to happen only on your branch.

In order to get more refined traces, I suggest using https://github.com/bloomberg/memray

If you're able to improve perf on your branch _while_ fixing the periodicity issue, that'd be fantastic, but for now I'd suggest focusing on *not degrading* perfs too much (although I think it's acceptable to get worse perfs to make more reliable results, but only to an extent)

**Comment by neutrinoceros** [comment]
I ran it again on your branch and get this:
![Figure_1](https://user-images.githubusercontent.com/14075922/186614743-ab372159-f191-4d39-a978-9ac94fc5777b.png)
So the behaviour is qualitatively the same on my computer, but it takes a little longer on your branch (within acceptable limits).
Now I would just like to make sure that this issue is about the behaviour of the main branch, otherwise we should move the discussion to your PR

**Comment by neutrinoceros** [comment]
I missed that you reported the problem as seen on yt 4.0.4... so I ran again (with 4.0.5) and I get very similar results as what I get on the main branch. Sorry about this back and forth.

**Comment by mameehan5** [comment]
@neutrinoceros Thanks for looking into this! First, I unfortunately was not able to get memray working on my computer with the error: `error: command '/usr/bin/gcc' failed with exit code 1`. Once I get it installed, I will report that trace here. 

Second, yes, I feel very silly accidentally running it on my branch! I updated the original code above to work with the main, still 4.0.4.

Third, to be clear, the issue isn't that the peak at the end of the graphs that you plotted; it is the fact that the big image takes about as long as the small image to produce since there should be less computational demand on making the gradient field of the smaller region (e.g., less ghost zones to generate, etc.). 

I wrapped the code above now with some simple time measurements. This is not robust, but just to get a sense of what is going on. For me, it takes about 60 sec for the big image and about 95 sec for the small image. If you swap the order of producing big and small, the small takes around 60 and big about 90. Nonetheless, they are roughly the same. 

Anyways, I just would not have guessed that the small image needed anywhere near the amount of computation time compared to the big image. Since I don't see the same behavior in non-gradient fields, this has led me to think that there is some fixed additional underlying computation required for the gradient fields causing this, but intuitively, I would expect the computation to scale with size of region to be extracted. Hopefully that makes sense!

**Comment by neutrinoceros** [comment]
>  First, I unfortunately was not able to get memray working on my computer with the error: error: command '/usr/bin/gcc' failed with exit code 1.

Binaries are available via PyPI (using `pip`), just in case that's not what you already tried.


> Anyways, I just would not have guessed that the small image needed anywhere near the amount of computation time compared to the big image. Since I don't see the same behavior in non-gradient fields, this has led me to think that there is some fixed additional underlying computation required for the gradient fields causing this, but intuitively, I would expect the computation to scale with size of region to be extracted. Hopefully that makes sense!


I does, and I agree that it warrants careful inspection

**Comment by mameehan5** [comment]
Is it possible it has something to do with the function `_generate_spatial_fluid` : https://github.com/yt-project/yt/blob/6f2a54244a8d3313f2ab9d1ef6090f0d63d827eb/yt/data_objects/data_containers.py#L325

The reason I ask is because I checked the size of `rv` and it appears to be have a size of 1566128 for both the small and large image. This seems to be quite large and would be something that I expect to vary in size depending on the problem. But I am also not very familiar with how the code works through these sections so I could be missing something!

**Comment by neutrinoceros** [comment]
memray indicates that it's only responsible for about 5% of the allocated memory in your example. In general I would avoid taking bets without a profile.

**Comment by mameehan5** [comment]
That is fair. I was able to get it installed so let me play around with it and see what comes of it.

**Comment by jzuhone** [comment]
@mameehan5 the reason for this, I think, is that `SlicePlot` creates a slice of the entire domain at the coordinate in question. Only when it computes the fixed resolution image does it take the subset. @matthewturk should confirm this.

If you want it to only consider a portion of the domain, you can define a rectangular region as a `data_source` input to `SlicePlot`:

```
# this example assumes a domain with left edge = [0,0,0] and right  edge = [1,1,1]

le = [0.3,0,3,0.3]
re = [0.6,0.6,0.6]

box = ds.box(le, re)

slc = yt.SlicePlot(ds, "z", ("gas","density"), data_source=box)
```

**Comment by jzuhone** [comment]
And of course what I mean by "entire domain" is extending across the domain in the two dimensions defined by the slice, not the entire 3D domain.

**Comment by mameehan5** [comment]
Ah! This is very helpful and testing shows it is indeed much faster for the small window. Thank you for the help!
