### ISSUE TITLE
DOC: update docs for magnetic fields

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4113]
The following section needs some attention 
https://yt-project.org/docs/dev/analyzing/fields.html#magnetic-fields
in particular, we should evaluate if revisions are needed following #3812

**Comment by neutrinoceros** [comment]
this is the last item on the 4.1 milestone at the moment. It’s possible that it’s a pure no-op, but I don’t trust my own expertise to establish this myself. @jzuhone, I originally assigned you because you are the obvious expert on this, I hope that’s ok.

**Comment by jzuhone** [comment]
I'll do this within the next few days
