### ISSUE TITLE
Discrepancy between yt 4 and 3.6.0 `ProjectionPlot` using `GADGET` dataset

### ISSUE THREAD

**Issue by koarakawaii** [yt-project/yt#4114]
### Bug report

**Bug summary**

##### `yt-4.1.dev0` `ProjectionPlot` with `add_sph_fields` gives result different from `yt-3.6.0`, using `GADGET` dataset:
   * For  `yt-4.1.dev0`, to plot projection for the `all` particle particle type, `add_sph_fields` function is applied, to get fields `("io", "density")` and `("io", "smoothing_length")` from `("all","particle_mass")`, `("all","particle_position_x")`, `("all","position_y")` and `("all","particle_position_z")`, following the sample code [here](https://yt-project.org/doc/examining/loading_data.html#adding-smoothing-lengths-for-non-sph-particles)
   * Obviously, the outcome for  `yt-4.1.dev0` shown below in the left panel, has artificial particles, highlighted by the red circle; `ProjectionPlot` for `yt-3.6.0` has no such issue, as shown by the right panel
   <p align="center">
   <img src="https://drive.google.com/uc?export=view&id=1ZoOCI328qyniEeib4fs62sVwzb0oCocU" width="1000">
   </p>

   * We further use `arbitrary_grid` to deposit the `('deposit','all_density')` field onto the uniform grid for the same dataset, and find the result is more consistent with `yt-3.6.0`, shown below, suggesting that **`ProjectionPlot`s given by using `add_sph_fields` and `arbitrary_grid` have discrepancy**
   <p align="center">
   <img src="https://drive.google.com/uc?export=view&id=1AtOSYeOa9oud2GUhMLFOsUFTGo8Rq1PN" width="450">
   </p>

**Code for reproduction**

##### URL for `GADGET` Dataset
https://yt-project.org/data/snapshot_010.tar.gz

#####  `yt-4.1.dev0` `ProjectionPlot` with `add_sph_fields`:
```python
import yt

ds      = yt.load("./snapshot_010/snapshot_010")
ad      = ds.all_data()
pt      = "all"
fields  = ["particle_mass"] + [f"particle_position_{ax}" for ax in "xyz"]
data    = {field: ad[pt, field] for field in fields}
ds_dm   = yt.load_particles(data, data_source=ad)
ds_dm.add_sph_fields()
pz      = yt.ProjectionPlot( ds_dm, 'z', ("io", "density") )
pz.set_zlim(("io", "density"), 1e2, 2e5)
pz.annotate_title("yt-4.1.dev0")
pz.save()
```
#####  `yt-3.6.0` `ProjectionPlot` with oct-tree:
```python
import yt

ds = yt.load("./snapshot_010/snapshot_010")
pz = yt.ProjectionPlot( ds, 'z', ("deposit", "all_density") )
pz.set_zlim(("deposit", "all_density"), 1e2, 2e5)
pz.annotate_title("yt-3.6.0")
pz.save()
```

##### [Optional] `yt-4.1.dev0` `ProjectionPlot` with `arbitrary_grid`:
```python
import yt
import numpy as np

L              = 2**9
field          = [('deposit','all_density')]
ds             = yt.load( "snapshot_010/snapshot_010",index_filename="./snapshot_010/snapshot_010.index6_2.ewah" )
bbox           = np.array([ [ds.domain_left_edge[0].to("kpc"),ds.domain_right_edge[0].to("kpc")],\
                            [ds.domain_left_edge[1].to("kpc"),ds.domain_right_edge[1].to("kpc")],\
                            [ds.domain_left_edge[2].to("kpc"),ds.domain_right_edge[2].to("kpc")]])

cg             = ds.arbitrary_grid(left_edge=ds.domain_left_edge, right_edge=ds.domain_right_edge, dims=[L,L,L])
smoothed_field = cg[field[0]].to("g/cm**3")
data           = dict(deposit_density = (smoothed_field, "g/cm**3"))
# convert and use kpc as unit from now on, since after yt.load_uniform_grid, yt can never know this data is from cosmology simulation, so it does not know how to convert Mpc/h -> kpc, etc... So we just fix the unit as kpc
ds_grid        = yt.load_uniform_grid(data, smoothed_field.shape, length_unit="kpc", bbox=bbox, nprocs=16)
field_grid     = ('stream', 'deposit_density')

pz             = yt.ProjectionPlot( ds_grid, 'z', field_grid )
pz.set_zlim(field_grid, 1e2, 2e5)
pz.annotate_title("yt-4.1.dev0-artbitrary_grid_deposited")
pz.save()
```

**Version Information**

  * Operating System: CentOS Linux release 7.7.1908 (Core)
  * Python Version: `Python 3.7.4`
  * yt version: `yt-4.1.dev0`, `yt-3.6.0`

**Comment by neutrinoceros** [comment]
hi @koarakawaii, thank you for reporting this !
We also need to check the behaviour on yt 4.0.5, can you do that ?

**Comment by neutrinoceros** [comment]
I checked that the results with the dev branch and consistent with 4.0.5 and 4.0.2, so at least we know this isn't a regression.
I added the "bug" label but I am not yet certain that this is actually a bug: the block-based viz method shipped in yt 3 is known to wash out small scale features, so it seems to me that the most likely explanation is that yt 3 is the one that produces artefacts, not yt 4. That said we need someone more expert than me on the topic.

**Comment by koarakawaii** [comment]
> We also need to check the behaviour on yt 4.0.5, can you do that ?
@neutrinoceros 
Sorry for the late reply😢 Do I still need to check `yt-4.0.5` now~? BTW, I am just curious that using `arbitrary_grid` seems to not have the artefact as well, so I am a little bit confused that why `yt-4` cannot give consistent result between `add_sph_fields` and `arbitrary_grid`~

**Comment by neutrinoceros** [comment]
No worries. No need for additional tests, but I'll edit the title to reflect that the discrepancy isn't specifically with yt 4.1

**Comment by koarakawaii** [comment]
Hi @matthewturk: 

>  If there are noticable artifacts that diverge from the "correct" solution in 4.0 (which would likely be worse in 3.x) then we should address them, but 4.0 should be approached as having better resolution.

Yes, I totally agree the resolution looks much better for `yt-4`. But also due to the SPH smoothing kernels and particle index, we also encountered some issue when doing projection and profile using latest version of `yt`, including being time consuming, need to rely on some `covering_grid` methods to deposit the field to mesh, and cannot deal periodicity (mainly reported in these two slack threads: [1](https://yt-project.slack.com/archives/C1YCPSX08/p1661932982207789) and [2](https://yt-project.slack.com/archives/C1YCPSX08/p1661940485755659)). So besides the artefact issue reported here, we also would like to confirm whether using `covering_gird` or `add_sph_fields` is the only way to do operations like projection and profile for `GADGET` dataset~

**Comment by jzuhone** [comment]
It should be noted that `add_sph_fields` is somewhat experimental--it takes particle fields (like DM) that don't have smoothing lengths, derives smoothing lengths for them based on nearest neighbors, and then smooths them out onto the pixelated image and projects them. I certainly don't expect such a procedure to look like what yt 3.6 was doing in all aspects, especially since for the DM particles in 3.6 they were deposited onto the octree either by NGP or CIC and no smoothing lengths were involved at all.

**Comment by jzuhone** [comment]
Are you using `add_sph_fields` to create a new dataset for the DM and doing profiles, etc? If so, that's an unnecessary step. You should only use `add_sph_fields` if you want to make a slice or projection of DM. Because everything else can be done without adding smoothing lengths.

**Comment by koarakawaii** [comment]
Hi @jzuhone,

>  it takes particle fields (like DM) that don't have smoothing lengths, derives smoothing lengths for them based on nearest neighbors, and then smooths them out onto the pixelated image and projects them. I certainly don't expect such a procedure to look like what yt 3.6 was doing in all aspects, especially since for the DM particles in 3.6 they were deposited onto the octree either by NGP or CIC and no smoothing lengths were involved at all.

Thank you for the clear explanation! I agree that outcome of projection plots by `yt-3.6.0` and `yt-4.1.dev0` should not be totally identical, and the indeed are different, say in resolution and some detail structures, as shown in the [figure](https://drive.google.com/uc?export=view&id=1ZoOCI328qyniEeib4fs62sVwzb0oCocU); but our point is that for the area highlighted by the red circle, the discrepancy is so significant that we are not confident that this it is purely caused by using smoothing length or octree, and the particles there looks quite different from other region: they even don't look like they get smoothed~

> Are you using `add_sph_fields` to create a new dataset for the DM and doing profiles, etc? If so, that's an unnecessary step. You should only use `add_sph_fields` if you want to make a slice or projection of DM. Because everything else can be done without adding smoothing lengths.

Thank you pointing this out. We originally used `arbitrary_grid` to obtain an uniform grid data, converted it to a new dataset by `yt.load_uniform_grid`, and then computed profile (and can be used to do projection as well); we then try  `add_sph_fields` for projection, to explore whether there is other way to deal with `GADGET` dataset. But we found out both of them are not very satisfying: the former need manually determine the grid resolution, and the latter might have issue we reported here~

**Comment by neutrinoceros** [comment]
> our point is that for the area highlighted by the red circle, the discrepancy is so significant that we are not confident that this is purely caused by using smoothing length or octree, and the particles there looks quite different from other region: they even don't look like they get smoothed~

@koarakawaii I guess the right way to know for sure would be to compare with a different viz tool, but that may not be easy. It would also be interesting to see what happens if you zoom into your plot: do the features disappear, or are they further smoothed out ?

**Comment by neutrinoceros** [comment]
I have no expertise in cosmological simulations so this may come off as very naive, but isn't that just a very compact clump ? I would expect such features to only pop out with yt 4

**Comment by koarakawaii** [comment]
Hi @neutrinoceros:
Just wonder that if the structure is real, then I am not sure why it cannot be shown in the `arbitrary_grid` test [here](https://camo.githubusercontent.com/b82554f794a93098ab36b36f8682b20616bc69d90f99770f1894cdd4b8141621/68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f6578706f72743d766965772669643d3141744f5359654f61396f7564324755684d4c464f73554654476f38527131504e). Maybe I can first zoom-in and then do the `arbitrary_grid` test to confirm it as well~?

**Comment by neutrinoceros** [comment]
Maybe the grid simply doesn't resolve this structure ? Yes, zooming in with the arbitrary grid method would give precious hints too

**Comment by koarakawaii** [comment]
@neutrinoceros:
We tried performing `arbitrary_grid` on the same box used for the zoom-in `ProjectionPlot` above, with `1024X1024X1024` resolution. The result is a little bit ugly, since there seems to be a lot of low density regions, but it looks to me there are indeed some local high density regions that can correspond to the zoom-in projection using `add_sph_fields` shown above (see the attached figure). So is the conclusion that the absence of the feature we are discussing on is caused by lacking of spatial resolution for oct-tree of `yt-3.6.0` and `arbitrary_grid` method for `yt-4.1.dev0`? Or we should perform some more careful tests~?

<p align="center">
<img src="https://drive.google.com/uc?export=view&id=1fLc4fSB21e7NxzrcEugXI8wy94zTRwN7" width="750">
</p>

**Comment by neutrinoceros** [comment]
To me this test looks conclusive indeed, but I'll let others weigh in.
