### ISSUE TITLE
Ray casting in cylindrical coordinates

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#422]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

By using the method developed by @jzuhone and @scopatz , we should be able to walk rays across a cylindrical domain.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/422

**Comment by ngoldbaum** [comment]
Duplicate of #556
