### ISSUE TITLE
load hint

### ISSUE THREAD

**Issue by pedro-velarde** [yt-project/yt#4236]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Version Information**

  * Operating System:
  * Python Version:
  * yt version:
  * Other Libraries (if applicable):

**Comment by neutrinoceros** [comment]
@pedro-velarde Looks like you hit the green button prematurely, do you wish to fill in the details (you can edit your message) or was this a mistake ?

**Comment by neutrinoceros** [comment]
I'll assume this was a mistake, please feel free to reopen if you'd like to fill in more details
