### ISSUE TITLE
TST: ci_install.sh is currently flaky

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4299]
### Bug report

**Bug summary**

Many CI jobs are failing randomly these days with
![Screenshot 2023-01-13 at 10 44 19](https://user-images.githubusercontent.com/14075922/212288965-3f665f15-e7c2-4b6a-8fad-a392acc22025.png)

Let's try the solutions contain in the error message

**Comment by matthewturk** [comment]
huh, surprised to see `http` in all those

**Comment by neutrinoceros** [comment]
Seems like there's nothing we can do about this on our end. It's also not failing anymore, so it seems.
