### ISSUE TITLE
BUG: axes labelling in spectral cube geometry

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4350]
### Bug report

**Bug summary**

While working on #4179, I noticed that when plotting a SlicePlot of a spectral cube, with `z` as one of the plot axes, no unit is shown for this axis (I think that's expected ?), but you still get an empty pair of parentheses, and the the label ends up as `"z ()"`

**Code for reproduction**

```python
import yt
from yt.testing import fake_amr_ds

ds = fake_amr_ds(fields=[("gas", "density")], units=["g/cm**3"], geometry="spectral_cube")
yt.SlicePlot(ds, "x", ("gas", "density"), buff_size=(8, 8)).save("/tmp/")
```

**Actual outcome**

![AMRGridData_Slice_x_density](https://user-images.githubusercontent.com/14075922/220617352-0b0a3752-a9b0-41cf-9fbd-e82c3d5e7558.png)

This should be relatively easy to fix in the context of #4179, but I'd like to know what's the expected behaviour ? Should there be a unit there (if so, which one ?), or should we simply get rid of the parens, as we normally do for dimensionless axes ?

I assume @jzuhone would know what's best here.

**Comment by neutrinoceros** [comment]
Assuming no unit should be shown, #4179 now resolves this.

**Comment by neutrinoceros** [comment]
@jzuhone can you weigh in ?

**Comment by jzuhone** [comment]
So this is a contrived example--if you're plotting with the spectral axis as one of the plot axes, then the units should be _something_ if you are working with "real" spectral cubes. But `fake_amr_ds` is faking a `FITSDataset` here: 

https://github.com/yt-project/yt/blob/d73939ec7f13d9028cad8603f6d8302a5a61a8d8/yt/frontends/stream/data_structures.py#L345-L364

and not giving the `z` axis a unit. Normally it's going to be velocity, energy, wavelength, or frequency. 

But I guess that for this case the blank label is correct and we should not have any units (and no parentheses) or it should say (dimensionless). I have no preference.

**Comment by neutrinoceros** [comment]
Thank you for clarifying ! Then it's not so much an issue with the spectral cube geometry, but it's still a real issue with how empty strings are transcribed as labels. #4417 fixes it without touching geometry handlers
