### ISSUE TITLE
BLD: compatibility with Cython 3.0

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4355]
Cython 3.0 is now in beta (after several years of alpha).

#4043 contains an initial effort to discover and patch incompatibilities, but at the moment it seems to me that this migration is better done incrementally, as only some of the patches will be seamless and uncontroversial.
I'll be using this issue to track progress on this effort.

The most urgent issues are listed in the following. A useful resource for this task is the [migration guide](http://docs.cython.org/en/latest/src/userguide/migrating_to_cy30.html).

### blockers
- [x] #4146
- [x] #4357
- [x] #4365 
- [x] #4373
- [x] #4374

### restoring performance
- [x] #4386
- [x] #4390
- [x] #4392 

performance issues are discussed in the present thread.

### deprecation warnings
- [x] #4375
- [ ] `The 'DEF' statement is deprecated and will be removed in a future Cython version`. 
  - [x] see #4043 for a first attempt at removing these
  - [x] #4376
  - [ ] https://github.com/cython/cython/pull/5242

Since the migration path for some items is a moving target (see https://github.com/cython/cython/pull/5242), I think the minimal effort approach would be to set our requirement to `Cython>=3.0,<3.1` at first. According to the current plan for Cython 3.1 and 3.2, we should be able to drop the upper limit completely once we reach compatibility with version 3.2

### low priority (expected gains from dropping Cython 0.29.x)
- [ ] forbid deprecation warnings from numpy C-API (see http://docs.cython.org/en/latest/src/userguide/migrating_to_cy30.html#numpy-c-api)
This one is easy, as it just requires adding some compiler flags to all `*.pyx` files, but it requires dropping Cython 0.29.x first.
For future reference, here's a simple way to apply the change systematically
<details><summary> Details </summary>

with `header.txt`
```shell
# distutils: define_macros=NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION
```
and `t.sh`
```shell
for file in "$@"
do
    cat header.txt "$file" > /tmp/xx.$$
    mv /tmp/xx.$$ "$file"
done
```
apply the change as
```
git ls-files | grep .pyx | xargs bash t.sh
```

</details>

- [ ] (?) Start releasing more portable wheels with `PY_LIMITED_API` https://cython.readthedocs.io/en/latest/src/changes.html?highlight=CYTHON_LIMITED_API#id27

**Comment by neutrinoceros** [comment]
The last item without a PR on the "blockers" list is a little hard for me to decipher. It only affects `yt/geometry/oct_container.pyx`, which I am not familiar with. It looks like @matthewturk and @cphyc last authored the lines these errors are pointing to. Any chance you guys could give me a hand here ?

For reference, here's a simple script that can be used for testing compilation
```shell
python -m pip install -U --pre Cython build
python -m build --no-isolation .
```

**Comment by neutrinoceros** [comment]
We are currently compatible with Cython 3.0.0b1, but I note that some tests are showing performance regressions.
There are very visible in the bleeding-edge CI job history: running tests went from under 5min to over 13min. I can also reproduce this regression locally and measure which tests are most affected using `pytest-durations`. Here are my results

```
With Cython 3.0.0b1

total          name                                           num avg            min
0:00:21.818796                    RotationTest::test_rotation   1 0:00:21.818796 0:00:21.818796
0:00:19.647312                LensTest::test_perspective_lens   1 0:00:19.647312 0:00:19.647312
0:00:17.663738           test_add_gradient_fields_curvilinear   1 0:00:17.663738 0:00:17.663738
0:00:16.087412           VariousVRTests::test_multiple_fields   1 0:00:16.087412 0:00:16.087412
0:00:15.884202               SaveRenderTest::test_save_render   1 0:00:15.884202 0:00:15.884202
0:00:15.345128 VariousVRTests::test_rotation_volume_rendering   1 0:00:15.345128 0:00:15.345128
0:00:14.989918  VariousVRTests::test_modify_transfer_function   1 0:00:14.989918 0:00:14.989918
0:00:13.948768                            test_point_selector   1 0:00:13.948768 0:00:13.948768
0:00:13.781540                     test_amr_kdtree_set_fields   1 0:00:13.781540 0:00:13.781540
0:00:13.541609                           test_compose_overlap   1 0:00:13.541609 0:00:13.541609
0:00:10.365563                                test_projection   1 0:00:10.365563 0:00:10.365563
0:00:10.068168                                 test_ellipsoid   1 0:00:10.068168 0:00:10.068168
0:00:09.264413                        test_compose_no_overlap   1 0:00:09.264413 0:00:09.264413
0:00:08.577762                 test_boolean_cylinders_overlap   1 0:00:08.577762 0:00:08.577762
0:00:08.008635   VariousVRTests::test_simple_volume_rendering   1 0:00:08.008635 0:00:08.008635
0:00:07.843007                 SigmaClipTest::test_sigma_clip   1 0:00:07.843007 0:00:07.843007
0:00:07.822579                   SimpleVRTest::test_simple_vr   1 0:00:07.822579 0:00:07.822579
0:00:07.640429                              test_field_access   1 0:00:07.640429 0:00:07.640429
0:00:07.561692                                       test_ray   2 0:00:03.780846 0:00:00.717569
0:00:07.272802                   test_boolean_mix_periodicity   1 0:00:07.272802 0:00:07.272802
0:00:07.191133                               test_annotations   1 0:00:07.191133 0:00:07.191133
0:00:05.887486              test_boolean_cylinders_no_overlap   1 0:00:05.887486 0:00:05.887486
0:00:05.853210                      test_region_and_particles   1 0:00:05.853210 0:00:05.853210
0:00:05.568958                            test_offaxis_moment   1 0:00:05.568958 0:00:05.568958
0:00:05.147904                 ZBufferTest::test_composite_vr   1 0:00:05.147904 0:00:05.147904
0:00:04.973548                    test_boolean_slices_overlap   1 0:00:04.973548 0:00:04.973548
0:00:04.946019                 test_boolean_slices_no_overlap   1 0:00:04.946019 0:00:04.946019
0:00:04.929659             CompositeVRTest::test_composite_vr   1 0:00:04.929659 0:00:04.929659
0:00:04.911772                   PointsVRTest::test_points_vr   1 0:00:04.911772 0:00:04.911772
0:00:04.853476                   test_boolean_spheres_overlap   1 0:00:04.853476 0:00:04.853476
0:08:21.841224                                    grand total 488 0:00:00.234941 0:00:00.000044

With Cython 0.29.33

total          name                                           num avg            min
0:00:13.668872                            test_point_selector   1 0:00:13.668872 0:00:13.668872
0:00:13.002215           test_add_gradient_fields_curvilinear   1 0:00:13.002215 0:00:13.002215
0:00:10.452180                                test_projection   1 0:00:10.452180 0:00:10.452180
0:00:09.817984                     test_amr_kdtree_set_fields   1 0:00:09.817984 0:00:09.817984
0:00:06.553763                    RotationTest::test_rotation   1 0:00:06.553763 0:00:06.553763
0:00:06.185139                      test_region_and_particles   1 0:00:06.185139 0:00:06.185139
0:00:05.647264                LensTest::test_perspective_lens   1 0:00:05.647264 0:00:05.647264
0:00:05.333219                                       test_ray   2 0:00:02.666610 0:00:00.846876
0:00:04.999946               SaveRenderTest::test_save_render   1 0:00:04.999946 0:00:04.999946
0:00:04.983511                              test_field_access   1 0:00:04.983511 0:00:04.983511
0:00:04.841462           VariousVRTests::test_multiple_fields   1 0:00:04.841462 0:00:04.841462
0:00:04.511641 VariousVRTests::test_rotation_volume_rendering   1 0:00:04.511641 0:00:04.511641
0:00:04.410010  VariousVRTests::test_modify_transfer_function   1 0:00:04.410010 0:00:04.410010
0:00:04.339119                            test_arbitrary_grid   2 0:00:02.169559 0:00:00.711297
0:00:04.289835                    test_smoothed_covering_grid   1 0:00:04.289835 0:00:04.289835
0:00:04.234965                       test_testable_geometries   7 0:00:00.593930 0:00:00.510673
0:00:04.157473                                  test_profiles   1 0:00:04.157473 0:00:04.157473
0:00:03.841644                           test_icoords_to_ires   1 0:00:03.841644 0:00:03.841644
0:00:03.834416                 test_boolean_cylinders_overlap   1 0:00:03.834416 0:00:03.834416
0:00:03.485764                           test_compose_overlap   1 0:00:03.485764 0:00:03.485764
0:00:03.399844                                     test_slice   2 0:00:01.699922 0:00:00.614181
0:00:03.371764                             test_cutting_plane   1 0:00:03.371764 0:00:03.371764
0:00:03.177318                         test_particle_profiles   1 0:00:03.177318 0:00:03.177318
0:00:03.060623                                  test_chunking   1 0:00:03.060623 0:00:03.060623
0:00:03.012477                   test_boolean_mix_periodicity   1 0:00:03.012477 0:00:03.012477
0:00:02.848275                test_boolean_ray_region_overlap   1 0:00:02.848275 0:00:02.848275
0:00:02.755700                                 test_ellipsoid   1 0:00:02.755700 0:00:02.755700
0:00:02.735369                        test_mean_sum_integrate   1 0:00:02.735369 0:00:02.735369
0:00:02.638087                 SigmaClipTest::test_sigma_clip   1 0:00:02.638087 0:00:02.638087
0:00:02.623963   VariousVRTests::test_simple_volume_rendering   1 0:00:02.623963 0:00:02.623963
0:05:01.671335                                    grand total 488 0:00:00.204368 0:00:00.000045
```

I will investigate this, and report anything useful upstream.

**Comment by matthewturk** [comment]
I can't do this right now, but probably the most effective thing to do would be to run `cython -a` on a handful of representative ones, like `RotationTest::test_rotation` and briefly inspect the generated code.  My guess is there are some default behavior changes that we are not accounting for, likely to make things more python-like that we relied on being c-like.

**Comment by neutrinoceros** [comment]
Taking the worst offender as a starting point (`RotationTest::test_rotation`), I'm able to boil it down to
```
from time import monotonic

import numpy as np

from yt.testing import fake_random_ds
from yt.visualization.volume_rendering.api import volume_render

tstart = monotonic()

ds = fake_random_ds(8)
dd = ds.sphere(ds.domain_center, ds.domain_width[0] / 2)
im, sc = volume_render(dd, field=("gas", "density"))

tstop = monotonic()

print(f"{(tstop-tstart)*1000:.0f} ms")
```

and still see the perf difference.
Following this trail, I annotated (as suggested) `yt/utilities/lib/bounding_volume_hierarchy.pyx`, and I found some suspicious differences (Cython 3.0.0b1 is on the left, yellow lines hint at Python interaction)

![Screenshot 2023-03-17 at 15 52 14](https://user-images.githubusercontent.com/14075922/225939742-48649505-f067-4d76-b2af-751bec983263.png)

**Comment by neutrinoceros** [comment]
Here are the annotations
http://use.yt/upload/66b16f8c
http://use.yt/upload/959c81a7

**Comment by neutrinoceros** [comment]
While I'm far from mastering every relevant details here, I think you might find this paragraph enlightening (maybe ?)
https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#exception-values-and-noexcept

**Comment by matthewturk** [comment]
Seems like the right usage of the legacy option to me!

**Comment by neutrinoceros** [comment]
Nevermind, the reason it didn't compile is that I forgot to also include the directive in the header, resulting in mismatches between declarations and implementations.
Anyway, I see that [`noexcept` was actually backported to Cython 0.29.x as a noop](https://github.com/cython/cython/pull/4903), so in principle it _is_ possible to add it explicitly where we rely on the old behaviour. In the particular case we've been inspecting however, I do not see any significant improvement doing so, which seems to match your (@matthewturk) intuition that these functions are not actually called that much.
So I learned about `noexpect`, which might come handy later, but I'm back to square one regarding the regressions we're seeing. I'll try to scan for other known performance-affecting changes in Cython 3's release notes.

**Comment by neutrinoceros** [comment]
This seems related https://github.com/cython/cython/pull/5327

**Comment by neutrinoceros** [comment]
Looks like the problem was adressed upstream https://github.com/cython/cython/issues/5324 (assuming it's indeed the same issue).
I'll try out the new beta release once it's available on PyPI (later today)

**Comment by neutrinoceros** [comment]
Cython 3.0.0b2 still shows degraded performance (there are no obvious differences with 3.0.0b1). I really need to take a minute to report this properly.

**Comment by neutrinoceros** [comment]
[Enabling profiling in Cython](https://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html#enabling-profiling-for-a-complete-source-file) helped me determine that the main offender is `ImageSampler.cast_through_kdtree`
Annotating the source file, I can spot one place were there's visibly more Python interaction with Cython 3.0.0b2 (left)
![Screenshot 2023-03-27 at 23 21 26](https://user-images.githubusercontent.com/14075922/228069563-a6ab022d-8cc0-46ad-8de0-4ffc9f8499e9.png)

An uneducated look at the code generated for these calls to `i64clip` seem to indicate that it includes error handling (which the old version does not).

For instance, for this line
```python
iter[0] = i64clip(iter[0]-1, 0, self.nv[0])
```
this is the old generated code
```
(__pyx_v_iter[0]) = __pyx_f_2yt_9utilities_3lib_8fp_utils_i64clip(((__pyx_v_iter[0]) - 1), 0, (__pyx_v_self->nv[0]));
```
And this is the new code
```
__pyx_t_3 = __pyx_f_2yt_9utilities_3lib_8fp_utils_i64clip(((__pyx_v_iter[0]) - 1), 0, (__pyx_v_self->nv[0])); if (unlikely(__pyx_t_3 == ((__pyx_t_5numpy_int64_t)-1) && PyErr_Occurred())) __PYX_ERR(0, 163, __pyx_L1_error)
  (__pyx_v_iter[0]) = __pyx_t_3;
```

I further note that the code generated for the `i64clip` function itself is identical in both versions.

I tried applying the `noexcept` qualifier to `cast_through_kdtree` but it crashes at compile time (supposedly because this is a `def` function, not a `cdef` one).

**Comment by neutrinoceros** [comment]
I was close to solving it: in fact what's needed is to add the `noexcept` qualifier to `i64clip` itself. Done in #4386
Note that this measurably reduces the excessive runtime overhead observed earlier, but further efforts are needed to get back to baseline perfs

**Comment by matthewturk** [comment]
Haha, we call those `fp_utils` functions all the time!  Everywhere!  All at once!  I can see why adding even a smidgen of runtime overhead to them would clobber us everywhere.

**Comment by neutrinoceros** [comment]
"fp" : functional programming ?

**Comment by neutrinoceros** [comment]
`ImageSampler.cast_through_kdtree` is still the main source of overhead in the example I'm working on.
The generated code for the function signature itself is visibly different (and as far as I can tell that's the only difference), but it's difficult to pin down exactly what can be so time consuming in the new version.
@matthewturk, any chance you could have a look there ?
here is the reference: http://use.yt/upload/c98c3d98
and here's the new result: http://use.yt/upload/071b3456

**Comment by matthewturk** [comment]
Yes, I'll take a look.

**Comment by neutrinoceros** [comment]
I've escalated this question to Cython's user mailing list, hopefully it'll get some attention

**Comment by neutrinoceros** [comment]
In the end it's again all about sprinkling `noexcept` where needed. The challenge being in the identification of functions where it's performance critical. Anyway VR regressions should be overcome with #4390 

Next in line is `test_add_gradient_fields_curvilinear`, which we can boil down to the following self-contained script, still exposing the regression

```python
from time import monotonic
from yt.testing import fake_amr_ds

ds = fake_amr_ds(fields=["density"], units=["g/cm**3"])
ds.add_gradient_fields(("gas", "density"))
ad = ds.all_data()

tstart = monotonic()
ret = ad[("gas", "density_gradient_x")]
tstop = monotonic()

print(f"{(tstop-tstart)*1000:.0f} ms")
```

(on my laptop it takes about 2200ms with Cython 0.29 and 3500ms with Cython 3.0.0b2)

**Comment by neutrinoceros** [comment]
Already identified performance issues are fixed, as far as I can tell. We should be able to close this issue when we do the switch from `>=0.29.33,<3` to `>=3.0,<3.1`, which won't happen until Cython 3.0.0 final is released, *and* we take extra time to verify that performances do not degrade over a larger fraction of our tests.

**Comment by neutrinoceros** [comment]
#4575 fixes the remaining issues with, and switch requirements to Cython>=3.0,<3.1
The remaining, low priority problems and further development listed above will be addressed in follow up works and for the most part will not be possible until Cython 3.1 is out.
