### ISSUE TITLE
implement vector callbacks for geogrpahic coords

### ISSUE THREAD

**Issue by chrishavlin** [yt-project/yt#4356]
Trying to use `annotate_velocity` and `annotate_quiver` with data in geographic coordinates returns not `YTDataTypeUnsupported` errors. These callbacks **are** implemented for spherical coordinates, so it should be straightforward to implement for geographic coordinates (though I haven't looked in detail yet).

**Comment by neutrinoceros** [comment]
for reference, here are the PRs you might want to have a look to (impletation for spherical coordinates)
- #3817
- #4021

The main issue you might find is that maybe some derived fields must be properly defined first.

**Comment by chrishavlin** [comment]
Great! Thanks for the references!

**Comment by chrishavlin** [comment]
This was closed by #4740
