### ISSUE TITLE
BLD: dropping support for matplotlib < 3.5 ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4379]
I would like to propose dropping support for versions of Matplotlib older than 3.5

Motivations:
- MPL is the one dependency for which we entertain version-dependent code (beside Python itself)
- most current version-dependent blocks make a distinction between MPL pre/post 3.5, and some are actually non-functional with older versions, for instance
https://github.com/yt-project/yt/blob/00c3110921c20be9fc8e0ffba124a32ff62e0d95/yt/visualization/base_plot_types.py#L331-L334
- MPL 3.5-3.7 currently represent about 66% of all downloads (source https://pepy.tech/project/matplotlib?versions=3.2.*&versions=3.3.*&versions=3.4.*&versions=3.5.*&versions=3.6.*&versions=3.7.*&display=monthly)

Of course we should not just support the very latest version, but since version 3.2, 3.3 and 3.4 are not actually 100% compatible with yt, it makes more and more sense to just drop them.
Thoughts ? objections ?

**Comment by matthewturk** [comment]
I think before we aggressively drop older versions we need to understand
our specific install base, particularly on HPC systems. We've been a bit
more aggressive with compile -time stuff, but I am not sure I agree with
dropping this yet.

**Comment by neutrinoceros** [comment]
I get that, but I also genuinely wonder if it makes a difference: in what environment is one able to upgrade yt (or build it from source) *and* unable to upgrade matplotlib ?

**Comment by matthewturk** [comment]
I think the main environment that this would happen is when folks rely on a systemwide installation that doesn't include yt.  Which ... isn't that uncommon?  yt is not a universally installed (or even known-of) package!

**Comment by neutrinoceros** [comment]
@jzuhone any inputs on this ? IIRC you only ever install yt from source on clusters

**Comment by jzuhone** [comment]
@neutrinoceros I install yt from source pretty much everywhere, but I also never use any Python that is installed by the sysadmins--I always put conda in my home directory.

**Comment by neutrinoceros** [comment]
@matthewturk what would be the criterion for this to become acceptable to you ? Should it time-based, loosely constant version span (dropping support for older versions as new one are released), something else ?

**Comment by matthewturk** [comment]
I think you convinced me and we can do this.
