### ISSUE TITLE
DEPR: deprecate re-exports of numpy.testing functions in yt.testing

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4433]
### Report

Currently 7 functions from the `numpy.testing` namespace are re-exported in `yt.testing`. The code currently looks like this:

```python
# we import this in a weird way from numpy.testing to avoid triggering
# flake8 errors from the unused imports. These test functions are imported
# elsewhere in yt from here so we want them to be imported here.
from numpy.testing import assert_array_equal, assert_almost_equal  # NOQA isort:skip
from numpy.testing import assert_equal, assert_array_less  # NOQA isort:skip
from numpy.testing import assert_string_equal  # NOQA isort:skip
from numpy.testing import assert_array_almost_equal_nulp  # isort:skip
from numpy.testing import assert_allclose, assert_raises  # NOQA isort:skip
from numpy.testing import assert_approx_equal  # NOQA isort:skip
from numpy.testing import assert_array_almost_equal  # NOQA isort:skip
```

Last time this was updated (~3yrs ago, when isort was first enabled), we didn't attempt to get rid of that, but there is no actual gain to doing that excepts for backward compatibility, but we can actually go through a deprecation cycle if we wrap these functions instead of directly re-exporting them.

This is probably a reasonable goal to set for the next feature release so I'll triage this into the 4.2 milestone for now

**Comment by matthewturk** [comment]
This just doesn't seem like a huge priority to me.

**Comment by neutrinoceros** [comment]
clearly it's not, otherwise it would have been done years ago. I still think it's worth 30min of my time.

**Comment by neutrinoceros** [comment]
If I haven't opened a PR for it by tomorrow (or if it turns out to be large), I'll postpone it to post-4.2
