### ISSUE TITLE
Better showcase of community on homepage

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#446]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

The homepage right now does now showcase the work being done by the community.  This should include:

 * Recent uploads to the hub of data or notebooks
 * Projects on the hub
 * Better display of commits (switch to BitBucket.js ?)
 * Links to things like workshop photos and so on

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/446

**Comment by ngoldbaum** [comment]
This has substantially improved since it was reported and is not a code issue. I'm closing this.
