### ISSUE TITLE
pytest required to use yt.testing

### ISSUE THREAD

**Issue by chrishavlin** [yt-project/yt#4507]
This is likely a bit of an edge case, but because we `import pytest` at the top of `yt.testing`, one needs `pytest` installed to import `yt.testing`. 

I commonly use the `fake_` datasets in various ways, often in fresh environments and I know of at least one place in the docs where we explicitly import `yt.testing` (https://yt-project.org/doc/examining/loading_via_functions.html), both of which result in import errors if you only do a `pip install yt` or even a `pip install yt[full]`. 

Any objection to me fixing that? 

I the minimal fix is to just move that `import pytest` to within the only function that uses it (`requires_module_pytest`). alternatively, I think `yt.testing` has grown to the point where it might make sense to split it up a bit -- maybe move all of the `fake_` dataset constructors to their own module in order to separate dataset construction from test execution utilities?

**Comment by matthewturk** [comment]
I also ran into this!  I think moving the fake stuff somewhere else would be fine, or even hiding it inside something like `load_sample()` somehow, I dunno.

**Comment by neutrinoceros** [comment]
For context https://github.com/yt-project/yt/issues/3771
No objection to nesting the imports. Splitting the module may not be worth the backward compatibility layer needed to not break downstream users.

**Comment by chrishavlin** [comment]
Oh! I remember that discussion now. Thanks for the reminder!

I'll think a bit about splitting the module, but if it gets annoying I'll settle for moving the import... more soon...

**Comment by chrishavlin** [comment]
Ok, splitting out the fake_ datasets did indeed prove rather annoying... I may think more about that in the future, but for now I just submitted a PR that simply nests the pytest import.
