### ISSUE TITLE
Creating a DatasetSeries from Generic Particle Data

### ISSUE THREAD

**Issue by Ecskrabacz10** [yt-project/yt#4526]
Hello! This is not a bug report, more of a question about the DatasetSeries object.

I want to create a DatasetSeries, but all of the documentation revolves around file types that are already supported by YT. Normally, this would not be an issue, but I am trying to write some code such that I can create my own datasets from a new simulation and have been using the `load_particles()` function to do so.  I have also been adding things to the dataset after its creation, such as the current time, Hubble constant, and adjusting the unit registry of the dataset. This has not run into any issues so far, which is great. 

I now want to create a time series of these datasets that I have created. However, all I am seeing on the documentation is how to create a DatasetSeries from paths to files as opposed to datasets that have already been created. All of this is in efforts to run rockstar 
over a time series through the yt.astro_analysis tool.

Is there a way for me to create a time series of already created datasets?

i.e. instead of doing:
```python
my_sim = yt.load_simulation("enzo_tiny_cosmology/32Mpc_32.enzo", "Enzo")
my_sim.get_time_series()
```
can I do:
```python
ts = []
for filename in folder:
    ds = yt.load_particles(filename)
    ds.current_time = time    
    ds.unit_registry = unit_registry
    ts.append(ds)
my_sim = yt.DatasetSeries(ts)
```

Any help would be greatly appreciated!

**Comment by chrishavlin** [comment]
Thanks for the question!

You can indeed create `DataSeries` objects from a list of datasets! Here's a trivial example that saves the same slice from a timeseries constructed from in-memory datasets:

```python
import yt
import numpy as np 

density_0 = np.random.random((32,32,32))

ts = []
for time in np.linspace(0, 2, 10):
    data = {'density': density_0 * np.exp(-time)}
    ds = yt.load_uniform_grid(data, density_0.shape)
    ds.current_time = time    
    ts.append(ds)
    
my_sim = yt.DatasetSeries(ts)

for ids, ds in enumerate(my_sim):
    slc = yt.SlicePlot(ds, "x", "density", window_size=2, buff_size=(50, 50))
    slc.set_zlim("density", 0, 1)
    slc.set_log("density", False)
    slc.save(f"density_{str(ids).zfill(2)}")
```

With a nontrivial case, there is potential for memory issues depending on how large your datasets are. If you're using `load_particles(particle_data)`,  you'll need to be sure all of your particle data  across all your timesteps can fit into memory at once. If that's not the case, it'd be helpful to hear more about your dataset to suggest an approach.

**Comment by chrishavlin** [comment]
Oh, one note, I don't think the full entire-simulation functionality ([as shown here](https://yt-project.org/doc/analyzing/time_series_analysis.html#analyzing-an-entire-simulation)) is implemented for in-memory dataseries, so you likely will be limited to analysis via iteration like above. I'm not sure if that will limit how you're hoping to using your data (rockstar via yt.astro_analysis)
