### ISSUE TITLE
BUG: Octree loading with 1 zone not functioning at present

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt#4542]
This comes from the `load_octree` docstring:

```python
import yt
import numpy as np
oct_mask = np.zeros(25)
oct_mask[[0,  5,  7, 16]] = 8
octree_mask = np.array(oct_mask, dtype=np.uint8)
quantities = {}
quantities["gas", "density"] = np.random.random((22, 1))
bbox = np.array([[-10.0, 10.0], [-10.0, 10.0], [-10.0, 10.0]])

ds_octree = yt.load_octree(
    octree_mask=octree_mask,
    data=quantities,
    bbox=bbox,
    num_zones=1,
    partial_coverage=0,
)

s = yt.SlicePlot(ds_octree, "x", "density")
s.save()
```

At present it isn't working; I am working on a fix.  I believe it's related to the `nzones != 2` PR, but I'm not certain.

**Comment by neutrinoceros** [comment]
On my machine, this script isn't just broken, it somehow crashes IPython completely (invalid malloc). So while #4544 indeed fixes the docstring, I'm not sure it should close this issue.

**Comment by matthewturk** [comment]
@neutrinoceros I am aware of that issue, and it is a side-effect.  Typically the error will be raised through the `RuntimeError` inside `load_octree`.  That is far outside the scope of this correction.

**Comment by matthewturk** [comment]
Fuzzing against all possible inputs is not an undesirable goal, but I am not prepared to add that to this fix, as it resides within the `oct_visitors` and `recursively_visit_octs` operations, which operate outside bound-safety for performance reasons.  I am open to further discussions, but right now I would consider them out of scope.

**Comment by neutrinoceros** [comment]
Sure, I'm fine with merging #4544 as is, I'm just proposing we keep this issue open after it goes in

**Comment by matthewturk** [comment]
I would prefer we open a new issue that more accurately reflects the problem, which is that `load_octree` and the nested oct visitor (`LoadOctree`) is not resilient against malformed input.

**Comment by neutrinoceros** [comment]
Fair enough

**Comment by neutrinoceros** [comment]
@matthewturk would you like me to open this other issue ?

**Comment by matthewturk** [comment]
Oops, I will
