### ISSUE TITLE
DOC: let's drop install_script.sh ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4633]
### Bug report

**Bug summary**

As [recently discussed on the user mailing list](https://mail.python.org/archives/list/yt-users@python.org/thread/PGFASTGYO7IXTJYKZHPDZNSAZTS6PPUP/), `doc/install_script.sh` hasn't been updated in 2 years, and is currently in a non-functional state.

My personal opinion is that this script isn't bringing much value within the modern ecosystem, where build systems and compilation are completely encapsulated with `pyproject.toml` + `pip`, so I would prefer just dropping the script completely.

**Comment by brittonsmith** [comment]
+1

This install script has outlived its utility and is now a maintenance burden.

**Comment by matthewturk** [comment]
ok

![is there a ralph's around here](https://github.com/yt-project/yt/assets/89019/aa45308e-575f-4cc8-aaa5-ba93fb04fb7c)
