### ISSUE TITLE
DEP: ewah-bool-utils as a build-only dependency (?)

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4654]
As of yt 4.2.2, ewah-bool-utils is a build-time dependency *and* a runtime dependency to yt. In working on various transitions happening this year (Cython 3, Python 3.12, numpy 2.0), I've come to think that this makes maintenance of *both* packages harder than it needs to be.

There's only *one* line that makes ewah-bool-utils a runtime requirement to yt. Here it is:
https://github.com/yt-project/yt/blob/db6862e2bd476471aa519ab58e1c49dc8a364874/yt/geometry/particle_geometry_handler.py#L8C3-L8C3

I would like to try and find a way to avoid that.

**Comment by neutrinoceros** [comment]
I note that this was already rapidly discussed in https://github.com/yt-project/yt/pull/2711/files#r1055757122

**Comment by neutrinoceros** [comment]
Closing as "wont fix". See #4655

**Comment by matthewturk** [comment]
Is it the `import` statement specifically?  Is there any way to do the import in Python, access some `void*` or something in Cython, etc, to work around it?  I haven't thought through it too much but I do want to try to make the build system simpler.

**Comment by neutrinoceros** [comment]
See my attempt in #4655. I don't think I understand how to implement your suggestion, but feel free to try it out !
