### ISSUE TITLE
[4.3.0] Compilation error, PyArrayObject misses some attributes

### ISSUE THREAD

**Issue by olebole** [yt-project/yt#4697]
### Bug report

**Bug summary**

I am trying to build the package for Debian. The compilation process however fails with a number of errors about missing members `data`, `dimensions`, `nd`

**Actual outcome**

First error message is:
```
yt/utilities/cython_fortran_utils.c: In function '__pyx_f_2yt_9utilities_20cython_fortran_utils_11FortranFile_read_vector':
yt/utilities/cython_fortran_utils.c:3294:37: error: 'PyArrayObject' {aka 'struct tagPyArrayObject'} has no member named 'data'
 3294 |   (void)(fread(((void *)__pyx_v_data->data), __pyx_v_size, __Pyx_div___pyx_t_2yt_9utilities_20cython_fortran_utils_INT32_t(__pyx_v_s1, __pyx_v_size), __pyx_v_self->cfile));
      |                                     ^~
```
The full build log is attached: [yt_4.3.0-1_amd64.build](https://github.com/yt-project/yt/files/12859600/yt_4.3.0-1_amd64.build.txt)

**Expected outcome**

I'd expect that the build succeeds :-)

**Version Information**

  * Operating System: Debian sid
  * Python Version: 3.11.6
  * yt version: 4.3.0
  * Other Libraries (if applicable): cython 0.29.36
  * Installation from PyPI source tarball, .c files are recreated from .pyx with cython

**Comment by neutrinoceros** [comment]
> Other Libraries (if applicable): cython 0.29.36

I think that's where the problem is: in yt 4.3.0 we've bumped our requirement to Cython 3.0.3 (3.0.0 to 3.0.2 also works fine except on Python 3.12)

**Comment by olebole** [comment]
Sounds reasonable, thank you for the clarification. So, I'll have to wait until cython 3.x is in Debian.
