### ISSUE TITLE
Package Cython-generated *.cpp and *.c files

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#4701]
At the moment, we are including both *.cpp and *.c files generated by Cython in the wheels and, subsequently, in the locally-installed directory. That means that, for each .so file we compile, we have a corresponding source file.

While this isn't a problem per se, it inflates quite significantly the space occupied by yt. To give some number for yt 4.0.3, we have 51M of .c files, 23M of .cpp files and 13M of .so files once decompressed.

To measure:
```bash
find /usr/lib/python3.11/site-packages/yt -type f -name '*.so' | xargs du -ch
find /usr/lib/python3.11/site-packages/yt -type f -name '*.cpp' | xargs du -ch
find /usr/lib/python3.11/site-packages/yt -type f -name '*.c' | xargs du -ch
```

I dug into this because yt's AUR package for Arch Linux ends up installing more than 100M of data, which surprised me!

**Comment by matthewturk** [comment]
Wowza, that is a lot!

My understanding -- which may in fact be incorrect -- is that a lot of the code in these is identical between files.  For instance,

`grep -Fxf yt/frontends/gamer/cfields.c yt/frontends/ramses/io_utils.c|wc`

returns about 1.1M of data over 32000 lines.  I *believe* that if we had these linked into the same object file, it would not.  That's ... probably too much of a lift, though.

Alternately, I think we would be in the clear if we did not package the generated source in the wheels, but retained it in the source tarballs.

**Comment by neutrinoceros** [comment]
related:
- current state of documentation: https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html?highlight=wheel#distributing-cython-modules
- open issue on Cython: https://github.com/cython/cython/issues/5089#issuecomment-1408714455

@matthewturk , what's your rationale for including these files in source dist ?

**Comment by cphyc** [comment]
Note that, since installing yt *requires* Cython and Cython builds are deterministic, I don't really see why we would include the generated source files anymore. The only advantage of doing so would be to be able to compile directly the source files without needing Cython, but (a) we're currently not supporting this and (b) if we were to support it, that would make our setup more complex. Is it worth it?

**Comment by neutrinoceros** [comment]
I also don't think it's worth it. I think those C files were a useful resource some time back, before the build system configuration was standardised (pyproject.toml), but it's most likely useless now that we don't support any version of Python that's older than this spec any more.

**Comment by matthewturk** [comment]
Okay. I thought we still needed to distribute them for some reason, but if
not, then we don't.
