### ISSUE TITLE
yt.add_field with units=yt.dimensions.length does not work

### ISSUE THREAD

**Issue by BenWibking** [yt-project/yt#4714]
### Bug report

**Bug summary**

The example code (below) from the [documentation on creating derived fields](https://yt-project.org/doc/developing/creating_derived_fields.html#defining-a-new-field) does not work in the current version of yt.

**Code for reproduction**

```python
import yt
from yt.units import dimensions
import numpy as np

def _abs_z(field, data):
    return np.abs(data["gas", "z"])

yt.add_field(
    name=("gas", "abs_z"),
    function=_abs_z,
    sampling_type="local",
    units=dimensions.length
)
```

**Actual outcome**

```
File ~/.conda/envs/yt-upstream-version/lib/python3.11/site-packages/yt/fields/derived_field.py:167, in DerivedField.__init__(self, name, sampling_type, function, units, take_log, validators, vector_field, display_field, not_in_all, display_name, output_units, dimensions, ds, nodal_flag, alias)
    165     self.units = units.decode("utf-8")
    166 else:
--> 167     raise FieldUnitsError(
    168         f"Cannot handle units {units!r} (type {type(units)}). "
    169         "Please provide a string or Unit object."
    170     )
    171 if output_units is None:
    172     output_units = self.units

FieldUnitsError: Cannot handle units (length) (type <class 'sympy.core.symbol.Symbol'>). Please provide a string or Unit object.
```

**Expected outcome**

The [documentation](https://yt-project.org/doc/developing/creating_derived_fields.html#defining-a-new-field) says it should successfully create a derived field.

**Version Information**

  * Operating System: RHEL 8.8
  * Python Version: 3.11.5
  * yt version: 4.3.0
  * Other Libraries (if applicable):

Installed inside a fresh conda environment by using `pip install yt`.

**Comment by neutrinoceros** [comment]
I'm honestly not sure this *should* work, as the `dimensions` argument is better suited to pass a dimension. So my opinion is that the docs should be updated to reflect correct (already working) usage.

**Comment by neutrinoceros** [comment]
I wasn't able to find anywhere in the documentation where we'd use `units=yt.dimensions.stuff`

@BenWibking can you clarify where your example was picked from ? was it actually copied, or *adapted* from the docs ?

**Comment by BenWibking** [comment]
Sorry, I'm not sure what happened here. I re-typed the code, but I must have done so incorrectly. The example in the docs works.

**Comment by neutrinoceros** [comment]
I see. Well, thanks for circling back here :)
