### ISSUE TITLE
DOCS: Notebooks are blank

### ISSUE THREAD

**Issue by chrishavlin** [yt-project/yt#4718]
The notebooks dont seem to be rendering in the docs 
e.g., 
https://yt-project.org/doc/examining/loading_via_functions.html#loading-via-functions 

Screenshot: 

![Screenshot from 2023-10-31 10-23-49](https://github.com/yt-project/yt/assets/22038879/ade8cbbe-721b-48ef-b234-ca77482dc1b1)

Haven't investigated, will try to do so later today...

**Comment by matthewturk** [comment]
Looks like it's all the notebooks: https://yt-project.org/doc/analyzing/domain_analysis/xray_emission_fields.html

**Comment by chrishavlin** [comment]
just updated the title to reflect that

**Comment by matthewturk** [comment]
Oh, wait, no -- we use this as a diagnostic!

**Comment by Xarthisius** [comment]
They're there. Rendered directly not via `.. notebook`. Just remove the stub .rst files. Notebook's first cell should be the header you want to see. E.g. `# Loading Generic Particle Data`

Missing notebook https://yt-project.org/doc/examining/Loading_Generic_Particle_Data.html

**Comment by jzuhone** [comment]
FWIW, the broken "Loading Generic Particle Data" notebook is fixed here, awaiting a second approval and merge: https://github.com/yt-project/yt/pull/4696
