### ISSUE TITLE
STY: switching from black to ruff-format ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4748]
`ruff` now comes with a super fast formatter, which [draws heavily from black](https://docs.astral.sh/ruff/formatter/#black-compatibility). The formatter is currently in beta but is expected to reach maturity very soon.
There are [a couple intentional deviations from black's style](https://docs.astral.sh/ruff/formatter/black/), which currently affect about 100 lines of code in yt (roughly 0.1%), and to me they all make sense.

Do we want to migrate from black to ruff at some point ?

Expected gains:
- 3x faster runs for running pre-commit eagerly (`pre-commit run --all-files`) locally as well as pre-commit.ci (from 20s to 7s as of my latest measurement)
- one less pre-commit hook to keep updated and manage

Predictable costs:
- Currently there's no replacement for `blacken-docs` so we'd have to manage 2 very-slightly different styles and hooks if we migrated now
- contrary to black, ruff-format doesn't validate AST conservation at runtime (but its test suite does, see https://github.com/astral-sh/ruff/issues/8184), so it's marginally less safe than black.

To me gains seem to outweigh costs, so I'd propose to perform the migration sometimes after the formatter is out of beta, if a consensus is reached.

**Comment by neutrinoceros** [comment]
Yes, there are a number of actively discussed tickets about it, most prominently https://github.com/astral-sh/ruff/issues/7146

**Comment by neutrinoceros** [comment]
[black 24.1.0 is here](https://github.com/psf/black/releases/tag/24.1.0), and should land in a pre-commit.ci auto PR about 10 days from now.
I ran some experiments to measure the impact of different scenarios. I'm using `git diff main --stat`
- `black` 23 ➡️  `black` 24 : `52 files changed, 92 insertions(+), 89 deletions(-)`
- `black` 23 ➡️  `black` 24  ➡️ `ruff-format` :  `57 files changed, 147 insertions(+), 119 deletions(-)`
- `black` 23 ➡️ `ruff-format`: ` 27 files changed, 102 insertions(+), 87 deletions(-)`

In my opinion, smaller diffs are preferable, but the comparison might be slightly biased towards `ruff-format`, which is intended to follow black in its yearly style update but hasn't done it yet, so its current style is intentionally closer to `black` 23 at the moment. Easiest course of action is probably to let pre-commit upgrade to black 24 for now, and maybe move to ruff-format once it's marked as stable.

**Comment by matthewturk** [comment]
OK, this is pretty convincing.  I think it might be time!

**Comment by matthewturk** [comment]
Then shall we?

**Comment by neutrinoceros** [comment]
Yes, but just to avoid shooting ourselves in the foot by making some backports harder, I suggest we do that after yt 4.3.1 !
