### ISSUE TITLE
TST: `yt/tests/test_load_archive.py::test_load_archive` is failing

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4799]
For instance, see https://github.com/yt-project/yt/actions/runs/7733683213/job/21093334760?pr=4797

The failure is due to a combination of a couple factors:
- Python 3.12 introduced a `DeprecationWarning` about use of `os.fork()` in multi-threaded processes (this is https://github.com/python/cpython/pull/100229)
- Pytest 8.0 was just released a couple days ago. Up until version 7.4.4, unmatched warnings in a `pytest.warns` context would be swallowed silently, which is why we haven't caught this before. (see https://github.com/pytest-dev/pytest/issues/9288)

Note that the failing test requires ratarmount (Linux only) and Python 3.12, so it's still pretty mild, as far as failures go. I suppose it should be escalated upstream to ratarmount, and the warning should be ignored on our side, as it seems out of our control.
What do you think @cphyc ?

**Comment by cphyc** [comment]
I think the way forward is:
1. On the short term, this is fixed by #4819 that ignores the warning on Python 3.12,
2. On the longer term, update the version of ratarmount. At the moment, we're using 0.8.1 but the latest version is now 0.14!
