### ISSUE TITLE
Possible bug: eps_writer doesn't retain formatting of SlicePlot object

### ISSUE THREAD

**Issue by dunhamsj** [yt-project/yt#4803]
### Bug report

**Bug summary**

Saving a figure using `yt.visualization.eps_writer.single_plot( slc ).save_fig( 'fig', format = 'pdf' )` causes some of the formatting of the original `SlicePlot` to be lost. In particular, ticks and all three axis labels are different and the `origin` parameter seems to be reset.

**Code for reproduction**

```python
#!/usr/bin/env python3

import yt

# Taken from the yt data hub
file = 'castro_sedov_2d_cyl_in_cart_plt00150'
ds = yt.load( file )

bl = 'gas'
Field = 'density'
blField = (bl,Field)

slc \
  = yt.SlicePlot \
      ( ds, 'z', blField, \
        origin = 'native' )

slc.set_log( Field, log = True )

slc.set_axes_unit( [ 'code_length', 'code_length' ] )

slc.set_xlabel( r'$x$' )
slc.set_ylabel( r'$y$' )

slc.set_colorbar_label( Field, r'$\rho$' )

slc.save()

import yt.visualization.eps_writer as eps

eps_fig = eps.single_plot( slc )
eps_fig.save_fig( 'fig', format = 'pdf' )
```
**Actual outcome**

![2024-02-02--165146](https://github.com/yt-project/yt/assets/9784969/b78cb83f-732f-4b1d-84af-999be2f61984)

**Expected outcome**
![2024-02-02--165541](https://github.com/yt-project/yt/assets/9784969/e81fa79b-1637-4ffd-a7e3-cc8232d20e99)

**Version Information**
  * Operating System: arch linux
  * Python Version: 3.11.6
  * yt version: 4.3.0

I installed python with `pacman -S python`, made a virtual environment, and installed yt to the virtual environment.

**Comment by dunhamsj** [comment]
Ah, I didn't know about the `slc.save('fig_slc_save.pdf', suffix="pdf")`. That did it! I couldn't find that in the [this](https://yt-project.org/doc/visualizing/plots.html#publication-ready-figures) documentation. It may be worth adding that in. Thank you for your help! I knew it was easier than I was trying to make it, as is so often the case.

**Comment by neutrinoceros** [comment]
@dunhamsj I'm not sure I get it. The `.save` method is used extensively in docs, including (seems to me) in the page you just linked.

**Comment by dunhamsj** [comment]
It may be, and I just missed it. I was making this figure for a publication and so I went to the section of the docs that referred to "Publication-Ready Figures", and that section didn't mention the method that chrishaviln suggested. The docs seemed to rely on the eps_writer method

**Comment by neutrinoceros** [comment]
Ah well, I guess that section title didn't age very well.
