### ISSUE TITLE
BUG: segault on manylinux2014 image

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4910]
### Bug report

**Bug summary**

In my attempts to enable artifacts testing (#4906 and #4909), we discovered that running even the simplest test `python -c "import yt"` triggered a segmentation fault on `manylinux2014`.
@yut23 gave more details about the error in https://github.com/yt-project/yt/pull/4906#issuecomment-2118520417

Every other target (macOS ARM, macOS x86_64 and Windows 64) appear to behave correctly.

In my experiments, I also discovered that using targeting `manylinux_2_28` instead of `manylinux2014` (using `CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28`) avoided the issue but this move requires a bump in the oldest supported Python version from 3.9.2 to 3.9.5 (see pip requirements in https://github.com/pypa/manylinux). Would this be an acceptable solution for yt 4.4.0 ?

**Comment by yut23** [comment]
I got it to work with `manylinux2014` by removing `CIBW_ENVIRONMENT: "LDFLAGS='-static-libstdc++'"`. It seems like that used to be needed for C++14 support, but evidently not anymore?

**Comment by neutrinoceros** [comment]
Awesome, thank you very much ! I see you already have a branch for this patch so I suggest you merge #4909 and follow up with a PR closing this issue :)

**Comment by yut23** [comment]
Should I put the pytest fixes in a separate PR, for separation of concerns?

**Comment by yut23** [comment]
Here's a StackOverflow post from someone with a very similar issue: https://stackoverflow.com/questions/47202468/segfault-on-declaring-a-variable-of-type-vectorshared-ptrint.

**Comment by neutrinoceros** [comment]
> Should I put the pytest fixes in a separate PR, for separation of concerns?

Preferably, yes. And if you can pull it off don't hesitate to close #4906. Thank you !
