### ISSUE TITLE
DOC: docs builds are failing

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4924]
### Bug report

**Bug summary**

Error message
```
Sphinx parallel build error:
nbsphinx.NotebookError: NoSuchKernel in cookbook/custom_colorbar_tickmarks.ipynb:
No such kernel named python3
make: *** [Makefile:51: html] Error 2
Build step 'Execute shell' marked build as failure
```

[example logs](https://tests.yt-project.org/job/yt_docs_new/2792/console)
Seen twice in #4923 

ping @Xarthisius

**Comment by yut23** [comment]
Looks like ipykernel is missing: https://nbsphinx.readthedocs.io/en/0.9.4/installation.html#Jupyter-Kernel
The previous successful build happened to pull it in through a glueviz dependency:
```
Collecting ipykernel!=5.0.0,!=5.1.0,>=4.0 (from glue-qt>=0.1.0->glue-vispy-viewers>=1.0.3->glueviz>=0.13.3->yt==4.4.dev0)
```

**Comment by neutrinoceros** [comment]
I don't get it. yt depends on `ipywidgets` which in turn depends on `ipykernel`

**Comment by yut23** [comment]
`pip show ipywidgets` says it doesn't: `Requires: comm, ipython, jupyterlab-widgets, traitlets, widgetsnbextension`

**Comment by neutrinoceros** [comment]
Oh right, it's now an *optional* dependency, I missed that.
Well then it should be trivial to fix. Since we need to change docs somehow to even trigger the job, do you mind doing it with your already active PR ?

**Comment by yut23** [comment]
Do you mean https://github.com/yt-project/yt/pull/4923? It was already merged.

**Comment by neutrinoceros** [comment]
Whoops. I didn't have enough coffee. Or maybe I had too much ? 🤔

**Comment by chrishavlin** [comment]
adding ipykernel as a dep in #4925 now
