### ISSUE TITLE
Question:  How the weight field operates to an yt.create_profile average?

### ISSUE THREAD

**Issue by aisclark91** [yt-project/yt#4946]
I want to compute the horizontal average of a rectangular domain over the "y" axis. For such purpose I have created the following script:
```
profile = yt.create_profile(
        sp,
        ["y"], [f],
        weight_field=None,
        accumulation=False,
        n_bins=128,
       )
```
However `weight=None` will sum the quantity `f` over all the cells inside each bin and return the sum. By default `weight_field=("gas", "mass")` but how I can make an average, just by dividing that sum by the total number of cells inside the bin?. 

In addition, I am not clear how the actual weight function computes the averages, For example, if I decide to use `weight_field=("gas, volume")` over a field f, I am computing:

$$\bar{X} = \dfrac{\sum_i V_i X_i}{\sum_i V_i}$$

for all the cells inside the bins or something different?, and, If I use `weight_field=("index, cell_volume")` instead, do I get the same answer?.

**Comment by chrishavlin** [comment]
Quick answer on getting an unweighted average: The `(`index`, `ones`)` field is available for gridded data and has a value of 1 for each cell. So if you use it as a weighting field, it will calculate an unweighted average.

**Comment by chrishavlin** [comment]
and to the second question: I think the sum you wrote is correct. And I believe `('gas', 'volume')` is an alias to `('index', 'cell_volume')`, so you should get the same answer.

**Comment by matthewturk** [comment]
I believe the sum is correct, yup.  For situations where there are more cells of higher density, etc, it's typically appropriate to average by mass or volume and not, for instance, density.  If you have a wild unbalance in the *number* of cells at different points in phase space (i.e., AMR or some SPH setups) then averaging by `ones` is biased toward the values found in regions with higher refinement.

**Comment by aisclark91** [comment]
Thanks so much for your prompt and complete answer!!. You made my day.

**Comment by chrishavlin** [comment]
Will close out the issue, but feel free to re-open if our answers were insufficient!
