### ISSUE TITLE
BLD: can we remove dev-only extra targets ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4976]
We have a couple "dev-only" (but still user-visible) extra dependency target that don't really have a use case for end users (or downstream developers, to the best of my knowledge).
Up until now, they haven't really been an issue, but I'm finding that their existence makes working with [`uv`](https://docs.astral.sh/uv/) (my new preferred universal workflow) more cumbersome[^1], so I'm proposing to replace them:

- `yt[doc]` and `yt[typecheck]` can be replaced by `requirements.txt` files (`yt[typecheck]` would actually benefit from this as it could be auto-updated by dependabot)
- `yt[minimal]` is entirely redundant and can be replaced by `uv pip compile pyproject.toml resolution=lowest-direct` in CI

Any objection ?
(putting this in the 4.4.0, hoping it'll get attention by the time we want to cut that release)

[^1]: specifically, it makes `uv sync` kinda-of useless

**Comment by chrishavlin** [comment]
> yt[doc] and yt[typecheck] can be replaced by requirements.txt files (yt[typecheck] would actually benefit from this as it could be auto-updated by dependabot)

I'm on board with this one. 

> yt[minimal] is entirely redundant and can be replaced by uv pip compile pyproject.toml resolution=lowest-direct in CI

I'd rather not simply remove the minimal target as it would make it more annoying to create a minimal environment* for anyone not using uv. That said, I wouldn't mind if we had another file with minimal requirements, and it'd be pretty easy to write a new github action to use uv to automatically update that file on changes to `pyrpoject.toml`.

*I know... probably not many people are doing this. But I do occasionally, particularly with other yt-related packages I maintain to check that they work with the minimal yt install and I'm not ready to switch all my workflows over to using uv.

**Comment by neutrinoceros** [comment]
Tangent, but in case you didn't know, GitHub markdown supports actual footnotes[^1] !

> I'd rather not simply remove the minimal target as it would make it more annoying to create a minimal environment* for anyone not using uv. That said, I wouldn't mind if we had another file with minimal requirements, and it'd be pretty easy to write a new github action to use uv to automatically update that file on changes to pyrpoject.toml.

So, would having a `requirements/minimal_env.txt` file work for you ? It's simple enough to generate it (and supposedly keep updated) with uv, so if that's acceptable to you I might go for it.

[^1]: https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/

**Comment by chrishavlin** [comment]
> So, would having a requirements/minimal_env.txt file work for you ?

Ya! That'd work for me.
