### ISSUE TITLE
DEP: can we drop support for Python 3.9 now ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4977]
It is that time of the year were a new version of Python is (about to be) born, and we can rotate out the oldest-supported one.
This one however is a bit special: Python 3.9 was the last version to work out-of-the-box with the now long-discontinued nosetest.
We already have a manually patched version of nosetest running on Jenkins with Python 3.10 so we know that's doable, but dropping Python 3.9 means it will become even harder to reproduce failures locally.
However, since there hasn't been much progress on the front of migrating our oldest tests to pytest, running the patched version of nose might still be the way to go for now.

@Xarthisius, is your patch publicly visible anywhere ? It would be useful to add it to the repo so it can be used on GHA CI too.

**Comment by neutrinoceros** [comment]
(this shouldn't block the 4.4.0 release, I'm just hoping it could be resolved by then)

**Comment by Xarthisius** [comment]
I'm not doing anything beside what was mentioned here: https://github.com/yt-project/yt/issues/4302#issuecomment-1696143424

Is it publicly visible? Yes, it's in every log:
```
+ python -m pip install nose nose-exclude
Collecting nose
  Using cached nose-1.3.7-py3-none-any.whl.metadata (1.7 kB)
Collecting nose-exclude
  Using cached nose_exclude-0.5.0-py3-none-any.whl
Using cached nose-1.3.7-py3-none-any.whl (154 kB)
Installing collected packages: nose, nose-exclude
Successfully installed nose-1.3.7 nose-exclude-0.5.0
+ find .venv/lib/python3.10/site-packages/nose -name '*.py' -exec sed -i -e s/collections.Callable/collections.abc.Callable/g '{}' ';'
```

**Comment by nastasha-w** [comment]
Is there something specific about the nose tests that makes them difficult to switch to pytest? I.e., is there some technical issue to resolve there? Or is it just a whole lot of work nobody's really gotten around to or committed to?

**Comment by neutrinoceros** [comment]
It's tangent to this issue so I suggest we don't pull that thread here but in short: pytest dropped support for `yield` based tests a while ago (which was a form of parametrization in nosetests), and we have a substantial amount of testing infrastructure built around these, so migrating them isn't trivial (and there are a lot of them).
see for instance https://github.com/yt-project/yt/issues/3734 (and the `pytest` label in general).

**Comment by chrishavlin** [comment]
+1 for dropping support for python 3.9. but until we drop nose, it'd be nice to document what you need to do to run locally in a clearer spot than this issue. how bout we add the find/sed command from @Xarthisius's comment to the note that @nastasha-w added in #4955 ?

**Comment by neutrinoceros** [comment]
Good point. Done in #4979
