### ISSUE TITLE
`urllib.request.URLopener` is deprecated

### ISSUE THREAD

**Issue by barneygale** [yt-project/yt#5027]
### Bug report

yt uses [`urllib.request.URLopener`](https://docs.python.org/3/library/urllib.request.html#urllib.request.URLopener), which was deprecated in Python 3.3. Would you accept a PR that uses [`urlretrieve()`](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve) instead? Ta!

**Comment by neutrinoceros** [comment]
Yes, absolutely! Thanks for spotting this !
