### ISSUE TITLE
[BUG] annotate_sphere radius depends on choice of center

### ISSUE THREAD

**Issue by cphyc** [yt-project/yt#5062]
### Bug report

**Bug summary**

When annotating plots with a sphere, the apparent size of the sphere depends on the units of the center of the plot.

**Code for reproduction**

```python
import yt
import numpy as np

ds = yt.load_sample("output_00080")

rad = ds.quan(200, "kpccm/h")
# Option 1
center = ds.arr(ds.all_data().argmax("density"))
# Option 2
center = ds.arr(ds.all_data().argmax("density")).in_units("code_length")
# Option 3
center = ds.arr(ds.all_data().argmax("density")).in_units("Mpccm/h")
sp = ds.sphere(center, 2*rad)

p = yt.ProjectionPlot(
    ds,
    "x",
    ("gas", "density"),
    center=center,
    width=rad * 2,
    data_source=sp,
    origin="native",
)
p.annotate_sphere(center, rad, circle_args={"color": "white"})
p.set_axes_unit("Mpccm/h")
p.save("/tmp/")
```

**Actual outcome**

| Option | Outcome |
|--------|---------|
| 1 | ![info_00080_Projection_x_density](https://github.com/user-attachments/assets/ecd1bdde-8562-4c25-b3a0-d262701f1785) |
| 2 | ![info_00080_Projection_x_density](https://github.com/user-attachments/assets/ced09933-f92c-403d-8ca0-f4642439f818) |
| 3 | ![info_00080_Projection_x_density](https://github.com/user-attachments/assets/4ad57847-6e79-460d-9824-0483732a9f16) |

**Expected outcome**

All three images should be the same.

**Comment by neutrinoceros** [comment]
It looks exactly as if input units are completely ignored and code units are assumed in all cases.

**Comment by cphyc** [comment]
Found the issue!
