### ISSUE TITLE
Unit and answer tests should be parallel safe

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#509]
Originally reported by: **Kacper Kowalik (Bitbucket: [xarthisius](https://bitbucket.org/xarthisius), GitHub: [xarthisius](https://github.com/xarthisius))**

----------------------------------------

Goal is to make the testsuite much faster than it's now. The most demanding tests should be identified and rewritten if necessary. Tentative plan is to achieve less than 5 minutes for total time.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/509

**Comment by ngoldbaum** [comment]
We now run the tests in parallel on fido.
