### ISSUE TITLE
Standardize arguments to plot annotations

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#547]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

`plot_args` and `text_args` should only be one or the other.  Having multiple argument names is confusing.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/547

**Comment by neutrinoceros** [comment]
@matthewturk I'm considering closing this after #3957 went in. Thoughts ?

**Comment by matthewturk** [comment]
yup
