### ISSUE TITLE
annotate_contour on only half the image

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#588]
Originally reported by: **Kyle Stewart (Bitbucket: [kstewart](https://bitbucket.org/kstewart), GitHub: [kstewart](https://github.com/kstewart))**

----------------------------------------

I came across a curious bug where I was looking at a SlicePlot and using annotate_contour to add density contours on top of the plot.  When zoomed pretty far out, everything works fine, but when I began to zoom in on the galaxy in my simulation, the contours stopped displaying correctly, and began to only display on *exactly* half the image (the left half).

Code:

```
#!python

p=SlicePlot(pf, 2, ["Density", "HI_Density", "Temperature"], center=center, width=(500,'kpc'))
p.annotate_contour("Density")
p.save("test1")

p.set_width(140,'kpc')
p.save("test2")

```

I thought maybe it would help to call p.annotate_contour("Density") again after re-setting the width, but that doesn't accomplish anything.  

I've included the resulting images.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/588

**Comment by ngoldbaum** [comment]
Can't reproduce.
