### ISSUE TITLE
Volume Rendering + Log Fields + Zeros

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#647]
Originally reported by: **Sam Skillman (Bitbucket: [samskillman](https://bitbucket.org/samskillman), GitHub: [samskillman](https://github.com/samskillman))**

----------------------------------------

Currently if you have a volume rendering of a field that is done in log-space and there are zeros/negative values in the raw field data, the resulting NaNs contaminate the image, causing most if not all of the rendering to be empty (zeros).

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/647

**Comment by ngoldbaum** [comment]
I don't think rendering negative data in log space contaminates the volume rendering anymore. The final image just shows up blank in those regions.
