### ISSUE TITLE
tracking rays on top of cut region

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#717]
Originally reported by: **yong zheng (Bitbucket: [yongzheng](https://bitbucket.org/yongzheng), GitHub: [yongzheng](https://github.com/yongzheng))**

----------------------------------------

I am trying to use the .hierarchy.ray( ) to extract data along a particular
 light ray, but when I check the temperature field of that light ray data, I
find that the data points it extracted were not really what I want, the temperature range goes beyond my limit, here is part of my code:

>     sp = pf.h.sphere(center, radius)
>     warmhot = sp.cut_region(['grid["Temperature"] >= 1e5',
> 'grid["Temperature"] < 1e6'])
>     p0 = np.array([center[0], center[1]-250./pf['kpc'], center[2]])
>     p1 = np.array([center[0], center[1]+250./pf['kpc'], center[2]])
>     ray = warmhot.hierarchy.ray(p0, p1)
>     tempt = warmhot['Temperature']
>     ray_tempt = ray['Temperature']
>
when I examine the temperature range for warmnot, it is
      (100000.1171875, 999999.5625)
but for ray_tempt, it is:
    (6607.2802734375, 86239664.0)
It seems that the .hierarchy.ray() extracts data directly from the pf.h dataset instead of the cut warmhot region. Could anyone help? 

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/717

**Comment by ngoldbaum** [comment]
Not reproducible.
