### ISSUE TITLE
Use nextafter instead of jittering in Cython

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#799]
Originally reported by: **Matt Turk (Bitbucket: [MatthewTurk](https://bitbucket.org/MatthewTurk), GitHub: [MatthewTurk](https://github.com/MatthewTurk))**

----------------------------------------

Instead of adding epsilons in Cython, we should be using `nextafter` from `math.h`.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/799

**Comment by ngoldbaum** [comment]
@MatthewTurk for posterity, can you describe where in the code this jittering is happening?

**Comment by neutrinoceros** [comment]
Closing as there’s not enough information to work with for this to be actionable, with Matt’s consent.
