### ISSUE TITLE
save_object bug in the Clump object

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#802]
Originally reported by: **Juan Camilo Ibañez Mejia (Bitbucket: [jcibanezm](https://bitbucket.org/jcibanezm), GitHub: [jcibanezm](https://github.com/jcibanezm))**

----------------------------------------

After a clump object is created with the functions:
> master_clump = Clump(sphere, None, field, function=function)
> find_clumps(master_clump, c_min, c_max, step)

It is not possible to save the data object with the 
> pf.h.save_object(master_clump, 'My_clumps')

call, neither with the 
> master_clump.save_object('%s_My_clumps' % pf, '%s_clumps_file.cpkl' % pf)

because the clump objet has no save_object attribute.

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/802

**Comment by ngoldbaum** [comment]
Closing this because it's not reproducible.
