### ISSUE TITLE
HaloCatalog fails for a RockstarDataset with "format_revision" = 2

### ISSUE THREAD

**Issue by yt-fido** [yt-project/yt#967]
Originally reported by: **Devin Silvia (Bitbucket: [devinsilvia](https://bitbucket.org/devinsilvia), GitHub: [devinsilvia](https://github.com/devinsilvia))**

----------------------------------------

HaloCatalog hits a Key Error for a rockstar halo dataset read from a rockstar halo binary filel.  The value of halos_ds.parameters['format_revision'] is 2.  If I change this to "0" before the halo catalog call, there doesn't seem to be a problem.  This is an issue for a newly created rockstar halo list.  A halo list created for the same dataset with an older version of rockstar seems to end up with "format_revision" value of 0.

The command that fails is:

hc = HaloCatalog(data_ds=data_ds, halos_ds=halos_ds, output_dir=os.path.join(tmpdir, 'halo_catalog'))

The traceback is here: http://paste.yt-project.org/show/5290/

----------------------------------------
- Bitbucket: https://bitbucket.org/yt_analysis/yt/issue/967

**Comment by brittonsmith** [comment]
This was fixed in [PR 2306](https://bitbucket.org/yt_analysis/yt/pull-requests/2306/adding-new-rockstar-halo-properties-from/diff) on bitbucket.
